# sklearn model with tensorflow keras tuner

In [ ]:
# ! python -m pip install --no-index --find-links=/kaggle/usr/lib/pip_install_permanent/my_packages -r /kaggle/usr/lib/pip_install_permanent/requirements.txt

In [ ]:
import os
os.environ['PACKAGE_DIR'] = '/kaggle/usr/lib/pip_install_permanent'

In [1]:
from helper_func import *
# import helper_functions as hf
import sys
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import string
from spellchecker import SpellChecker
from textblob import TextBlob
from multiprocessing import Pool
from tqdm import tqdm
import numpy as np
import pandas as pd
# Preprocessing
from nltk.tokenize import word_tokenize, sent_tokenize
import operator
from spellchecker import SpellChecker
from tqdm import tqdm  # Import tqdm
import re
import inflect
from wordsegment import load, segment
from nltk.corpus import words
word_list = set(words.words())
from spellchecker import SpellChecker

from tqdm.contrib.concurrent import process_map  # If this import fails, you might need to update tqdm

import multiprocessing
 
# Import Packages
# import shutup; shutup.please()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import keras_tuner as kt
import seaborn as sns

from nltk.corpus import stopwords, wordnet
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk import pos_tag, ne_chunk
from textblob import TextBlob

from textstat import flesch_reading_ease, smog_index

import spacy
from collections import Counter
from gensim import corpora, models
import pyLDAvis.gensim as gen
import pyLDAvis
import re

# Machine Learning & Data Preprocessing

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Deep Learning

from tensorflow.keras import layers
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Gensim
# from gensim.models import Word2Vec, KeyedVectors
import pandas as pd
# Progress bar
from tqdm import tqdm

# Keras Tuner
from keras_tuner.tuners import RandomSearch

# # Setting logging levels and environment variables
# tf.get_logger().setLevel(logging.ERROR)
# os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

from textstat import flesch_reading_ease

# from helper_functions import *
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import string
from spellchecker import SpellChecker
from textblob import TextBlob
from multiprocessing import Pool
from tqdm import tqdm
import numpy as np
import pandas as pd
# Preprocessing
from nltk.tokenize import word_tokenize, sent_tokenize
import operator
from spellchecker import SpellChecker
from tqdm import tqdm  # Import tqdm
import re
import inflect
from wordsegment import load, segment
from nltk.corpus import words
word_list = set(words.words())
print('Packages Instaled......')

/home/jack/envs/scoring/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2024-04-22 19:36:48.408152: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-22 19:36:49.025592: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

Packages Instaled......

[nltk_data] Downloading package punkt to /home/jack/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/jack/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /home/jack/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/jack/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [2]:
train = pd.read_csv('/home/jack/github/kaggle/scoring/data/train.csv')

In [3]:
import os

glove_path = 'data/glove-840B-300d.txt'

paragram_path = '/home/jack/github/kaggle/scoring/data/paragram-300-sl999.txt'

wiki_news_path = 'data/wiki-news-1M-300d.vec'


# Load embeddings

embeddings = parallel_load_embeddings([glove_path, paragram_path, wiki_news_path])

glove = embeddings["glove"]
paragram = embeddings["paragram"]
fasttext = embeddings["fasttext"]

Loading embeddings from /home/jack/github/kaggle/scoring/data/paragram-300-sl999.txtLoading embeddings from data/wiki-news-1M-300d.vecLoading embeddings from data/glove-840B-300d.txt

Reading Embedding File: 999995it [00:32, 30576.76it/s]]

Loaded embeddings from data/wiki-news-1M-300d.vec

Reading Embedding File: 1703756it [00:55, 30802.74it/s]

Loaded embeddings from /home/jack/github/kaggle/scoring/data/paragram-300-sl999.txt

Reading Embedding File: 2196017it [01:10, 31368.73it/s]

Loaded embeddings from data/glove-840B-300d.txt

In [4]:
train, glove, paragram, fastetxt = spellcheck_and_correct_text(train, embeddings)

Starting text cleaning process.

Mis-spelling Count.................

Checking Vocabulary.................

Processing dataset.
Building vocabulary.

Populating Vocabulary: 100%|██████████| 17307/17307 [00:00<00:00, 24632.63it/s]

Vocabulary built.
Checking coverage.

Checking Words: 100%|██████████| 65918/65918 [00:00<00:00, 1710394.45it/s]

Coverage checked.
Checking coverage.

Checking Words: 100%|██████████| 65918/65918 [00:00<00:00, 1827496.59it/s]

Coverage checked.
Checking coverage.

Checking Words: 100%|██████████| 65918/65918 [00:00<00:00, 1958407.46it/s]

Coverage checked.
Processed dataset.

100%|██████████| 21/21 [1:10:32<00:00, 201.56s/it]

Correcting Mis-spelling.................

Segmenting Words .................

100%|██████████| 20/20 [00:07<00:00,  2.57it/s]

Checking Vocabulary after segmentation.................

Processing dataset.
Building vocabulary.

Populating Vocabulary: 100%|██████████| 17307/17307 [00:00<00:00, 23503.94it/s]

Vocabulary built.
Checking coverage.

Checking Words: 100%|██████████| 25174/25174 [00:00<00:00, 1687211.92it/s]

Coverage checked.
Checking coverage.

Checking Words: 100%|██████████| 25174/25174 [00:00<00:00, 1909770.82it/s]

Coverage checked.
Checking coverage.

Checking Words: 100%|██████████| 25174/25174 [00:00<00:00, 1856122.93it/s]

Coverage checked.
Processed dataset.

100%|██████████| 21/21 [1:10:32<00:00, 201.54s/it]

Correcting Mis-spelling after segmentation.................

Adding Text Features.................

Complete.................

In [5]:
train_essays, val_essays = custom_train_validation_split(train, test_size=0.25, random_state=42)

In [6]:
train_essays.head()

,essay_id,full_text,score,lowered,clean_text,misspelling_count,corrected_text,segmented_text,combined_dense_vector,dense_vec_0,...,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score
3465,3348cd7,Imagine a car driving it's self. Seems like a ...,4,imagine a car driving it's self. seems like a ...,imagine a car driving it is self seems like a ...,6,imagine a car driving it is self seems like a ...,imagine a car driving it is self seems like a ...,"[0.0062907, 0.07971818, -0.12647843, -0.061767...",-0.041778,...,509,509.0,509,509,4.204322,13,1,-419.79,204.94,-0.9931
3466,334d4b0,Technology is a big part of today's society. I...,4,technology is a big part of today's society. i...,technology is a big part of todays society i f...,9,technology is a big part of todays society i f...,technology is a big part of todays society i f...,"[0.005591229, 0.038926236, -0.070733815, -0.03...",0.014226,...,410,410.0,410,410,4.468293,13,1,-327.76,165.66,0.9143
3468,33504eb,"In the article ""Driverless Care Are Coming"" th...",5,"in the article ""driverless care are coming"" th...",in the article driverless care are coming the ...,17,in the article driverless care are coming the ...,in the article driverless care are coming the ...,"[0.008718464, 0.07904561, -0.11216053, -0.0659...",-0.011984,...,766,766.0,766,766,4.083551,12,1,-680.64,307.44,0.9952
3470,335556a,I think driverless car would be a great idea f...,2,i think driverless car would be a great idea f...,i think driverless car would be a great idea f...,2,i think driverless car would be a great idea f...,i think driverless car would be a great idea f...,"[0.03039162, 0.055163573, -0.10792485, -0.0249...",0.006382,...,209,209.0,209,209,4.105263,13,1,-115.29,85.13,0.9949
3471,3355650,"Dear state senator,\n\nI wish to inform you ab...",4,"dear state senator,\n\ni wish to inform you ab...",dear state senator i wish to inform you about ...,8,dear state senator i wish to in form you about...,dear state senator i wish to in form you about...,"[0.016582694, 0.006666562, -0.045603786, -0.05...",0.002974,...,400,400.0,400,400,4.475000,15,1,-309.15,161.70,0.9856

In [7]:
# import pandas as pd

# train_essays = pd.read_parquet('/home/jack/github/kaggle/scoring/train_essays.parquet')
# val_essays = pd.read_parquet('/home/jack/github/kaggle/scoring/validation_essays.parquet')

In [8]:
# pd.set_option('display.max_columns', None)

train_essays.head()

,essay_id,full_text,score,lowered,clean_text,misspelling_count,corrected_text,segmented_text,combined_dense_vector,dense_vec_0,...,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score
3465,3348cd7,Imagine a car driving it's self. Seems like a ...,4,imagine a car driving it's self. seems like a ...,imagine a car driving it is self seems like a ...,6,imagine a car driving it is self seems like a ...,imagine a car driving it is self seems like a ...,"[0.0062907, 0.07971818, -0.12647843, -0.061767...",-0.041778,...,509,509.0,509,509,4.204322,13,1,-419.79,204.94,-0.9931
3466,334d4b0,Technology is a big part of today's society. I...,4,technology is a big part of today's society. i...,technology is a big part of todays society i f...,9,technology is a big part of todays society i f...,technology is a big part of todays society i f...,"[0.005591229, 0.038926236, -0.070733815, -0.03...",0.014226,...,410,410.0,410,410,4.468293,13,1,-327.76,165.66,0.9143
3468,33504eb,"In the article ""Driverless Care Are Coming"" th...",5,"in the article ""driverless care are coming"" th...",in the article driverless care are coming the ...,17,in the article driverless care are coming the ...,in the article driverless care are coming the ...,"[0.008718464, 0.07904561, -0.11216053, -0.0659...",-0.011984,...,766,766.0,766,766,4.083551,12,1,-680.64,307.44,0.9952
3470,335556a,I think driverless car would be a great idea f...,2,i think driverless car would be a great idea f...,i think driverless car would be a great idea f...,2,i think driverless car would be a great idea f...,i think driverless car would be a great idea f...,"[0.03039162, 0.055163573, -0.10792485, -0.0249...",0.006382,...,209,209.0,209,209,4.105263,13,1,-115.29,85.13,0.9949
3471,3355650,"Dear state senator,\n\nI wish to inform you ab...",4,"dear state senator,\n\ni wish to inform you ab...",dear state senator i wish to inform you about ...,8,dear state senator i wish to in form you about...,dear state senator i wish to in form you about...,"[0.016582694, 0.006666562, -0.045603786, -0.05...",0.002974,...,400,400.0,400,400,4.475000,15,1,-309.15,161.70,0.9856

In [9]:
train_essays['score'].value_counts()

score
3    4686
2    3529
4    2988
1     927
5     736
6     114
Name: count, dtype: int64

In [10]:
import sklearn
print(sklearn.__version__)

1.4.2

In [11]:
drop_cols = [ 'full_text', 'lowered', 'clean_text','corrected_text', 'segmented_text', 'combined_dense_vector']


train_df = train_essays.copy()
val_df = val_essays.copy()

train_df.drop(columns=drop_cols, inplace= True)
val_df.drop(columns=drop_cols, inplace= True)

In [12]:
train_df.head()

,essay_id,score,misspelling_count,dense_vec_0,dense_vec_1,dense_vec_2,dense_vec_3,dense_vec_4,dense_vec_5,dense_vec_6,...,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score
3465,3348cd7,4,6,-0.041778,0.044854,-0.096914,-0.014853,0.056038,-0.034430,0.039637,...,509,509.0,509,509,4.204322,13,1,-419.79,204.94,-0.9931
3466,334d4b0,4,9,0.014226,0.030074,-0.102048,-0.083270,0.071240,-0.031495,0.036372,...,410,410.0,410,410,4.468293,13,1,-327.76,165.66,0.9143
3468,33504eb,5,17,-0.011984,0.044340,-0.118346,-0.027359,0.042147,-0.030980,0.033971,...,766,766.0,766,766,4.083551,12,1,-680.64,307.44,0.9952
3470,335556a,2,2,0.006382,0.027070,-0.084359,-0.008475,0.070072,0.014962,0.027000,...,209,209.0,209,209,4.105263,13,1,-115.29,85.13,0.9949
3471,3355650,4,8,0.002974,0.034574,-0.080980,-0.038124,0.060055,-0.038066,0.027215,...,400,400.0,400,400,4.475000,15,1,-309.15,161.70,0.9856

In [13]:
feature_cols = []

for col in train_df.columns:
    if (col != 'essay_id') and (col != 'score'):
        feature_cols.append(col)

In [14]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pickle
import numpy as np

# Extract labels from the training and validation datasets
train_labels = train_df['score']  # Extracts 'score' column as the label
val_labels = val_df['score']

# Extract features for scaling
train_features = train_df[feature_cols] # Subset with only feature columns
val_features = val_df[feature_cols]

# Initialize the scaler
scaler = MinMaxScaler()  # Using StandardScaler for scaling

# Fit the scaler to the training features
scaler.fit(train_features)  # This defines the transformation based on the training data

# Transform training and validation features
train_feats_scaled = scaler.transform(train_features)  # Transforms the training data
val_feats_scaled = scaler.transform(val_features)  # Transforms the validation data

# Reassign the scaled features to the original DataFrames, keeping the same column names
train_df[feature_cols] = train_feats_scaled  # Replace the original features with scaled ones
val_df[feature_cols] = val_feats_scaled

# Save the scaler for later use
with open('sklearn_scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)  # Persist the scaler for future use or reference

In [15]:
# Check if the file has been written correctly and is not empty
import os
scaler_path = 'sklearn_scaler.pkl'
if os.path.getsize(scaler_path) > 0:
    print(f"Scaler saved successfully in {scaler_path}.")
else:
    print(f"Failed to save scaler to {scaler_path}. File is empty.")

Scaler saved successfully in sklearn_scaler.pkl.

In [16]:
# Check if the scaler is StandardScaler
if isinstance(scaler, StandardScaler):
    print("The scaler is a StandardScaler.")
elif isinstance(scaler, MinMaxScaler):
    print("The scaler is a MinMaxScaler.")
else:
    print("The scaler is neither StandardScaler nor MinMaxScaler.")

The scaler is a MinMaxScaler.

In [17]:
train_df = pca_dataframe(train_df)
val_df = pca_dataframe(val_df)

In [18]:
train_df

,essay_id,score,misspelling_count,dense_vec_0,dense_vec_1,dense_vec_2,dense_vec_3,dense_vec_4,dense_vec_5,dense_vec_6,...,gunning_fog_index,sentiment_score,cosine_mean,cosine_std,cosine_max,cosine_min,cluster,PCA_1,PCA_2,PCA_3
0,3348cd7,4,0.066667,0.415609,0.520533,0.378460,0.720988,0.537494,0.295806,0.620713,...,0.232516,0.002952,0.951806,0.016003,1.0,0.874308,0,0.018114,0.157500,-0.918484
1,334d4b0,4,0.100000,0.679254,0.449176,0.359911,0.256488,0.617130,0.313080,0.596344,...,0.168629,0.957320,0.935874,0.023412,1.0,0.861232,0,1.203732,-0.462806,1.283127
2,33504eb,5,0.188889,0.555871,0.518051,0.301024,0.636084,0.464729,0.316107,0.578429,...,0.399226,0.997798,0.946245,0.020412,1.0,0.861342,0,1.244873,-0.226539,0.334649
3,335556a,2,0.022222,0.642328,0.434672,0.423819,0.764294,0.611010,0.586460,0.526405,...,0.037652,0.997648,0.940035,0.021181,1.0,0.848751,1,-1.341239,-0.676321,0.303925
4,3355650,4,0.088889,0.626287,0.470899,0.436029,0.562997,0.558540,0.274413,0.528009,...,0.162189,0.992995,0.950387,0.015156,1.0,0.867372,2,0.190335,1.194796,-0.441121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12975,e57f0b9,4,0.055556,0.440765,0.596323,0.396638,0.725078,0.518863,0.228632,0.427758,...,0.200995,0.991994,0.939141,0.019188,1.0,0.855487,0,0.050637,0.254942,-1.287867
12976,e58330e,2,0.055556,0.643559,0.423002,0.528769,0.540976,0.487868,0.324056,0.652925,...,0.017517,0.958921,0.945449,0.015594,1.0,0.864986,2,-0.095690,1.525390,-0.167532
12977,e5865e9,5,0.122222,0.687992,0.442949,0.393083,0.709717,0.839327,0.539299,0.662978,...,0.260491,0.951266,0.930850,0.024305,1.0,0.823876,1,-1.689520,-0.875977,0.552632
12978,e58d29b,3,0.066667,0.779296,0.354671,0.400944,0.365866,0.562821,0.463495,0.272099,...,0.103604,0.006605,0.936677,0.015773,1.0,0.855984,0,0.157151,-0.225415,-0.362238
12979,e59ae28,3,0.133333,0.768186,0.644772,0.366379,0.181040,0.699740,0.518157,0.592316,...,0.184341,0.554788,0.930467,0.023112,1.0,0.841258,0,0.424081,-0.482741,1.836003

In [19]:
val_df

,essay_id,score,misspelling_count,dense_vec_0,dense_vec_1,dense_vec_2,dense_vec_3,dense_vec_4,dense_vec_5,dense_vec_6,...,gunning_fog_index,sentiment_score,cosine_mean,cosine_std,cosine_max,cosine_min,cluster,PCA_1,PCA_2,PCA_3
0,3342947,2,0.088889,0.492662,0.491769,0.477536,0.736259,0.487818,0.306018,0.461561,...,0.035440,0.011708,0.941608,0.016628,1.0,0.870724,0,0.324405,0.729647,0.130654
1,334eb50,3,0.066667,0.644579,0.359703,0.261136,0.334383,0.445929,0.306898,0.501359,...,0.212104,0.179275,0.920949,0.018897,1.0,0.823086,0,-0.549791,0.899233,-0.113496
2,3352d89,3,0.055556,0.695062,0.616421,0.266775,0.422809,0.620448,0.459218,0.734607,...,0.217992,0.969278,0.946149,0.016258,1.0,0.865615,0,-0.276093,0.579167,-0.234885
3,33568ce,4,0.066667,0.458793,0.663352,0.363732,0.461655,0.476980,0.373741,0.683762,...,0.231865,0.867807,0.952771,0.014309,1.0,0.881353,0,-0.012018,0.862981,0.014140
4,336f368,4,0.133333,0.516908,0.408910,0.302778,0.598714,0.444642,0.423878,0.651383,...,0.264849,0.000700,0.943817,0.017853,1.0,0.864530,1,0.869286,0.334637,-0.536351
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4322,e52f7a8,3,0.100000,0.555909,0.430049,0.631633,0.569158,0.441595,0.435385,0.458431,...,0.102336,0.998199,0.929685,0.019581,1.0,0.859525,2,0.294062,0.206322,2.201608
4323,e57467e,3,0.244444,0.493588,0.400266,0.765811,0.526206,0.371154,0.432902,0.429846,...,0.313041,0.862904,0.919338,0.022700,1.0,0.833815,2,0.615785,-0.207440,2.549619
4324,e576be9,3,0.155556,0.754961,0.161515,0.703792,0.499487,0.547856,0.446658,0.635357,...,0.131611,0.964775,0.911727,0.023260,1.0,0.832878,2,0.461020,-0.282272,2.712707
4325,e57c038,4,0.166667,0.522574,0.506696,0.353568,0.461326,0.500584,0.554233,0.615921,...,0.276267,0.990243,0.946311,0.017310,1.0,0.867229,1,0.860095,0.424628,-0.408655
4326,e596f8b,3,0.077778,0.415565,0.560031,0.450490,0.490771,0.435640,0.359439,0.612533,...,0.209014,0.052737,0.950348,0.015359,1.0,0.870961,0,0.051200,0.728743,-0.039392

In [20]:
# train_df.to_parquet('train_df.parquet')
# val_df.to_parquet('val_df.parquet')

In [21]:
import pandas as pd
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE

df = train_df.copy()
# Downsample majority classes to 1,000 samples
target_samples = 1000
balanced_df = pd.DataFrame()

for class_label in df['score'].unique():
    class_subset = df[df['score'] == class_label]
    
    if len(class_subset) > target_samples:
        # Downsample to 1,000 samples for majority classes
        class_subset = resample(
            class_subset,
            replace=False,
            n_samples=target_samples,
            random_state=42
        )
    
    balanced_df = pd.concat([balanced_df, class_subset], axis=0)

# Now, let's apply SMOTE to balance the minority classes up to 1,000 samples
X = balanced_df.drop(columns = ['essay_id','score'], axis=1)
y = balanced_df['score']

# Create SMOTE instance to ensure all classes have 1,000 samples
smote = SMOTE(sampling_strategy={k: 1000 for k in y.unique()}, random_state=42)

X_resampled, y_resampled = smote.fit_resample(X, y)

# Create the resampled DataFrame
df_resampled = pd.DataFrame(X_resampled, columns=X.columns)
df_resampled['score'] = y_resampled

# Display the resampled class distribution to confirm the balancing
print("Resampled class distribution:")
print(df_resampled['score'].value_counts())

Resampled class distribution:
score
4    1000
5    1000
2    1000
3    1000
1    1000
6    1000
Name: count, dtype: int64

In [22]:
UPSAMPLE = False

if UPSAMPLE:
    
    # Balance only the training DataFrame
    train_df = df_resampled.copy()

    
else:
    pass

print(train_df['score'].value_counts())
print(val_df['score'].value_counts())

score
3    4686
2    3529
4    2988
1     927
5     736
6     114
Name: count, dtype: int64
score
3    1594
2    1194
4     938
1     325
5     234
6      42
Name: count, dtype: int64

In [23]:
# To convert features and targets to NumPy arrays for ML use
train_features = train_df.drop(columns=['essay_id','cosine_max','score'], axis=1).values
train_labels = train_df['score'].values

val_features = val_df.drop(columns=['essay_id','score', 'cosine_max'], axis=1).values
val_labels = val_df['score'].values


print("Features shape:", train_features.shape)
print("Target shape:", train_labels.shape)

print("Features shape:", val_features.shape)
print("Target shape:", val_labels.shape)

Features shape: (12980, 323)
Target shape: (12980,)
Features shape: (4327, 323)
Target shape: (4327,)

In [24]:
train_features

array([[ 0.06666667,  0.41560948,  0.52053296, ...,  0.01811374,
         0.15749955, -0.91848385],
       [ 0.1       ,  0.67925384,  0.44917552, ...,  1.20373162,
        -0.46280598,  1.28312686],
       [ 0.18888889,  0.55587076,  0.51805076, ...,  1.2448734 ,
        -0.22653912,  0.33464886],
       ...,
       [ 0.12222222,  0.68799245,  0.44294919, ..., -1.68951951,
        -0.87597695,  0.55263176],
       [ 0.06666667,  0.77929633,  0.35467115, ...,  0.15715054,
        -0.22541526, -0.36223849],
       [ 0.13333333,  0.76818638,  0.64477231, ...,  0.42408121,
        -0.48274054,  1.83600256]])

In [25]:

def quadratic_weighted_kappa_scorer(y_true, y_pred):
    """
    Compute the Quadratic Weighted Kappa (QWK), also known as Cohen's kappa.
    
    Parameters:
    y_true : array-like of shape (n_samples,)
        True labels.
    y_pred : array-liimport keras_tuner
from sklearn import ensemble
from sklearn import datasets
from sklearn import linear_model
from sklearn import metrics
from sklearn import model_selection

def build_model(hp):
  model_type = hp.Choice('model_type', ['random_forest', 'ridge'])
  if model_type == 'random_forest':
    model = ensemble.RandomForestClassifier(
        n_estimators=hp.Int('n_estimators', 10, 50, step=10),
        max_depth=hp.Int('max_depth', 3, 10))
  else:
    model = linear_model.RidgeClassifier(
        alpha=hp.Float('alpha', 1e-3, 1, sampling='log'))
  return model

tuner = keras_tuner.tuners.SklearnTuner(
    oracle=keras_tuner.oracles.BayesianOptimizationOracle(
        objective=keras_tuner.Objective('score', 'max'),
        max_trials=100),
    hypermodel=build_model,
    scoring=metrics.make_scorer(metrics.accuracy_score),
    cv=model_selection.StratifiedKFold(10),
    directory='.',
    project_name='my_project')ke of shape (n_samples,)
        Predicted labels.
    
    Returns:
    score : float
        Quadratic Weighted Kappa score.
    """
    return cohen_kappa_score(y_true, y_pred, weights='quadratic')

In [26]:
# from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
# import keras_tuner as kt

# model_checkpoint = ModelCheckpoint('data/models/best_standard_model_epoch.keras', 
#                                    save_best_only=True, monitor='val_loss', mode='min')

# early_stopping = EarlyStopping(monitor='val_loss', patience=5, 
#                                restore_best_weights=True)

# call_backs = [model_checkpoint, early_stopping]

In [27]:
import keras_tuner
from sklearn import ensemble, linear_model, model_selection, svm
from sklearn.metrics import make_scorer, cohen_kappa_score
from lightgbm import LGBMClassifier


def build_model(hp):
    """
    Builds a more comprehensive machine learning model based on hyperparameters for multiclass classification.
    
    Parameters:
    hp : HyperParameters
        Hyperparameters for tuning the model.
    
    Returns:
    model : An instance of a Scikit-learn model.
    """
    # Adding 'lightgbm' as a new model type
    model_type = hp.Choice('model_type', ['random_forest',  'gradient_boosting', 'lightgbm'])

    if model_type == 'random_forest':
        model = ensemble.RandomForestClassifier(
            n_estimators=hp.Int('n_estimators', 10, 100, step=10),
            max_depth=hp.Int('max_depth', 3, 20),
            min_samples_split=hp.Int('min_samples_split', 2, 20),
            min_samples_leaf=hp.Int('min_samples_leaf', 1, 10),
            criterion=hp.Choice('criterion', ['gini', 'entropy']),
            class_weight=hp.Choice('class_weight', ['balanced', 'balanced_subsample']),
            max_samples=hp.Float('max_samples', 0.1, 1.0, sampling='log')
        )



    elif model_type == 'gradient_boosting':
        model = ensemble.GradientBoostingClassifier(
            n_estimators=hp.Int('n_estimators', 50, 200, step=50),
            learning_rate=hp.Float('learning_rate', 0.01, 0.2, sampling='log'),
            max_depth=hp.Int('max_depth', 3, 15),
            subsample=hp.Float('subsample', 0.5, 1.0, step=0.1)
        )

    # Adding LightGBM as a new model type
    elif model_type == 'lightgbm':
        model = LGBMClassifier(
            n_estimators=hp.Int('n_estimators', 50, 200, step=50),
            num_leaves=hp.Int('num_leaves', 31, 127, step=16),
            learning_rate=hp.Float('learning_rate', 0.01, 0.2, sampling='log'),
            min_child_samples=hp.Int('min_child_samples', 10, 50, step=10),
            class_weight=hp.Choice('class_weight', ['balanced', None])
        )

    return model


# Defining the custom QWK scorer
qwk_scorer = make_scorer(quadratic_weighted_kappa_scorer)

# Tuner configuration
tuner = keras_tuner.tuners.SklearnTuner(
    oracle=keras_tuner.oracles.BayesianOptimizationOracle(
        objective=keras_tuner.Objective('score', 'max'),
        max_trials=50),
    hypermodel=build_model,
    scoring=qwk_scorer,
    cv=model_selection.StratifiedKFold(3),
    directory='.',
    project_name='data/sklearn',
    overwrite=True)

# Starting the search
tuner.search(train_features, train_labels)      # class_weight=class_weights_dict,

# Retrieving the best model
best_model = tuner.get_best_models(num_models=1)[0]

Trial 33 Complete [00h 00m 00s]

Best score So Far: 0.6710820097674417
Total elapsed time: 03h 24m 45s

Search: Running Trial #34

Value             |Best Value So Far |Hyperparameter
lightgbm          |gradient_boosting |model_type
90                |100               |n_estimators
15                |4                 |max_depth
16                |14                |min_samples_split
6                 |1                 |min_samples_leaf
gini              |entropy           |criterion
balanced_subsample|balanced_subsample|class_weight
0.14239           |0.26449           |max_samples
0.10235           |0.027445          |learning_rate
0.8               |0.9               |subsample
79                |127               |num_leaves
40                |40                |min_child_samples

Traceback (most recent call last):
  File "/home/jack/envs/scoring/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py", line 274, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "/home/jack/envs/scoring/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py", line 239, in _run_and_update_trial
    results = self.run_trial(trial, *fit_args, **fit_kwargs)
  File "/home/jack/envs/scoring/lib/python3.10/site-packages/keras_tuner/src/tuners/sklearn_tuner.py", line 178, in run_trial
    model = self.hypermodel.build(trial.hyperparameters)
  File "/tmp/ipykernel_388974/2111098680.py", line 49, in build_model
    class_weight=hp.Choice('class_weight', ['balanced', None])
  File "/home/jack/envs/scoring/lib/python3.10/site-packages/keras_tuner/src/engine/hyperparameters/hyperparameters.py", line 293, in Choice
    hp = hp_types.Choice(
  File "/home/jack/envs/scoring/lib/python3.10/site-packages/keras_tuner/src/engine/hyperparameters/hp_types/choice_hp.py", line 50, in __init__
    raise TypeError(
TypeError: A `Choice` can contain only one type of value, found values: ['balanced', None] with types {<class 'NoneType'>, <class 'str'>}.

RuntimeError: Number of consecutive failures exceeded the limit of 3.
Traceback (most recent call last):
  File "/home/jack/envs/scoring/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py", line 274, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "/home/jack/envs/scoring/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py", line 239, in _run_and_update_trial
    results = self.run_trial(trial, *fit_args, **fit_kwargs)
  File "/home/jack/envs/scoring/lib/python3.10/site-packages/keras_tuner/src/tuners/sklearn_tuner.py", line 178, in run_trial
    model = self.hypermodel.build(trial.hyperparameters)
  File "/tmp/ipykernel_388974/2111098680.py", line 49, in build_model
    class_weight=hp.Choice('class_weight', ['balanced', None])
  File "/home/jack/envs/scoring/lib/python3.10/site-packages/keras_tuner/src/engine/hyperparameters/hyperparameters.py", line 293, in Choice
    hp = hp_types.Choice(
  File "/home/jack/envs/scoring/lib/python3.10/site-packages/keras_tuner/src/engine/hyperparameters/hp_types/choice_hp.py", line 50, in __init__
    raise TypeError(
TypeError: A `Choice` can contain only one type of value, found values: ['balanced', None] with types {<class 'NoneType'>, <class 'str'>}.

In [ ]:
# sampled_train_labels.unique()

In [ ]:
best_model.fit(train_features, train_labels)

In [ ]:
predictions = best_model.predict(val_features)

y_true = val_labels

# predictions = target_scaler.inverse_transform(predictions.reshape(-1, 1)).flatten()

In [ ]:
# confusion matrix

from sklearn.metrics import confusion_matrix

confusion_matrix(y_true, predictions)

In [ ]:
# classification report

from sklearn.metrics import classification_report

print(classification_report(y_true, predictions))

In [ ]:
# cohens kappa

from sklearn.metrics import cohen_kappa_score

cohen = cohen_kappa_score(y_true, predictions)

In [ ]:
# quadratic weighted kappa

from sklearn.metrics import cohen_kappa_score

quadratic = cohen_kappa_score(y_true, predictions, weights='quadratic')

print(f"Cohen's Kappa: {cohen}")
print(f"Quadratic Weighted Kappa: {quadratic}")

In [ ]:
from joblib import dump, load

dump(best_model, 'standard_random_forest.joblib')

In [ ]:
# forest_model = load('random_forest.joblib')

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Generate and display the confusion matrix for the test predictions
cm = confusion_matrix(y_true, predictions, labels=best_model.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=best_model.classes_)
disp.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix')
plt.show()