# sklearn model with tensorflow keras tuner

In [1]:
import sklearn
print(sklearn.__version__)

1.2.2

In [2]:
import re
import pandas as pd
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm import tqdm
from textstat import flesch_reading_ease, gunning_fog
import numpy as np

# nltk.download('punkt')
# nltk.download('averaged_perceptron_tagger')
# nltk.download('stopwords')
# nltk.download('vader_lexicon')

def extract_and_aggregate_features(df, text_column):
    """Extracts and aggregates features at the paragraph, sentence, and word levels."""
    # Processing text into paragraphs, sentences, and words
    df['paragraph_lengths'] = df[text_column].apply(lambda x: [len(p.split()) for p in x.split('\n\n') if p.strip()])
    df['sentence_lengths'] = df[text_column].apply(lambda x: [len(s.split()) for s in nltk.sent_tokenize(x)])
    df['word_lengths'] = df[text_column].apply(lambda x: [len(w) for w in x.split()])

    # Aggregating features
    df['paragraph_count'] = df['paragraph_lengths'].apply(len)
    df['sentence_count'] = df['sentence_lengths'].apply(len)
    df['word_count'] = df['word_lengths'].apply(len)

    df['avg_paragraph_length'] = df['paragraph_lengths'].apply(np.mean)
    df['max_paragraph_length'] = df['paragraph_lengths'].apply(max)
    df['min_paragraph_length'] = df['paragraph_lengths'].apply(min)

    df['avg_sentence_length'] = df['sentence_lengths'].apply(np.mean)
    df['max_sentence_length'] = df['sentence_lengths'].apply(max)
    df['min_sentence_length'] = df['sentence_lengths'].apply(min)

    df['avg_word_length'] = df['word_lengths'].apply(np.mean)
    df['max_word_length'] = df['word_lengths'].apply(max)
    df['min_word_length'] = df['word_lengths'].apply(min)

    # Cleaning up DataFrame to remove list columns
    df.drop(['paragraph_lengths', 'sentence_lengths', 'word_lengths'], axis=1, inplace=True)

    return df

def compute_readability_and_sentiment(df, text_column):
    """Computes readability scores and sentiment analysis."""
    df['flesch_reading_ease'] = df[text_column].apply(flesch_reading_ease)
    df['gunning_fog_index'] = df[text_column].apply(gunning_fog)
    sia = SentimentIntensityAnalyzer()
    df['sentiment_score'] = df[text_column].apply(lambda x: sia.polarity_scores(x)['compound'])

    return df


def add_text_features(df, text_column):
    """Main function to aggregate all text processing and feature extraction steps."""
    tqdm.pandas(desc="Extracting and aggregating text features")
    df = extract_and_aggregate_features(df, text_column)
    df = compute_readability_and_sentiment(df, text_column)


    
    return df

In [3]:

import wordninja
from nltk.corpus import words

# Load a set of valid English words from NLTK for verification (if needed)
word_list = set(words.words())

def segment_text(text, word_list=word_list):
    """
    Segments concatenated words using wordninja, verifying segmentation with an NLTK words list.

    Args:
    text (str): A string of concatenated words.
    word_list (set): A set containing valid words.

    Returns:
    str: Segmented text, or the original text if segmentation results in less common words.
    """
    segmented_words = wordninja.split(text)
    segmented_text = ' '.join(segmented_words)

    # Optional: verify if the original text is a valid word and if the segmented version introduces less common words
    if text in word_list and not all(word in word_list for word in segmented_words):
        return text
    else:
        return segmented_text



def apply_segmentation(df_chunk, text_col='clean_text'):
    """
    Applies text segmentation to the specified 'text' column of a DataFrame chunk using wordninja.

    Args:
    df_chunk (pd.DataFrame): DataFrame chunk containing a text column with concatenated words.

    Returns:
    pd.DataFrame: DataFrame chunk with a new column 'segmented_text' containing segmented text.
    """
    df_chunk['clean_text'] = df_chunk[text_col].apply(lambda x: segment_text(x))
    return df_chunk

In [4]:
def clean_text(df, col_name = 'full_text'):
    """
    Preprocesses text for both training and testing datasets. 
    Includes loading embeddings, building vocabularies, cleaning text among other things.
    
    :param summaries_train: DataFrame with the training data
    :param summaries_test: DataFrame with the testing data
    :param glove_path: path to the GloVe embedding
    :param paragram_path: path to the Paragram embedding
    :param wiki_news_path: path to the Wiki News embedding
    
    :return: Preprocessed DataFrame and list of out-of-vocab words
    """
    print("Starting text cleaning process. \n")

    
    # Lowercase all texts

    df['lowered'] = df[col_name].apply(lambda x: x.lower())

    
    
    def clean_spacing(text):
        
        # Remove spaces before punctuation
        text = re.sub(r'\s+([,.!?])', r'\1', text)

        # Ensure there is one space after punctuation
        text = re.sub(r'([,.!?])([^\s])', r'\1 \2', text)

        return text
    

    df['clean_text'] = df['lowered'].apply(lambda x: clean_spacing(x))


        
    punct = "/-'?!.,#$%\'()*+-/:;<=>@[\\]^_`{|}~" + '""“”’' + '∞θ÷α•à−β∅³π‘₹´°£€\×™√²—–&'
    
    punct_mapping = {"‘": "'", "₹": "e", "´": "'", "°": "", "€": "e", "™": "tm", "√": " sqrt ", "×": "x", "²": "2", "—": "-", "–": "-", "’": "'", "_": "-",
                     "`": "'", '“': '"', '”': '"', '“': '"', "£": "e", '∞': 'infinity', 'θ': 'theta', '÷': '/', 'α': 'alpha', '•': '.', 'à': 'a', '−': '-', 
                     'β': 'beta', '∅': '', '³': '3', 'π': 'pi', }

    def clean_special_chars(text, punct, mapping):
        for p in mapping:
            text = text.replace(p, mapping[p])
        for p in punct:
            text = text.replace(p, f' {p} ')
        specials = {'\u200b': ' ', '…': ' ... ', '\ufeff': '', 'करना': '', 'है': ''}  
        for s in specials:
            text = text.replace(s, specials[s])
        return text
    

    df['clean_text'] = df['clean_text'].apply(lambda x: clean_special_chars(x, punct, punct_mapping))

    df['clean_text'] = df['lowered'].apply(lambda x: clean_spacing(x))


    cont_map = {
        "ain't": "am not","aren't": "are not","can't": "cannot","can't've": "cannot have","'cause": "because",  "could've": "could have",
        "couldn't": "could not","couldn't've": "could not have","didn't": "did not","doesn't": "does not","don't": "do not","hadn't": "had not",
        "hadn't've": "had not have","hasn't": "has not",
        "haven't": "have not","he'd": "he would","he'd've": "he would have","he'll": "he will","he'll've": "he will have","he's": "he is",
        "how'd": "how did","how'd'y": "how do you","how'll": "how will","how's": "how is","I'd": "I would","I'd've": "I would have","I'll": "I will",
        "I'll've": "I will have","I'm": "I am","I've": "I have",
        "isn't": "is not","it'd": "it had","it'd've": "it would have","it'll": "it will", "it'll've": "it will have","it's": "it is","let's": "let us",
        "ma'am": "madam","mayn't": "may not",
        "might've": "might have","mightn't": "might not","mightn't've": "might not have","must've": "must have","mustn't": "must not",
        "mustn't've": "must not have","needn't": "need not","needn't've": "need not have","o'clock": "of the clock","oughtn't": "ought not",
        "oughtn't've": "ought not have","shan't": "shall not","sha'n't": "shall not",
        "shan't've": "shall not have","she'd": "she would","she'd've": "she would have","she'll": "she will","she'll've": "she will have","she's": "she is",
        "should've": "should have","shouldn't": "should not","shouldn't've": "should not have","so've": "so have","so's": "so is","that'd": "that would",
        "that'd've": "that would have","that's": "that is","there'd": "there had","there'd've": "there would have","there's": "there is",
        "they'd": "they would","they'd've": "they would have","they'll": "they will","they'll've": "they will have","they're": "they are",
        "they've": "they have","to've": "to have","wasn't": "was not","we'd": "we had",
        "we'd've": "we would have","we'll": "we will","we'll've": "we will have","we're": "we are","we've": "we have",
        "weren't": "were not","what'll": "what will","what'll've": "what will have",
        "what're": "what are","what's": "what is","what've": "what have","when's": "when is","when've": "when have",
        "where'd": "where did","where's": "where is","where've": "where have","who'll": "who will","who'll've": "who will have","who's": "who is",
        "who've": "who have","why's": "why is",
        "why've": "why have","will've": "will have","won't": "will not","won't've": "will not have","would've": "would have","wouldn't": "would not",
        "wouldn't've": "would not have","y'all": "you all","y'alls": "you alls","y'all'd": "you all would",
        "y'all'd've": "you all would have","y'all're": "you all are","y'all've": "you all have","you'd": "you had","you'd've": "you would have",
        "you'll": "you you will","you'll've": "you you will have","you're": "you are",  "you've": "you have"}

    c_re = re.compile('(%s)' % '|'.join(cont_map.keys()))

    def expandContractions(text, c_re=c_re):
        def replace(match):
            return cont_map[match.group(0)]
        return c_re.sub(replace, text)


#     p = inflect.engine()

    def removeHTML(text):
        """
        Remove HTML tags from a given text string using regex.
    
        Args:
            text (str): The input text string containing HTML tags.
    
        Returns:
            str: The text string with HTML tags removed.
        """
        html = re.compile(r'<.*?>')
        return html.sub('', text)

    def dataPreprocessing(text):
        """
        Process the input text to perform a series of cleaning and formatting tasks,
        including converting numbers to words, removing specific patterns and whitespace,
        and stripping unwanted characters.
    
        Args:
            text (str): The input text string to preprocess.
    
        Returns:
            str: The cleaned and formatted text.
        """
        text = text.lower()
        text = removeHTML(text)
        # text = re.sub(r'\d+', lambda match: p.number_to_words(match.group()) + " ", text)  # Add spaces around the number words
        text = re.sub(r'\s+', ' ', text)  # Normalize multiple spaces to a single space
        text = re.sub(r"@\w+", '', text)
        text = re.sub(r"'\d+", '', text)
        text = re.sub(r"\d+", '', text)
        text = re.sub(r"http\w+", '', text)
        text = re.sub(r"[-_]+", " ", text)  # Replace hyphens and underscores with space
        text = expandContractions(text)
        text = re.sub(r"\.+", ".", text)
        text = re.sub(r"\,+", ",", text)
        text = re.sub(r"[^\w\s]", "", text)  # Remove all non-alphanumeric and non-space characters
        text = re.sub(r"\s+", " ", text)    # Normalize multiple spaces to a single space

        text = text.strip()

        return text

    
    df['clean_text'] = df['clean_text'].apply(lambda x: dataPreprocessing(x))
    
    # Step 8: Generate combined dense vector for each row of text
    
    # df['combined_dense_vector'] = df['clean_text'].apply(lambda x: get_combined_dense_vector(x, embeddings))

    # # Expand the combined dense vector into separate columns
    
    # combined_df = pd.DataFrame(list(df['combined_dense_vector']), 
    #                            columns=[f"dense_vec_{i}" for i in range(df['combined_dense_vector'][0].size)])

    # # Concatenate this new DataFrame with the original DataFrame
    
    # df = pd.concat([df, combined_df], axis=1)

    # # Step 9: Add TF-IDF features to the corrected text
    
    # df.drop(columns=['combined_dense_vector'], inplace=True)
    
    print('Adding Text Features................. \n')
    
    df = add_text_features(df, 'full_text')

    print('Complete................. \n')
    
    return df

In [5]:
import sklearn
print(sklearn.__version__)

1.2.2

In [6]:
laptop = False

if laptop:
    csv_path = '/home/laptop/github/kaggle/scoring/xlnet_hash.csv'

if not laptop:
    csv_path = '/home/jack/github/kaggle/scoring/data/trainining_full (2).csv'

In [9]:
pd.set_option('display.max_columns', None)

deberta_full = pd.read_csv(csv_path)

# deberta_full.drop(columns=['clean_text', 'score', 'labels'], inplace=True, axis=1)

deberta_full.drop(columns=['full_text', 'score'], inplace=True, axis=1)

deberta_full.head()

,essay_id,deberta_prob_0_full,deberta_prob_1_full,deberta_prob_2_full,deberta_prob_3_full,deberta_prob_4_full,deberta_prob_5_full,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,use_embedding_0,use_embedding_1,use_embedding_2,use_embedding_3,use_embedding_4,use_embedding_5,use_embedding_6,use_embedding_7,use_embedding_8,use_embedding_9,use_embedding_10,use_embedding_11,use_embedding_12,use_embedding_13,use_embedding_14,use_embedding_15,use_embedding_16,use_embedding_17,use_embedding_18,use_embedding_19,use_embedding_20,use_embedding_21,use_embedding_22,use_embedding_23,use_embedding_24,use_embedding_25,use_embedding_26,use_embedding_27,use_embedding_28,use_embedding_29,use_embedding_30,use_embedding_31,use_embedding_32,use_embedding_33,use_embedding_34,use_embedding_35,use_embedding_36,use_embedding_37,use_embedding_38,use_embedding_39,use_embedding_40,use_embedding_41,use_embedding_42,use_embedding_43,use_embedding_44,use_embedding_45,use_embedding_46,use_embedding_47,use_embedding_48,use_embedding_49,use_embedding_50,use_embedding_51,use_embedding_52,use_embedding_53,use_embedding_54,use_embedding_55,use_embedding_56,use_embedding_57,use_embedding_58,use_embedding_59,use_embedding_60,use_embedding_61,use_embedding_62,use_embedding_63,use_embedding_64,use_embedding_65,use_embedding_66,use_embedding_67,use_embedding_68,use_embedding_69,use_embedding_70,use_embedding_71,use_embedding_72,use_embedding_73,use_embedding_74,use_embedding_75,use_embedding_76,use_embedding_77,use_embedding_78,use_embedding_79,use_embedding_80,use_embedding_81,use_embedding_82,use_embedding_83,use_embedding_84,use_embedding_85,use_embedding_86,use_embedding_87,use_embedding_88,use_embedding_89,use_embedding_90,use_embedding_91,use_embedding_92,use_embedding_93,use_embedding_94,use_embedding_95,use_embedding_96,use_embedding_97,use_embedding_98,use_embedding_99,use_embedding_100,use_embedding_101,use_embedding_102,use_embedding_103,use_embedding_104,use_embedding_105,use_embedding_106,use_embedding_107,use_embedding_108,use_embedding_109,use_embedding_110,use_embedding_111,use_embedding_112,use_embedding_113,use_embedding_114,use_embedding_115,use_embedding_116,use_embedding_117,use_embedding_118,use_embedding_119,use_embedding_120,use_embedding_121,use_embedding_122,use_embedding_123,use_embedding_124,use_embedding_125,use_embedding_126,use_embedding_127,use_embedding_128,use_embedding_129,use_embedding_130,use_embedding_131,use_embedding_132,use_embedding_133,use_embedding_134,use_embedding_135,use_embedding_136,use_embedding_137,use_embedding_138,use_embedding_139,use_embedding_140,use_embedding_141,use_embedding_142,use_embedding_143,use_embedding_144,use_embedding_145,use_embedding_146,use_embedding_147,use_embedding_148,use_embedding_149,use_embedding_150,use_embedding_151,use_embedding_152,use_embedding_153,use_embedding_154,use_embedding_155,use_embedding_156,use_embedding_157,use_embedding_158,use_embedding_159,use_embedding_160,use_embedding_161,use_embedding_162,use_embedding_163,use_embedding_164,use_embedding_165,use_embedding_166,use_embedding_167,use_embedding_168,use_embedding_169,use_embedding_170,use_embedding_171,use_embedding_172,use_embedding_173,use_embedding_174,use_embedding_175,use_embedding_176,use_embedding_177,use_embedding_178,use_embedding_179,use_embedding_180,use_embedding_181,use_embedding_182,use_embedding_183,use_embedding_184,use_embedding_185,use_embedding_186,use_embedding_187,use_embedding_188,use_embedding_189,use_embedding_190,use_embedding_191,use_embedding_192,use_embedding_193,use_embedding_194,use_embedding_195,use_embedding_196,use_embedding_197,use_embedding_198,use_embedding_199,use_embedding_200,use_embedding_201,use_embedding_202,use_embedding_203,use_embedding_204,use_embedding_205,use_embedding_206,use_embedding_207,use_embedding_208,use_embedding_209,use_embedding_210,use_embedding_211,use_embedding_212,use_embedding_213,use_embedding_214,use_embedding_215,use_embedding_216,use_embedding_217,use_embedding_218,use_embedding_219,use_embedding_220,use_embedding_221,use_embedding_222,use_embedding_223,use_embedding_224,use_embedding_225,use_embedding_226,use_embedding_227,use_embedding_228,use_embedding_229,use_embedding_230,use_embedding_231,use_embedding_232,use_embedding_233,use_embedding_234,use_embedding_235,use_embedding_236,use_embedding_237,use_embedding_238,use_embedding_239,use_embedding_240,use_embedding_241,use_embedding_242,use_embedding_243,use_embedding_244,use_embedding_245,use_embedding_246,use_embedding_247,use_embedding_248,use_embedding_249,use_embedding_250,use_embedding_251,use_embedding_252,use_embedding_253,use_embedding_254,use_embedding_255,use_embedding_256,use_embedding_257,use_embedding_258,use_embedding_259,use_embedding_260,use_embedding_261,use_embedding_262,use_embedding_263,use_embedding_264,use_embedding_265,use_embedding_266,use_embedding_267,use_embedding_268,use_embedding_269,use_embedding_270,use_embedding_271,use_embedding_272,use_embedding_273,use_embedding_274,use_embedding_275,use_embedding_276,use_embedding_277,use_embedding_278,use_embedding_279,use_embedding_280,use_embedding_281,use_embedding_282,use_embedding_283,use_embedding_284,use_embedding_285,use_embedding_286,use_embedding_287,use_embedding_288,use_embedding_289,use_embedding_290,use_embedding_291,use_embedding_292,use_embedding_293,use_embedding_294,use_embedding_295,use_embedding_296,use_embedding_297,use_embedding_298,use_embedding_299,use_embedding_300,use_embedding_301,use_embedding_302,use_embedding_303,use_embedding_304,use_embedding_305,use_embedding_306,use_embedding_307,use_embedding_308,use_embedding_309,use_embedding_310,use_embedding_311,use_embedding_312,use_embedding_313,use_embedding_314,use_embedding_315,use_embedding_316,use_embedding_317,use_embedding_318,use_embedding_319,use_embedding_320,use_embedding_321,use_embedding_322,use_embedding_323,use_embedding_324,use_embedding_325,use_embedding_326,use_embedding_327,use_embedding_328,use_embedding_329,use_embedding_330,use_embedding_331,use_embedding_332,use_embedding_333,use_embedding_334,use_embedding_335,use_embedding_336,use_embedding_337,use_embedding_338,use_embedding_339,use_embedding_340,use_embedding_341,use_embedding_342,use_embedding_343,use_embedding_344,use_embedding_345,use_embedding_346,use_embedding_347,use_embedding_348,use_embedding_349,use_embedding_350,use_embedding_351,use_embedding_352,use_embedding_353,use_embedding_354,use_embedding_355,use_embedding_356,use_embedding_357,use_embedding_358,use_embedding_359,use_embedding_360,use_embedding_361,use_embedding_362,use_embedding_363,use_embedding_364,use_embedding_365,use_embedding_366,use_embedding_367,use_embedding_368,use_embedding_369,use_embedding_370,use_embedding_371,use_embedding_372,use_embedding_373,use_embedding_374,use_embedding_375,use_embedding_376,use_embedding_377,use_embedding_378,use_embedding_379,use_embedding_380,use_embedding_381,use_embedding_382,use_embedding_383,use_embedding_384,use_embedding_385,use_embedding_386,use_embedding_387,use_embedding_388,use_embedding_389,use_embedding_390,use_embedding_391,use_embedding_392,use_embedding_393,use_embedding_394,use_embedding_395,use_embedding_396,use_embedding_397,use_embedding_398,use_embedding_399,use_embedding_400,use_embedding_401,use_embedding_402,use_embedding_403,use_embedding_404,use_embedding_405,use_embedding_406,use_embedding_407,use_embedding_408,use_embedding_409,use_embedding_410,use_embedding_411,use_embedding_412,use_embedding_413,use_embedding_414,use_embedding_415,use_embedding_416,use_embedding_417,use_embedding_418,use_embedding_419,use_embedding_420,use_embedding_421,use_embedding_422,use_embedding_423,use_embedding_424,use_embedding_425,use_embedding_426,use_embedding_427,use_embedding_428,use_embedding_429,use_embedding_430,use_embedding_431,use_embedding_432,use_embedding_433,use_embedding_434,use_embedding_435,use_embedding_436,use_embedding_437,use_embedding_438,use_embedding_439,use_embedding_440,use_embedding_441,use_embedding_442,use_embedding_443,use_embedding_444,use_embedding_445,use_embedding_446,use_embedding_447,use_embedding_448,use_embedding_449,use_embedding_450,use_embedding_451,use_embedding_452,use_embedding_453,use_embedding_454,use_embedding_455,use_embedding_456,use_embedding_457,use_embedding_458,use_embedding_459,use_embedding_460,use_embedding_461,use_embedding_462,use_embedding_463,use_embedding_464,use_embedding_465,use_embedding_466,use_embedding_467,use_embedding_468,use_embedding_469,use_embedding_470,use_embedding_471,use_embedding_472,use_embedding_473,use_embedding_474,use_embedding_475,use_embedding_476,use_embedding_477,use_embedding_478,use_embedding_479,use_embedding_480,use_embedding_481,use_embedding_482,use_embedding_483,use_embedding_484,use_embedding_485,use_embedding_486,use_embedding_487,use_embedding_488,use_embedding_489,use_embedding_490,use_embedding_491,use_embedding_492,use_embedding_493,use_embedding_494,use_embedding_495,use_embedding_496,use_embedding_497,use_embedding_498,use_embedding_499,use_embedding_500,use_embedding_501,use_embedding_502,use_embedding_503,use_embedding_504,use_embedding_505,use_embedding_506,use_embedding_507,use_embedding_508,use_embedding_509,use_embedding_510,use_embedding_511
0,000d118,0.021534,0.379466,0.529225,0.066918,0.002071,0.000785,0.118853,0.174859,0.158128,0.286387,0.150762,0.111011,0.041960,-0.067975,0.063115,-0.026617,0.020445,0.003867,0.009433,-0.055062,-0.053429,-0.068910,0.003696,0.020061,0.010820,0.030742,0.031649,-0.024020,-0.039520,0.064324,-0.042426,0.003099,-0.061533,-0.049349,0.064297,-0.046063,0.027209,-0.001092,0.067016,0.013396,-0.018858,0.005713,-0.046208,0.061453,0.025858,-0.065615,-0.009667,0.020207,0.041979,0.043658,-0.040748,-0.044444,0.070164,0.021018,-0.024099,-0.005362,-0.071371,0.035344,0.041532,-0.023140,-0.058027,0.054723,-0.067398,0.067929,0.044899,0.028260,-0.004224,0.041252,-0.069346,0.029246,0.054705,-0.022725,0.067761,0.011572,-0.046673,-0.065254,0.038006,-0.054666,0.054993,0.048035,-0.067260,0.068754,-0.059997,0.070202,0.001794,0.000592,-0.037192,0.068251,0.023958,0.017307,0.020281,0.061545,0.071371,0.021947,0.012009,0.019711,-0.023376,-0.067905,0.039303,-0.029714,0.063064,0.002921,-0.040765,-0.047585,0.016403,-0.044314,0.046679,-0.009566,0.059428,0.070486,0.069928,-0.065749,-0.018764,0.042294,0.006362,-0.023871,0.030309,0.016379,-0.041109,-0.032971,0.002925,0.018498,0.000143,0.058467,0.000987,-0.038852,-0.036589,-0.054337,0.059496,-0.042548,-0.046451,-0.031428,-0.010024,0.042607,-0.045928,0.063880,0.038856,0.024155,0.070443,-0.006666,-0.056390,-0.035999,0.051709,0.064817,0.047425,-0.045911,-0.049027,0.030614,-0.040154,0.063312,-0.032446,0.036782,-0.039622,0.071370,0.012913,-0.008181,-0.034732,-0.033297,-0.015363,-0.058130,-0.053483,0.020124,-0.053279,-0.041406,-0.048052,-0.035815,-0.013730,0.037375,-0.017255,0.020483,0.002358,0.023412,-0.012597,-0.053291,0.033583,-0.010574,-0.003540,-0.069473,0.071366,0.054643,-0.068388,-0.064088,0.066670,-0.038012,0.019919,-0.004788,-0.064347,0.001131,0.068402,0.000661,-0.067122,-0.003331,0.063472,-0.051861,-0.044486,-0.050887,0.057314,-0.029539,-0.031860,-0.036725,0.041054,-0.053439,-0.004333,-0.036958,-0.066456,0.051601,0.051689,-0.027728,-0.046687,-0.014484,0.041124,-0.049070,-0.050803,-0.013115,0.030927,-0.027560,0.024903,0.045176,0.060203,-0.064167,-0.015315,0.039040,-0.001104,-0.030634,0.052694,0.065995,-0.006444,-0.038799,-0.034884,-0.061379,-0.064539,-0.063232,-0.057870,-0.020313,-0.040312,-0.037624,-0.005407,0.001163,-0.055657,-0.018361,-0.064925,-0.015646,0.006727,0.008707,-0.011466,-0.071371,-0.044108,-0.032368,-0.003105,-0.038499,-0.031501,-0.023844,0.054657,0.063964,0.051588,-0.051797,-0.030078,0.014294,0.035134,0.007030,-0.060549,0.064968,0.066650,-0.027763,-0.058404,-0.016382,0.058279,0.018375,0.040670,0.071371,0.065500,-0.014465,-0.038476,0.059109,-0.067125,-0.049336,-0.063630,0.021852,0.019758,-0.002733,0.006326,-0.024114,0.011878,-0.014790,0.043370,0.023703,0.050950,0.071371,0.059837,0.039993,0.038431,0.051483,0.044776,0.000354,0.047293,-0.005842,-0.054922,-0.042430,0.001070,0.045360,-0.020034,-0.044304,-0.014710,0.066070,0.071367,-0.049273,0.070306,-0.003790,-0.036913,-0.069527,-0.024357,0.055035,-0.023613,0.040803,-0.017518,-0.004023,0.059491,0.027278,-0.047328,-0.066081,0.019251,-0.037691,0.066000,0.024990,-0.030948,0.068791,-0.009601,0.002681,0.056763,-0.062401,0.071371,-0.060261,-0.024053,0.023458,-0.032442,-0.064972,-0.049233,0.034958,0.069878,0.040890,-0.067782,-0.041387,0.037316,0.007718,0.061763,0.066382,-0.058967,-0.071254,-0.071371,0.011155,-0.025287,-0.022174,0.047553,-0.058263,0.024759,0.029193,-0.024868,-0.054448,-0.002453,-0.027240,0.032908,-0.056552,0.011536,0.021389,0.057826,0.000437,-0.071370,-0.007521,-0.071364,0.014566,0.008622,0.042498,-0.066004,0.041452,0.059630,0.070452,-0.006149,-0.039841,0.071189,0.017589,0.064986,-0.013094,0.043275,0.020360,0.046465,-0.052584,-0.010322,0.042739,0.016355,-0.065323,-0.027748,-0.071104,0.040146,-0.046841,-0.038165,-0.020255,0.053590,-0.071151,0.067579,0.049357,0.041716,-0.070446,0.032949,0.057034,0.039261,0.026086,-0.015122,-0.050257,-0.031067,-0.032788,-0.003558,0.013688,0.039404,-0.039750,0.042409,-0.064589,-0.041032,0.067824,-0.049411,0.017081,-0.066030,-0.066868,0.007367,-0.070757,-0.029886,-0.026018,0.018590,0.005558,0.059106,0.001964,0.026464,0.066635,-0.019242,-0.034284,0.049228,-0.071371,-0.007047,0.019111,-0.038933,0.071341,0.036698,-0.025863,-0.024102,0.011815,0.041411,0.065308,-0.045996,-0.023617,0.032700,0.028220,0.021491,0.002222,-0.050719,0.002196,0.056928,-0.056453,0.043710,0.000036,-0.014522,-0.024649,-0.065260,-0.031657,0.040400,0.065655,0.026706,0.033668,0.039243,-0.071263,0.011052,0.069375,0.034212,-0.013674,-0.021122,-0.050833,0.007043,0.045696,-0.069217,0.056066,-0.058675,0.029123,0.032382,-0.006292,0.006040,-0.010777,-0.063777,-0.061843,0.020677,0.060870,-0.049698,0.011714,0.069174,-0.071364,0.013807,-0.062454,0.005369,-0.071131,-0.004194,0.016565,0.053957,0.056543,-0.010677,0.061315,-0.043281,-0.044195,-0.049923,0.033462,0.021511,0.032322,0.066321,-0.019292,-0.032224,-0.042763,0.064419,0.003147,-0.050996,-0.071371,0.003971,-0.067729,-0.057812,0.008325,-0.067852,0.034543,0.036840,0.023667
1,000fe60,0.001421,0.071248,0.839510,0.086768,0.000765,0.000288,0.116731,0.167865,0.149173,0.298451,0.157676,0.110105,-0.051479,-0.021961,0.028500,0.046144,0.066032,-0.067002,-0.021723,0.052850,-0.017364,-0.019699,0.020906,0.001037,-0.040863,0.051007,0.002075,-0.066549,-0.052261,0.049969,-0.031710,-0.040906,-0.035889,0.026802,0.037872,0.067021,0.044432,0.000260,0.003485,0.029175,0.059963,0.010278,-0.062609,0.033071,-0.035046,-0.026370,-0.064978,-0.062706,-0.036433,0.046896,0.000985,0.048611,0.027040,-0.048923,-0.065221,-0.037086,-0.065955,0.061284,0.020419,-0.057120,0.006482,0.019873,-0.060475,0.066505,0.041101,0.063308,0.005009,-0.010041,-0.053509,0.019620,0.052488,0.035222,0.065084,-0.067002,0.008657,-0.062776,-0.061192,-0.065175,-0.042654,-0.064762,-0.004593,0.058477,-0.067005,0.064837,0.010205,-0.045082,-0.040998,-0.032445,0.065940,0.030846,0.056887,0.040423,0.067011,0.032525,-0.032819,-0.004531,-0.056104,-0.047383,-0.059658,-0.050210,-0.060052,0.014958,-0.014195,0.032115,-0.025213,0.012917,-0.023260,0.041962,0.041418,0.065898,0.067020,-0.033995,0.011879,0.054088,-0.033447,0.028367,-0.053240,0.039212,-0.061964,0.059464,-0.043827,-0.051984,-0.021650,0.023439,0.031394,-0.001974,-0.054017,-0.037773,-0.011044,0.045843,-0.066827,0.026491,0.004700,-0.003484,-0.044614,0.051810,0.000436,-0.011676,0.066958,-0.067003,0.048434,-0.043947,0.014173,0.067021,-0.004581,0.032035,-0.012303,-0.040991,-0.056477,-0.053691,-0.058233,-0.010542,-0.066287,0.066543,0.019010,0.021237,0.067000,0.031089,-0.027444,-0.019946,-0.035823,-0.024304,-0.018887,-0.058063,0.013828,0.051214,0.013180,-0.006692,-0.014195,0.036092,-0.058373,-0.038636,0.010424,0.008642,0.049344,-0.003114,-0.060982,0.039349,0.066387,0.001091,-0.059071,-0.066322,0.060390,0.020047,-0.054678,-0.022469,-0.040458,-0.030480,0.065721,0.002643,-0.045563,-0.042620,-0.059654,0.020804,-0.065161,0.001976,-0.062852,0.030460,0.062039,-0.048913,0.036090,0.018646,0.037559,-0.048654,-0.000206,-0.048885,-0.000221,-0.015980,0.038679,-0.019721,-0.040000,0.042993,0.028629,-0.017034,-0.030301,0.033707,0.033675,-0.049585,0.061736,-0.032425,0.030514,-0.067013,-0.007081,0.010512,-0.012522,0.054985,-0.057914,-0.018753,0.027773,-0.066142,-0.033433,-0.009461,0.012417,-0.031640,-0.043996,-0.055336,-0.043127,-0.025196,-0.060108,0.022734,0.036739,0.038120,0.065899,0.027284,-0.011504,-0.067021,-0.023898,0.064792,-0.033563,0.048967,-0.047272,-0.005843,0.058259,0.033669,-0.006504,-0.044859,-0.019406,0.043046,0.009882,0.052062,-0.010808,0.059840,0.062612,0.006401,-0.044627,-0.060283,0.065039,0.015543,-0.063099,0.067021,0.013384,0.003180,0.063062,0.026004,-0.030277,0.025539,0.061139,-0.040113,0.057921,-0.047227,-0.016565,0.059296,0.024480,0.055017,-0.007139,0.048058,-0.050762,0.016345,-0.063273,-0.063621,0.066682,0.027299,-0.051662,-0.056344,0.041896,0.054822,-0.015531,-0.008632,0.052533,0.064902,-0.034600,-0.045894,-0.034633,-0.052690,0.066999,0.056311,0.047240,-0.046792,-0.004646,-0.029737,-0.062470,0.064299,-0.035579,0.059590,-0.020649,-0.006715,-0.066158,0.026028,0.009596,-0.038528,-0.060089,0.013946,0.053846,0.024153,0.055554,-0.034467,0.048546,0.049149,0.044983,-0.056929,0.066954,0.057209,0.063011,-0.048788,0.035786,-0.065445,0.014469,-0.014805,-0.052418,0.026075,0.025840,-0.065531,0.029024,-0.060700,-0.018071,0.040578,-0.066716,0.032717,0.049908,0.045795,0.033240,-0.021871,0.036630,-0.012704,0.052266,0.041658,-0.063919,-0.046185,0.060374,0.010215,-0.009218,-0.007089,-0.018702,0.061406,0.064759,0.061264,0.049647,-0.055409,-0.066946,-0.063784,0.030436,-0.065794,-0.062857,-0.021844,0.066589,0.066004,0.012869,-0.034649,0.064070,0.046278,0.062397,0.066689,0.010447,0.060377,0.023742,-0.065541,-0.023657,0.024724,0.018777,0.040129,0.004834,-0.039282,0.065957,0.043373,-0.030512,-0.034230,0.053910,-0.062529,0.036950,-0.029817,0.021001,0.067009,0.011278,-0.057214,0.060464,-0.021033,-0.066924,-0.020412,-0.058390,0.035072,0.053230,0.004231,-0.051832,0.023478,0.051619,-0.027542,0.037266,-0.027557,-0.027899,0.043979,-0.062473,0.015535,-0.062917,0.049793,-0.044933,-0.058138,0.025258,0.058518,0.051512,0.038653,0.036127,0.067021,0.047591,-0.001700,-0.036168,0.051094,0.059034,0.029016,-0.043924,0.066861,-0.008969,-0.055409,0.057114,-0.050352,0.024322,-0.040760,-0.051975,0.024613,-0.001890,-0.006649,-0.052705,-0.057253,-0.044619,0.000504,0.050173,0.030599,-0.063234,0.020349,0.028310,0.060774,-0.009020,0.052508,0.062168,0.065920,-0.030328,-0.019231,0.000001,-0.065773,-0.034343,0.018724,-0.014764,-0.044333,0.020038,0.050004,0.010134,0.051897,-0.067003,-0.049477,0.020499,0.005765,-0.026884,0.055708,-0.044731,0.015931,0.032537,-0.065933,0.061594,0.059759,0.045386,-0.041905,-0.061628,-0.066671,0.000463,-0.017599,-0.061341,-0.062759,-0.051816,-0.025417,0.029997,0.019344,0.062147,-0.048258,-0.000873,-0.007189,0.016317,-0.001390,0.040245,0.011546,-0.061655,-0.034496,-0.009525,-0.054707,0.020701,0.061149,-0.026610,-0.066975,0.061543,0.047325,-0.059555,0.040239,-0.001867,0.054495,-0.043866,-0.059719

In [10]:
# set file paths for either laptop or desktop

if laptop:

    file_config = {

        'vectorizer': '/home/laptop/github/kaggle/scoring/model_data/sklearn/vectorizer.pkl',
        'lda_model': '/home/laptop/github/kaggle/scoring/model_data/sklearn/lda_model.pkl',
        'tf_vectorizer': '/home/laptop/github/kaggle/scoring/model_data/sklearn/tf_vectorizer.pkl',
        'feature_cols': '/home/laptop/github/kaggle/scoring/model_data/sklearn/feature_cols.txt',
        'scaler': '/home/laptop/github/kaggle/scoring/model_data/sklearn/scaler.pkl',   
        'top_corelations': '/home/laptop/github/kaggle/scoring/model_data/sklearn/top_corelations.txt',
        'sklearn_model': '/home/laptop/github/kaggle/scoring/model_data/sklearn/sklearn_model.joblib'}
    
if not laptop:

    file_config = {
        'vectorizer': '/home/jack/github/kaggle/scoring/model_data/sklearn/vectorizer.pkl',
        'lda_model': '/home/jack/github/kaggle/scoring/model_data/sklearn/lda_model.pkl',
        'tf_vectorizer': '/home/jack/github/kaggle/scoring/model_data/sklearn/tf_vectorizer.pkl',
        'feature_cols': '/home/jack/github/kaggle/scoring/model_data/sklearn/feature_cols.txt',
        'scaler': '/home/jack/github/kaggle/scoring/model_data/sklearn/scaler.pkl',   
        'top_corelations': '/home/jack/github/kaggle/scoring/model_data/sklearn/top_corelations.txt',
        'sklearn_model': '/home/jack/github/kaggle/scoring/model_data/sklearn/sklearn_model.joblib'}

In [11]:
if laptop:
    csv_path = '/home/laptop/github/kaggle/scoring/data/train.csv'

if not laptop:
    csv_path = '/home/jack/github/kaggle/scoring/data/train.csv'

In [12]:
train = pd.read_csv(csv_path)

In [13]:
train = clean_text(train)

train.head()

Starting text cleaning process.

Adding Text Features.................

Complete.................

,essay_id,full_text,score,lowered,clean_text,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score
0,000d118,Many people have car where they live. The thin...,3,many people have car where they live. the thin...,many people have car where they live the thing...,1,13,498,498.000000,498,498,38.307692,127,7,4.369478,25,1,57.98,17.33,0.9937
1,000fe60,I am a scientist at NASA that is discussing th...,3,i am a scientist at nasa that is discussing th...,i am a scientist at nasa that is discussing th...,5,21,332,66.400000,98,37,15.809524,48,2,4.018072,11,1,87.55,7.48,0.7705
2,001ab80,People always wish they had the same technolog...,4,people always wish they had the same technolog...,people always wish they had the same technolog...,4,24,550,137.500000,199,85,22.916667,46,9,4.574545,15,1,65.15,11.49,-0.9731
3,001bdc0,"We all heard about Venus, the planet without a...",4,"we all heard about venus, the planet without a...",we all heard about venus the planet without al...,5,20,451,90.200000,165,25,22.550000,38,5,4.982262,20,1,58.32,11.91,0.9702
4,002ba53,"Dear, State Senator\n\nThis is a letter to arg...",3,"dear, state senator\n\nthis is a letter to arg...",dear state senator this is a letter to argue i...,6,15,373,62.166667,118,2,24.933333,76,2,4.873995,14,1,54.66,12.64,0.9771

In [14]:
print(deberta_full.shape, train.shape)

(17307, 525) (17307, 20)

In [15]:
# Combine train and deberta_full on essay_id

train = train.merge(deberta_full, on='essay_id')

In [16]:
train.head()

,essay_id,full_text,score,lowered,clean_text,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score,deberta_prob_0_full,deberta_prob_1_full,deberta_prob_2_full,deberta_prob_3_full,deberta_prob_4_full,deberta_prob_5_full,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,use_embedding_0,use_embedding_1,use_embedding_2,use_embedding_3,use_embedding_4,use_embedding_5,use_embedding_6,use_embedding_7,use_embedding_8,use_embedding_9,use_embedding_10,use_embedding_11,use_embedding_12,use_embedding_13,use_embedding_14,use_embedding_15,use_embedding_16,use_embedding_17,use_embedding_18,use_embedding_19,use_embedding_20,use_embedding_21,use_embedding_22,use_embedding_23,use_embedding_24,use_embedding_25,use_embedding_26,use_embedding_27,use_embedding_28,use_embedding_29,use_embedding_30,use_embedding_31,use_embedding_32,use_embedding_33,use_embedding_34,use_embedding_35,use_embedding_36,use_embedding_37,use_embedding_38,use_embedding_39,use_embedding_40,use_embedding_41,use_embedding_42,use_embedding_43,use_embedding_44,use_embedding_45,use_embedding_46,use_embedding_47,use_embedding_48,use_embedding_49,use_embedding_50,use_embedding_51,use_embedding_52,use_embedding_53,use_embedding_54,use_embedding_55,use_embedding_56,use_embedding_57,use_embedding_58,use_embedding_59,use_embedding_60,use_embedding_61,use_embedding_62,use_embedding_63,use_embedding_64,use_embedding_65,use_embedding_66,use_embedding_67,use_embedding_68,use_embedding_69,use_embedding_70,use_embedding_71,use_embedding_72,use_embedding_73,use_embedding_74,use_embedding_75,use_embedding_76,use_embedding_77,use_embedding_78,use_embedding_79,use_embedding_80,use_embedding_81,use_embedding_82,use_embedding_83,use_embedding_84,use_embedding_85,use_embedding_86,use_embedding_87,use_embedding_88,use_embedding_89,use_embedding_90,use_embedding_91,use_embedding_92,use_embedding_93,use_embedding_94,use_embedding_95,use_embedding_96,use_embedding_97,use_embedding_98,use_embedding_99,use_embedding_100,use_embedding_101,use_embedding_102,use_embedding_103,use_embedding_104,use_embedding_105,use_embedding_106,use_embedding_107,use_embedding_108,use_embedding_109,use_embedding_110,use_embedding_111,use_embedding_112,use_embedding_113,use_embedding_114,use_embedding_115,use_embedding_116,use_embedding_117,use_embedding_118,use_embedding_119,use_embedding_120,use_embedding_121,use_embedding_122,use_embedding_123,use_embedding_124,use_embedding_125,use_embedding_126,use_embedding_127,use_embedding_128,use_embedding_129,use_embedding_130,use_embedding_131,use_embedding_132,use_embedding_133,use_embedding_134,use_embedding_135,use_embedding_136,use_embedding_137,use_embedding_138,use_embedding_139,use_embedding_140,use_embedding_141,use_embedding_142,use_embedding_143,use_embedding_144,use_embedding_145,use_embedding_146,use_embedding_147,use_embedding_148,use_embedding_149,use_embedding_150,use_embedding_151,use_embedding_152,use_embedding_153,use_embedding_154,use_embedding_155,use_embedding_156,use_embedding_157,use_embedding_158,use_embedding_159,use_embedding_160,use_embedding_161,use_embedding_162,use_embedding_163,use_embedding_164,use_embedding_165,use_embedding_166,use_embedding_167,use_embedding_168,use_embedding_169,use_embedding_170,use_embedding_171,use_embedding_172,use_embedding_173,use_embedding_174,use_embedding_175,use_embedding_176,use_embedding_177,use_embedding_178,use_embedding_179,use_embedding_180,use_embedding_181,use_embedding_182,use_embedding_183,use_embedding_184,use_embedding_185,use_embedding_186,use_embedding_187,use_embedding_188,use_embedding_189,use_embedding_190,use_embedding_191,use_embedding_192,use_embedding_193,use_embedding_194,use_embedding_195,use_embedding_196,use_embedding_197,use_embedding_198,use_embedding_199,use_embedding_200,use_embedding_201,use_embedding_202,use_embedding_203,use_embedding_204,use_embedding_205,use_embedding_206,use_embedding_207,use_embedding_208,use_embedding_209,use_embedding_210,use_embedding_211,use_embedding_212,use_embedding_213,use_embedding_214,use_embedding_215,use_embedding_216,use_embedding_217,use_embedding_218,use_embedding_219,use_embedding_220,use_embedding_221,use_embedding_222,use_embedding_223,use_embedding_224,use_embedding_225,use_embedding_226,use_embedding_227,use_embedding_228,use_embedding_229,use_embedding_230,use_embedding_231,use_embedding_232,use_embedding_233,use_embedding_234,use_embedding_235,use_embedding_236,use_embedding_237,use_embedding_238,use_embedding_239,use_embedding_240,use_embedding_241,use_embedding_242,use_embedding_243,use_embedding_244,use_embedding_245,use_embedding_246,use_embedding_247,use_embedding_248,use_embedding_249,use_embedding_250,use_embedding_251,use_embedding_252,use_embedding_253,use_embedding_254,use_embedding_255,use_embedding_256,use_embedding_257,use_embedding_258,use_embedding_259,use_embedding_260,use_embedding_261,use_embedding_262,use_embedding_263,use_embedding_264,use_embedding_265,use_embedding_266,use_embedding_267,use_embedding_268,use_embedding_269,use_embedding_270,use_embedding_271,use_embedding_272,use_embedding_273,use_embedding_274,use_embedding_275,use_embedding_276,use_embedding_277,use_embedding_278,use_embedding_279,use_embedding_280,use_embedding_281,use_embedding_282,use_embedding_283,use_embedding_284,use_embedding_285,use_embedding_286,use_embedding_287,use_embedding_288,use_embedding_289,use_embedding_290,use_embedding_291,use_embedding_292,use_embedding_293,use_embedding_294,use_embedding_295,use_embedding_296,use_embedding_297,use_embedding_298,use_embedding_299,use_embedding_300,use_embedding_301,use_embedding_302,use_embedding_303,use_embedding_304,use_embedding_305,use_embedding_306,use_embedding_307,use_embedding_308,use_embedding_309,use_embedding_310,use_embedding_311,use_embedding_312,use_embedding_313,use_embedding_314,use_embedding_315,use_embedding_316,use_embedding_317,use_embedding_318,use_embedding_319,use_embedding_320,use_embedding_321,use_embedding_322,use_embedding_323,use_embedding_324,use_embedding_325,use_embedding_326,use_embedding_327,use_embedding_328,use_embedding_329,use_embedding_330,use_embedding_331,use_embedding_332,use_embedding_333,use_embedding_334,use_embedding_335,use_embedding_336,use_embedding_337,use_embedding_338,use_embedding_339,use_embedding_340,use_embedding_341,use_embedding_342,use_embedding_343,use_embedding_344,use_embedding_345,use_embedding_346,use_embedding_347,use_embedding_348,use_embedding_349,use_embedding_350,use_embedding_351,use_embedding_352,use_embedding_353,use_embedding_354,use_embedding_355,use_embedding_356,use_embedding_357,use_embedding_358,use_embedding_359,use_embedding_360,use_embedding_361,use_embedding_362,use_embedding_363,use_embedding_364,use_embedding_365,use_embedding_366,use_embedding_367,use_embedding_368,use_embedding_369,use_embedding_370,use_embedding_371,use_embedding_372,use_embedding_373,use_embedding_374,use_embedding_375,use_embedding_376,use_embedding_377,use_embedding_378,use_embedding_379,use_embedding_380,use_embedding_381,use_embedding_382,use_embedding_383,use_embedding_384,use_embedding_385,use_embedding_386,use_embedding_387,use_embedding_388,use_embedding_389,use_embedding_390,use_embedding_391,use_embedding_392,use_embedding_393,use_embedding_394,use_embedding_395,use_embedding_396,use_embedding_397,use_embedding_398,use_embedding_399,use_embedding_400,use_embedding_401,use_embedding_402,use_embedding_403,use_embedding_404,use_embedding_405,use_embedding_406,use_embedding_407,use_embedding_408,use_embedding_409,use_embedding_410,use_embedding_411,use_embedding_412,use_embedding_413,use_embedding_414,use_embedding_415,use_embedding_416,use_embedding_417,use_embedding_418,use_embedding_419,use_embedding_420,use_embedding_421,use_embedding_422,use_embedding_423,use_embedding_424,use_embedding_425,use_embedding_426,use_embedding_427,use_embedding_428,use_embedding_429,use_embedding_430,use_embedding_431,use_embedding_432,use_embedding_433,use_embedding_434,use_embedding_435,use_embedding_436,use_embedding_437,use_embedding_438,use_embedding_439,use_embedding_440,use_embedding_441,use_embedding_442,use_embedding_443,use_embedding_444,use_embedding_445,use_embedding_446,use_embedding_447,use_embedding_448,use_embedding_449,use_embedding_450,use_embedding_451,use_embedding_452,use_embedding_453,use_embedding_454,use_embedding_455,use_embedding_456,use_embedding_457,use_embedding_458,use_embedding_459,use_embedding_460,use_embedding_461,use_embedding_462,use_embedding_463,use_embedding_464,use_embedding_465,use_embedding_466,use_embedding_467,use_embedding_468,use_embedding_469,use_embedding_470,use_embedding_471,use_embedding_472,use_embedding_473,use_embedding_474,use_embedding_475,use_embedding_476,use_embedding_477,use_embedding_478,use_embedding_479,use_embedding_480,use_embedding_481,use_embedding_482,use_embedding_483,use_embedding_484,use_embedding_485,use_embedding_486,use_embedding_487,use_embedding_488,use_embedding_489,use_embedding_490,use_embedding_491,use_embedding_492,use_embedding_493,use_embedding_494,use_embedding_495,use_embedding_496,use_embedding_497,use_embedding_498,use_embedding_499,use_embedding_500,use_embedding_501,use_embedding_502,use_embedding_503,use_embedding_504,use_embedding_505,use_embedding_506,use_embedding_507,use_embedding_508,use_embedding_509,use_embedding_510,use_embedding_511
0,000d118,Many people have car where they live. The thin...,3,many people have car where they live. the thin...,many people have car where they live the thing...,1,13,498,498.000000,498,498,38.307692,127,7,4.369478,25,1,57.98,17.33,0.9937,0.021534,0.379466,0.529225,0.066918,0.002071,0.000785,0.118853,0.174859,0.158128,0.286387,0.150762,0.111011,0.041960,-0.067975,0.063115,-0.026617,0.020445,0.003867,0.009433,-0.055062,-0.053429,-0.068910,0.003696,0.020061,0.010820,0.030742,0.031649,-0.024020,-0.039520,0.064324,-0.042426,0.003099,-0.061533,-0.049349,0.064297,-0.046063,0.027209,-0.001092,0.067016,0.013396,-0.018858,0.005713,-0.046208,0.061453,0.025858,-0.065615,-0.009667,0.020207,0.041979,0.043658,-0.040748,-0.044444,0.070164,0.021018,-0.024099,-0.005362,-0.071371,0.035344,0.041532,-0.023140,-0.058027,0.054723,-0.067398,0.067929,0.044899,0.028260,-0.004224,0.041252,-0.069346,0.029246,0.054705,-0.022725,0.067761,0.011572,-0.046673,-0.065254,0.038006,-0.054666,0.054993,0.048035,-0.067260,0.068754,-0.059997,0.070202,0.001794,0.000592,-0.037192,0.068251,0.023958,0.017307,0.020281,0.061545,0.071371,0.021947,0.012009,0.019711,-0.023376,-0.067905,0.039303,-0.029714,0.063064,0.002921,-0.040765,-0.047585,0.016403,-0.044314,0.046679,-0.009566,0.059428,0.070486,0.069928,-0.065749,-0.018764,0.042294,0.006362,-0.023871,0.030309,0.016379,-0.041109,-0.032971,0.002925,0.018498,0.000143,0.058467,0.000987,-0.038852,-0.036589,-0.054337,0.059496,-0.042548,-0.046451,-0.031428,-0.010024,0.042607,-0.045928,0.063880,0.038856,0.024155,0.070443,-0.006666,-0.056390,-0.035999,0.051709,0.064817,0.047425,-0.045911,-0.049027,0.030614,-0.040154,0.063312,-0.032446,0.036782,-0.039622,0.071370,0.012913,-0.008181,-0.034732,-0.033297,-0.015363,-0.058130,-0.053483,0.020124,-0.053279,-0.041406,-0.048052,-0.035815,-0.013730,0.037375,-0.017255,0.020483,0.002358,0.023412,-0.012597,-0.053291,0.033583,-0.010574,-0.003540,-0.069473,0.071366,0.054643,-0.068388,-0.064088,0.066670,-0.038012,0.019919,-0.004788,-0.064347,0.001131,0.068402,0.000661,-0.067122,-0.003331,0.063472,-0.051861,-0.044486,-0.050887,0.057314,-0.029539,-0.031860,-0.036725,0.041054,-0.053439,-0.004333,-0.036958,-0.066456,0.051601,0.051689,-0.027728,-0.046687,-0.014484,0.041124,-0.049070,-0.050803,-0.013115,0.030927,-0.027560,0.024903,0.045176,0.060203,-0.064167,-0.015315,0.039040,-0.001104,-0.030634,0.052694,0.065995,-0.006444,-0.038799,-0.034884,-0.061379,-0.064539,-0.063232,-0.057870,-0.020313,-0.040312,-0.037624,-0.005407,0.001163,-0.055657,-0.018361,-0.064925,-0.015646,0.006727,0.008707,-0.011466,-0.071371,-0.044108,-0.032368,-0.003105,-0.038499,-0.031501,-0.023844,0.054657,0.063964,0.051588,-0.051797,-0.030078,0.014294,0.035134,0.007030,-0.060549,0.064968,0.066650,-0.027763,-0.058404,-0.016382,0.058279,0.018375,0.040670,0.071371,0.065500,-0.014465,-0.038476,0.059109,-0.067125,-0.049336,-0.063630,0.021852,0.019758,-0.002733,0.006326,-0.024114,0.011878,-0.014790,0.043370,0.023703,0.050950,0.071371,0.059837,0.039993,0.038431,0.051483,0.044776,0.000354,0.047293,-0.005842,-0.054922,-0.042430,0.001070,0.045360,-0.020034,-0.044304,-0.014710,0.066070,0.071367,-0.049273,0.070306,-0.003790,-0.036913,-0.069527,-0.024357,0.055035,-0.023613,0.040803,-0.017518,-0.004023,0.059491,0.027278,-0.047328,-0.066081,0.019251,-0.037691,0.066000,0.024990,-0.030948,0.068791,-0.009601,0.002681,0.056763,-0.062401,0.071371,-0.060261,-0.024053,0.023458,-0.032442,-0.064972,-0.049233,0.034958,0.069878,0.040890,-0.067782,-0.041387,0.037316,0.007718,0.061763,0.066382,-0.058967,-0.071254,-0.071371,0.011155,-0.025287,-0.022174,0.047553,-0.058263,0.024759,0.029193,-0.024868,-0.054448,-0.002453,-0.027240,0.032908,-0.056552,0.011536,0.021389,0.057826,0.000437,-0.071370,-0.007521,-0.071364,0.014566,0.008622,0.042498,-0.066004,0.041452,0.059630,0.070452,-0.006149,-0.039841,0.071189,0.017589,0.064986,-0.013094,0.043275,0.020360,0.046465,-0.052584,-0.010322,0.042739,0.016355,-0.065323,-0.027748,-0.071104,0.040146,-0.046841,-0.038165,-0.020255,0.053590,-0.071151,0.067579,0.049357,0.041716,-0.070446,0.032949,0.057034,0.039261,0.026086,-0.015122,-0.050257,-0.031067,-0.032788,-0.003558,0.013688,0.039404,-0.039750,0.042409,-0.064589,-0.041032,0.067824,-0.049411,0.017081,-0.066030,-0.066868,0.007367,-0.070757,-0.029886,-0.026018,0.018590,0.005558,0.059106,0.001964,0.026464,0.066635,-0.019242,-0.034284,0.049228,-0.071371,-0.007047,0.019111,-0.038933,0.071341,0.036698,-0.025863,-0.024102,0.011815,0.041411,0.065308,-0.045996,-0.023617,0.032700,0.028220,0.021491,0.002222,-0.050719,0.002196,0.056928,-0.056453,0.043710,0.000036,-0.014522,-0.024649,-0.065260,-0.031657,0.040400,0.065655,0.026706,0.033668,0.039243,-0.071263,0.011052,0.069375,0.034212,-0.013674,-0.021122,-0.050833,0.007043,0.045696,-0.069217,0.056066,-0.058675,0.029123,0.032382,-0.006292,0.006040,-0.010777,-0.063777,-0.061843,0.020677,0.060870,-0.049698,0.011714,0.069174,-0.071364,0.013807,-0.062454,0.005369,-0.071131,-0.004194,0.016565,0.053957,0.056543,-0.010677,0.061315,-0.043281,-0.044195,-0.049923,0.033462,0.021511,0.032322,0.066321,-0.019292,-0.032224,-0.042763,0.064419,0.003147,-0.050996,-0.071371,0.003971,-0.067729,-0.057812,0.008325,-0.067852,0.034543,0.036840,0.023667

In [17]:
print(train.shape)

(17307, 544)

In [18]:
import pandas as pd
import textwrap

# Function to format and print the text
def print_formatted_text(df, column_name, index, width=70):
    """
    Print the text from a specified column and row in a formatted and wrapped manner.

    Args:
        df (pd.DataFrame): The DataFrame containing the text data.
        column_name (str): The name of the column containing the text.
        index (int): The index of the row to print.
        width (int, optional): The maximum width of each line. Defaults to 70.
    """
    if index < 0 or index >= len(df):
        print(f"Index {index} is out of bounds for DataFrame with length {len(df)}.")
        return

    wrapped_text = textwrap.fill(df.at[index, column_name], width=width)
    print(f"Text at index {index}:\n{wrapped_text}\n")

In [19]:
# Usage
print_formatted_text(train, 'full_text', 0 ,  width=50)

Text at index 0:
Many people have car where they live. The thing
they don't know is that when you use a car alot of
thing can happen like you can get in accidet
or the smoke that the car has is bad to breath on
if someone is walk but in VAUBAN,Germany they dont
have that proble because 70 percent of vauban's
families do not own cars,and 57 percent sold a car
to move there. Street parkig ,driveways and home
garages are forbidden on the outskirts of freiburd
that near the French and Swiss borders. You
probaly won't see a car in Vauban's streets
because they are completely "car free" but If some
that lives in VAUBAN that owns a car ownership is
allowed,but there are only two places that you can
park a large garages at the edge of the
development,where a car owner buys a space but it
not cheap to buy one they sell the space for you
car for $40,000 along with a home. The vauban
people completed this in 2006 ,they said that this
an example of a growing trend in Europe,The untile
states and some where else are suburban life from
auto use this is called "smart planning". The
current efforts to drastically reduce greenhouse
gas emissions from tailes the passengee cars are
responsible for 12 percent of greenhouse gas
emissions in Europe and up to 50 percent in some
car intensive in the United States. I honeslty
think that good idea that they did that is Vaudan
because that makes cities denser and better for
walking and in VAUBAN there are 5,500 residents
within a rectangular square mile. In the artical
David Gold berg said that "All of our development
since World war 2 has been centered on the
cars,and that will have to change" and i think
that was very true what David Gold said because
alot thing we need cars to do we can go anyway
were with out cars beacuse some people are a very
lazy to walk to place thats why they alot of
people use car and i think that it was a good idea
that that they did that in VAUBAN so people can
see how we really don't need car to go to place
from place because we can walk from were we need
to go or we can ride bycles with out the use of a
car. It good that they are doing that if you thik
about your help the earth in way and thats a very
good thing to. In the United states ,the
Environmental protection Agency is promoting what
is called "car reduced"communtunties,and the
legislators are starting to act,if cautiously.
Maany experts expect pubic transport serving
suburbs to play a much larger role in a new six
years federal transportation bill to approved this
year. In previous bill,80 percent of
appropriations have by law gone to highways and
only 20 percent to other transports. There many
good reason why they should do this.

In [20]:
print_formatted_text(train, 'clean_text', 0 ,  width=50)

Text at index 0:
many people have car where they live the thing
they do not know is that when you use a car alot
of thing can happen like you can get in accidet or
the smoke that the car has is bad to breath on if
someone is walk but in vauban germany they dont
have that proble because percent of vaubans
families do not own cars and percent sold a car to
move there street parkig driveways and home
garages are forbidden on the outskirts of freiburd
that near the french and swiss borders you probaly
will not see a car in vaubans streets because they
are completely car free but if some that lives in
vauban that owns a car ownership is allowed but
there are only two places that you can park a
large garages at the edge of the development where
a car owner buys a space but it not cheap to buy
one they sell the space for you car for along with
a home the vauban people completed this in they
said that this an example of a growing trend in
europe the untile states and some where else are
suburban life from auto use this is called smart
planning the current efforts to drastically reduce
greenhouse gas emissions from tailes the passengee
cars are responsible for percent of greenhouse gas
emissions in europe and up to percent in some car
intensive in the united states i honeslty think
that good idea that they did that is vaudan
because that makes cities denser and better for
walking and in vauban there are residents within a
rectangular square mile in the artical david gold
berg said that all of our development since world
war has been centered on the cars and that will
have to change and i think that was very true what
david gold said because alot thing we need cars to
do we can go anyway were with out cars beacuse
some people are a very lazy to walk to place thats
why they alot of people use car and i think that
it was a good idea that that they did that in
vauban so people can see how we really do not need
car to go to place from place because we can walk
from were we need to go or we can ride bycles with
out the use of a car it good that they are doing
that if you thik about your help the earth in way
and thats a very good thing to in the united
states the environmental protection agency is
promoting what is called car reducedcommuntunties
and the legislators are starting to act if
cautiously maany experts expect pubic transport
serving suburbs to play a much larger role in a
new six years federal transportation bill to
approved this year in previous bill percent of
appropriations have by law gone to highways and
only percent to other transports there many good
reason why they should do this

In [21]:
df = train.copy()

In [ ]:
# from sklearn.feature_extraction.text import CountVectorizer
# import pandas as pd
# import dill
# import spacy

# # Initialize a CountVectorizer with n-gram range from 1 to 3 (unigrams to trigrams)
# vectorizer = CountVectorizer(ngram_range=(1, 3), max_features=1000, stop_words='english')

# # Initialize and fit the vectorizer
# X_ngrams = vectorizer.fit_transform(df['full_text'])
# df_ngrams = pd.DataFrame(X_ngrams.toarray(), columns=vectorizer.get_feature_names_out())

# # Save the vectorizer
# with open('/home/laptop/github/kaggle/scoring/model_data/sklearn/vectorizer.pkl', 'wb') as f:
#     dill.dump(vectorizer, f)

# # Load the spaCy model
# nlp = spacy.load("en_core_web_sm")

# # Function to count POS tags
# def pos_counts(text):
#     doc = nlp(text)
#     total_tokens = len(doc)
#     pos_counts = doc.count_by(spacy.attrs.POS)
#     return {f'pos_{doc.vocab.strings[pos_id]}': count / total_tokens for pos_id, count in pos_counts.items() if total_tokens > 0}

# # Function to count Named Entities
# def named_entities(text):
#     doc = nlp(text)
#     total_tokens = len(doc)
#     entities = {}
#     for ent in doc.ents:
#         entities[ent.label_] = entities.get(ent.label_, 0) + 1
#     return {f'ner_{label}': count / total_tokens for label, count in entities.items() if total_tokens > 0}

# # Function to count Dependency Tags
# def dependency_tags(text):
#     doc = nlp(text)
#     total_tokens = len(doc)
#     dep_counts = doc.count_by(spacy.attrs.DEP)
#     return {f'dep_{doc.vocab.strings[dep_id]}': count / total_tokens for dep_id, count in dep_counts.items() if total_tokens > 0}

# # Define all possible columns
# all_pos_cols = [f'pos_{pos}' for pos in nlp.get_pipe("tagger").labels]
# all_ent_cols = [f'ner_{ent}' for ent in nlp.get_pipe("ner").labels]
# all_dep_cols = [f'dep_{dep}' for dep in nlp.get_pipe("parser").labels]

# # Extract POS tags, named entities, and dependency tags
# df_pos = df['full_text'].apply(pos_counts).apply(pd.Series).fillna(0)
# df_entities = df['full_text'].apply(named_entities).apply(pd.Series).fillna(0)
# df_deps = df['full_text'].apply(dependency_tags).apply(pd.Series).fillna(0)

# # Ensure all POS, NER, and Dependency columns are present
# for col_list, df_features in [(all_pos_cols, df_pos), (all_ent_cols, df_entities), (all_dep_cols, df_deps)]:
#     for col in col_list:
#         if col not in df_features.columns:
#             df_features[col] = 0

# # Sort columns for consistency
# df_pos = df_pos[sorted(df_pos.columns)]
# df_entities = df_entities[sorted(df_entities.columns)]
# df_deps = df_deps[sorted(df_deps.columns)]

# # Concatenate all feature DataFrames with the original DataFrame
# df = pd.concat([df.reset_index(drop=True), df_ngrams.reset_index(drop=True), 
#                          df_pos.reset_index(drop=True), df_entities.reset_index(drop=True), 
#                          df_deps.reset_index(drop=True)], axis=1)

In [ ]:
# import pandas as pd
# import dill
# import spacy
# import re
# from collections import Counter
# from sklearn.decomposition import LatentDirichletAllocation
# from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
# from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
# from sentence_transformers import SentenceTransformer
# from nltk.corpus import stopwords
# from spellchecker import SpellChecker
# import textstat

# # Load spaCy model
# nlp = spacy.load("en_core_web_sm")
# stop_words = set(stopwords.words('english'))
# sentiment_analyzer = SentimentIntensityAnalyzer()
# spell = SpellChecker()
# bert_model = SentenceTransformer('all-MiniLM-L6-v2')

# text_col = 'clean_text'

# # Define feature extraction functions
# def pos_counts(text):
#     doc = nlp(text)
#     pos_counts = doc.count_by(spacy.attrs.POS)
#     return {f'pos_{doc.vocab.strings[pos_id]}': count for pos_id, count in pos_counts.items()}

# def named_entities(text):
#     doc = nlp(text)
#     entities = {ent.label_: ent for ent in doc.ents}
#     return {f'ner_{label}': count for label, count in entities.items()}

# def dependency_tags(text):
#     doc = nlp(text)
#     dep_counts = doc.count_by(spacy.attrs.DEP)
#     return {f'dep_{doc.vocab.strings[dep_id]}': count for dep_id, count in dep_counts.items()}

# def compute_linguistic_features(text):
#     doc = nlp(text)
#     tenses = [token.tag_ for token in doc if token.pos_ == "VERB"]
#     tense_counts = Counter(tenses)
#     most_common_tense = tense_counts.most_common(1)[0][0] if tense_counts else None
#     verb_tense_consistency = tense_counts[most_common_tense] / len(tenses) if tenses else 0
#     passive_count = sum(1 for token in doc if token.dep_ == "nsubjpass")
#     passive_voice_usage = passive_count / len([token for token in doc if token.pos_ == "VERB"]) if doc else 0
#     modal_verbs = {"can", "could", "will", "would", "shall", "should", "may", "might", "must"}
#     modal_count = sum(1 for token in doc if token.lemma_ in modal_verbs)
#     modal_verb_usage = modal_count / len(doc) if doc else 0
#     lexical_diversity = len(set(doc)) / len(doc) if doc else 0
#     dale_chall_readability = textstat.dale_chall_readability_score(text)
#     automated_readability_index = textstat.automated_readability_index(text)
#     coleman_liau_index = textstat.coleman_liau_index(text)
#     conjunction_count = sum(1 for token in doc if token.pos_ in {"CCONJ", "SCONJ"})
#     clause_count = sum(1 for token in doc if token.dep_ in {"csubj", "advcl", "ccomp", "xcomp"})
#     clause_density = clause_count / max(len([token for token in doc if token.dep_ in {"ROOT", "nsubj"}]), 1)
#     return {
#         "verb_tense_consistency": verb_tense_consistency,
#         "passive_voice_usage": passive_voice_usage,
#         "modal_verb_usage": modal_verb_usage,
#         "lexical_diversity": lexical_diversity,
#         "dale_chall_readability": dale_chall_readability,
#         "automated_readability_index": automated_readability_index,
#         "coleman_liau_index": coleman_liau_index,
#         "conjunction_usage": conjunction_count,
#         "clause_density": clause_density
#     }

# def compute_sentiment_features(text):
#     sentiment_scores = sentiment_analyzer.polarity_scores(text)
#     return {
#         "vader_compound": sentiment_scores["compound"],
#         "vader_positive": sentiment_scores["pos"],
#         "vader_negative": sentiment_scores["neg"],
#         "vader_neutral": sentiment_scores["neu"]
#     }

# def extract_bert_embedding(text):
#     embedding = bert_model.encode([text])[0]
#     return {f'bert_dim_{i}': value for i, value in enumerate(embedding)}

# def extract_topic_features(text, lda_model, vectorizer):
#     text_vector = vectorizer.transform([text])
#     topic_distribution = lda_model.transform(text_vector)[0]
#     return {f'topic_{i}': prob for i, prob in enumerate(topic_distribution)}

# def extract_spelling_grammar_errors(text):
#     misspelled = spell.unknown(text.split())
#     return {
#         "spelling_errors": len(misspelled),
#         "grammar_errors": sum(1 for token in nlp(text) if token.dep_ == "pcomp")
#     }

# def compute_advanced_readability_scores(text):
#     return {
#         "linsear_write_formula": textstat.linsear_write_formula(text),
#         "ari_score": textstat.automated_readability_index(text),
#     }

# def apply_feature_extraction(df, lda_model, vectorizer):
#     df_pos = df[text_col].apply(pos_counts).apply(pd.Series).fillna(0)
#     df_entities = df[text_col].apply(named_entities).apply(pd.Series).fillna(0)
#     df_deps = df[text_col].apply(dependency_tags).apply(pd.Series).fillna(0)
#     df_linguistic = df[text_col].apply(compute_linguistic_features).apply(pd.Series)
#     df_sentiment = df[text_col].apply(compute_sentiment_features).apply(pd.Series)
#     df_bert = df[text_col].apply(extract_bert_embedding).apply(pd.Series)
#     df_topics = df[text_col].apply(lambda x: extract_topic_features(x, lda_model, vectorizer)).apply(pd.Series)
#     df_spelling_grammar = df[text_col].apply(extract_spelling_grammar_errors).apply(pd.Series)
#     df_readability = df[text_col].apply(compute_advanced_readability_scores).apply(pd.Series)
#     return pd.concat([df.reset_index(drop=True), df_pos.reset_index(drop=True), 
#                       df_entities.reset_index(drop=True), df_deps.reset_index(drop=True), 
#                       df_linguistic.reset_index(drop=True), df_sentiment.reset_index(drop=True),
#                       df_bert.reset_index(drop=True), df_topics.reset_index(drop=True),
#                       df_spelling_grammar.reset_index(drop=True),
#                       df_readability.reset_index(drop=True)], axis=1)

# # Train LDA topic model
# tf_vectorizer = TfidfVectorizer(max_features=200, stop_words='english')
# tf = tf_vectorizer.fit_transform(df[text_col])
# lda_model = LatentDirichletAllocation(n_components=10, random_state=42)
# lda_model.fit(tf)

# # Apply feature extraction
# df_train_features = apply_feature_extraction(df, lda_model, tf_vectorizer)

# # Save the LDA model and vectorizers
# with open('/home/jack/github/kaggle/scoring/model_data/sklearn/lda_model.pkl', 'wb') as f:
#     dill.dump(lda_model, f)
# with open('/home/jack/github/kaggle/scoring/model_data/sklearn/vectorizer.pkl', 'wb') as f:
#     dill.dump(vectorizer, f)
# with open('/home/jack/github/kaggle/scoring/model_data/sklearn/tf_vectorizer.pkl', 'wb') as f:
#     dill.dump(tf_vectorizer, f)

# # Initialize and fit the CountVectorizer for n-grams
# X_ngrams_train = vectorizer.fit_transform(df[text_col])
# df_ngrams_train = pd.DataFrame(X_ngrams_train.toarray(), columns=vectorizer.get_feature_names_out())

# # Combine all features
# df_train_combined = pd.concat([df_train_features.reset_index(drop=True), df_ngrams_train.reset_index(drop=True)], axis=1)
# df = df_train_combined.copy()

In [22]:
import pandas as pd
import dill
import spacy
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sentence_transformers import SentenceTransformer
from nltk.corpus import stopwords
from spellchecker import SpellChecker
import textstat
from collections import Counter

# Load spaCy model
nlp = spacy.load("en_core_web_sm")
stop_words = set(stopwords.words('english'))
sentiment_analyzer = SentimentIntensityAnalyzer()
spell = SpellChecker()
bert_model = SentenceTransformer('all-MiniLM-L6-v2')

text_col = 'full_text'

# Initialize a CountVectorizer with n-gram range from 1 to 3 (unigrams to trigrams)
vectorizer = CountVectorizer(ngram_range=(1, 3), max_features=500, stop_words='english')

# Initialize and fit the vectorizer
X_ngrams_train = vectorizer.fit_transform(df[text_col])
df_ngrams_train = pd.DataFrame(X_ngrams_train.toarray(), columns=vectorizer.get_feature_names_out())

# Save the vectorizer
with open(file_config['vectorizer'], 'wb') as f:
    dill.dump(vectorizer, f)

# Train LDA topic model

# tf_vectorizer = TfidfVectorizer(max_features=200, stop_words='english')
# tf = tf_vectorizer.fit_transform(df[text_col])

# lda_model = LatentDirichletAllocation(n_components=10, random_state=42)
# lda_model.fit(tf)

# Save the LDA model and vectorizers

# with open(file_config['lda_model'], 'wb') as f:
#     dill.dump(lda_model, f)
    
# with open(file_config['tf_vectorizer'], 'wb') as f:
#     dill.dump(tf_vectorizer, f)

# Define feature extraction functions
def pos_counts(text):
    doc = nlp(text)
    total_tokens = len(doc)
    pos_counts = doc.count_by(spacy.attrs.POS)
    pos_features = {f'pos_{doc.vocab.strings[pos_id]}_count': count for pos_id, count in pos_counts.items()}
    pos_ratios = {f'pos_{doc.vocab.strings[pos_id]}_ratio': count / total_tokens for pos_id, count in pos_counts.items() if total_tokens > 0}
    return {**pos_features, **pos_ratios}

def named_entities(text):
    doc = nlp(text)
    total_tokens = len(doc)
    entities = {}
    for ent in doc.ents:
        entities[ent.label_] = entities.get(ent.label_, 0) + 1
    entity_features = {f'ner_{label}_count': count for label, count in entities.items()}
    entity_ratios = {f'ner_{label}_ratio': count / total_tokens for label, count in entities.items() if total_tokens > 0}
    return {**entity_features, **entity_ratios}

def dependency_tags(text):
    doc = nlp(text)
    total_tokens = len(doc)
    dep_counts = doc.count_by(spacy.attrs.DEP)
    dep_features = {f'dep_{doc.vocab.strings[dep_id]}_count': count for dep_id, count in dep_counts.items()}
    dep_ratios = {f'dep_{doc.vocab.strings[dep_id]}_ratio': count / total_tokens for dep_id, count in dep_counts.items() if total_tokens > 0}
    return {**dep_features, **dep_ratios}

def compute_linguistic_features(text):
    doc = nlp(text)
    tenses = [token.tag_ for token in doc if token.pos_ == "VERB"]
    tense_counts = Counter(tenses)
    most_common_tense = tense_counts.most_common(1)[0][0] if tense_counts else None
    verb_tense_consistency = tense_counts[most_common_tense] / len(tenses) if tenses else 0

    verbs = [token for token in doc if token.pos_ == "VERB"]
    passive_count = sum(1 for token in doc if token.dep_ == "nsubjpass")
    passive_voice_usage = passive_count / len(verbs) if verbs else 0

    modal_verbs = {"can", "could", "will", "would", "shall", "should", "may", "might", "must"}
    modal_count = sum(1 for token in doc if token.lemma_ in modal_verbs)
    modal_verb_usage = modal_count / len(doc) if len(doc) > 0 else 0

    lexical_diversity = len(set(doc)) / len(doc) if len(doc) > 0 else 0

    dale_chall_readability = textstat.dale_chall_readability_score(text)
    automated_readability_index = textstat.automated_readability_index(text)
    coleman_liau_index = textstat.coleman_liau_index(text)

    conjunction_count = sum(1 for token in doc if token.pos_ in {"CCONJ", "SCONJ"})
    clause_count = sum(1 for token in doc if token.dep_ in {"csubj", "advcl", "ccomp", "xcomp"})
    clause_density = clause_count / max(len([token for token in doc if token.dep_ in {"ROOT", "nsubj"}]), 1)

    return {
        "verb_tense_consistency": verb_tense_consistency,
        "passive_voice_usage": passive_voice_usage,
        "modal_verb_usage": modal_verb_usage,
        "lexical_diversity": lexical_diversity,
        "dale_chall_readability": dale_chall_readability,
        "automated_readability_index": automated_readability_index,
        "coleman_liau_index": coleman_liau_index,
        "conjunction_usage": conjunction_count,
        "clause_density": clause_density
    }

def compute_sentiment_features(text):
    sentiment_scores = sentiment_analyzer.polarity_scores(text)
    return {
        "vader_compound": sentiment_scores["compound"],
        "vader_positive": sentiment_scores["pos"],
        "vader_negative": sentiment_scores["neg"],
        "vader_neutral": sentiment_scores["neu"]
    }

def extract_bert_embedding(text):
    embedding = bert_model.encode([text])[0]
    return {f'bert_dim_{i}': value for i, value in enumerate(embedding)}

def extract_topic_features(text, lda_model, vectorizer):
    text_vector = vectorizer.transform([text])
    topic_distribution = lda_model.transform(text_vector)[0]
    return {f'topic_{i}': prob for i, prob in enumerate(topic_distribution)}

def extract_spelling_grammar_errors(text):
    misspelled = spell.unknown(text.split())
    return {
        "spelling_errors": len(misspelled),
        "grammar_errors": sum(1 for token in nlp(text) if token.dep_ == "pcomp")
    }

def compute_advanced_readability_scores(text):
    return {
        "linsear_write_formula": textstat.linsear_write_formula(text),
        "ari_score": textstat.automated_readability_index(text),
    }

def apply_feature_extraction(df, lda_model=None, vectorizer=None):
    df_pos = df[text_col].apply(pos_counts).apply(pd.Series).fillna(0)
    df_entities = df[text_col].apply(named_entities).apply(pd.Series).fillna(0)
    df_deps = df[text_col].apply(dependency_tags).apply(pd.Series).fillna(0)
    # df_linguistic = df[text_col].apply(compute_linguistic_features).apply(pd.Series)
    # df_sentiment = df[text_col].apply(compute_sentiment_features).apply(pd.Series)

    # df_bert = df[text_col].apply(extract_bert_embedding).apply(pd.Series)
    # df_topics = df[text_col].apply(lambda x: extract_topic_features(x, lda_model, vectorizer)).apply(pd.Series)

    df_spelling_grammar = df[text_col].apply(extract_spelling_grammar_errors).apply(pd.Series)
    df_readability = df[text_col].apply(compute_advanced_readability_scores).apply(pd.Series)
    
    return pd.concat([df.reset_index(drop=True), df_pos.reset_index(drop=True), 
                      df_entities.reset_index(drop=True), df_deps.reset_index(drop=True), 
                    #   df_linguistic.reset_index(drop=True), df_sentiment.reset_index(drop=True),
                      df_spelling_grammar.reset_index(drop=True),
                      df_readability.reset_index(drop=True)], axis=1)    # df_bert.reset_index(drop=True), df_topics.reset_index(drop=True)
                      

# Apply feature extraction
df_train_features = apply_feature_extraction(df) # , lda_model, tf_vectorizer)

# Combine all features
df_train_combined = pd.concat([df_train_features.reset_index(drop=True), df_ngrams_train.reset_index(drop=True)], axis=1)

df = df_train_combined.copy()

/home/jack/envs/scoring/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [23]:
df.head()

,essay_id,full_text,score,lowered,clean_text,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score,deberta_prob_0_full,deberta_prob_1_full,deberta_prob_2_full,deberta_prob_3_full,deberta_prob_4_full,deberta_prob_5_full,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,use_embedding_0,use_embedding_1,use_embedding_2,use_embedding_3,use_embedding_4,use_embedding_5,use_embedding_6,use_embedding_7,use_embedding_8,use_embedding_9,use_embedding_10,use_embedding_11,use_embedding_12,use_embedding_13,use_embedding_14,use_embedding_15,use_embedding_16,use_embedding_17,use_embedding_18,use_embedding_19,use_embedding_20,use_embedding_21,use_embedding_22,use_embedding_23,use_embedding_24,use_embedding_25,use_embedding_26,use_embedding_27,use_embedding_28,use_embedding_29,use_embedding_30,use_embedding_31,use_embedding_32,use_embedding_33,use_embedding_34,use_embedding_35,use_embedding_36,use_embedding_37,use_embedding_38,use_embedding_39,use_embedding_40,use_embedding_41,use_embedding_42,use_embedding_43,use_embedding_44,use_embedding_45,use_embedding_46,use_embedding_47,use_embedding_48,use_embedding_49,use_embedding_50,use_embedding_51,use_embedding_52,use_embedding_53,use_embedding_54,use_embedding_55,use_embedding_56,use_embedding_57,use_embedding_58,use_embedding_59,use_embedding_60,use_embedding_61,use_embedding_62,use_embedding_63,use_embedding_64,use_embedding_65,use_embedding_66,use_embedding_67,use_embedding_68,use_embedding_69,use_embedding_70,use_embedding_71,use_embedding_72,use_embedding_73,use_embedding_74,use_embedding_75,use_embedding_76,use_embedding_77,use_embedding_78,use_embedding_79,use_embedding_80,use_embedding_81,use_embedding_82,use_embedding_83,use_embedding_84,use_embedding_85,use_embedding_86,use_embedding_87,use_embedding_88,use_embedding_89,use_embedding_90,use_embedding_91,use_embedding_92,use_embedding_93,use_embedding_94,use_embedding_95,use_embedding_96,use_embedding_97,use_embedding_98,use_embedding_99,use_embedding_100,use_embedding_101,use_embedding_102,use_embedding_103,use_embedding_104,use_embedding_105,use_embedding_106,use_embedding_107,use_embedding_108,use_embedding_109,use_embedding_110,use_embedding_111,use_embedding_112,use_embedding_113,use_embedding_114,use_embedding_115,use_embedding_116,use_embedding_117,use_embedding_118,use_embedding_119,use_embedding_120,use_embedding_121,use_embedding_122,use_embedding_123,use_embedding_124,use_embedding_125,use_embedding_126,use_embedding_127,use_embedding_128,use_embedding_129,use_embedding_130,use_embedding_131,use_embedding_132,use_embedding_133,use_embedding_134,use_embedding_135,use_embedding_136,use_embedding_137,use_embedding_138,use_embedding_139,use_embedding_140,use_embedding_141,use_embedding_142,use_embedding_143,use_embedding_144,use_embedding_145,use_embedding_146,use_embedding_147,use_embedding_148,use_embedding_149,use_embedding_150,use_embedding_151,use_embedding_152,use_embedding_153,use_embedding_154,use_embedding_155,use_embedding_156,use_embedding_157,use_embedding_158,use_embedding_159,use_embedding_160,use_embedding_161,use_embedding_162,use_embedding_163,use_embedding_164,use_embedding_165,use_embedding_166,use_embedding_167,use_embedding_168,use_embedding_169,use_embedding_170,use_embedding_171,use_embedding_172,use_embedding_173,use_embedding_174,use_embedding_175,use_embedding_176,use_embedding_177,use_embedding_178,use_embedding_179,use_embedding_180,use_embedding_181,use_embedding_182,use_embedding_183,use_embedding_184,use_embedding_185,use_embedding_186,use_embedding_187,use_embedding_188,use_embedding_189,use_embedding_190,use_embedding_191,use_embedding_192,use_embedding_193,use_embedding_194,use_embedding_195,use_embedding_196,use_embedding_197,use_embedding_198,use_embedding_199,use_embedding_200,use_embedding_201,use_embedding_202,use_embedding_203,use_embedding_204,use_embedding_205,use_embedding_206,use_embedding_207,use_embedding_208,use_embedding_209,use_embedding_210,use_embedding_211,use_embedding_212,use_embedding_213,use_embedding_214,use_embedding_215,use_embedding_216,use_embedding_217,use_embedding_218,use_embedding_219,use_embedding_220,use_embedding_221,use_embedding_222,use_embedding_223,use_embedding_224,use_embedding_225,use_embedding_226,use_embedding_227,use_embedding_228,use_embedding_229,use_embedding_230,use_embedding_231,use_embedding_232,use_embedding_233,use_embedding_234,use_embedding_235,use_embedding_236,use_embedding_237,use_embedding_238,use_embedding_239,use_embedding_240,use_embedding_241,use_embedding_242,use_embedding_243,use_embedding_244,use_embedding_245,use_embedding_246,use_embedding_247,use_embedding_248,use_embedding_249,use_embedding_250,use_embedding_251,use_embedding_252,use_embedding_253,use_embedding_254,use_embedding_255,use_embedding_256,use_embedding_257,use_embedding_258,use_embedding_259,use_embedding_260,use_embedding_261,use_embedding_262,use_embedding_263,use_embedding_264,use_embedding_265,use_embedding_266,use_embedding_267,use_embedding_268,use_embedding_269,use_embedding_270,use_embedding_271,use_embedding_272,use_embedding_273,use_embedding_274,use_embedding_275,use_embedding_276,use_embedding_277,use_embedding_278,use_embedding_279,use_embedding_280,use_embedding_281,use_embedding_282,use_embedding_283,use_embedding_284,use_embedding_285,use_embedding_286,use_embedding_287,use_embedding_288,use_embedding_289,use_embedding_290,use_embedding_291,use_embedding_292,use_embedding_293,use_embedding_294,use_embedding_295,use_embedding_296,use_embedding_297,use_embedding_298,use_embedding_299,use_embedding_300,use_embedding_301,use_embedding_302,use_embedding_303,use_embedding_304,use_embedding_305,use_embedding_306,use_embedding_307,use_embedding_308,use_embedding_309,use_embedding_310,use_embedding_311,use_embedding_312,use_embedding_313,use_embedding_314,use_embedding_315,use_embedding_316,use_embedding_317,use_embedding_318,use_embedding_319,use_embedding_320,use_embedding_321,use_embedding_322,use_embedding_323,use_embedding_324,use_embedding_325,use_embedding_326,use_embedding_327,use_embedding_328,use_embedding_329,use_embedding_330,use_embedding_331,use_embedding_332,use_embedding_333,use_embedding_334,use_embedding_335,use_embedding_336,use_embedding_337,use_embedding_338,use_embedding_339,use_embedding_340,use_embedding_341,use_embedding_342,use_embedding_343,use_embedding_344,use_embedding_345,use_embedding_346,use_embedding_347,use_embedding_348,use_embedding_349,use_embedding_350,use_embedding_351,use_embedding_352,use_embedding_353,use_embedding_354,use_embedding_355,use_embedding_356,use_embedding_357,use_embedding_358,use_embedding_359,use_embedding_360,use_embedding_361,use_embedding_362,use_embedding_363,use_embedding_364,use_embedding_365,use_embedding_366,use_embedding_367,use_embedding_368,use_embedding_369,use_embedding_370,use_embedding_371,use_embedding_372,use_embedding_373,use_embedding_374,use_embedding_375,use_embedding_376,use_embedding_377,use_embedding_378,use_embedding_379,use_embedding_380,use_embedding_381,use_embedding_382,use_embedding_383,use_embedding_384,use_embedding_385,use_embedding_386,use_embedding_387,use_embedding_388,use_embedding_389,use_embedding_390,use_embedding_391,use_embedding_392,use_embedding_393,use_embedding_394,use_embedding_395,use_embedding_396,use_embedding_397,use_embedding_398,use_embedding_399,use_embedding_400,use_embedding_401,use_embedding_402,use_embedding_403,use_embedding_404,use_embedding_405,use_embedding_406,use_embedding_407,use_embedding_408,use_embedding_409,use_embedding_410,use_embedding_411,use_embedding_412,use_embedding_413,use_embedding_414,use_embedding_415,use_embedding_416,use_embedding_417,use_embedding_418,use_embedding_419,use_embedding_420,use_embedding_421,use_embedding_422,use_embedding_423,use_embedding_424,use_embedding_425,use_embedding_426,use_embedding_427,use_embedding_428,use_embedding_429,use_embedding_430,use_embedding_431,use_embedding_432,use_embedding_433,use_embedding_434,use_embedding_435,use_embedding_436,use_embedding_437,use_embedding_438,use_embedding_439,use_embedding_440,use_embedding_441,use_embedding_442,use_embedding_443,use_embedding_444,use_embedding_445,use_embedding_446,use_embedding_447,use_embedding_448,use_embedding_449,use_embedding_450,use_embedding_451,use_embedding_452,use_embedding_453,use_embedding_454,use_embedding_455,use_embedding_456,use_embedding_457,use_embedding_458,use_embedding_459,use_embedding_460,use_embedding_461,use_embedding_462,use_embedding_463,use_embedding_464,use_embedding_465,use_embedding_466,use_embedding_467,use_embedding_468,use_embedding_469,use_embedding_470,use_embedding_471,use_embedding_472,use_embedding_473,use_embedding_474,use_embedding_475,use_embedding_476,use_embedding_477,use_embedding_478,use_embedding_479,use_embedding_480,use_embedding_481,use_embedding_482,use_embedding_483,use_embedding_484,use_embedding_485,use_embedding_486,use_embedding_487,use_embedding_488,use_embedding_489,use_embedding_490,use_embedding_491,use_embedding_492,use_embedding_493,use_embedding_494,use_embedding_495,use_embedding_496,use_embedding_497,use_embedding_498,use_embedding_499,use_embedding_500,use_embedding_501,use_embedding_502,use_embedding_503,use_embedding_504,use_embedding_505,use_embedding_506,use_embedding_507,use_embedding_508,use_embedding_509,use_embedding_510,use_embedding_511,pos_ADJ_count,pos_NOUN_count,pos_VERB_count,pos_SCONJ_count,pos_PRON_count,pos_PUNCT_count,pos_DET_count,pos_AUX_count,pos_PART_count,pos_ADP_count,pos_SPACE_count,pos_CCONJ_count,pos_PROPN_count,pos_NUM_count,pos_ADV_count,pos_SYM_count,pos_ADJ_ratio,pos_NOUN_ratio,pos_VERB_ratio,pos_SCONJ_ratio,pos_PRON_ratio,pos_PUNCT_ratio,pos_DET_ratio,pos_AUX_ratio,pos_PART_ratio,pos_ADP_ratio,pos_SPACE_ratio,pos_CCONJ_ratio,pos_PROPN_ratio,pos_NUM_ratio,pos_ADV_ratio,pos_SYM_ratio,pos_INTJ_count,pos_INTJ_ratio,pos_X_count,pos_X_ratio,ner_GPE_count,ner_PERCENT_count,ner_NORP_count,ner_ORG_count,ner_CARDINAL_count,ner_MONEY_count,ner_DATE_count,ner_LOC_count,ner_PERSON_count,ner_QUANTITY_count,ner_EVENT_count,ner_GPE_ratio,ner_PERCENT_ratio,ner_NORP_ratio,ner_ORG_ratio,ner_CARDINAL_ratio,ner_MONEY_ratio,ner_DATE_ratio,ner_LOC_ratio,ner_PERSON_ratio,ner_QUANTITY_ratio,ner_EVENT_ratio,ner_ORDINAL_count,ner_ORDINAL_ratio,ner_WORK_OF_ART_count,ner_WORK_OF_ART_ratio,ner_LAW_count,ner_LAW_ratio,ner_PRODUCT_count,ner_PRODUCT_ratio,ner_TIME_count,ner_TIME_ratio,ner_FAC_count,ner_FAC_ratio,ner_LANGUAGE_count,ner_LANGUAGE_ratio,dep_amod_count,dep_nsubj_count,dep_ROOT_count,dep_dobj_count,dep_advmod_count,dep_relcl_count,dep_punct_count,dep_det_count,dep_aux_count,dep_neg_count,dep_mark_count,dep_csubj_count,dep_compound_count,dep_prep_count,dep_pobj_count,dep_ccomp_count,dep_dep_count,dep_advcl_count,dep_cc_count,dep_acomp_count,dep_attr_count,dep_appos_count,dep_conj_count,dep_nummod_count,dep_poss_count,dep_case_count,dep_nsubjpass_count,dep_nmod_count,dep_auxpass_count,dep_npadvmod_count,dep_expl_count,dep_xcomp_count,dep_dative_count,dep_oprd_count,dep_acl_count,dep_quantmod_count,dep_pcomp_count,dep_amod_ratio,dep_nsubj_ratio,dep_ROOT_ratio,dep_dobj_ratio,dep_advmod_ratio,dep_relcl_ratio,dep_punct_ratio,dep_det_ratio,dep_aux_ratio,dep_neg_ratio,dep_mark_ratio,dep_csubj_ratio,dep_compound_ratio,dep_prep_ratio,dep_pobj_ratio,dep_ccomp_ratio,dep_dep_ratio,dep_advcl_ratio,dep_cc_ratio,dep_acomp_ratio,dep_attr_ratio,dep_appos_ratio,dep_conj_ratio,dep_nummod_ratio,dep_poss_ratio,dep_case_ratio,dep_nsubjpass_ratio,dep_nmod_ratio,dep_auxpass_ratio,dep_npadvmod_ratio,dep_expl_ratio,dep_xcomp_ratio,dep_dative_ratio,dep_oprd_ratio,dep_acl_ratio,dep_quantmod_ratio,dep_pcomp_ratio,dep_agent_count,dep_intj_count,dep_predet_count,dep_prt_count,dep_agent_ratio,dep_intj_ratio,dep_predet_ratio,dep_prt_ratio,dep_meta_count,dep_meta_ratio,dep_preconj_count,dep_preconj_ratio,dep_parataxis_count,dep_parataxis_ratio,dep_csubjpass_count,dep_csubjpass_ratio,spelling_errors,grammar_errors,linsear_write_formula,ari_score,2001,800,800 degrees,90,able,accident,accidents,according,action,action coding,actually,advantages,ago,agree,air,alert,alien,aliens,allow,alot,amazing,america,american,animals,aren,article,ask,atmosphere,attention,author,average,away,bad,ban,based,believe,benefit,best,better,big,boat,bogota,bored,bring,butte,called,camera,candidate,candidates,car,car free,car usage,carbon,carbon dioxide,care,cars,case,cause,certain,challenge,challenge exploring,challenge exploring venus,challenging,chance,change,china,choose,cities,citizens,city,claim,class,classroom,clear,close,closer,closest,clouds,coding,college,come,comes,coming,common,completely,computer,computers,conclusion,conditions,confused,confused bored,control,cool,cost,countries,country,cowboy,cowboys,cowboys program,crash,create,created,created aliens,cydonia,danger,dangerous,dangers,day,days,degrees,degrees fahrenheit,despite,despite dangers,detect,development,did,didn,different,dioxide,distance,does,doesn,doing,don,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,drivers,driving,earth,earth like,easier,easy,elect,election,elections,electoral,electoral college,electoral votes,electors,emissions,emotion,emotional,emotions,end,environment,europe,everyday,evidence,example,experience,explains,explore,exploring,exploring venus,expression,expressions,eyes,face,face mars,faces,facial,facial action,facial action coding,facs,fact,facts,fahrenheit,fair,far,fault,features,feel,feeling,finally,form,formation,forms,free,friend,fuel,fun,future,games,gas,gets,getting,given,gives,giving,global,goes,going,good,good idea,google,got,great,greater,greenhouse,half,happen,happy,hard,having,help,help people,helpful,helping,helps,high,home,hope,huang,huge,human,humans,idea,image,imagine,important,improve,information,instead,isn,issues,job,join,just,just like,just natural,just natural landform,kids,kind,know,knowing,land,landform,landforms,large,laws,lead,learn,learning,lesson,let,life,like,like earth,likely,limited,limiting,limiting car,limiting car usage,lisa,little,live,lives,living,ll,long,look,look like,looking,looks,lot,lower,luke,major,majority,make,makes,making,mars,martian,matter,maybe,mean,means,meet,mesa,method,miles,mona,mona lisa,money,muscles,nasa,natural,natural landform,near,need,needed,needs,new,new technology,number,oceans,ones,opinion,opportunity,order,paragraph,paris,passage,pay,people,people think,percent,person,photo,picture,pictures,place,places,planet,planet earth,planet solar,planets,play,point,pollution,popular,popular vote,positive,possible,possibly,power,presents,president,presidential,pressure,probably,problem,problems,process,program,prove,public,pursuit,pursuit despite,read,reading,real,really,reason,reasons,recognize,reduce,research,ride,right,risk,road,roads,rock,run,sad,safe,safer,safety,said,save,say,saying,says,school,schools,scientist,scientists,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,senator,sensors,shadows,ship,shows,similar,simply,size,small,smart,smile,smog,society,software,solar,source,space,spacecraft,start,state,stated,states,stay,stop,streets,stress,student,student confused,students,study,study venus,studying,studying venus,sun,support,supported,supports,sure,surface,taken,takes,taking,talk,teacher,teachers,technology,tell,temperature,test,text,thats,thing,things,think,thought,time,times,today,took,traffic,transportation,travel,true,try,trying,turn,type,understand,unfair,united,united states,usage,use,used,useful,using,valuable,vauban,vehicle,vehicles,venus,venus author,venus worthy,venus worthy pursuit,viking,visit,vote,vote president,voters,votes,voting,walk,walking,want,wanted,war,way,ways,went,wheel,win,winner,won,work,working,world,worth,worthy,worthy pursuit,wouldn,wrong,year,years,yes

In [24]:

# Import necessary libraries
import pandas as pd
from itertools import combinations

# Assuming the DataFrame `df` and `score` are already defined
# and excluding irrelevant columns

# Calculate correlations with the target

cor = df.drop(columns=['essay_id', 'full_text', 'clean_text', 'lowered' , 'score'], axis=1) # ,'processed_docs', 'topics',

correlations = cor.corrwith(df['score']).sort_values(ascending=False)



# Set a correlation threshold or select top N features
correlation_threshold = 0.3

top_features = correlations[abs(correlations) > correlation_threshold].index.tolist()

# Print the most correlated features
print("Top correlations with the score:")
print(top_features)

# Generate interaction terms between pairs of top features
for feature1, feature2 in combinations(top_features, 2):
    df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]


# Optional: print the list of created interaction terms
interaction_terms = [f'interaction_{feature1}_{feature2}' for feature1, feature2 in combinations(top_features, 2)]
print("Created interaction terms:")
print(interaction_terms)


# export top_features to text file

with open('/home/jack/github/kaggle/scoring/model_data/sklearn/top_corelations.txt', 'w') as f:
    for item in top_features:
        f.write("%s\n" % item)

Top correlations with the score:
['word_count', 'pos_DET_count', 'pos_NOUN_count', 'dep_det_count', 'pos_AUX_count', 'pos_ADJ_count', 'pos_VERB_count', 'pos_PUNCT_count', 'deberta_prob_4_full', 'dep_punct_count', 'deberta_prob_3_full', 'pos_ADP_count', 'dep_prep_count', 'dep_ROOT_count', 'sentence_count', 'dep_pobj_count', 'dep_nsubj_count', 'dep_aux_count', 'dep_advmod_count', 'dep_amod_count', 'spelling_errors', 'pos_ADV_count', 'dep_dobj_count', 'pos_PART_count', 'use_embedding_233', 'use_embedding_356', 'pos_SCONJ_count', 'use_embedding_503', 'dep_advcl_count', 'dep_acomp_count', 'dep_mark_count', 'dep_cc_count', 'pos_CCONJ_count', 'dep_conj_count', 'deberta_prob_5_full', 'dep_relcl_count', 'dep_pcomp_count', 'grammar_errors', 'dep_auxpass_count', 'dep_acl_count', 'dep_nsubjpass_count', 'use_embedding_483', 'pos_PRON_count', 'dep_xcomp_count', 'dep_compound_count', 'dep_neg_count', 'dep_ccomp_count', 'dep_attr_count', 'dep_poss_count', 'use_embedding_141', 'use_embedding_427', 'use_embedding_366', 'use_embedding_257', 'deberta_prob_0_full', 'deberta_prob_1_full']

/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]

Created interaction terms:

/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]
/tmp/ipykernel_104197/3155286109.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]

In [25]:
df.head()

  essay_id                                          full_text  score  \
0  000d118  Many people have car where they live. The thin...      3
1  000fe60  I am a scientist at NASA that is discussing th...      3
2  001ab80  People always wish they had the same technolog...      4
3  001bdc0  We all heard about Venus, the planet without a...      4
4  002ba53  Dear, State Senator\n\nThis is a letter to arg...      3

                                             lowered  \
0  many people have car where they live. the thin...
1  i am a scientist at nasa that is discussing th...
2  people always wish they had the same technolog...
3  we all heard about venus, the planet without a...
4  dear, state senator\n\nthis is a letter to arg...

                                          clean_text  paragraph_count  \
0  many people have car where they live the thing...                1
1  i am a scientist at nasa that is discussing th...                5
2  people always wish they had the same technolog...                4
3  we all heard about venus the planet without al...                5
4  dear state senator this is a letter to argue i...                6

   sentence_count  word_count  avg_paragraph_length  max_paragraph_length  \
0              13         498            498.000000                   498
1              21         332             66.400000                    98
2              24         550            137.500000                   199
3              20         451             90.200000                   165
4              15         373             62.166667                   118

   min_paragraph_length  avg_sentence_length  max_sentence_length  \
0                   498            38.307692                  127
1                    37            15.809524                   48
2                    85            22.916667                   46
3                    25            22.550000                   38
4                     2            24.933333                   76

   min_sentence_length  avg_word_length  max_word_length  min_word_length  \
0                    7         4.369478               25                1
1                    2         4.018072               11                1
2                    9         4.574545               15                1
3                    5         4.982262               20                1
4                    2         4.873995               14                1

   flesch_reading_ease  gunning_fog_index  sentiment_score  \
0                57.98              17.33           0.9937
1                87.55               7.48           0.7705
2                65.15              11.49          -0.9731
3                58.32              11.91           0.9702
4                54.66              12.64           0.9771

   deberta_prob_0_full  deberta_prob_1_full  deberta_prob_2_full  \
0             0.021534             0.379466             0.529225
1             0.001421             0.071248             0.839510
2             0.001564             0.001929             0.033057
3             0.000927             0.005752             0.206941
4             0.031210             0.388895             0.522782

   deberta_prob_3_full  deberta_prob_4_full  deberta_prob_5_full  \
0             0.066918             0.002071             0.000785
1             0.086768             0.000765             0.000288
2             0.516632             0.433214             0.013603
3             0.767750             0.017782             0.000848
4             0.054104             0.002046             0.000963

   xlnet_prob_0  xlnet_prob_1  xlnet_prob_2  xlnet_prob_3  xlnet_prob_4  \
0      0.118853      0.174859      0.158128      0.286387      0.150762
1      0.116731      0.167865      0.149173      0.298451      0.157676
2      0.121194      0.172987      0.152385      0.294505      0.148131
3      0.120910      0.168503      0.148743      0.297890      0.153702
4      0.117731      0.174473      0.146372      0.301475      0.148458

   xlnet_prob_5  use_embedding_0  use_embedding_1  use_embedding_2  \
0      0.111011         0.041960        -0.067975         0.063115
1      0.110105        -0.051479        -0.021961         0.028500
2      0.110798        -0.001355        -0.050998        -0.028374
3      0.110252         0.024647        -0.046599        -0.010909
4      0.111491        -0.052357        -0.057141        -0.007919

   use_embedding_3  use_embedding_4  use_embedding_5  use_embedding_6  \
0        -0.026617         0.020445         0.003867         0.009433
1         0.046144         0.066032        -0.067002        -0.021723
2        -0.011676        -0.022839         0.022662         0.041136
3         0.027460         0.060216        -0.060324         0.057520
4        -0.028717         0.057074        -0.004967         0.038998

   use_embedding_7  use_embedding_8  use_embedding_9  use_embedding_10  \
0        -0.055062        -0.053429        -0.068910          0.003696
1         0.052850        -0.017364        -0.019699          0.020906
2        -0.014291        -0.063853        -0.062540         -0.043295
3        -0.055015         0.056964         0.045649         -0.010923
4        -0.025629         0.056967         0.046033         -0.002287

   use_embedding_11  use_embedding_12  use_embedding_13  use_embedding_14  \
0          0.020061          0.010820          0.030742          0.031649
1          0.001037         -0.040863          0.051007          0.002075
2         -0.033152          0.063500          0.036367         -0.009697
3         -0.012663          0.009247         -0.059563         -0.050419
4         -0.007752          0.056892          0.043772         -0.037327

   use_embedding_15  use_embedding_16  use_embedding_17  use_embedding_18  \
0         -0.024020         -0.039520          0.064324         -0.042426
1         -0.066549         -0.052261          0.049969         -0.031710
2         -0.041174          0.012809          0.021321          0.005839
3         -0.060405          0.055298          0.052108          0.012833
4         -0.057134          0.056958         -0.010395         -0.056792

   use_embedding_19  use_embedding_20  use_embedding_21  use_embedding_22  \
0          0.003099         -0.061533         -0.049349          0.064297
1         -0.040906         -0.035889          0.026802          0.037872
2         -0.053551         -0.043605          0.001487         -0.036566
3         -0.056798         -0.027848         -0.030608         -0.020283
4         -0.055701         -0.056912          0.053445          0.056458

   use_embedding_23  use_embedding_24  use_embedding_25  use_embedding_26  \
0         -0.046063          0.027209         -0.001092          0.067016
1          0.067021          0.044432          0.000260          0.003485
2          0.023517          0.039610         -0.024071          0.060916
3          0.060418          0.045912         -0.050202         -0.006652
4         -0.024645         -0.037869         -0.055765         -0.024979

   use_embedding_27  use_embedding_28  use_embedding_29  use_embedding_30  \
0          0.013396         -0.018858          0.005713         -0.046208
1          0.029175          0.059963          0.010278         -0.062609
2          0.046432          0.027933         -0.047315          0.034343
3         -0.053361         -0.021137         -0.045045         -0.051187
4          0.053384          0.004337          0.056096          0.055947

   use_embedding_31  use_embedding_32  use_embedding_33  use_embedding_34  \
0          0.061453          0.025858         -0.065615         -0.009667
1          0.033071         -0.035046         -0.026370         -0.064978
2         -0.013625          0.013998         -0.060110         -0.032791
3         -0.000408         -0.057508         -0.049918         -0.059986
4         -0.041637         -0.030988         -0.044782          0.039119

   use_embedding_35  use_embedding_36  use_embedding_37  use_embedding_38  \
0          0.020207          0.041979          0.043658         -0.040748
1         -0.062706         -0.036433          0.046896          0.000985
2          0.061172         -0.056258         -0.062734          0.009421
3         -0.060300         -0.059696          0.038481          0.055906
4          0.056875         -0.040509          0.053329         -0.029096

   use_embedding_39  use_embedding_40  use_embedding_41  use_embedding_42  \
0         -0.044444          0.070164          0.021018         -0.024099
1          0.048611          0.027040         -0.048923         -0.065221
2          0.041022          0.062976         -0.003421         -0.047037
3          0.041262         -0.018947          0.038756         -0.049328
4          0.057141          0.057127          0.018674          0.029065

   use_embedding_43  use_embedding_44  use_embedding_45  use_embedding_46  \
0         -0.005362         -0.071371          0.035344          0.041532
1         -0.037086         -0.065955          0.061284          0.020419
2         -0.060805         -0.063935          0.063272          0.060794
3         -0.022084         -0.060416          0.057604         -0.024043
4         -0.026538          0.057104          0.056720          0.032240

   use_embedding_47  use_embedding_48  use_embedding_49  use_embedding_50  \
0         -0.023140         -0.058027          0.054723         -0.067398
1         -0.057120          0.006482          0.019873         -0.060475
2         -0.028247         -0.017291          0.009007         -0.063280
3          0.033002          0.026457         -0.018980         -0.051183
4         -0.036187         -0.047185         -0.057120         -0.057040

   use_embedding_51  use_embedding_52  use_embedding_53  use_embedding_54  \
0          0.067929          0.044899          0.028260         -0.004224
1          0.066505          0.041101          0.063308          0.005009
2          0.049199          0.015410          0.036894         -0.000519
3          0.060250         -0.045615          0.018385          0.013513
4          0.042297         -0.022413         -0.014404          0.006164

   use_embedding_55  use_embedding_56  use_embedding_57  use_embedding_58  \
0          0.041252         -0.069346          0.029246          0.054705
1         -0.010041         -0.053509          0.019620          0.052488
2         -0.059126          0.019596          0.046049          0.054661
3         -0.059468         -0.055230          0.033768          0.058371
4         -0.046382         -0.044283          0.048129          0.056749

   use_embedding_59  use_embedding_60  use_embedding_61  use_embedding_62  \
0         -0.022725          0.067761          0.011572         -0.046673
1          0.035222          0.065084         -0.067002          0.008657
2         -0.061738          0.000274          0.035095         -0.032151
3          0.033985          0.060413         -0.060414         -0.060196
4         -0.042635          0.037369          0.014928         -0.056962

   use_embedding_63  use_embedding_64  use_embedding_65  use_embedding_66  \
0         -0.065254          0.038006         -0.054666          0.054993
1         -0.062776         -0.061192         -0.065175         -0.042654
2         -0.063900         -0.037521         -0.024060          0.063176
3         -0.060355         -0.055481         -0.041791         -0.007672
4         -0.052511          0.052131         -0.054217          0.050045

   use_embedding_67  use_embedding_68  use_embedding_69  use_embedding_70  \
0          0.048035         -0.067260          0.068754         -0.059997
1         -0.064762         -0.004593          0.058477         -0.067005
2          0.062045         -0.059013          0.063166         -0.057158
3         -0.058432          0.024716          0.057402         -0.060415
4          0.052801         -0.026071         -0.052646          0.036818

   use_embedding_71  use_embedding_72  use_embedding_73  use_embedding_74  \
0          0.070202          0.001794          0.000592         -0.037192
1          0.064837          0.010205         -0.045082         -0.040998
2          0.060995          0.010601          0.043433         -0.029307
3          0.060343          0.004184          0.026752         -0.043707
4          0.057062          0.057113          0.057141         -0.042895

   use_embedding_75  use_embedding_76  use_embedding_77  use_embedding_78  \
0          0.068251          0.023958          0.017307          0.020281
1         -0.032445          0.065940          0.030846          0.056887
2         -0.029356          0.015355         -0.003193         -0.018835
3         -0.009958          0.059448         -0.056450          0.016931
4          0.057096         -0.013839         -0.045384          0.052273

   use_embedding_79  use_embedding_80  use_embedding_81  use_embedding_82  \
0          0.061545          0.071371          0.021947          0.012009
1          0.040423          0.067011          0.032525         -0.032819
2          0.045939          0.063933         -0.017072          0.025266
3          0.041255          0.060418          0.045765         -0.005101
4          0.055540         -0.056875         -0.047517          0.003064

   use_embedding_83  use_embedding_84  use_embedding_85  use_embedding_86  \
0          0.019711         -0.023376         -0.067905          0.039303
1         -0.004531         -0.056104         -0.047383         -0.059658
2          0.024835         -0.059263         -0.053388          0.005747
3          0.050778         -0.037281         -0.038848          0.001385
4         -0.017337         -0.036200          0.043635         -0.052637

   use_embedding_87  use_embedding_88  use_embedding_89  use_embedding_90  \
0         -0.029714          0.063064          0.002921         -0.040765
1         -0.050210         -0.060052          0.014958         -0.014195
2          0.001636          0.060662         -0.000956         -0.051920
3         -0.017633         -0.059356         -0.034744          0.045907
4         -0.057141          0.057138          0.051495          0.006991

   use_embedding_91  use_embedding_92  use_embedding_93  use_embedding_94  \
0         -0.047585          0.016403         -0.044314          0.046679
1          0.032115         -0.025213          0.012917         -0.023260
2          0.042363         -0.040258          0.031452         -0.047307
3         -0.047177         -0.008337         -0.012812         -0.028096
4         -0.020925         -0.044415          0.036394         -0.055680

   use_embedding_95  use_embedding_96  use_embedding_97  use_embedding_98  \
0         -0.009566          0.059428          0.070486          0.069928
1          0.041962          0.041418          0.065898          0.067020
2         -0.021450          0.058053          0.063926          0.062044
3          0.058796          0.054468          0.060402          0.060418
4          0.054995          0.052411          0.042511          0.057141

   use_embedding_99  use_embedding_100  use_embedding_101  use_embedding_102  \
0         -0.065749          -0.018764           0.042294           0.006362
1         -0.033995           0.011879           0.054088          -0.033447
2         -0.061909           0.061972           0.048886           0.038663
3         -0.040360          -0.059995           0.052046          -0.053413
4         -0.052003          -0.055361           0.054592           0.035628

   use_embedding_103  use_embedding_104  use_embedding_105  use_embedding_106  \
0          -0.023871           0.030309           0.016379          -0.041109
1           0.028367          -0.053240           0.039212          -0.061964
2          -0.025581           0.054376           0.049209          -0.029361
3           0.039346           0.000203           0.052885          -0.057654
4          -0.048903           0.046274           0.050103          -0.050178

   use_embedding_107  use_embedding_108  use_embedding_109  use_embedding_110  \
0          -0.032971           0.002925           0.018498           0.000143
1           0.059464          -0.043827          -0.051984          -0.021650
2           0.020779          -0.056195           0.042168          -0.042049
3           0.059101          -0.047141           0.052338           0.011158
4           0.051901           0.056836           0.054598          -0.021453

   use_embedding_111  use_embedding_112  use_embedding_113  use_embedding_114  \
0           0.058467           0.000987          -0.038852          -0.036589
1           0.023439           0.031394          -0.001974          -0.054017
2           0.041116           0.063082           0.004375           0.016231
3          -0.046191           0.051240          -0.055519          -0.053501
4          -0.028808          -0.006012           0.052699           0.046713

   use_embedding_115  use_embedding_116  use_embedding_117  use_embedding_118  \
0          -0.054337           0.059496          -0.042548          -0.046451
1          -0.037773          -0.011044           0.045843          -0.066827
2          -0.047069          -0.024435          -0.046582          -0.024175
3           0.011346           0.035329          -0.054524          -0.053668
4          -0.018010          -0.036578           0.013994          -0.022293

   use_embedding_119  use_embedding_120  use_embedding_121  use_embedding_122  \
0          -0.031428          -0.010024           0.042607          -0.045928
1           0.026491           0.004700          -0.003484          -0.044614
2           0.001402           0.011380           0.044003          -0.021870
3          -0.036169          -0.055400          -0.015511           0.006612
4           0.038749          -0.056647           0.039160           0.034544

   use_embedding_123  use_embedding_124  use_embedding_125  use_embedding_126  \
0           0.063880           0.038856           0.024155           0.070443
1           0.051810           0.000436          -0.011676           0.066958
2           0.045338          -0.018274           0.033559          -0.029616
3           0.002364           0.056944           0.019525           0.060301
4           0.007430           0.021570           0.056976           0.057141

   use_embedding_127  use_embedding_128  use_embedding_129  use_embedding_130  \
0          -0.006666          -0.056390          -0.035999           0.051709
1          -0.067003           0.048434          -0.043947           0.014173
2          -0.057934           0.018105           0.063504          -0.057897
3          -0.060417          -0.009839          -0.021683           0.011133
4           0.032225           0.006405          -0.024418          -0.020719

   use_embedding_131  use_embedding_132  use_embedding_133  use_embedding_134  \
0           0.064817           0.047425          -0.045911          -0.049027
1           0.067021          -0.004581           0.032035          -0.012303
2           0.059603           0.041422          -0.061163          -0.051872
3           0.060418           0.051292          -0.051956          -0.055540
4          -0.051973           0.032064          -0.056502          -0.051768

   use_embedding_135  use_embedding_136  use_embedding_137  use_embedding_138  \
0           0.030614          -0.040154           0.063312          -0.032446
1          -0.040991          -0.056477          -0.053691          -0.058233
2           0.057651          -0.059385           0.016291          -0.054941
3          -0.033903          -0.055913           0.033394          -0.028456
4           0.039705          -0.009750           0.050909          -0.056384

   use_embedding_139  use_embedding_140  use_embedding_141  use_embedding_142  \

In [26]:
df.tail()

      essay_id                                          full_text  score  \
17302  ffd378d  the story " The Challenge of Exploing Venus " ...      2
17303  ffddf1f  Technology has changed a lot of ways that we l...      4
17304  fff016d  If you don't like sitting around all day than ...      2
17305  fffb49b  In "The Challenge of Exporing Venus," the auth...      1
17306  fffed3e  Venus is worthy place to study but dangerous. ...      2

                                                 lowered  \
17302  the story " the challenge of exploing venus " ...
17303  technology has changed a lot of ways that we l...
17304  if you don't like sitting around all day than ...
17305  in "the challenge of exporing venus," the auth...
17306  venus is worthy place to study but dangerous. ...

                                              clean_text  paragraph_count  \
17302  the story the challenge of exploing venus is a...                3
17303  technology has changed a lot of ways that we l...                6
17304  if you do not like sitting around all day than...                3
17305  in the challenge of exporing venus the author ...                1
17306  venus is worthy place to study but dangerous t...                4

       sentence_count  word_count  avg_paragraph_length  max_paragraph_length  \
17302               9         157             52.333333                    82
17303              26         579             96.500000                   167
17304              15         215             71.666667                    86
17305              11         231            231.000000                   231
17306              11         155             38.750000                    94

       min_paragraph_length  avg_sentence_length  max_sentence_length  \
17302                    23            17.444444                   36
17303                    44            22.269231                   61
17304                    63            14.333333                   23
17305                   231            21.000000                   38
17306                     3            14.090909                   28

       min_sentence_length  avg_word_length  max_word_length  min_word_length  \
17302                    7         4.445860               12                1
17303                    1         4.770294               12                1
17304                    5         4.213953               11                1
17305                   11         5.181818               12                1
17306                    6         4.051613               10                1

       flesch_reading_ease  gunning_fog_index  sentiment_score  \
17302                70.94               9.72           0.3626
17303                56.39              11.42           0.9973
17304                90.80               6.28           0.9803
17305                58.72              11.66           0.9513
17306                83.76               5.93           0.8294

       deberta_prob_0_full  deberta_prob_1_full  deberta_prob_2_full  \
17302             0.092310             0.891637             0.014393
17303             0.001012             0.005224             0.197986
17304             0.043474             0.935611             0.019348
17305             0.675936             0.293551             0.025413
17306             0.131172             0.857495             0.009533

       deberta_prob_3_full  deberta_prob_4_full  deberta_prob_5_full  \
17302             0.000741             0.000411             0.000507
17303             0.711231             0.082317             0.002229
17304             0.000795             0.000298             0.000474
17305             0.002706             0.001254             0.001139
17306             0.000750             0.000413             0.000638

       xlnet_prob_0  xlnet_prob_1  xlnet_prob_2  xlnet_prob_3  xlnet_prob_4  \
17302      0.118304      0.174102      0.153757      0.292315      0.150599
17303      0.119870      0.174937      0.147717      0.293687      0.152818
17304      0.116705      0.167461      0.164036      0.290082      0.149289
17305      0.120563      0.165994      0.154362      0.295437      0.153045
17306      0.118454      0.176704      0.148839      0.294156      0.155662

       xlnet_prob_5  use_embedding_0  use_embedding_1  use_embedding_2  \
17302      0.110922         0.034845        -0.057741         0.003000
17303      0.110970         0.024527        -0.039607         0.004543
17304      0.112427         0.035917        -0.079950         0.047437
17305      0.110598        -0.029692        -0.060374        -0.044843
17306      0.106185        -0.002810        -0.088783        -0.037484

       use_embedding_3  use_embedding_4  use_embedding_5  use_embedding_6  \
17302         0.022938         0.056945        -0.073307         0.039711
17303         0.008204        -0.054703         0.040301        -0.041548
17304         0.017324        -0.002800        -0.031046        -0.072141
17305         0.055301         0.061733        -0.062235         0.040193
17306         0.044209         0.062233        -0.080977         0.042886

       use_embedding_7  use_embedding_8  use_embedding_9  use_embedding_10  \
17302        -0.006256         0.075030         0.038705          0.068364
17303         0.058607        -0.060230         0.059119         -0.018006
17304        -0.033778        -0.046768        -0.057036          0.035674
17305        -0.043408         0.042572         0.039599         -0.004543
17306        -0.004197        -0.020264        -0.007195          0.000446

       use_embedding_11  use_embedding_12  use_embedding_13  use_embedding_14  \
17302          0.026150         -0.001351         -0.032209         -0.044171
17303         -0.059146         -0.003572         -0.006617         -0.042454
17304         -0.024162          0.035129          0.063730          0.042429
17305          0.019201         -0.058196          0.023631         -0.052222
17306          0.022509         -0.049759          0.050749         -0.078787

       use_embedding_15  use_embedding_16  use_embedding_17  use_embedding_18  \
17302         -0.070821          0.057593          0.051776          0.039833
17303         -0.060950         -0.053500         -0.053726         -0.025297
17304         -0.031583         -0.078935         -0.052090         -0.010231
17305         -0.061649          0.019898         -0.008432          0.043568
17306         -0.037866          0.020219          0.033827          0.045011

       use_embedding_19  use_embedding_20  use_embedding_21  use_embedding_22  \
17302          0.033526         -0.012747          0.002976         -0.054483
17303         -0.061192          0.058277          0.005214         -0.013437
17304         -0.065402         -0.056662          0.045889          0.067197
17305          0.043320         -0.037555         -0.046556         -0.015814
17306         -0.041653         -0.058785         -0.010006         -0.008309

       use_embedding_23  use_embedding_24  use_embedding_25  use_embedding_26  \
17302          0.075916          0.058798          0.017764          0.009301
17303         -0.044742         -0.051393         -0.027803         -0.031759
17304          0.013072          0.018819         -0.021129         -0.036217
17305          0.062253          0.058393         -0.022859         -0.015842
17306          0.083430          0.037289         -0.032726         -0.048658

       use_embedding_27  use_embedding_28  use_embedding_29  use_embedding_30  \
17302         -0.060587         -0.022728         -0.044613          0.006615
17303          0.030929          0.048160         -0.035512         -0.043073
17304          0.019023         -0.010146         -0.065464          0.012080
17305         -0.035793         -0.022914          0.019007         -0.036063
17306          0.017939         -0.069172         -0.013293         -0.030855

       use_embedding_31  use_embedding_32  use_embedding_33  use_embedding_34  \
17302          0.023059         -0.043912         -0.057060         -0.052406
17303          0.055552          0.054495         -0.043324         -0.053126
17304          0.080473          0.034907         -0.016219         -0.053706
17305          0.005302         -0.056960         -0.061632         -0.057052
17306          0.006620         -0.034229         -0.068980         -0.015149

       use_embedding_35  use_embedding_36  use_embedding_37  use_embedding_38  \
17302         -0.056655         -0.039798          0.052988          0.071599
17303          0.012808         -0.024318         -0.059938          0.034491
17304          0.005188          0.041486         -0.013057          0.019219
17305         -0.061365          0.025488          0.053826          0.056529
17306         -0.017958         -0.052158         -0.042887          0.057181

       use_embedding_39  use_embedding_40  use_embedding_41  use_embedding_42  \
17302          0.028996          0.003322         -0.010825         -0.058446
17303          0.051313          0.027304         -0.004404          0.020930
17304          0.074990         -0.027769          0.073578         -0.065595
17305          0.018651          0.019675         -0.006338         -0.054730
17306         -0.023753          0.019904          0.010413         -0.060499

       use_embedding_43  use_embedding_44  use_embedding_45  use_embedding_46  \
17302          0.040343         -0.070103          0.051303         -0.023328
17303         -0.043130          0.057258          0.020916          0.053460
17304         -0.027477          0.051763          0.006903         -0.078521
17305          0.035410         -0.062127          0.060668         -0.042649
17306          0.044063         -0.052174         -0.040438         -0.028863

       use_embedding_47  use_embedding_48  use_embedding_49  use_embedding_50  \
17302         -0.041215          0.035937         -0.019457         -0.000485
17303         -0.042577         -0.046603         -0.054045         -0.033433
17304         -0.001406          0.055845         -0.029525         -0.030457
17305         -0.043504          0.049173          0.055349          0.003877
17306          0.063156          0.021859          0.045172          0.002317

       use_embedding_51  use_embedding_52  use_embedding_53  use_embedding_54  \
17302          0.053940          0.010999         -0.038398          0.044848
17303          0.060110         -0.057308         -0.056780         -0.048518
17304          0.023898          0.049834          0.014649          0.044315
17305          0.031338         -0.045772          0.021420          0.034231
17306          0.060456          0.037007          0.019173          0.007111

       use_embedding_55  use_embedding_56  use_embedding_57  use_embedding_58  \
17302         -0.069223         -0.056459          0.005210          0.051553
17303         -0.035125         -0.059472         -0.017375          0.057772
17304         -0.038420         -0.055095         -0.002005          0.025296
17305         -0.061430         -0.058470          0.011896          0.051200
17306         -0.031151         -0.065201          0.001657          0.013577

       use_embedding_59  use_embedding_60  use_embedding_61  use_embedding_62  \
17302          0.059216          0.076342         -0.074862         -0.076293
17303          0.003425          0.055740          0.057798         -0.061190
17304          0.048480         -0.030232          0.018152          0.021237
17305          0.059981         -0.007824         -0.062235         -0.049143
17306          0.000949          0.054499         -0.063919         -0.077718

       use_embedding_63  use_embedding_64  use_embedding_65  use_embedding_66  \
17302         -0.065121         -0.037116         -0.056487          0.002799
17303         -0.030894          0.026949         -0.038548          0.060155
17304         -0.077351         -0.053387          0.069212          0.038101
17305         -0.049028         -0.038830         -0.056827         -0.000276
17306         -0.089663          0.013757         -0.033825          0.019186

       use_embedding_67  use_embedding_68  use_embedding_69  use_embedding_70  \
17302         -0.066074          0.015043          0.023607         -0.073319
17303         -0.045908         -0.046700          0.059712          0.014592
17304         -0.058746         -0.039336          0.017351         -0.021916
17305         -0.059747          0.044604          0.060546         -0.062251
17306          0.004898          0.034974          0.082439         -0.071971

       use_embedding_71  use_embedding_72  use_embedding_73  use_embedding_74  \
17302          0.057947          0.013599          0.025596         -0.044752
17303          0.061116          0.006108         -0.047312         -0.033796
17304          0.031125         -0.001349          0.032820         -0.051456
17305          0.060425          0.034523          0.053647         -0.014120
17306         -0.010316         -0.010844          0.009415         -0.022489

       use_embedding_75  use_embedding_76  use_embedding_77  use_embedding_78  \
17302          0.006972          0.051608          0.000631          0.030136
17303         -0.041015         -0.024563         -0.011231          0.019595
17304          0.012121          0.013267         -0.011839         -0.016693
17305          0.034519          0.061667         -0.054976          0.011509
17306          0.024122          0.039597         -0.011204          0.004621

       use_embedding_79  use_embedding_80  use_embedding_81  use_embedding_82  \
17302          0.055586          0.074494          0.049191          0.059103
17303          0.024127         -0.031682         -0.022001          0.027781
17304         -0.079375         -0.009534         -0.010922          0.060715
17305          0.038271          0.062253          0.053469          0.033365
17306         -0.053099          0.036777          0.030463         -0.019727

       use_embedding_83  use_embedding_84  use_embedding_85  use_embedding_86  \
17302         -0.029828         -0.017951         -0.041307          0.013072
17303          0.060188         -0.052128         -0.051561         -0.023355
17304         -0.022772          0.024335         -0.066256         -0.056784
17305          0.016490         -0.045474         -0.002718          0.007510
17306          0.053298         -0.008453         -0.047128         -0.075690

       use_embedding_87  use_embedding_88  use_embedding_89  use_embedding_90  \
17302          0.056203         -0.073285         -0.003867         -0.038458
17303          0.027962         -0.041733          0.060003         -0.053259
17304          0.008994         -0.009386          0.031060         -0.073037
17305         -0.010818         -0.061478         -0.014262          0.043284
17306          0.043139         -0.019908         -0.008717          0.062373

       use_embedding_91  use_embedding_92  use_embedding_93  use_embedding_94  \
17302         -0.074727          0.024622          0.007476          0.031320
17303          0.041247          0.017555         -0.002036         -0.050909
17304         -0.057670         -0.021686          0.045453          0.019482
17305         -0.059609          0.029602          0.040479          0.051874
17306         -0.059098         -0.069833          0.056196          0.039476

       use_embedding_95  use_embedding_96  use_embedding_97  use_embedding_98  \
17302          0.073778          0.039378          0.015660          0.076358
17303          0.061007          0.043029          0.061191          0.061189
17304          0.073612          0.051831          0.067541          0.056805
17305          0.049474          0.054110          0.060950          0.062253
17306          0.066745          0.063354          0.077207          0.067280

       use_embedding_99  use_embedding_100  use_embedding_101  \
17302         -0.013306          -0.062104          -0.040063
17303         -0.058564          -0.017061           0.059059
17304         -0.074962           0.019035           0.008320
17305          0.021721          -0.060953          -0.031656
17306         -0.065658          -0.016271          -0.004513

       use_embedding_102  use_embedding_103  use_embedding_104  \
17302          -0.033051           0.055321           0.025284
17303          -0.056762           0.024977          -0.048502
17304           0.073834          -0.033100          -0.014833
17305          -0.058888           0.041253           0.004164
17306          -0.066225           0.004705           0.026438

       use_embedding_105  use_embedding_106  use_embedding_107  \
17302           0.042101          -0.024883           0.033495
17303           0.050045           0.027472          -0.002281
17304           0.064000           0.005447          -0.002978
17305           0.061210          -0.037973           0.061138
17306           0.018607          -0.025558           0.040874

       use_embedding_108  use_embedding_109  use_embedding_110  \
17302          -0.024993           0.045702          -0.063435
17303          -0.058145           0.048886           0.030457
17304          -0.040726          -0.039772          -0.014883
17305          -0.050131           0.048920          -0.041187
17306          -0.050105           0.049530          -0.078518

       use_embedding_111  use_embedding_112  use_embedding_113  \
17302          -0.066731           0.058398           0.022069
17303           0.047478           0.031811          -0.061048
17304           0.067487          -0.057725           0.061119
17305           0.010455          -0.030910          -0.024822
17306          -0.001020           0.024138           0.006653

       use_embedding_114  use_embedding_115  use_embedding_116  \
17302          -0.063601          -0.025177           0.047802
17303           0.006582           0.009858          -0.003633
17304          -0.056338           0.007170          -0.034638
17305          -0.054099          -0.008919           0.055069
17306          -0.064594          -0.042407           0.010300

       use_embedding_117  use_embedding_118  use_embedding_119  \
17302           0.016444          -0.058146          -0.029500
17303           0.040267           0.014306           0.050904
17304           0.019795          -0.009350          -0.048309
17305          -0.028503          -0.061274          -0.044095
17306          -0.018933          -0.074438          -0.058232

       use_embedding_120  use_embedding_121  use_embedding_122  \
17302          -0.046204          -0.042352           0.007336
17303           0.014037           0.047305           0.045630
17304          -0.001696           0.018187           0.012865
17305          -0.059730          -0.049830          -0.013796
17306          -0.056141           0.028453          -0.046364

       use_embedding_123  use_embedding_124  use_embedding_125  \
17302           0.009553           0.020599          -0.038861
17303           0.060234          -0.053925           0.036673
17304           0.015326           0.023683          -0.049485
17305           0.008546          -0.027481           0.060530
17306          -0.027387          -0.010505           0.042300

       use_embedding_126  use_embedding_127  use_embedding_128  \
17302           0.051411          -0.074948          -0.022435
17303          -0.056088          -0.061196           0.000487
17304           0.031392          -0.042009          -0.070347
17305           0.059899          -0.062251           0.009038
17306           0.071940          -0.074512           0.013527

       use_embedding_129  use_embedding_130  use_embedding_131  \
17302          -0.016591          -0.004467           0.075798

In [27]:
# drop columns with hash in the name

hash_cols = [col for col in deberta_full.columns if 'hash' in col]

df.drop(columns=hash_cols, inplace=True)

import pandas as pd
from sklearn.feature_extraction.text import HashingVectorizer


# Initialize the HashingVectorizer
n_features = 200  # Number of columns in the hashed vector
hashing_vectorizer = HashingVectorizer(n_features=n_features, alternate_sign=False)

# Transform the text column into hash vector features
hashed_features = hashing_vectorizer.transform(df[text_col])

# Convert the hashed features to a dense representation for easier manipulation
hashed_features_dense = hashed_features.todense()

# Create new column names based on the number of features
hashed_columns = [f'hash_{i}' for i in range(n_features)]

# Convert dense representation to a dataframe
hashed_df = pd.DataFrame(hashed_features_dense, columns=hashed_columns)

# Concatenate the original dataframe with the hashed dataframe

df = pd.concat([df, hashed_df], axis=1)

In [28]:
train = df.copy()

In [29]:
train.head()

  essay_id                                          full_text  score  \
0  000d118  Many people have car where they live. The thin...      3
1  000fe60  I am a scientist at NASA that is discussing th...      3
2  001ab80  People always wish they had the same technolog...      4
3  001bdc0  We all heard about Venus, the planet without a...      4
4  002ba53  Dear, State Senator\n\nThis is a letter to arg...      3

                                             lowered  \
0  many people have car where they live. the thin...
1  i am a scientist at nasa that is discussing th...
2  people always wish they had the same technolog...
3  we all heard about venus, the planet without a...
4  dear, state senator\n\nthis is a letter to arg...

                                          clean_text  paragraph_count  \
0  many people have car where they live the thing...                1
1  i am a scientist at nasa that is discussing th...                5
2  people always wish they had the same technolog...                4
3  we all heard about venus the planet without al...                5
4  dear state senator this is a letter to argue i...                6

   sentence_count  word_count  avg_paragraph_length  max_paragraph_length  \
0              13         498            498.000000                   498
1              21         332             66.400000                    98
2              24         550            137.500000                   199
3              20         451             90.200000                   165
4              15         373             62.166667                   118

   min_paragraph_length  avg_sentence_length  max_sentence_length  \
0                   498            38.307692                  127
1                    37            15.809524                   48
2                    85            22.916667                   46
3                    25            22.550000                   38
4                     2            24.933333                   76

   min_sentence_length  avg_word_length  max_word_length  min_word_length  \
0                    7         4.369478               25                1
1                    2         4.018072               11                1
2                    9         4.574545               15                1
3                    5         4.982262               20                1
4                    2         4.873995               14                1

   flesch_reading_ease  gunning_fog_index  sentiment_score  \
0                57.98              17.33           0.9937
1                87.55               7.48           0.7705
2                65.15              11.49          -0.9731
3                58.32              11.91           0.9702
4                54.66              12.64           0.9771

   deberta_prob_0_full  deberta_prob_1_full  deberta_prob_2_full  \
0             0.021534             0.379466             0.529225
1             0.001421             0.071248             0.839510
2             0.001564             0.001929             0.033057
3             0.000927             0.005752             0.206941
4             0.031210             0.388895             0.522782

   deberta_prob_3_full  deberta_prob_4_full  deberta_prob_5_full  \
0             0.066918             0.002071             0.000785
1             0.086768             0.000765             0.000288
2             0.516632             0.433214             0.013603
3             0.767750             0.017782             0.000848
4             0.054104             0.002046             0.000963

   xlnet_prob_0  xlnet_prob_1  xlnet_prob_2  xlnet_prob_3  xlnet_prob_4  \
0      0.118853      0.174859      0.158128      0.286387      0.150762
1      0.116731      0.167865      0.149173      0.298451      0.157676
2      0.121194      0.172987      0.152385      0.294505      0.148131
3      0.120910      0.168503      0.148743      0.297890      0.153702
4      0.117731      0.174473      0.146372      0.301475      0.148458

   xlnet_prob_5  use_embedding_0  use_embedding_1  use_embedding_2  \
0      0.111011         0.041960        -0.067975         0.063115
1      0.110105        -0.051479        -0.021961         0.028500
2      0.110798        -0.001355        -0.050998        -0.028374
3      0.110252         0.024647        -0.046599        -0.010909
4      0.111491        -0.052357        -0.057141        -0.007919

   use_embedding_3  use_embedding_4  use_embedding_5  use_embedding_6  \
0        -0.026617         0.020445         0.003867         0.009433
1         0.046144         0.066032        -0.067002        -0.021723
2        -0.011676        -0.022839         0.022662         0.041136
3         0.027460         0.060216        -0.060324         0.057520
4        -0.028717         0.057074        -0.004967         0.038998

   use_embedding_7  use_embedding_8  use_embedding_9  use_embedding_10  \
0        -0.055062        -0.053429        -0.068910          0.003696
1         0.052850        -0.017364        -0.019699          0.020906
2        -0.014291        -0.063853        -0.062540         -0.043295
3        -0.055015         0.056964         0.045649         -0.010923
4        -0.025629         0.056967         0.046033         -0.002287

   use_embedding_11  use_embedding_12  use_embedding_13  use_embedding_14  \
0          0.020061          0.010820          0.030742          0.031649
1          0.001037         -0.040863          0.051007          0.002075
2         -0.033152          0.063500          0.036367         -0.009697
3         -0.012663          0.009247         -0.059563         -0.050419
4         -0.007752          0.056892          0.043772         -0.037327

   use_embedding_15  use_embedding_16  use_embedding_17  use_embedding_18  \
0         -0.024020         -0.039520          0.064324         -0.042426
1         -0.066549         -0.052261          0.049969         -0.031710
2         -0.041174          0.012809          0.021321          0.005839
3         -0.060405          0.055298          0.052108          0.012833
4         -0.057134          0.056958         -0.010395         -0.056792

   use_embedding_19  use_embedding_20  use_embedding_21  use_embedding_22  \
0          0.003099         -0.061533         -0.049349          0.064297
1         -0.040906         -0.035889          0.026802          0.037872
2         -0.053551         -0.043605          0.001487         -0.036566
3         -0.056798         -0.027848         -0.030608         -0.020283
4         -0.055701         -0.056912          0.053445          0.056458

   use_embedding_23  use_embedding_24  use_embedding_25  use_embedding_26  \
0         -0.046063          0.027209         -0.001092          0.067016
1          0.067021          0.044432          0.000260          0.003485
2          0.023517          0.039610         -0.024071          0.060916
3          0.060418          0.045912         -0.050202         -0.006652
4         -0.024645         -0.037869         -0.055765         -0.024979

   use_embedding_27  use_embedding_28  use_embedding_29  use_embedding_30  \
0          0.013396         -0.018858          0.005713         -0.046208
1          0.029175          0.059963          0.010278         -0.062609
2          0.046432          0.027933         -0.047315          0.034343
3         -0.053361         -0.021137         -0.045045         -0.051187
4          0.053384          0.004337          0.056096          0.055947

   use_embedding_31  use_embedding_32  use_embedding_33  use_embedding_34  \
0          0.061453          0.025858         -0.065615         -0.009667
1          0.033071         -0.035046         -0.026370         -0.064978
2         -0.013625          0.013998         -0.060110         -0.032791
3         -0.000408         -0.057508         -0.049918         -0.059986
4         -0.041637         -0.030988         -0.044782          0.039119

   use_embedding_35  use_embedding_36  use_embedding_37  use_embedding_38  \
0          0.020207          0.041979          0.043658         -0.040748
1         -0.062706         -0.036433          0.046896          0.000985
2          0.061172         -0.056258         -0.062734          0.009421
3         -0.060300         -0.059696          0.038481          0.055906
4          0.056875         -0.040509          0.053329         -0.029096

   use_embedding_39  use_embedding_40  use_embedding_41  use_embedding_42  \
0         -0.044444          0.070164          0.021018         -0.024099
1          0.048611          0.027040         -0.048923         -0.065221
2          0.041022          0.062976         -0.003421         -0.047037
3          0.041262         -0.018947          0.038756         -0.049328
4          0.057141          0.057127          0.018674          0.029065

   use_embedding_43  use_embedding_44  use_embedding_45  use_embedding_46  \
0         -0.005362         -0.071371          0.035344          0.041532
1         -0.037086         -0.065955          0.061284          0.020419
2         -0.060805         -0.063935          0.063272          0.060794
3         -0.022084         -0.060416          0.057604         -0.024043
4         -0.026538          0.057104          0.056720          0.032240

   use_embedding_47  use_embedding_48  use_embedding_49  use_embedding_50  \
0         -0.023140         -0.058027          0.054723         -0.067398
1         -0.057120          0.006482          0.019873         -0.060475
2         -0.028247         -0.017291          0.009007         -0.063280
3          0.033002          0.026457         -0.018980         -0.051183
4         -0.036187         -0.047185         -0.057120         -0.057040

   use_embedding_51  use_embedding_52  use_embedding_53  use_embedding_54  \
0          0.067929          0.044899          0.028260         -0.004224
1          0.066505          0.041101          0.063308          0.005009
2          0.049199          0.015410          0.036894         -0.000519
3          0.060250         -0.045615          0.018385          0.013513
4          0.042297         -0.022413         -0.014404          0.006164

   use_embedding_55  use_embedding_56  use_embedding_57  use_embedding_58  \
0          0.041252         -0.069346          0.029246          0.054705
1         -0.010041         -0.053509          0.019620          0.052488
2         -0.059126          0.019596          0.046049          0.054661
3         -0.059468         -0.055230          0.033768          0.058371
4         -0.046382         -0.044283          0.048129          0.056749

   use_embedding_59  use_embedding_60  use_embedding_61  use_embedding_62  \
0         -0.022725          0.067761          0.011572         -0.046673
1          0.035222          0.065084         -0.067002          0.008657
2         -0.061738          0.000274          0.035095         -0.032151
3          0.033985          0.060413         -0.060414         -0.060196
4         -0.042635          0.037369          0.014928         -0.056962

   use_embedding_63  use_embedding_64  use_embedding_65  use_embedding_66  \
0         -0.065254          0.038006         -0.054666          0.054993
1         -0.062776         -0.061192         -0.065175         -0.042654
2         -0.063900         -0.037521         -0.024060          0.063176
3         -0.060355         -0.055481         -0.041791         -0.007672
4         -0.052511          0.052131         -0.054217          0.050045

   use_embedding_67  use_embedding_68  use_embedding_69  use_embedding_70  \
0          0.048035         -0.067260          0.068754         -0.059997
1         -0.064762         -0.004593          0.058477         -0.067005
2          0.062045         -0.059013          0.063166         -0.057158
3         -0.058432          0.024716          0.057402         -0.060415
4          0.052801         -0.026071         -0.052646          0.036818

   use_embedding_71  use_embedding_72  use_embedding_73  use_embedding_74  \
0          0.070202          0.001794          0.000592         -0.037192
1          0.064837          0.010205         -0.045082         -0.040998
2          0.060995          0.010601          0.043433         -0.029307
3          0.060343          0.004184          0.026752         -0.043707
4          0.057062          0.057113          0.057141         -0.042895

   use_embedding_75  use_embedding_76  use_embedding_77  use_embedding_78  \
0          0.068251          0.023958          0.017307          0.020281
1         -0.032445          0.065940          0.030846          0.056887
2         -0.029356          0.015355         -0.003193         -0.018835
3         -0.009958          0.059448         -0.056450          0.016931
4          0.057096         -0.013839         -0.045384          0.052273

   use_embedding_79  use_embedding_80  use_embedding_81  use_embedding_82  \
0          0.061545          0.071371          0.021947          0.012009
1          0.040423          0.067011          0.032525         -0.032819
2          0.045939          0.063933         -0.017072          0.025266
3          0.041255          0.060418          0.045765         -0.005101
4          0.055540         -0.056875         -0.047517          0.003064

   use_embedding_83  use_embedding_84  use_embedding_85  use_embedding_86  \
0          0.019711         -0.023376         -0.067905          0.039303
1         -0.004531         -0.056104         -0.047383         -0.059658
2          0.024835         -0.059263         -0.053388          0.005747
3          0.050778         -0.037281         -0.038848          0.001385
4         -0.017337         -0.036200          0.043635         -0.052637

   use_embedding_87  use_embedding_88  use_embedding_89  use_embedding_90  \
0         -0.029714          0.063064          0.002921         -0.040765
1         -0.050210         -0.060052          0.014958         -0.014195
2          0.001636          0.060662         -0.000956         -0.051920
3         -0.017633         -0.059356         -0.034744          0.045907
4         -0.057141          0.057138          0.051495          0.006991

   use_embedding_91  use_embedding_92  use_embedding_93  use_embedding_94  \
0         -0.047585          0.016403         -0.044314          0.046679
1          0.032115         -0.025213          0.012917         -0.023260
2          0.042363         -0.040258          0.031452         -0.047307
3         -0.047177         -0.008337         -0.012812         -0.028096
4         -0.020925         -0.044415          0.036394         -0.055680

   use_embedding_95  use_embedding_96  use_embedding_97  use_embedding_98  \
0         -0.009566          0.059428          0.070486          0.069928
1          0.041962          0.041418          0.065898          0.067020
2         -0.021450          0.058053          0.063926          0.062044
3          0.058796          0.054468          0.060402          0.060418
4          0.054995          0.052411          0.042511          0.057141

   use_embedding_99  use_embedding_100  use_embedding_101  use_embedding_102  \
0         -0.065749          -0.018764           0.042294           0.006362
1         -0.033995           0.011879           0.054088          -0.033447
2         -0.061909           0.061972           0.048886           0.038663
3         -0.040360          -0.059995           0.052046          -0.053413
4         -0.052003          -0.055361           0.054592           0.035628

   use_embedding_103  use_embedding_104  use_embedding_105  use_embedding_106  \
0          -0.023871           0.030309           0.016379          -0.041109
1           0.028367          -0.053240           0.039212          -0.061964
2          -0.025581           0.054376           0.049209          -0.029361
3           0.039346           0.000203           0.052885          -0.057654
4          -0.048903           0.046274           0.050103          -0.050178

   use_embedding_107  use_embedding_108  use_embedding_109  use_embedding_110  \
0          -0.032971           0.002925           0.018498           0.000143
1           0.059464          -0.043827          -0.051984          -0.021650
2           0.020779          -0.056195           0.042168          -0.042049
3           0.059101          -0.047141           0.052338           0.011158
4           0.051901           0.056836           0.054598          -0.021453

   use_embedding_111  use_embedding_112  use_embedding_113  use_embedding_114  \
0           0.058467           0.000987          -0.038852          -0.036589
1           0.023439           0.031394          -0.001974          -0.054017
2           0.041116           0.063082           0.004375           0.016231
3          -0.046191           0.051240          -0.055519          -0.053501
4          -0.028808          -0.006012           0.052699           0.046713

   use_embedding_115  use_embedding_116  use_embedding_117  use_embedding_118  \
0          -0.054337           0.059496          -0.042548          -0.046451
1          -0.037773          -0.011044           0.045843          -0.066827
2          -0.047069          -0.024435          -0.046582          -0.024175
3           0.011346           0.035329          -0.054524          -0.053668
4          -0.018010          -0.036578           0.013994          -0.022293

   use_embedding_119  use_embedding_120  use_embedding_121  use_embedding_122  \
0          -0.031428          -0.010024           0.042607          -0.045928
1           0.026491           0.004700          -0.003484          -0.044614
2           0.001402           0.011380           0.044003          -0.021870
3          -0.036169          -0.055400          -0.015511           0.006612
4           0.038749          -0.056647           0.039160           0.034544

   use_embedding_123  use_embedding_124  use_embedding_125  use_embedding_126  \
0           0.063880           0.038856           0.024155           0.070443
1           0.051810           0.000436          -0.011676           0.066958
2           0.045338          -0.018274           0.033559          -0.029616
3           0.002364           0.056944           0.019525           0.060301
4           0.007430           0.021570           0.056976           0.057141

   use_embedding_127  use_embedding_128  use_embedding_129  use_embedding_130  \
0          -0.006666          -0.056390          -0.035999           0.051709
1          -0.067003           0.048434          -0.043947           0.014173
2          -0.057934           0.018105           0.063504          -0.057897
3          -0.060417          -0.009839          -0.021683           0.011133
4           0.032225           0.006405          -0.024418          -0.020719

   use_embedding_131  use_embedding_132  use_embedding_133  use_embedding_134  \
0           0.064817           0.047425          -0.045911          -0.049027
1           0.067021          -0.004581           0.032035          -0.012303
2           0.059603           0.041422          -0.061163          -0.051872
3           0.060418           0.051292          -0.051956          -0.055540
4          -0.051973           0.032064          -0.056502          -0.051768

   use_embedding_135  use_embedding_136  use_embedding_137  use_embedding_138  \
0           0.030614          -0.040154           0.063312          -0.032446
1          -0.040991          -0.056477          -0.053691          -0.058233
2           0.057651          -0.059385           0.016291          -0.054941
3          -0.033903          -0.055913           0.033394          -0.028456
4           0.039705          -0.009750           0.050909          -0.056384

   use_embedding_139  use_embedding_140  use_embedding_141  use_embedding_142  \

In [30]:
len(train.columns)

2895

In [ ]:
# import gc

# del df_train_final, df, df_ngrams, df_svd, df_pos, df_entities, df_deps, pos_df, ner_df, dep_df, pos_features, ner_features, dep_features

# gc.collect()

In [31]:
# show columns with nan values greater than 0

nan_cols = train.isna().sum()

nan_cols = nan_cols[nan_cols > 0]

nan_cols

Series([], dtype: int64)

In [33]:
drop_cols = ['full_text', 'clean_text', 'lowered']   # processed_docs', , 'global_coherence', 'topics'


train_df = train.copy()

train_df.drop(columns=drop_cols, inplace= True)

In [34]:
train_df.head()

  essay_id  score  paragraph_count  sentence_count  word_count  \
0  000d118      3                1              13         498
1  000fe60      3                5              21         332
2  001ab80      4                4              24         550
3  001bdc0      4                5              20         451
4  002ba53      3                6              15         373

   avg_paragraph_length  max_paragraph_length  min_paragraph_length  \
0            498.000000                   498                   498
1             66.400000                    98                    37
2            137.500000                   199                    85
3             90.200000                   165                    25
4             62.166667                   118                     2

   avg_sentence_length  max_sentence_length  min_sentence_length  \
0            38.307692                  127                    7
1            15.809524                   48                    2
2            22.916667                   46                    9
3            22.550000                   38                    5
4            24.933333                   76                    2

   avg_word_length  max_word_length  min_word_length  flesch_reading_ease  \
0         4.369478               25                1                57.98
1         4.018072               11                1                87.55
2         4.574545               15                1                65.15
3         4.982262               20                1                58.32
4         4.873995               14                1                54.66

   gunning_fog_index  sentiment_score  deberta_prob_0_full  \
0              17.33           0.9937             0.021534
1               7.48           0.7705             0.001421
2              11.49          -0.9731             0.001564
3              11.91           0.9702             0.000927
4              12.64           0.9771             0.031210

   deberta_prob_1_full  deberta_prob_2_full  deberta_prob_3_full  \
0             0.379466             0.529225             0.066918
1             0.071248             0.839510             0.086768
2             0.001929             0.033057             0.516632
3             0.005752             0.206941             0.767750
4             0.388895             0.522782             0.054104

   deberta_prob_4_full  deberta_prob_5_full  xlnet_prob_0  xlnet_prob_1  \
0             0.002071             0.000785      0.118853      0.174859
1             0.000765             0.000288      0.116731      0.167865
2             0.433214             0.013603      0.121194      0.172987
3             0.017782             0.000848      0.120910      0.168503
4             0.002046             0.000963      0.117731      0.174473

   xlnet_prob_2  xlnet_prob_3  xlnet_prob_4  xlnet_prob_5  use_embedding_0  \
0      0.158128      0.286387      0.150762      0.111011         0.041960
1      0.149173      0.298451      0.157676      0.110105        -0.051479
2      0.152385      0.294505      0.148131      0.110798        -0.001355
3      0.148743      0.297890      0.153702      0.110252         0.024647
4      0.146372      0.301475      0.148458      0.111491        -0.052357

   use_embedding_1  use_embedding_2  use_embedding_3  use_embedding_4  \
0        -0.067975         0.063115        -0.026617         0.020445
1        -0.021961         0.028500         0.046144         0.066032
2        -0.050998        -0.028374        -0.011676        -0.022839
3        -0.046599        -0.010909         0.027460         0.060216
4        -0.057141        -0.007919        -0.028717         0.057074

   use_embedding_5  use_embedding_6  use_embedding_7  use_embedding_8  \
0         0.003867         0.009433        -0.055062        -0.053429
1        -0.067002        -0.021723         0.052850        -0.017364
2         0.022662         0.041136        -0.014291        -0.063853
3        -0.060324         0.057520        -0.055015         0.056964
4        -0.004967         0.038998        -0.025629         0.056967

   use_embedding_9  use_embedding_10  use_embedding_11  use_embedding_12  \
0        -0.068910          0.003696          0.020061          0.010820
1        -0.019699          0.020906          0.001037         -0.040863
2        -0.062540         -0.043295         -0.033152          0.063500
3         0.045649         -0.010923         -0.012663          0.009247
4         0.046033         -0.002287         -0.007752          0.056892

   use_embedding_13  use_embedding_14  use_embedding_15  use_embedding_16  \
0          0.030742          0.031649         -0.024020         -0.039520
1          0.051007          0.002075         -0.066549         -0.052261
2          0.036367         -0.009697         -0.041174          0.012809
3         -0.059563         -0.050419         -0.060405          0.055298
4          0.043772         -0.037327         -0.057134          0.056958

   use_embedding_17  use_embedding_18  use_embedding_19  use_embedding_20  \
0          0.064324         -0.042426          0.003099         -0.061533
1          0.049969         -0.031710         -0.040906         -0.035889
2          0.021321          0.005839         -0.053551         -0.043605
3          0.052108          0.012833         -0.056798         -0.027848
4         -0.010395         -0.056792         -0.055701         -0.056912

   use_embedding_21  use_embedding_22  use_embedding_23  use_embedding_24  \
0         -0.049349          0.064297         -0.046063          0.027209
1          0.026802          0.037872          0.067021          0.044432
2          0.001487         -0.036566          0.023517          0.039610
3         -0.030608         -0.020283          0.060418          0.045912
4          0.053445          0.056458         -0.024645         -0.037869

   use_embedding_25  use_embedding_26  use_embedding_27  use_embedding_28  \
0         -0.001092          0.067016          0.013396         -0.018858
1          0.000260          0.003485          0.029175          0.059963
2         -0.024071          0.060916          0.046432          0.027933
3         -0.050202         -0.006652         -0.053361         -0.021137
4         -0.055765         -0.024979          0.053384          0.004337

   use_embedding_29  use_embedding_30  use_embedding_31  use_embedding_32  \
0          0.005713         -0.046208          0.061453          0.025858
1          0.010278         -0.062609          0.033071         -0.035046
2         -0.047315          0.034343         -0.013625          0.013998
3         -0.045045         -0.051187         -0.000408         -0.057508
4          0.056096          0.055947         -0.041637         -0.030988

   use_embedding_33  use_embedding_34  use_embedding_35  use_embedding_36  \
0         -0.065615         -0.009667          0.020207          0.041979
1         -0.026370         -0.064978         -0.062706         -0.036433
2         -0.060110         -0.032791          0.061172         -0.056258
3         -0.049918         -0.059986         -0.060300         -0.059696
4         -0.044782          0.039119          0.056875         -0.040509

   use_embedding_37  use_embedding_38  use_embedding_39  use_embedding_40  \
0          0.043658         -0.040748         -0.044444          0.070164
1          0.046896          0.000985          0.048611          0.027040
2         -0.062734          0.009421          0.041022          0.062976
3          0.038481          0.055906          0.041262         -0.018947
4          0.053329         -0.029096          0.057141          0.057127

   use_embedding_41  use_embedding_42  use_embedding_43  use_embedding_44  \
0          0.021018         -0.024099         -0.005362         -0.071371
1         -0.048923         -0.065221         -0.037086         -0.065955
2         -0.003421         -0.047037         -0.060805         -0.063935
3          0.038756         -0.049328         -0.022084         -0.060416
4          0.018674          0.029065         -0.026538          0.057104

   use_embedding_45  use_embedding_46  use_embedding_47  use_embedding_48  \
0          0.035344          0.041532         -0.023140         -0.058027
1          0.061284          0.020419         -0.057120          0.006482
2          0.063272          0.060794         -0.028247         -0.017291
3          0.057604         -0.024043          0.033002          0.026457
4          0.056720          0.032240         -0.036187         -0.047185

   use_embedding_49  use_embedding_50  use_embedding_51  use_embedding_52  \
0          0.054723         -0.067398          0.067929          0.044899
1          0.019873         -0.060475          0.066505          0.041101
2          0.009007         -0.063280          0.049199          0.015410
3         -0.018980         -0.051183          0.060250         -0.045615
4         -0.057120         -0.057040          0.042297         -0.022413

   use_embedding_53  use_embedding_54  use_embedding_55  use_embedding_56  \
0          0.028260         -0.004224          0.041252         -0.069346
1          0.063308          0.005009         -0.010041         -0.053509
2          0.036894         -0.000519         -0.059126          0.019596
3          0.018385          0.013513         -0.059468         -0.055230
4         -0.014404          0.006164         -0.046382         -0.044283

   use_embedding_57  use_embedding_58  use_embedding_59  use_embedding_60  \
0          0.029246          0.054705         -0.022725          0.067761
1          0.019620          0.052488          0.035222          0.065084
2          0.046049          0.054661         -0.061738          0.000274
3          0.033768          0.058371          0.033985          0.060413
4          0.048129          0.056749         -0.042635          0.037369

   use_embedding_61  use_embedding_62  use_embedding_63  use_embedding_64  \
0          0.011572         -0.046673         -0.065254          0.038006
1         -0.067002          0.008657         -0.062776         -0.061192
2          0.035095         -0.032151         -0.063900         -0.037521
3         -0.060414         -0.060196         -0.060355         -0.055481
4          0.014928         -0.056962         -0.052511          0.052131

   use_embedding_65  use_embedding_66  use_embedding_67  use_embedding_68  \
0         -0.054666          0.054993          0.048035         -0.067260
1         -0.065175         -0.042654         -0.064762         -0.004593
2         -0.024060          0.063176          0.062045         -0.059013
3         -0.041791         -0.007672         -0.058432          0.024716
4         -0.054217          0.050045          0.052801         -0.026071

   use_embedding_69  use_embedding_70  use_embedding_71  use_embedding_72  \
0          0.068754         -0.059997          0.070202          0.001794
1          0.058477         -0.067005          0.064837          0.010205
2          0.063166         -0.057158          0.060995          0.010601
3          0.057402         -0.060415          0.060343          0.004184
4         -0.052646          0.036818          0.057062          0.057113

   use_embedding_73  use_embedding_74  use_embedding_75  use_embedding_76  \
0          0.000592         -0.037192          0.068251          0.023958
1         -0.045082         -0.040998         -0.032445          0.065940
2          0.043433         -0.029307         -0.029356          0.015355
3          0.026752         -0.043707         -0.009958          0.059448
4          0.057141         -0.042895          0.057096         -0.013839

   use_embedding_77  use_embedding_78  use_embedding_79  use_embedding_80  \
0          0.017307          0.020281          0.061545          0.071371
1          0.030846          0.056887          0.040423          0.067011
2         -0.003193         -0.018835          0.045939          0.063933
3         -0.056450          0.016931          0.041255          0.060418
4         -0.045384          0.052273          0.055540         -0.056875

   use_embedding_81  use_embedding_82  use_embedding_83  use_embedding_84  \
0          0.021947          0.012009          0.019711         -0.023376
1          0.032525         -0.032819         -0.004531         -0.056104
2         -0.017072          0.025266          0.024835         -0.059263
3          0.045765         -0.005101          0.050778         -0.037281
4         -0.047517          0.003064         -0.017337         -0.036200

   use_embedding_85  use_embedding_86  use_embedding_87  use_embedding_88  \
0         -0.067905          0.039303         -0.029714          0.063064
1         -0.047383         -0.059658         -0.050210         -0.060052
2         -0.053388          0.005747          0.001636          0.060662
3         -0.038848          0.001385         -0.017633         -0.059356
4          0.043635         -0.052637         -0.057141          0.057138

   use_embedding_89  use_embedding_90  use_embedding_91  use_embedding_92  \
0          0.002921         -0.040765         -0.047585          0.016403
1          0.014958         -0.014195          0.032115         -0.025213
2         -0.000956         -0.051920          0.042363         -0.040258
3         -0.034744          0.045907         -0.047177         -0.008337
4          0.051495          0.006991         -0.020925         -0.044415

   use_embedding_93  use_embedding_94  use_embedding_95  use_embedding_96  \
0         -0.044314          0.046679         -0.009566          0.059428
1          0.012917         -0.023260          0.041962          0.041418
2          0.031452         -0.047307         -0.021450          0.058053
3         -0.012812         -0.028096          0.058796          0.054468
4          0.036394         -0.055680          0.054995          0.052411

   use_embedding_97  use_embedding_98  use_embedding_99  use_embedding_100  \
0          0.070486          0.069928         -0.065749          -0.018764
1          0.065898          0.067020         -0.033995           0.011879
2          0.063926          0.062044         -0.061909           0.061972
3          0.060402          0.060418         -0.040360          -0.059995
4          0.042511          0.057141         -0.052003          -0.055361

   use_embedding_101  use_embedding_102  use_embedding_103  use_embedding_104  \
0           0.042294           0.006362          -0.023871           0.030309
1           0.054088          -0.033447           0.028367          -0.053240
2           0.048886           0.038663          -0.025581           0.054376
3           0.052046          -0.053413           0.039346           0.000203
4           0.054592           0.035628          -0.048903           0.046274

   use_embedding_105  use_embedding_106  use_embedding_107  use_embedding_108  \
0           0.016379          -0.041109          -0.032971           0.002925
1           0.039212          -0.061964           0.059464          -0.043827
2           0.049209          -0.029361           0.020779          -0.056195
3           0.052885          -0.057654           0.059101          -0.047141
4           0.050103          -0.050178           0.051901           0.056836

   use_embedding_109  use_embedding_110  use_embedding_111  use_embedding_112  \
0           0.018498           0.000143           0.058467           0.000987
1          -0.051984          -0.021650           0.023439           0.031394
2           0.042168          -0.042049           0.041116           0.063082
3           0.052338           0.011158          -0.046191           0.051240
4           0.054598          -0.021453          -0.028808          -0.006012

   use_embedding_113  use_embedding_114  use_embedding_115  use_embedding_116  \
0          -0.038852          -0.036589          -0.054337           0.059496
1          -0.001974          -0.054017          -0.037773          -0.011044
2           0.004375           0.016231          -0.047069          -0.024435
3          -0.055519          -0.053501           0.011346           0.035329
4           0.052699           0.046713          -0.018010          -0.036578

   use_embedding_117  use_embedding_118  use_embedding_119  use_embedding_120  \
0          -0.042548          -0.046451          -0.031428          -0.010024
1           0.045843          -0.066827           0.026491           0.004700
2          -0.046582          -0.024175           0.001402           0.011380
3          -0.054524          -0.053668          -0.036169          -0.055400
4           0.013994          -0.022293           0.038749          -0.056647

   use_embedding_121  use_embedding_122  use_embedding_123  use_embedding_124  \
0           0.042607          -0.045928           0.063880           0.038856
1          -0.003484          -0.044614           0.051810           0.000436
2           0.044003          -0.021870           0.045338          -0.018274
3          -0.015511           0.006612           0.002364           0.056944
4           0.039160           0.034544           0.007430           0.021570

   use_embedding_125  use_embedding_126  use_embedding_127  use_embedding_128  \
0           0.024155           0.070443          -0.006666          -0.056390
1          -0.011676           0.066958          -0.067003           0.048434
2           0.033559          -0.029616          -0.057934           0.018105
3           0.019525           0.060301          -0.060417          -0.009839
4           0.056976           0.057141           0.032225           0.006405

   use_embedding_129  use_embedding_130  use_embedding_131  use_embedding_132  \
0          -0.035999           0.051709           0.064817           0.047425
1          -0.043947           0.014173           0.067021          -0.004581
2           0.063504          -0.057897           0.059603           0.041422
3          -0.021683           0.011133           0.060418           0.051292
4          -0.024418          -0.020719          -0.051973           0.032064

   use_embedding_133  use_embedding_134  use_embedding_135  use_embedding_136  \
0          -0.045911          -0.049027           0.030614          -0.040154
1           0.032035          -0.012303          -0.040991          -0.056477
2          -0.061163          -0.051872           0.057651          -0.059385
3          -0.051956          -0.055540          -0.033903          -0.055913
4          -0.056502          -0.051768           0.039705          -0.009750

   use_embedding_137  use_embedding_138  use_embedding_139  use_embedding_140  \
0           0.063312          -0.032446           0.036782          -0.039622
1          -0.053691          -0.058233          -0.010542          -0.066287
2           0.016291          -0.054941          -0.037733           0.028245
3           0.033394          -0.028456           0.038619          -0.056702
4           0.050909          -0.056384           0.036385          -0.056789

   use_embedding_141  use_embedding_142  use_embedding_143  use_embedding_144  \
0           0.071370           0.012913          -0.008181          -0.034732
1           0.066543           0.019010           0.021237           0.067000
2           0.063801           0.021817           0.027768          -0.053253
3           0.060418          -0.058716           0.014750           0.060417
4           0.057127           0.008737          -0.056470          -0.004777

   use_embedding_145  use_embedding_146  use_embedding_147  use_embedding_148  \
0          -0.033297          -0.015363          -0.058130          -0.053483
1           0.031089          -0.027444          -0.019946          -0.035823
2          -0.034967           0.057619          -0.057555           0.043024

In [35]:
from sklearn.model_selection import train_test_split

# Features and target variable
X = train_df.drop('score', axis=1)
y = train_df['score']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

In [36]:
feature_cols = []

for col in X_train.columns:
    if (col != 'essay_id') and (col != 'score'):
        feature_cols.append(col)

In [37]:
# pd.set_option('display.max_columns', None)
# feature_cols

In [38]:
# save the order of the column names to a txt file

with open(file_config['feature_cols'], 'w') as f:
    for item in feature_cols:
        f.write("%s\n" % item)

In [39]:
import sklearn
print(sklearn.__version__)

1.2.2

In [40]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pickle
import numpy as np

# Extract labels from the training and validation datasets
train_labels = y_train.copy()
val_labels = y_test.copy()

# Extract features for scaling
train_features = X_train[feature_cols] # Subset with only feature columns
val_features = X_test[feature_cols]

# Initialize the scaler
scaler = StandardScaler()  # Using StandardScaler for scaling

# Fit the scaler to the training features
scaler.fit(train_features)  # This defines the transformation based on the training data

# Transform training and validation features
train_feats_scaled = scaler.transform(train_features)  # Transforms the training data
val_feats_scaled = scaler.transform(val_features)  # Transforms the validation data

# Reassign the scaled features to the original DataFrames, keeping the same column names
X_train[feature_cols] = train_feats_scaled  # Replace the original features with scaled ones
X_test[feature_cols] = val_feats_scaled

# Save the scaler for later use
with open(file_config['scaler'], 'wb') as f:
    pickle.dump(scaler, f)  # Persist the scaler for future use or reference

In [41]:
print(X_train.shape, X_test.shape)

(12114, 2891) (5193, 2891)

In [42]:
# Check if the file has been written correctly and is not empty
import os

scaler_path = file_config['scaler']

if os.path.getsize(scaler_path) > 0:

    print(f"Scaler saved successfully in {scaler_path}.")
    
else:

    print(f"Failed to save scaler to {scaler_path}. File is empty.")

Scaler saved successfully in /home/jack/github/kaggle/scoring/model_data/sklearn/scaler.pkl.

In [43]:
# Check if the scaler is StandardScaler
if isinstance(scaler, StandardScaler):
    print("The scaler is a StandardScaler.")
elif isinstance(scaler, MinMaxScaler):
    print("The scaler is a MinMaxScaler.")
else:
    print("The scaler is neither StandardScaler nor MinMaxScaler.")

The scaler is a StandardScaler.

In [44]:
# To convert features and targets to NumPy arrays for ML use

# train_features = X_train.values

# train_labels = np.array(train_labels.values)

# val_features = X_test.values

# val_labels = np.array(y_test.values)




# print("Features shape:", train_features.shape)
# print("Target shape:", train_labels.shape)

# print("Features shape:", val_features.shape)
# print("Target shape:", val_labels.shape)



#####     Features shape: (3, 1389)

In [45]:
import pandas as pd
from sklearn.utils import resample
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from imblearn.over_sampling import SMOTE
from sklearn import ensemble, model_selection, metrics
import numpy as np
import pickle
import os
from sklearn.base import clone
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import make_scorer, accuracy_score, cohen_kappa_score
import keras_tuner

# Function to compute Quadratic Weighted Kappa
def quadratic_weighted_kappa_scorer(y_true, y_pred):
    return cohen_kappa_score(y_true, y_pred, weights='quadratic')

# Define the model building function for the tuner
def build_model(hp):
    model_type = hp.Choice('model_type', ['random_forest', 'gradient_boosting', 'lightgbm'])
    if model_type == 'random_forest':
        model = ensemble.RandomForestClassifier(
            n_estimators=hp.Int('n_estimators', 10, 100, step=10),
            max_depth=hp.Int('max_depth', 3, 20),
            min_samples_split=hp.Int('min_samples_split', 2, 20),
            min_samples_leaf=hp.Int('min_samples_leaf', 1, 10),
            criterion=hp.Choice('criterion', ['gini', 'entropy']),
            class_weight=hp.Choice('class_weight', ['balanced', 'balanced_subsample']),
            max_samples=hp.Float('max_samples', 0.1, 1.0, sampling='log'))
    elif model_type == 'gradient_boosting':
        model = ensemble.GradientBoostingClassifier(
            n_estimators=hp.Int('n_estimators', 50, 200, step=50),
            learning_rate=hp.Float('learning_rate', 0.01, 0.2, sampling='log'),
            max_depth=hp.Int('max_depth', 3, 15),
            subsample=hp.Float('subsample', 0.5, 1.0, step=0.1))
    else:  # LightGBM
        from lightgbm import LGBMClassifier
        model = LGBMClassifier(
            n_estimators=hp.Int('n_estimators', 50, 200, step=50),
            num_leaves=hp.Int('num_leaves', 31, 127, step=16),
            learning_rate=hp.Float('learning_rate', 0.01, 0.2, sampling='log'),
            min_child_samples=hp.Int('min_child_samples', 10, 50, step=10),
            max_depth=hp.Int('max_depth', 3, 15),  # Tunable max_depth parameter
            min_data_in_leaf=hp.Int('min_data_in_leaf', 20, 100, step=10),  # Increases the minimum data per leaf
            min_gain_to_split=hp.Float('min_gain_to_split', 0.001, 0.1, sampling='log'),  # Ensures splits bring gains
            lambda_l1=hp.Float('lambda_l1', 0.01, 10.0, sampling='log'),  # L1 regularization
            lambda_l2=hp.Float('lambda_l2', 0.01, 10.0, sampling='log'),  # L2 regularization
            force_col_wise=True,  # Force using column-wise calculation to avoid overhead
            class_weight='balanced'  # Handling class imbalance
        )
    return model





# Prepare data: Assuming X_train and y_train are already defined
X_train_original = X_train.drop(columns='essay_id').copy()  # Keep the original training data
y_train_original = y_train.drop(columns='essay_id').copy() 

# Apply SMOTE to balance the minority classes
smote = SMOTE(sampling_strategy='not majority', random_state=42)
X_train_upsampled, y_train_upsampled = smote.fit_resample(X_train_original, y_train_original)

2024-05-27 17:46:38.826113: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-27 17:46:39.674064: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [46]:
# Tuner configuration
tuner = keras_tuner.tuners.SklearnTuner(
    oracle=keras_tuner.oracles.BayesianOptimizationOracle(
        objective=keras_tuner.Objective('score', 'max'),
        max_trials=10),
    hypermodel=build_model,
    scoring=make_scorer(quadratic_weighted_kappa_scorer),
    cv=model_selection.StratifiedKFold(5),
    directory='.',
    project_name='data/sklearn',
    overwrite=True)


# Tuning on the original data
tuner.search(X_train_original.values, y_train_original.values)

Trial 4 Complete [00h 00m 24s]
score: 0.8972618410327252

Best score So Far: 0.902710733539065
Total elapsed time: 00h 03m 39s

Search: Running Trial #5

Value             |Best Value So Far |Hyperparameter
gradient_boosting |lightgbm          |model_type
20                |60                |n_estimators
10                |18                |max_depth
5                 |3                 |min_samples_split
10                |7                 |min_samples_leaf
gini              |entropy           |criterion
balanced_subsample|balanced_subsample|class_weight
0.50961           |0.12221           |max_samples
111               |127               |num_leaves
0.12777           |0.021199          |learning_rate
50                |50                |min_child_samples
60                |80                |min_data_in_leaf
0.038145          |0.0016527         |min_gain_to_split
0.17072           |0.44372           |lambda_l1
0.59275           |0.010688          |lambda_l2

In [ ]:
# # apply smote within k-fold cross validation in order to avoid data leakage

# # Define the cross-validation strategy

# cv = model_selection.StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# # Initialize the model
# model = ensemble.RandomForestClassifier(random_state=42)

# # Initialize the SMOTE object

# smote = SMOTE(sampling_strategy='not majority', random_state=42)

# # Initialize the StandardScaler
# scaler = StandardScaler()

# # Initialize the list to store the cross-validated scores

# cv_scores = []

# # Perform cross-validation

# for train_idx, val_idx in cv.split(X_train, y_train):

#     # Extract the training and validation data
#     X_train_fold, y_train_fold = X_train.iloc[train_idx], y_train.iloc[train_idx]
#     X_val_fold, y_val_fold = X_train.iloc[val_idx], y_train.iloc[val_idx]

#     # Apply SMOTE to the training data
#     X_train_resampled, y_train_resampled = smote.fit_resample(X_train_fold, y_train_fold)

#     # Scale the training and validation data
#     X_train_scaled = scaler.fit_transform(X_train_resampled)
#     X_val_scaled = scaler.transform(X_val_fold)

#     # Fit the model on the training data
#     model.fit(X_train_scaled, y_train_resampled)

#     # Predict the target on the validation data
#     y_pred = model.predict(X_val_scaled)

#     # Compute the Quadratic Weighted Kappa
#     qwk = quadratic_weighted_kappa_scorer(y_val_fold, y_pred)

#     # Append the score to the list
#     cv_scores.append(qwk)

# # Compute the average score

# cv_score = np.mean(cv_scores)

# # Print the average score

# print(f"Average Quadratic Weighted Kappa: {cv_score:.4f}")

# # Save the model

# with open(file_config['sklearn_model'], 'wb') as f:
#     pickle.dump(model, f)

In [ ]:
# Retrieve the best model
best_model = tuner.get_best_models(num_models=1)[0]

# Fit models on both upsampled and original data
model_standard = clone(best_model)
model_standard.fit(X_train_original, y_train_original)

model_upsampled = clone(best_model)
model_upsampled.fit(X_train_upsampled, y_train_upsampled)

# Ensemble using voting
ensemble_model = VotingClassifier(estimators=[
    ('standard', model_standard),
    ('upsampled', model_upsampled)
], voting='soft')

In [ ]:
# Assuming X_val and y_val are your validation sets

ensemble_model.fit(X_train_original, y_train_original)  # Optionally refit if necessary

In [ ]:
predictions = ensemble_model.predict(X_test)

# Evaluate and print results
print("Validation Accuracy:", accuracy_score(val_labels, predictions))
print("Validation Cohen's Kappa:", quadratic_weighted_kappa_scorer(val_labels, predictions))
print("Validation Quadratic Weighted Kappa:", quadratic_weighted_kappa_scorer(val_labels, predictions))
print("Validation Cohens Weighted Kappa:",cohen_kappa_score(val_labels, predictions, weights='quadratic'))

In [ ]:
# confusion matrix

from sklearn.metrics import confusion_matrix

confusion_matrix(val_labels, predictions)

In [ ]:
# classification report

from sklearn.metrics import classification_report

print(classification_report(val_labels, predictions))

In [ ]:
from joblib import dump, load

dump(ensemble_model, file_config['sklearn_model'])

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Generate and display the confusion matrix for the test predictions
cm = confusion_matrix(val_labels, predictions, labels=best_model.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=best_model.classes_)
disp.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix')
plt.show()

In [ ]:
X_test['predictions'] = predictions

df_aggregated = X_test.groupby('essay_id')['predictions'].agg(lambda x: x.value_counts().index[0]).reset_index()

df_aggregated.head()

In [ ]:
# Identifying misclassified samples
misclassified_indices = (y_true != predictions)
misclassified_samples = val_features[misclassified_indices]
misclassified_true_labels = y_true[misclassified_indices]
misclassified_predicted_labels = predictions[misclassified_indices]

In [ ]:
# Examining features of misclassified samples
import pandas as pd
misclassified_df = pd.DataFrame(misclassified_samples)
misclassified_df['True_Label'] = misclassified_true_labels
misclassified_df['Predicted_Label'] = misclassified_predicted_labels
# Display the first few rows of the misclassified samples
misclassified_df.head()

In [ ]:
# # Feature importance from LightGBM
# feature_importance = best_model.feature_importance(importance_type='gain')
# feature_names = val_features.columns
# feature_importance_df = pd.DataFrame({
#     'Feature': feature_names,
#     'Importance': feature_importance
# })
# # Sort features by importance
# feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)
# print(feature_importance_df)

In [ ]:
# Checking class distribution in the true labels
label_counts = pd.Series(y_true).value_counts()
print(label_counts)

In [ ]:
# from sklearn.model_selection import GridSearchCV
# # Define the hyperparameters to tune
# param_grid = {
#     'learning_rate': [0.01, 0.05, 0.1],
#     'num_leaves': [31, 62, 128],
#     'n_estimators': [50, 100, 200]
# }
# grid_search = GridSearchCV(best_model, param_grid, scoring='', cv=5)
# grid_search.fit(val_features, val_labels)
# print("Best parameters:", grid_search.best_params_)

In [ ]:
# Check LightGBM version
import lightgbm as lgb
print(lgb.__version__)

In [ ]:
# # Ensure the model is fitted
# if not hasattr(best_model, 'feature_importance_'):
#     best_model.fit(val_features, val_labels)  # Train or re-train the model

# # Retrieve feature importance
# feature_importance = best_model.feature_importance_  # Underscore at the end
# feature_names = val_features.columns

# # Create DataFrame for feature importance
# feature_importance_df = pd.DataFrame({
#     'Feature': feature_names,
#     'Importance': feature_importance
# })
# feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# print(feature_importance_df)

In [ ]:
# Assuming `df` is the original DataFrame and `predictions` is a list/array of predicted labels
# If there's a subset used for predictions, ensure it aligns with the DataFrame
val_df['Predicted_Label'] = predictions

In [ ]:
print(len(val_features), len(val_df), len(predictions))

In [ ]:
val_df.tail()

In [ ]:
# merge 'clean_text' column back with val df 

text = val_essays[['essay_id', 'clean_text']]

val_df = val_df.merge(text, on = 'essay_id')

val_df.head()

In [ ]:
# Assuming `df` has the original labels in a column named 'True_Label'
misclassified_samples = val_df[val_df['score'] != val_df['Predicted_Label']]

# Display misclassified samples
print(misclassified_samples[['score', 'Predicted_Label', 'clean_text']][:15])

In [ ]:
# Example: Analyze original text of misclassified samples
misclassified_text = misclassified_samples['clean_text']  # Assuming 'Text' is the original text data
print(misclassified_text.head())

In [ ]:
# load tf model
len(misclassified_text)

In [ ]:
# add full mis classified text to a txt file seperated by  '---' and a new line after every 10 words in each essay

with open('misclassified_text.txt', 'w') as f:
    for essay in misclassified_text:
        f.write("%s\n" % essay)
        f.write('---\n')

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Assuming `df` has your model's features and labels
X = val_df[feature_cols]
y = val_df['score'] == val_df['Predicted_Label']

# Splitting the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Fit a RandomForest to see feature importances
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)

# Get the most important features
importances = clf.feature_importances_
features = feature_cols
important_features = {features[i]: importances[i] for i in range(len(features))}

# convert to percentages rounded and sort

important_features = {k: round(v, 5) for k, v in important_features.items()}

print("Most predictive features of misclassification:", sorted(important_features.items(), key=lambda x: x[1], reverse=True))

In [ ]:
# import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt

# # Assume val_df and feature_cols are already defined

# # Set the option to display all rows
# pd.set_option('display.max_rows', None)

# # Selecting the features and the target
# X = val_df[feature_cols]
# y = val_df['score']

# # Calculate the correlation between features and the target
# corr = X.corrwith(y)

# # Sort the correlation values
# corr = corr.sort_values(ascending=False)

# # Convert the Series to a DataFrame for heatmap compatibility
# corr_df = pd.DataFrame(corr, columns=['Correlation'])

# corr_df

In [ ]:
# from sklearn.model_selection import train_test_split
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.metrics import classification_report

# # Define the feature set with and without the specific features
# X_with = val_df[feature_cols]  # including all features
# X_without = val_df.drop(columns=['misspelling_count', 'sentence_length'], axis=1) # excluding problematic features

# y = val_df['score']  # target variable

# # Split the data
# X_train_with, X_test_with, y_train, y_test = train_test_split(X_with, y, test_size=0.3, random_state=42)
# X_train_without, X_test_without, _ , _ = train_test_split(X_without, y, test_size=0.3, random_state=42)

# # Train models
# model_with = RandomForestClassifier().fit(X_train_with, y_train)
# model_without = RandomForestClassifier().fit(X_train_without, y_train)

# # Evaluate models
# print("With features:")
# print(classification_report(y_test, model_with.predict(X_test_with)))

# print("Without features:")
# print(classification_report(y_test, model_without.predict(X_test_without)))