# sklearn model with tensorflow keras tuner

In [1]:
import sklearn
print(sklearn.__version__)

1.2.2

In [2]:
import re
import pandas as pd
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm import tqdm
from textstat import flesch_reading_ease, gunning_fog
import numpy as np

# nltk.download('punkt')
# nltk.download('averaged_perceptron_tagger')
# nltk.download('stopwords')
# nltk.download('vader_lexicon')

def extract_and_aggregate_features(df, text_column):
    """Extracts and aggregates features at the paragraph, sentence, and word levels."""
    # Processing text into paragraphs, sentences, and words
    df['paragraph_lengths'] = df[text_column].apply(lambda x: [len(p.split()) for p in x.split('\n\n') if p.strip()])
    df['sentence_lengths'] = df[text_column].apply(lambda x: [len(s.split()) for s in nltk.sent_tokenize(x)])
    df['word_lengths'] = df[text_column].apply(lambda x: [len(w) for w in x.split()])

    # Aggregating features
    df['paragraph_count'] = df['paragraph_lengths'].apply(len)
    df['sentence_count'] = df['sentence_lengths'].apply(len)
    df['word_count'] = df['word_lengths'].apply(len)

    df['avg_paragraph_length'] = df['paragraph_lengths'].apply(np.mean)
    df['max_paragraph_length'] = df['paragraph_lengths'].apply(max)
    df['min_paragraph_length'] = df['paragraph_lengths'].apply(min)

    df['avg_sentence_length'] = df['sentence_lengths'].apply(np.mean)
    df['max_sentence_length'] = df['sentence_lengths'].apply(max)
    df['min_sentence_length'] = df['sentence_lengths'].apply(min)

    df['avg_word_length'] = df['word_lengths'].apply(np.mean)
    df['max_word_length'] = df['word_lengths'].apply(max)
    df['min_word_length'] = df['word_lengths'].apply(min)

    # Cleaning up DataFrame to remove list columns
    df.drop(['paragraph_lengths', 'sentence_lengths', 'word_lengths'], axis=1, inplace=True)

    return df

def compute_readability_and_sentiment(df, text_column):
    """Computes readability scores and sentiment analysis."""
    df['flesch_reading_ease'] = df[text_column].apply(flesch_reading_ease)
    df['gunning_fog_index'] = df[text_column].apply(gunning_fog)
    sia = SentimentIntensityAnalyzer()
    df['sentiment_score'] = df[text_column].apply(lambda x: sia.polarity_scores(x)['compound'])

    return df


def add_text_features(df, text_column):
    """Main function to aggregate all text processing and feature extraction steps."""
    tqdm.pandas(desc="Extracting and aggregating text features")
    df = extract_and_aggregate_features(df, text_column)
    df = compute_readability_and_sentiment(df, text_column)


    
    return df

In [3]:

import wordninja
from nltk.corpus import words

# Load a set of valid English words from NLTK for verification (if needed)
word_list = set(words.words())

def segment_text(text, word_list=word_list):
    """
    Segments concatenated words using wordninja, verifying segmentation with an NLTK words list.

    Args:
    text (str): A string of concatenated words.
    word_list (set): A set containing valid words.

    Returns:
    str: Segmented text, or the original text if segmentation results in less common words.
    """
    segmented_words = wordninja.split(text)
    segmented_text = ' '.join(segmented_words)

    # Optional: verify if the original text is a valid word and if the segmented version introduces less common words
    if text in word_list and not all(word in word_list for word in segmented_words):
        return text
    else:
        return segmented_text



def apply_segmentation(df_chunk, text_col='clean_text'):
    """
    Applies text segmentation to the specified 'text' column of a DataFrame chunk using wordninja.

    Args:
    df_chunk (pd.DataFrame): DataFrame chunk containing a text column with concatenated words.

    Returns:
    pd.DataFrame: DataFrame chunk with a new column 'segmented_text' containing segmented text.
    """
    df_chunk['clean_text'] = df_chunk[text_col].apply(lambda x: segment_text(x))
    return df_chunk

In [4]:
def clean_text(df, col_name = 'full_text'):
    """
    Preprocesses text for both training and testing datasets. 
    Includes loading embeddings, building vocabularies, cleaning text among other things.
    
    :param summaries_train: DataFrame with the training data
    :param summaries_test: DataFrame with the testing data
    :param glove_path: path to the GloVe embedding
    :param paragram_path: path to the Paragram embedding
    :param wiki_news_path: path to the Wiki News embedding
    
    :return: Preprocessed DataFrame and list of out-of-vocab words
    """
    print("Starting text cleaning process. \n")

    
    # Lowercase all texts

    df['lowered'] = df[col_name].apply(lambda x: x.lower())

    
    
    def clean_spacing(text):
        
        # Remove spaces before punctuation
        text = re.sub(r'\s+([,.!?])', r'\1', text)

        # Ensure there is one space after punctuation
        text = re.sub(r'([,.!?])([^\s])', r'\1 \2', text)

        return text
    

    df['clean_text'] = df['lowered'].apply(lambda x: clean_spacing(x))


        
    punct = "/-'?!.,#$%\'()*+-/:;<=>@[\\]^_`{|}~" + '""“”’' + '∞θ÷α•à−β∅³π‘₹´°£€\×™√²—–&'
    
    punct_mapping = {"‘": "'", "₹": "e", "´": "'", "°": "", "€": "e", "™": "tm", "√": " sqrt ", "×": "x", "²": "2", "—": "-", "–": "-", "’": "'", "_": "-",
                     "`": "'", '“': '"', '”': '"', '“': '"', "£": "e", '∞': 'infinity', 'θ': 'theta', '÷': '/', 'α': 'alpha', '•': '.', 'à': 'a', '−': '-', 
                     'β': 'beta', '∅': '', '³': '3', 'π': 'pi', }

    def clean_special_chars(text, punct, mapping):
        for p in mapping:
            text = text.replace(p, mapping[p])
        for p in punct:
            text = text.replace(p, f' {p} ')
        specials = {'\u200b': ' ', '…': ' ... ', '\ufeff': '', 'करना': '', 'है': ''}  
        for s in specials:
            text = text.replace(s, specials[s])
        return text
    

    df['clean_text'] = df['clean_text'].apply(lambda x: clean_special_chars(x, punct, punct_mapping))

    df['clean_text'] = df['lowered'].apply(lambda x: clean_spacing(x))


    cont_map = {
        "ain't": "am not","aren't": "are not","can't": "cannot","can't've": "cannot have","'cause": "because",  "could've": "could have",
        "couldn't": "could not","couldn't've": "could not have","didn't": "did not","doesn't": "does not","don't": "do not","hadn't": "had not",
        "hadn't've": "had not have","hasn't": "has not",
        "haven't": "have not","he'd": "he would","he'd've": "he would have","he'll": "he will","he'll've": "he will have","he's": "he is",
        "how'd": "how did","how'd'y": "how do you","how'll": "how will","how's": "how is","I'd": "I would","I'd've": "I would have","I'll": "I will",
        "I'll've": "I will have","I'm": "I am","I've": "I have",
        "isn't": "is not","it'd": "it had","it'd've": "it would have","it'll": "it will", "it'll've": "it will have","it's": "it is","let's": "let us",
        "ma'am": "madam","mayn't": "may not",
        "might've": "might have","mightn't": "might not","mightn't've": "might not have","must've": "must have","mustn't": "must not",
        "mustn't've": "must not have","needn't": "need not","needn't've": "need not have","o'clock": "of the clock","oughtn't": "ought not",
        "oughtn't've": "ought not have","shan't": "shall not","sha'n't": "shall not",
        "shan't've": "shall not have","she'd": "she would","she'd've": "she would have","she'll": "she will","she'll've": "she will have","she's": "she is",
        "should've": "should have","shouldn't": "should not","shouldn't've": "should not have","so've": "so have","so's": "so is","that'd": "that would",
        "that'd've": "that would have","that's": "that is","there'd": "there had","there'd've": "there would have","there's": "there is",
        "they'd": "they would","they'd've": "they would have","they'll": "they will","they'll've": "they will have","they're": "they are",
        "they've": "they have","to've": "to have","wasn't": "was not","we'd": "we had",
        "we'd've": "we would have","we'll": "we will","we'll've": "we will have","we're": "we are","we've": "we have",
        "weren't": "were not","what'll": "what will","what'll've": "what will have",
        "what're": "what are","what's": "what is","what've": "what have","when's": "when is","when've": "when have",
        "where'd": "where did","where's": "where is","where've": "where have","who'll": "who will","who'll've": "who will have","who's": "who is",
        "who've": "who have","why's": "why is",
        "why've": "why have","will've": "will have","won't": "will not","won't've": "will not have","would've": "would have","wouldn't": "would not",
        "wouldn't've": "would not have","y'all": "you all","y'alls": "you alls","y'all'd": "you all would",
        "y'all'd've": "you all would have","y'all're": "you all are","y'all've": "you all have","you'd": "you had","you'd've": "you would have",
        "you'll": "you you will","you'll've": "you you will have","you're": "you are",  "you've": "you have"}

    c_re = re.compile('(%s)' % '|'.join(cont_map.keys()))

    def expandContractions(text, c_re=c_re):
        def replace(match):
            return cont_map[match.group(0)]
        return c_re.sub(replace, text)


#     p = inflect.engine()

    def removeHTML(text):
        """
        Remove HTML tags from a given text string using regex.
    
        Args:
            text (str): The input text string containing HTML tags.
    
        Returns:
            str: The text string with HTML tags removed.
        """
        html = re.compile(r'<.*?>')
        return html.sub('', text)

    def dataPreprocessing(text):
        """
        Process the input text to perform a series of cleaning and formatting tasks,
        including converting numbers to words, removing specific patterns and whitespace,
        and stripping unwanted characters.
    
        Args:
            text (str): The input text string to preprocess.
    
        Returns:
            str: The cleaned and formatted text.
        """
        text = text.lower()
        text = removeHTML(text)
        # text = re.sub(r'\d+', lambda match: p.number_to_words(match.group()) + " ", text)  # Add spaces around the number words
        text = re.sub(r'\s+', ' ', text)  # Normalize multiple spaces to a single space
        text = re.sub(r"@\w+", '', text)
        text = re.sub(r"'\d+", '', text)
        text = re.sub(r"\d+", '', text)
        text = re.sub(r"http\w+", '', text)
        text = re.sub(r"[-_]+", " ", text)  # Replace hyphens and underscores with space
        text = expandContractions(text)
        text = re.sub(r"\.+", ".", text)
        text = re.sub(r"\,+", ",", text)
        text = re.sub(r"[^\w\s]", "", text)  # Remove all non-alphanumeric and non-space characters
        text = re.sub(r"\s+", " ", text)    # Normalize multiple spaces to a single space

        text = text.strip()

        return text

    
    df['clean_text'] = df['clean_text'].apply(lambda x: dataPreprocessing(x))
    
    # Step 8: Generate combined dense vector for each row of text
    
    # df['combined_dense_vector'] = df['clean_text'].apply(lambda x: get_combined_dense_vector(x, embeddings))

    # # Expand the combined dense vector into separate columns
    
    # combined_df = pd.DataFrame(list(df['combined_dense_vector']), 
    #                            columns=[f"dense_vec_{i}" for i in range(df['combined_dense_vector'][0].size)])

    # # Concatenate this new DataFrame with the original DataFrame
    
    # df = pd.concat([df, combined_df], axis=1)

    # # Step 9: Add TF-IDF features to the corrected text
    
    # df.drop(columns=['combined_dense_vector'], inplace=True)
    
    print('Adding Text Features................. \n')
    
    df = add_text_features(df, 'full_text')

    print('Complete................. \n')
    
    return df

In [5]:
import sklearn
print(sklearn.__version__)

1.2.2

In [7]:
laptop = False

if laptop:
    csv_path = '/home/laptop/github/kaggle/scoring/xlnet_hash.csv'

if not laptop:
    csv_path = '/home/jack/github/kaggle/scoring/xlnet_hash.csv'

In [8]:
pd.set_option('display.max_columns', None)

deberta_full = pd.read_csv(csv_path)
deberta_full.drop(columns=['score', 'labels', 'clean_text'], inplace=True)
deberta_full.head()

,essay_id,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199
0,000fe60,0.015906,0.832160,0.148738,0.002510,0.000311,0.000375,0.136665,0.115104,0.258191,0.112356,0.164195,0.213489,0.071429,0.023810,0.023810,0.000000,0.000000,0.119048,0.000000,0.02381,0.000000,0.047619,0.023810,0.023810,0.023810,0.0,0.119048,0.023810,0.02381,0.000000,0.119048,0.023810,0.000000,0.000000,0.000000,0.023810,0.000000,0.0,0.000000,0.023810,0.000000,0.047619,0.000000,0.000000,0.047619,0.071429,0.047619,0.071429,0.000000,0.142857,0.000000,0.000000,0.190476,0.000000,0.000000,0.023810,0.000000,0.190476,0.047619,0.000000,0.000000,0.000000,0.000000,0.095238,0.000000,0.000000,0.000000,0.095238,0.071429,0.047619,0.000000,0.023810,0.023810,0.119048,0.047619,0.000000,0.000000,0.000000,0.0,0.000000,0.023810,0.023810,0.0,0.000000,0.000000,0.023810,0.023810,0.071429,0.047619,0.285714,0.000000,0.000000,0.000000,0.047619,0.000000,0.000000,0.00000,0.023810,0.119048,0.047619,0.023810,0.023810,0.071429,0.214286,0.023810,0.095238,0.000000,0.261905,0.000000,0.047619,0.023810,0.071429,0.000000,0.02381,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.023810,0.071429,0.285714,0.023810,0.000000,0.000000,0.071429,0.000000,0.000000,0.190476,0.023810,0.000000,0.023810,0.000000,0.023810,0.238095,0.000000,0.047619,0.000000,0.000000,0.000000,0.000000,0.071429,0.000000,0.000000,0.000000,0.000000,0.142857,0.0,0.000000,0.023810,0.071429,0.0,0.023810,0.047619,0.000000,0.095238,0.000000,0.0,0.02381,0.000000,0.000000,0.000000,0.047619,0.190476,0.023810,0.142857,0.000000,0.071429,0.214286,0.023810,0.047619,0.000000,0.000000,0.023810,0.000000,0.000000,0.047619,0.0,0.000000,0.047619,0.000000,0.02381,0.00000,0.000000,0.000000,0.071429,0.000000,0.000000,0.02381,0.000000,0.000000,0.071429,0.142857,0.0,0.047619,0.023810,0.047619,0.047619,0.285714,0.095238,0.000000,0.119048,0.000000,0.000000,0.000000,0.023810,0.190476,0.071429,0.000000,0.02381
1,001ab80,0.001099,0.010704,0.344778,0.631197,0.011407,0.000815,0.132327,0.110495,0.258206,0.115311,0.163469,0.220192,0.014565,0.000000,0.058259,0.000000,0.014565,0.058259,0.189343,0.00000,0.014565,0.029130,0.014565,0.058259,0.000000,0.0,0.029130,0.014565,0.00000,0.014565,0.000000,0.014565,0.000000,0.000000,0.000000,0.014565,0.014565,0.0,0.000000,0.029130,0.000000,0.160213,0.014565,0.029130,0.000000,0.029130,0.058259,0.043694,0.000000,0.145648,0.014565,0.029130,0.087389,0.029130,0.116519,0.000000,0.014565,0.116519,0.029130,0.000000,0.014565,0.043694,0.014565,0.014565,0.043694,0.029130,0.000000,0.043694,0.000000,0.014565,0.000000,0.000000,0.029130,0.131083,0.058259,0.014565,0.014565,0.000000,0.0,0.000000,0.014565,0.000000,0.0,0.000000,0.014565,0.029130,0.014565,0.072824,0.058259,0.145648,0.043694,0.029130,0.145648,0.000000,0.029130,0.000000,0.02913,0.029130,0.160213,0.029130,0.000000,0.131083,0.043694,0.305861,0.087389,0.087389,0.000000,0.189343,0.000000,0.014565,0.145648,0.014565,0.014565,0.00000,0.0,0.145648,0.000000,0.000000,0.000000,0.0,0.043694,0.000000,0.087389,0.160213,0.000000,0.014565,0.000000,0.029130,0.000000,0.014565,0.072824,0.029130,0.000000,0.029130,0.000000,0.014565,0.043694,0.014565,0.072824,0.029130,0.014565,0.000000,0.014565,0.087389,0.000000,0.101954,0.145648,0.116519,0.116519,0.0,0.014565,0.000000,0.000000,0.0,0.014565,0.014565,0.014565,0.160213,0.014565,0.0,0.00000,0.029130,0.000000,0.014565,0.087389,0.043694,0.000000,0.014565,0.043694,0.029130,0.407815,0.029130,0.000000,0.058259,0.014565,0.072824,0.000000,0.043694,0.029130,0.0,0.014565,0.058259,0.000000,0.00000,0.02913,0.000000,0.000000,0.000000,0.087389,0.014565,0.00000,0.000000,0.029130,0.029130,0.189343,0.0,0.101954,0.043694,0.087389,0.087389,0.189343,0.116519,0.029130,0.043694,0.014565,0.014565,0.000000,0.014565,0.262167,0.014565,0.000000,0.00000
2,002ba53,0.059430,0.691130,0.233244,0.014120,0.001189,0.000887,0.132971,0.113607,0.266656,0.112359,0.161093,0.213313,0.047637,0.000000,0.079395,0.015879,0.000000,0.000000,0.015879,0.00000,0.000000,0.000000,0.015879,0.079395,0.015879,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.063516,0.000000,0.031758,0.0,0.000000,0.015879,0.000000,0.031758,0.031758,0.000000,0.000000,0.000000,0.063516,0.015879,0.000000,0.015879,0.000000,0.015879,0.000000,0.015879,0.000000,0.031758,0.031758,0.079395,0.000000,0.206427,0.015879,0.000000,0.000000,0.015879,0.095274,0.095274,0.047637,0.015879,0.015879,0.000000,0.031758,0.015879,0.015879,0.000000,0.111153,0.015879,0.079395,0.000000,0.0,0.000000,0.000000,0.015879,0.0,0.000000,0.015879,0.015879,0.000000,0.047637,0.031758,0.238185,0.015879,0.000000,0.031758,0.000000,0.000000,0.015879,0.00000,0.000000,0.063516,0.285822,0.031758,0.238185,0.063516,0.079395,0.047637,0.031758,0.000000,0.127032,0.142911,0.031758,0.047637,0.127032,0.000000,0.00000,0.0,0.000000,0.031758,0.000000,0.031758,0.0,0.015879,0.000000,0.063516,0.031758,0.015879,0.000000,0.031758,0.000000,0.000000,0.000000,0.127032,0.000000,0.000000,0.000000,0.047637,0.015879,0.015879,0.047637,0.000000,0.000000,0.000000,0.000000,0.015879,0.031758,0.031758,0.000000,0.047637,0.000000,0.031758,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.015879,0.0,0.00000,0.015879,0.063516,0.000000,0.015879,0.015879,0.015879,0.000000,0.015879,0.000000,0.619282,0.000000,0.000000,0.079395,0.015879,0.031758,0.047637,0.000000,0.063516,0.0,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.015879,0.000000,0.015879,0.000000,0.00000,0.031758,0.000000,0.000000,0.031758,0.0,0.015879,0.031758,0.015879,0.063516,0.095274,0.031758,0.000000,0.031758,0.000000,0.000000,0.000000,0.000000,0.381096,0.000000,0.031758,0.00000
3,0033037,0.110127,0.875540,0.012530,0.000799,0.000427,0.000577,0.133904,0.109733,0.257915,0.112806,0.166446,0.219196,0.000000,0.000000,0.000000,0.000000,0.000000,0.039073,0.000000,0.00000,0.000000,0.078146,0.156293,0.117220,0.000000,0.0,0.039073,0.000000,0.00000,0.000000,0.000000,0.000000,0.039073,0.039073,0.000000,0.000000,0.000000,0.0,0.039073,0.000000,0.039073,0.000000,0.000000,0.039073,0.078146,0.000000,0.039073,0.000000,0.039073,0.039073,0.039073,0.039073,0.039073,0.000000,0.000000,0.000000,0.000000,0.195366,0.000000,0.000000,0.000000,0.078146,0.000000,0.039073,0.039073,0.000000,0.000000,0.000000,0.000000,0.078146,0.000000,0.039073,0.000000,0.039073,0.039073,0.000000,0.156293,0.000000,0.0,0.078146,0.000000,0.000000,0.0,0.078146,0.000000,0.000000,0.000000,0.000000,0.000000,0.195366,0.000000,0.039073,0.000000,0.000000,0.000000,0.195366,0.00000,0.039073,0.156293,0.039073,0.000000,0.273513,0.078146,0.117220,0.000000,0.000000,0.000000,0.156293,0.078146,0.000000,0.039073,0.000000,0.039073,0.00000,0.0,0.117220,0.039073,0.000000,0.000000,0.0,0.000000,0.000000,0.117220,0.078146,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.039073,0.000000,0.000000,0.000000,0.039073,0.039073,0.000000,0.156293,0.000000,0.039073,0.000000,0.000000,0.078146,0.078146,0.078146,0.000000,0.156293,0.000000,0.0,0.000000,0.078146,0.156293,0.0,0.000000,0.000000,0.000000,0.039073,0.039073,0.0,0.00000,0.156293,0.000000,0.039073,0.000000,0.000000,0.078146,0.156293,0.000000,0.000000,0.468879,0.078146,0.000000,0.039073,0.039073,0.195366,0.000000,0.000000,0.039073,0.0,0.000000,0.000000,0.039073,0.00000,0.00000,0.000000,0.000000,0.234439,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.117220,0.000000,0.000000,0.156293,0.000000,0.000000,0.039073,0.000000,0.000000,0.000000,0.000000,0.195366,0.000000,0.000000,0.00000
4,0033bf4,0.004650,0.469768,0.515730,0.009045,0.000419,0.000389,0.133583,0.111408,0.263863,0.108937,0.168764,0.213444,0.000000,0.019364,0.038727,0.019364,0.000000,0.019364,0.019364,0.00000,0.000000,0.116182,0.000000,0.038727,0.000000,0.0,0.038727,0.000000,0.00000,0.038727,0.019364,0.019364,0.000000,0.019364,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.058091,0.000000,0.000000,0.000000,0.038727,0.038727,0.019364,0.019364,0.019364,0.058091,0.000000,0.058091,0.000000,0.019364,0.000000,0.000000,0.213001,0.000000,0.096819,0.000000,0.019364,0.000000,0.000000,0.019364,0.000000,0.000000,0.019364,0.000000,0.019364,0.000000,0.000000,0.000000,0.116182,0.019364,0.000000,0.019364,0.077455,0.0,0.000000,0.116182,0.077455,0.0,0.000000,0.019364,0.000000,0.019364,0.019364,0.000000,0.019364,0.000000,0.000000,0.000000,0.000000,0.038727,0.000000,0.00000,0.000000,0.038727,0.038727,0.000000,0.135546,0.000000,0.251728,0.000000,0.154910,0.038727,0.135546,0.000000,0.000000,0.116182,0.058091,0.000000,0.00000,0.0,0.000000,0.000000,0.019364,0.000000,0.0,0.000000,0.135546,0.077455,0.058091,0.000000,0.077455,0.000000,0.154910,0.019364,0.000000,0.116182,0.058091,0.019364,0.096819,0.000000,0.096819,0.000000,0.000000,0.038727,0.038727,0.038727,0.077455,0.019364,0.000000,0.000000,0.038727,0.019364,0.077455,0.077455,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.116182,0.019364,0.0,0.00000,0.058091,0.000000,0.000000,0.000000,0.058091,0.000000,0.000000,0.000000,0.077455,0.426002,0.058091,0.154910,0.038727,0.000000,0.077455,0.116182,0.019364,0.058091,0.0,0.000000,0.038727,0.000000,0.00000,0.00000,0.019364,0.000000,0.174273,0.019364,0.000000,0.00000,0.019364,0.077455,0.000000,0.019364,0.0,0.213001,0.077455,0.019364,0.038727,0.445365,0.000000,0.019364,0.019364,0.000000,0.019364,0.019364,0.000000,0.096819,0.193637,0.000000,0.00000

In [20]:
# set file paths for either laptop or desktop

if laptop:

    file_config = {

        'vectorizer': '/home/laptop/github/kaggle/scoring/model_data/sklearn/vectorizer.pkl',
        'lda_model': '/home/laptop/github/kaggle/scoring/model_data/sklearn/lda_model.pkl',
        'tf_vectorizer': '/home/laptop/github/kaggle/scoring/model_data/sklearn/tf_vectorizer.pkl',
        'feature_cols': '/home/laptop/github/kaggle/scoring/model_data/sklearn/feature_cols.txt',
        'scaler': '/home/laptop/github/kaggle/scoring/model_data/sklearn/scaler.pkl',   
        'top_corelations': '/home/laptop/github/kaggle/scoring/model_data/sklearn/top_corelations.txt',
        'sklearn_model': '/home/laptop/github/kaggle/scoring/model_data/sklearn/sklearn_model.joblib'}
    
if not laptop:

    file_config = {
        'vectorizer': '/home/jack/github/kaggle/scoring/model_data/sklearn/vectorizer.pkl',
        'lda_model': '/home/jack/github/kaggle/scoring/model_data/sklearn/lda_model.pkl',
        'tf_vectorizer': '/home/jack/github/kaggle/scoring/model_data/sklearn/tf_vectorizer.pkl',
        'feature_cols': '/home/jack/github/kaggle/scoring/model_data/sklearn/feature_cols.txt',
        'scaler': '/home/jack/github/kaggle/scoring/model_data/sklearn/scaler.pkl',   
        'top_corelations': '/home/jack/github/kaggle/scoring/model_data/sklearn/top_corelations.txt',
        'sklearn_model': '/home/jack/github/kaggle/scoring/model_data/sklearn/sklearn_model.joblib'}

In [13]:
if laptop:
    csv_path = '/home/laptop/github/kaggle/scoring/data/train.csv'

if not laptop:
    csv_path = '/home/jack/github/kaggle/scoring/data/train.csv'

In [10]:
train = pd.read_csv(csv_path)

In [11]:
train = clean_text(train)

train.head()

Starting text cleaning process.

Adding Text Features.................

Complete.................

,essay_id,full_text,score,lowered,clean_text,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score
0,000d118,Many people have car where they live. The thin...,3,many people have car where they live. the thin...,many people have car where they live the thing...,1,13,498,498.000000,498,498,38.307692,127,7,4.369478,25,1,57.98,17.33,0.9937
1,000fe60,I am a scientist at NASA that is discussing th...,3,i am a scientist at nasa that is discussing th...,i am a scientist at nasa that is discussing th...,5,21,332,66.400000,98,37,15.809524,48,2,4.018072,11,1,87.55,7.48,0.7705
2,001ab80,People always wish they had the same technolog...,4,people always wish they had the same technolog...,people always wish they had the same technolog...,4,24,550,137.500000,199,85,22.916667,46,9,4.574545,15,1,65.15,11.49,-0.9731
3,001bdc0,"We all heard about Venus, the planet without a...",4,"we all heard about venus, the planet without a...",we all heard about venus the planet without al...,5,20,451,90.200000,165,25,22.550000,38,5,4.982262,20,1,58.32,11.91,0.9702
4,002ba53,"Dear, State Senator\n\nThis is a letter to arg...",3,"dear, state senator\n\nthis is a letter to arg...",dear state senator this is a letter to argue i...,6,15,373,62.166667,118,2,24.933333,76,2,4.873995,14,1,54.66,12.64,0.9771

In [14]:
print(deberta_full.shape, train.shape)

(17307, 213) (17307, 20)

In [15]:
# Combine train and deberta_full on essay_id

train = train.merge(deberta_full, on='essay_id')

In [16]:
train.head()

,essay_id,full_text,score,lowered,clean_text,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199
0,000d118,Many people have car where they live. The thin...,3,many people have car where they live. the thin...,many people have car where they live the thing...,1,13,498,498.000000,498,498,38.307692,127,7,4.369478,25,1,57.98,17.33,0.9937,0.156896,0.756281,0.079829,0.005163,0.000922,0.000909,0.116983,0.173203,0.157604,0.287849,0.154709,0.109652,0.031439,0.00000,0.047158,0.031439,0.015719,0.015719,0.220070,0.015719,0.031439,0.047158,0.000000,0.078597,0.015719,0.0,0.031439,0.000000,0.000000,0.031439,0.015719,0.000000,0.078597,0.000000,0.015719,0.015719,0.000000,0.00000,0.000000,0.031439,0.015719,0.204351,0.000000,0.015719,0.015719,0.015719,0.062877,0.000000,0.00000,0.094316,0.062877,0.015719,0.078597,0.047158,0.015719,0.000000,0.000000,0.204351,0.047158,0.062877,0.031439,0.031439,0.000000,0.015719,0.078597,0.015719,0.015719,0.015719,0.000000,0.078597,0.000000,0.047158,0.031439,0.047158,0.062877,0.000000,0.000000,0.015719,0.031439,0.0,0.015719,0.015719,0.062877,0.00000,0.047158,0.015719,0.000000,0.047158,0.015719,0.125754,0.000000,0.000000,0.015719,0.015719,0.015719,0.015719,0.078597,0.047158,0.047158,0.015719,0.015719,0.251509,0.000000,0.314386,0.000000,0.141474,0.0,0.345825,0.015719,0.015719,0.015719,0.031439,0.031439,0.00000,0.0,0.015719,0.000000,0.0,0.000000,0.000000,0.000000,0.031439,0.172912,0.125754,0.015719,0.000000,0.000000,0.000000,0.0,0.000000,0.062877,0.031439,0.015719,0.062877,0.110035,0.000000,0.031439,0.000000,0.047158,0.000000,0.000000,0.157193,0.015719,0.078597,0.031439,0.015719,0.000000,0.031439,0.157193,0.047158,0.015719,0.047158,0.078597,0.000000,0.000000,0.000000,0.015719,0.062877,0.000000,0.000000,0.00000,0.000000,0.000000,0.031439,0.062877,0.015719,0.015719,0.000000,0.015719,0.015719,0.330105,0.015719,0.015719,0.031439,0.000000,0.062877,0.015719,0.015719,0.062877,0.0,0.015719,0.000000,0.031439,0.031439,0.015719,0.00000,0.031439,0.000000,0.015719,0.015719,0.047158,0.031439,0.00000,0.047158,0.094316,0.0,0.094316,0.015719,0.031439,0.141474,0.204351,0.000000,0.00000,0.094316,0.015719,0.031439,0.015719,0.015719,0.267228,0.031439,0.000000,0.015719
1,000fe60,I am a scientist at NASA that is discussing th...,3,i am a scientist at nasa that is discussing th...,i am a scientist at nasa that is discussing th...,5,21,332,66.400000,98,37,15.809524,48,2,4.018072,11,1,87.55,7.48,0.7705,0.015906,0.832160,0.148738,0.002510,0.000311,0.000375,0.136665,0.115104,0.258191,0.112356,0.164195,0.213489,0.071429,0.02381,0.023810,0.000000,0.000000,0.119048,0.000000,0.023810,0.000000,0.047619,0.023810,0.023810,0.023810,0.0,0.119048,0.023810,0.023810,0.000000,0.119048,0.023810,0.000000,0.000000,0.000000,0.023810,0.000000,0.00000,0.000000,0.023810,0.000000,0.047619,0.000000,0.000000,0.047619,0.071429,0.047619,0.071429,0.00000,0.142857,0.000000,0.000000,0.190476,0.000000,0.000000,0.023810,0.000000,0.190476,0.047619,0.000000,0.000000,0.000000,0.000000,0.095238,0.000000,0.000000,0.000000,0.095238,0.071429,0.047619,0.000000,0.023810,0.023810,0.119048,0.047619,0.000000,0.000000,0.000000,0.000000,0.0,0.023810,0.023810,0.000000,0.00000,0.000000,0.023810,0.023810,0.071429,0.047619,0.285714,0.000000,0.000000,0.000000,0.047619,0.000000,0.000000,0.000000,0.023810,0.119048,0.047619,0.023810,0.023810,0.071429,0.214286,0.023810,0.095238,0.0,0.261905,0.000000,0.047619,0.023810,0.071429,0.000000,0.02381,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.023810,0.071429,0.285714,0.023810,0.000000,0.000000,0.071429,0.0,0.000000,0.190476,0.023810,0.000000,0.023810,0.000000,0.023810,0.238095,0.000000,0.047619,0.000000,0.000000,0.000000,0.000000,0.071429,0.000000,0.000000,0.000000,0.000000,0.142857,0.000000,0.000000,0.023810,0.071429,0.000000,0.023810,0.047619,0.000000,0.095238,0.000000,0.000000,0.02381,0.000000,0.000000,0.000000,0.047619,0.190476,0.023810,0.142857,0.000000,0.071429,0.214286,0.023810,0.047619,0.000000,0.000000,0.023810,0.000000,0.000000,0.047619,0.0,0.000000,0.047619,0.000000,0.023810,0.000000,0.00000,0.000000,0.071429,0.000000,0.000000,0.023810,0.000000,0.00000,0.071429,0.142857,0.0,0.047619,0.023810,0.047619,0.047619,0.285714,0.095238,0.00000,0.119048,0.000000,0.000000,0.000000,0.023810,0.190476,0.071429,0.000000,0.023810
2,001ab80,People always wish they had the same technolog...,4,people always wish they had the same technolog...,people always wish they had the same technolog...,4,24,550,137.500000,199,85,22.916667,46,9,4.574545,15,1,65.15,11.49,-0.9731,0.001099,0.010704,0.344778,0.631197,0.011407,0.000815,0.132327,0.110495,0.258206,0.115311,0.163469,0.220192,0.014565,0.00000,0.058259,0.000000,0.014565,0.058259,0.189343,0.000000,0.014565,0.029130,0.014565,0.058259,0.000000,0.0,0.029130,0.014565,0.000000,0.014565,0.000000,0.014565,0.000000,0.000000,0.000000,0.014565,0.014565,0.00000,0.000000,0.029130,0.000000,0.160213,0.014565,0.029130,0.000000,0.029130,0.058259,0.043694,0.00000,0.145648,0.014565,0.029130,0.087389,0.029130,0.116519,0.000000,0.014565,0.116519,0.029130,0.000000,0.014565,0.043694,0.014565,0.014565,0.043694,0.029130,0.000000,0.043694,0.000000,0.014565,0.000000,0.000000,0.029130,0.131083,0.058259,0.014565,0.014565,0.000000,0.000000,0.0,0.014565,0.000000,0.000000,0.00000,0.014565,0.029130,0.014565,0.072824,0.058259,0.145648,0.043694,0.029130,0.145648,0.000000,0.029130,0.000000,0.029130,0.029130,0.160213,0.029130,0.000000,0.131083,0.043694,0.305861,0.087389,0.087389,0.0,0.189343,0.000000,0.014565,0.145648,0.014565,0.014565,0.00000,0.0,0.145648,0.000000,0.0,0.000000,0.000000,0.043694,0.000000,0.087389,0.160213,0.000000,0.014565,0.000000,0.029130,0.0,0.014565,0.072824,0.029130,0.000000,0.029130,0.000000,0.014565,0.043694,0.014565,0.072824,0.029130,0.014565,0.000000,0.014565,0.087389,0.000000,0.101954,0.145648,0.116519,0.116519,0.000000,0.014565,0.000000,0.000000,0.000000,0.014565,0.014565,0.014565,0.160213,0.014565,0.000000,0.00000,0.029130,0.000000,0.014565,0.087389,0.043694,0.000000,0.014565,0.043694,0.029130,0.407815,0.029130,0.000000,0.058259,0.014565,0.072824,0.000000,0.043694,0.029130,0.0,0.014565,0.058259,0.000000,0.000000,0.029130,0.00000,0.000000,0.000000,0.087389,0.014565,0.000000,0.000000,0.02913,0.029130,0.189343,0.0,0.101954,0.043694,0.087389,0.087389,0.189343,0.116519,0.02913,0.043694,0.014565,0.014565,0.000000,0.014565,0.262167,0.014565,0.000000,0.000000
3,001bdc0,"We all heard about Venus, the planet without a...",4,"we all heard about venus, the planet without a...",we all heard about venus the planet without al...,5,20,451,90.200000,165,25,22.550000,38,5,4.982262,20,1,58.32,11.91,0.9702,0.009681,0.273882,0.657448,0.056872,0.001404,0.000713,0.118487,0.169333,0.149879,0.299778,0.153946,0.108576,0.000000,0.00000,0.000000,0.000000,0.000000,0.017090,0.000000,0.000000,0.017090,0.034179,0.000000,0.187986,0.000000,0.0,0.051269,0.000000,0.034179,0.034179,0.034179,0.017090,0.051269,0.034179,0.017090,0.017090,0.034179,0.01709,0.051269,0.017090,0.017090,0.051269,0.000000,0.034179,0.085448,0.051269,0.068359,0.000000,0.01709,0.034179,0.017090,0.017090,0.068359,0.000000,0.000000,0.000000,0.017090,0.222165,0.034179,0.017090,0.017090,0.034179,0.000000,0.034179,0.017090,0.000000,0.034179,0.119628,0.068359,0.085448,0.034179,0.017090,0.017090,0.017090,0.205076,0.017090,0.000000,0.017090,0.068359,0.0,0.017090,0.000000,0.051269,0.01709,0.034179,0.017090,0.000000,0.068359,0.102538,0.136717,0.000000,0.034179,0.051269,0.000000,0.068359,0.000000,0.000000,0.034179,0.290524,0.051269,0.034179,0.068359,0.068359,0.273434,0.000000,0.051269,0.0,0.187986,0.085448,0.000000,0.034179,0.068359,0.000000,0.00000,0.0,0.034179,0.017090,0.0,0.000000,0.051269,0.000000,0.000000,0.068359,0.068359,0.017090,0.000000,0.017090,0.153807,0.0,0.000000,0.068359,0.000000,0.000000,0.017090,0.051269,0.000000,0.000000,0.068359,0.000000,0.068359,0.017090,0.000000,0.000000,0.017090,0.034179,0.034179,0.017090,0.017090,0.034179,0.000000,0.017090,0.153807,0.000000,0.034179,0.068359,0.034179,0.000000,0.000000,0.034179,0.051269,0.01709,0.017090,0.017090,0.000000,0.000000,0.051269,0.017090,0.017090,0.017090,0.051269,0.529779,0.017090,0.017090,0.051269,0.017090,0.034179,0.000000,0.000000,0.034179,0.0,0.000000,0.017090,0.000000,0.034179,0.000000,0.01709,0.000000,0.102538,0.000000,0.017090,0.017090,0.000000,0.00000,0.034179,0.102538,0.0,0.085448,0.034179,0.000000,0.051269,0.085448,0.017090,0.00000,0.119628,0.017090,0.017090,0.034179,0.000000,0.256345,0.068359,0.051269,0.000000
4,002ba53,"Dear, State Senator\n\nThis is a letter to arg...",3,"dear, state senator\n\nthis is a letter to arg...",dear state senator this is a letter to argue i...,6,15,373,62.166667,118,2,24.933333,76,2,4.873995,14,1,54.66,12.64,0.9771,0.059430,0.691130,0.233244,0.014120,0.001189,0.000887,0.132971,0.113607,0.266656,0.112359,0.161093,0.213313,0.047637,0.00000,0.079395,0.015879,0.000000,0.000000,0.015879,0.000000,0.000000,0.000000,0.015879,0.079395,0.015879,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.063516,0.000000,0.031758,0.00000,0.000000,0.015879,0.000000,0.031758,0.031758,0.000000,0.000000,0.000000,0.063516,0.015879,0.00000,0.015879,0.000000,0.015879,0.000000,0.015879,0.000000,0.031758,0.031758,0.079395,0.000000,0.206427,0.015879,0.000000,0.000000,0.015879,0.095274,0.095274,0.047637,0.015879,0.015879,0.000000,0.031758,0.015879,0.015879,0.000000,0.111153,0.015879,0.079395,0.000000,0.000000,0.0,0.000000,0.015879,0.000000,0.00000,0.015879,0.015879,0.000000,0.047637,0.031758,0.238185,0.015879,0.000000,0.031758,0.000000,0.000000,0.015879,0.000000,0.000000,0.063516,0.285822,0.031758,0.238185,0.063516,0.079395,0.047637,0.031758,0.0,0.127032,0.142911,0.031758,0.047637,0.127032,0.000000,0.00000,0.0,0.000000,0.031758,0.0,0.031758,0.000000,0.015879,0.000000,0.063516,0.031758,0.015879,0.000000,0.031758,0.000000,0.0,0.000000,0.127032,0.000000,0.000000,0.000000,0.047637,0.015879,0.015879,0.047637,0.000000,0.000000,0.000000,0.000000,0.015879,0.031758,0.031758,0.000000,0.047637,0.000000,0.031758,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.015879,0.000000,0.00000,0.015879,0.063516,0.000000,0.015879,0.015879,0.015879,0.000000,0.015879,0.000000,0.619282,0.000000,0.000000,0.079395,0.015879,0.031758,0.047637,0.000000,0.063516,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.015879,0.000000,0.015879,0.000000,0.000000,0.031758,0.00000,0.000000,0.031758,0.0,0.015879,0.031758,0.015879,0.063516,0.095274,0.031758,0.00000,0.031758,0.000000,0.000000,0.000000,0.000000,0.381096,0.000000,0.031758,0.000000

In [17]:
df = train.copy()

In [ ]:
# from sklearn.feature_extraction.text import CountVectorizer
# import pandas as pd
# import dill
# import spacy

# # Initialize a CountVectorizer with n-gram range from 1 to 3 (unigrams to trigrams)
# vectorizer = CountVectorizer(ngram_range=(1, 3), max_features=1000, stop_words='english')

# # Initialize and fit the vectorizer
# X_ngrams = vectorizer.fit_transform(df['full_text'])
# df_ngrams = pd.DataFrame(X_ngrams.toarray(), columns=vectorizer.get_feature_names_out())

# # Save the vectorizer
# with open('/home/laptop/github/kaggle/scoring/model_data/sklearn/vectorizer.pkl', 'wb') as f:
#     dill.dump(vectorizer, f)

# # Load the spaCy model
# nlp = spacy.load("en_core_web_sm")

# # Function to count POS tags
# def pos_counts(text):
#     doc = nlp(text)
#     total_tokens = len(doc)
#     pos_counts = doc.count_by(spacy.attrs.POS)
#     return {f'pos_{doc.vocab.strings[pos_id]}': count / total_tokens for pos_id, count in pos_counts.items() if total_tokens > 0}

# # Function to count Named Entities
# def named_entities(text):
#     doc = nlp(text)
#     total_tokens = len(doc)
#     entities = {}
#     for ent in doc.ents:
#         entities[ent.label_] = entities.get(ent.label_, 0) + 1
#     return {f'ner_{label}': count / total_tokens for label, count in entities.items() if total_tokens > 0}

# # Function to count Dependency Tags
# def dependency_tags(text):
#     doc = nlp(text)
#     total_tokens = len(doc)
#     dep_counts = doc.count_by(spacy.attrs.DEP)
#     return {f'dep_{doc.vocab.strings[dep_id]}': count / total_tokens for dep_id, count in dep_counts.items() if total_tokens > 0}

# # Define all possible columns
# all_pos_cols = [f'pos_{pos}' for pos in nlp.get_pipe("tagger").labels]
# all_ent_cols = [f'ner_{ent}' for ent in nlp.get_pipe("ner").labels]
# all_dep_cols = [f'dep_{dep}' for dep in nlp.get_pipe("parser").labels]

# # Extract POS tags, named entities, and dependency tags
# df_pos = df['full_text'].apply(pos_counts).apply(pd.Series).fillna(0)
# df_entities = df['full_text'].apply(named_entities).apply(pd.Series).fillna(0)
# df_deps = df['full_text'].apply(dependency_tags).apply(pd.Series).fillna(0)

# # Ensure all POS, NER, and Dependency columns are present
# for col_list, df_features in [(all_pos_cols, df_pos), (all_ent_cols, df_entities), (all_dep_cols, df_deps)]:
#     for col in col_list:
#         if col not in df_features.columns:
#             df_features[col] = 0

# # Sort columns for consistency
# df_pos = df_pos[sorted(df_pos.columns)]
# df_entities = df_entities[sorted(df_entities.columns)]
# df_deps = df_deps[sorted(df_deps.columns)]

# # Concatenate all feature DataFrames with the original DataFrame
# df = pd.concat([df.reset_index(drop=True), df_ngrams.reset_index(drop=True), 
#                          df_pos.reset_index(drop=True), df_entities.reset_index(drop=True), 
#                          df_deps.reset_index(drop=True)], axis=1)

In [ ]:
# import pandas as pd
# import dill
# import spacy
# import re
# from collections import Counter
# from sklearn.decomposition import LatentDirichletAllocation
# from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
# from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
# from sentence_transformers import SentenceTransformer
# from nltk.corpus import stopwords
# from spellchecker import SpellChecker
# import textstat

# # Load spaCy model
# nlp = spacy.load("en_core_web_sm")
# stop_words = set(stopwords.words('english'))
# sentiment_analyzer = SentimentIntensityAnalyzer()
# spell = SpellChecker()
# bert_model = SentenceTransformer('all-MiniLM-L6-v2')

# text_col = 'clean_text'

# # Define feature extraction functions
# def pos_counts(text):
#     doc = nlp(text)
#     pos_counts = doc.count_by(spacy.attrs.POS)
#     return {f'pos_{doc.vocab.strings[pos_id]}': count for pos_id, count in pos_counts.items()}

# def named_entities(text):
#     doc = nlp(text)
#     entities = {ent.label_: ent for ent in doc.ents}
#     return {f'ner_{label}': count for label, count in entities.items()}

# def dependency_tags(text):
#     doc = nlp(text)
#     dep_counts = doc.count_by(spacy.attrs.DEP)
#     return {f'dep_{doc.vocab.strings[dep_id]}': count for dep_id, count in dep_counts.items()}

# def compute_linguistic_features(text):
#     doc = nlp(text)
#     tenses = [token.tag_ for token in doc if token.pos_ == "VERB"]
#     tense_counts = Counter(tenses)
#     most_common_tense = tense_counts.most_common(1)[0][0] if tense_counts else None
#     verb_tense_consistency = tense_counts[most_common_tense] / len(tenses) if tenses else 0
#     passive_count = sum(1 for token in doc if token.dep_ == "nsubjpass")
#     passive_voice_usage = passive_count / len([token for token in doc if token.pos_ == "VERB"]) if doc else 0
#     modal_verbs = {"can", "could", "will", "would", "shall", "should", "may", "might", "must"}
#     modal_count = sum(1 for token in doc if token.lemma_ in modal_verbs)
#     modal_verb_usage = modal_count / len(doc) if doc else 0
#     lexical_diversity = len(set(doc)) / len(doc) if doc else 0
#     dale_chall_readability = textstat.dale_chall_readability_score(text)
#     automated_readability_index = textstat.automated_readability_index(text)
#     coleman_liau_index = textstat.coleman_liau_index(text)
#     conjunction_count = sum(1 for token in doc if token.pos_ in {"CCONJ", "SCONJ"})
#     clause_count = sum(1 for token in doc if token.dep_ in {"csubj", "advcl", "ccomp", "xcomp"})
#     clause_density = clause_count / max(len([token for token in doc if token.dep_ in {"ROOT", "nsubj"}]), 1)
#     return {
#         "verb_tense_consistency": verb_tense_consistency,
#         "passive_voice_usage": passive_voice_usage,
#         "modal_verb_usage": modal_verb_usage,
#         "lexical_diversity": lexical_diversity,
#         "dale_chall_readability": dale_chall_readability,
#         "automated_readability_index": automated_readability_index,
#         "coleman_liau_index": coleman_liau_index,
#         "conjunction_usage": conjunction_count,
#         "clause_density": clause_density
#     }

# def compute_sentiment_features(text):
#     sentiment_scores = sentiment_analyzer.polarity_scores(text)
#     return {
#         "vader_compound": sentiment_scores["compound"],
#         "vader_positive": sentiment_scores["pos"],
#         "vader_negative": sentiment_scores["neg"],
#         "vader_neutral": sentiment_scores["neu"]
#     }

# def extract_bert_embedding(text):
#     embedding = bert_model.encode([text])[0]
#     return {f'bert_dim_{i}': value for i, value in enumerate(embedding)}

# def extract_topic_features(text, lda_model, vectorizer):
#     text_vector = vectorizer.transform([text])
#     topic_distribution = lda_model.transform(text_vector)[0]
#     return {f'topic_{i}': prob for i, prob in enumerate(topic_distribution)}

# def extract_spelling_grammar_errors(text):
#     misspelled = spell.unknown(text.split())
#     return {
#         "spelling_errors": len(misspelled),
#         "grammar_errors": sum(1 for token in nlp(text) if token.dep_ == "pcomp")
#     }

# def compute_advanced_readability_scores(text):
#     return {
#         "linsear_write_formula": textstat.linsear_write_formula(text),
#         "ari_score": textstat.automated_readability_index(text),
#     }

# def apply_feature_extraction(df, lda_model, vectorizer):
#     df_pos = df[text_col].apply(pos_counts).apply(pd.Series).fillna(0)
#     df_entities = df[text_col].apply(named_entities).apply(pd.Series).fillna(0)
#     df_deps = df[text_col].apply(dependency_tags).apply(pd.Series).fillna(0)
#     df_linguistic = df[text_col].apply(compute_linguistic_features).apply(pd.Series)
#     df_sentiment = df[text_col].apply(compute_sentiment_features).apply(pd.Series)
#     df_bert = df[text_col].apply(extract_bert_embedding).apply(pd.Series)
#     df_topics = df[text_col].apply(lambda x: extract_topic_features(x, lda_model, vectorizer)).apply(pd.Series)
#     df_spelling_grammar = df[text_col].apply(extract_spelling_grammar_errors).apply(pd.Series)
#     df_readability = df[text_col].apply(compute_advanced_readability_scores).apply(pd.Series)
#     return pd.concat([df.reset_index(drop=True), df_pos.reset_index(drop=True), 
#                       df_entities.reset_index(drop=True), df_deps.reset_index(drop=True), 
#                       df_linguistic.reset_index(drop=True), df_sentiment.reset_index(drop=True),
#                       df_bert.reset_index(drop=True), df_topics.reset_index(drop=True),
#                       df_spelling_grammar.reset_index(drop=True),
#                       df_readability.reset_index(drop=True)], axis=1)

# # Train LDA topic model
# tf_vectorizer = TfidfVectorizer(max_features=200, stop_words='english')
# tf = tf_vectorizer.fit_transform(df[text_col])
# lda_model = LatentDirichletAllocation(n_components=10, random_state=42)
# lda_model.fit(tf)

# # Apply feature extraction
# df_train_features = apply_feature_extraction(df, lda_model, tf_vectorizer)

# # Save the LDA model and vectorizers
# with open('/home/jack/github/kaggle/scoring/model_data/sklearn/lda_model.pkl', 'wb') as f:
#     dill.dump(lda_model, f)
# with open('/home/jack/github/kaggle/scoring/model_data/sklearn/vectorizer.pkl', 'wb') as f:
#     dill.dump(vectorizer, f)
# with open('/home/jack/github/kaggle/scoring/model_data/sklearn/tf_vectorizer.pkl', 'wb') as f:
#     dill.dump(tf_vectorizer, f)

# # Initialize and fit the CountVectorizer for n-grams
# X_ngrams_train = vectorizer.fit_transform(df[text_col])
# df_ngrams_train = pd.DataFrame(X_ngrams_train.toarray(), columns=vectorizer.get_feature_names_out())

# # Combine all features
# df_train_combined = pd.concat([df_train_features.reset_index(drop=True), df_ngrams_train.reset_index(drop=True)], axis=1)
# df = df_train_combined.copy()

In [19]:
import pandas as pd
import dill
import spacy
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sentence_transformers import SentenceTransformer
from nltk.corpus import stopwords
from spellchecker import SpellChecker
import textstat
from collections import Counter

# Load spaCy model
nlp = spacy.load("en_core_web_sm")
stop_words = set(stopwords.words('english'))
sentiment_analyzer = SentimentIntensityAnalyzer()
spell = SpellChecker()
bert_model = SentenceTransformer('all-MiniLM-L6-v2')

text_col = 'full_text'

# Initialize a CountVectorizer with n-gram range from 1 to 3 (unigrams to trigrams)
vectorizer = CountVectorizer(ngram_range=(1, 3), max_features=1000, stop_words='english')

# Initialize and fit the vectorizer
X_ngrams_train = vectorizer.fit_transform(df[text_col])
df_ngrams_train = pd.DataFrame(X_ngrams_train.toarray(), columns=vectorizer.get_feature_names_out())

# Save the vectorizer
with open(file_config['vectorizer'], 'wb') as f:
    dill.dump(vectorizer, f)

# Train LDA topic model
tf_vectorizer = TfidfVectorizer(max_features=200, stop_words='english')
tf = tf_vectorizer.fit_transform(df[text_col])
lda_model = LatentDirichletAllocation(n_components=10, random_state=42)
lda_model.fit(tf)

# Save the LDA model and vectorizers
with open(file_config['lda_model'], 'wb') as f:
    dill.dump(lda_model, f)
    
with open(file_config['tf_vectorizer'], 'wb') as f:
    dill.dump(tf_vectorizer, f)

# Define feature extraction functions
def pos_counts(text):
    doc = nlp(text)
    total_tokens = len(doc)
    pos_counts = doc.count_by(spacy.attrs.POS)
    pos_features = {f'pos_{doc.vocab.strings[pos_id]}_count': count for pos_id, count in pos_counts.items()}
    pos_ratios = {f'pos_{doc.vocab.strings[pos_id]}_ratio': count / total_tokens for pos_id, count in pos_counts.items() if total_tokens > 0}
    return {**pos_features, **pos_ratios}

def named_entities(text):
    doc = nlp(text)
    total_tokens = len(doc)
    entities = {}
    for ent in doc.ents:
        entities[ent.label_] = entities.get(ent.label_, 0) + 1
    entity_features = {f'ner_{label}_count': count for label, count in entities.items()}
    entity_ratios = {f'ner_{label}_ratio': count / total_tokens for label, count in entities.items() if total_tokens > 0}
    return {**entity_features, **entity_ratios}

def dependency_tags(text):
    doc = nlp(text)
    total_tokens = len(doc)
    dep_counts = doc.count_by(spacy.attrs.DEP)
    dep_features = {f'dep_{doc.vocab.strings[dep_id]}_count': count for dep_id, count in dep_counts.items()}
    dep_ratios = {f'dep_{doc.vocab.strings[dep_id]}_ratio': count / total_tokens for dep_id, count in dep_counts.items() if total_tokens > 0}
    return {**dep_features, **dep_ratios}

def compute_linguistic_features(text):
    doc = nlp(text)
    tenses = [token.tag_ for token in doc if token.pos_ == "VERB"]
    tense_counts = Counter(tenses)
    most_common_tense = tense_counts.most_common(1)[0][0] if tense_counts else None
    verb_tense_consistency = tense_counts[most_common_tense] / len(tenses) if tenses else 0
    passive_count = sum(1 for token in doc if token.dep_ == "nsubjpass")
    passive_voice_usage = passive_count / len([token for token in doc if token.pos_ == "VERB"]) if doc else 0
    modal_verbs = {"can", "could", "will", "would", "shall", "should", "may", "might", "must"}
    modal_count = sum(1 for token in doc if token.lemma_ in modal_verbs)
    modal_verb_usage = modal_count / len(doc) if doc else 0
    lexical_diversity = len(set(doc)) / len(doc) if doc else 0
    dale_chall_readability = textstat.dale_chall_readability_score(text)
    automated_readability_index = textstat.automated_readability_index(text)
    coleman_liau_index = textstat.coleman_liau_index(text)
    conjunction_count = sum(1 for token in doc if token.pos_ in {"CCONJ", "SCONJ"})
    clause_count = sum(1 for token in doc if token.dep_ in {"csubj", "advcl", "ccomp", "xcomp"})
    clause_density = clause_count / max(len([token for token in doc if token.dep_ in {"ROOT", "nsubj"}]), 1)
    return {
        "verb_tense_consistency": verb_tense_consistency,
        "passive_voice_usage": passive_voice_usage,
        "modal_verb_usage": modal_verb_usage,
        "lexical_diversity": lexical_diversity,
        "dale_chall_readability": dale_chall_readability,
        "automated_readability_index": automated_readability_index,
        "coleman_liau_index": coleman_liau_index,
        "conjunction_usage": conjunction_count,
        "clause_density": clause_density
    }

def compute_sentiment_features(text):
    sentiment_scores = sentiment_analyzer.polarity_scores(text)
    return {
        "vader_compound": sentiment_scores["compound"],
        "vader_positive": sentiment_scores["pos"],
        "vader_negative": sentiment_scores["neg"],
        "vader_neutral": sentiment_scores["neu"]
    }

def extract_bert_embedding(text):
    embedding = bert_model.encode([text])[0]
    return {f'bert_dim_{i}': value for i, value in enumerate(embedding)}

def extract_topic_features(text, lda_model, vectorizer):
    text_vector = vectorizer.transform([text])
    topic_distribution = lda_model.transform(text_vector)[0]
    return {f'topic_{i}': prob for i, prob in enumerate(topic_distribution)}

def extract_spelling_grammar_errors(text):
    misspelled = spell.unknown(text.split())
    return {
        "spelling_errors": len(misspelled),
        "grammar_errors": sum(1 for token in nlp(text) if token.dep_ == "pcomp")
    }

def compute_advanced_readability_scores(text):
    return {
        "linsear_write_formula": textstat.linsear_write_formula(text),
        "ari_score": textstat.automated_readability_index(text),
    }

def apply_feature_extraction(df, lda_model, vectorizer):
    df_pos = df[text_col].apply(pos_counts).apply(pd.Series).fillna(0)
    df_entities = df[text_col].apply(named_entities).apply(pd.Series).fillna(0)
    df_deps = df[text_col].apply(dependency_tags).apply(pd.Series).fillna(0)
    df_linguistic = df[text_col].apply(compute_linguistic_features).apply(pd.Series)
    df_sentiment = df[text_col].apply(compute_sentiment_features).apply(pd.Series)
    df_bert = df[text_col].apply(extract_bert_embedding).apply(pd.Series)
    df_topics = df[text_col].apply(lambda x: extract_topic_features(x, lda_model, vectorizer)).apply(pd.Series)
    df_spelling_grammar = df[text_col].apply(extract_spelling_grammar_errors).apply(pd.Series)
    df_readability = df[text_col].apply(compute_advanced_readability_scores).apply(pd.Series)
    return pd.concat([df.reset_index(drop=True), df_pos.reset_index(drop=True), 
                      df_entities.reset_index(drop=True), df_deps.reset_index(drop=True), 
                      df_linguistic.reset_index(drop=True), df_sentiment.reset_index(drop=True),
                      df_bert.reset_index(drop=True), df_topics.reset_index(drop=True),
                      df_spelling_grammar.reset_index(drop=True),
                      df_readability.reset_index(drop=True)], axis=1)

# Apply feature extraction
df_train_features = apply_feature_extraction(df, lda_model, tf_vectorizer)

# Combine all features
df_train_combined = pd.concat([df_train_features.reset_index(drop=True), df_ngrams_train.reset_index(drop=True)], axis=1)

df = df_train_combined.copy()

In [21]:
df.head()

,essay_id,full_text,score,lowered,clean_text,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,pos_ADJ_count,pos_NOUN_count,pos_VERB_count,pos_SCONJ_count,pos_PRON_count,pos_PUNCT_count,pos_DET_count,pos_AUX_count,pos_PART_count,pos_ADP_count,pos_SPACE_count,pos_CCONJ_count,pos_PROPN_count,pos_NUM_count,pos_ADV_count,pos_SYM_count,pos_ADJ_ratio,pos_NOUN_ratio,pos_VERB_ratio,pos_SCONJ_ratio,pos_PRON_ratio,pos_PUNCT_ratio,pos_DET_ratio,pos_AUX_ratio,pos_PART_ratio,pos_ADP_ratio,pos_SPACE_ratio,pos_CCONJ_ratio,pos_PROPN_ratio,pos_NUM_ratio,pos_ADV_ratio,pos_SYM_ratio,pos_INTJ_count,pos_INTJ_ratio,pos_X_count,pos_X_ratio,ner_GPE_count,ner_PERCENT_count,ner_NORP_count,ner_ORG_count,ner_CARDINAL_count,ner_MONEY_count,ner_DATE_count,ner_LOC_count,ner_PERSON_count,ner_QUANTITY_count,ner_EVENT_count,ner_GPE_ratio,ner_PERCENT_ratio,ner_NORP_ratio,ner_ORG_ratio,ner_CARDINAL_ratio,ner_MONEY_ratio,ner_DATE_ratio,ner_LOC_ratio,ner_PERSON_ratio,ner_QUANTITY_ratio,ner_EVENT_ratio,ner_ORDINAL_count,ner_ORDINAL_ratio,ner_WORK_OF_ART_count,ner_WORK_OF_ART_ratio,ner_LAW_count,ner_LAW_ratio,ner_PRODUCT_count,ner_PRODUCT_ratio,ner_TIME_count,ner_TIME_ratio,ner_FAC_count,ner_FAC_ratio,ner_LANGUAGE_count,ner_LANGUAGE_ratio,dep_amod_count,dep_nsubj_count,dep_ROOT_count,dep_dobj_count,dep_advmod_count,dep_relcl_count,dep_punct_count,dep_det_count,dep_aux_count,dep_neg_count,dep_mark_count,dep_csubj_count,dep_compound_count,dep_prep_count,dep_pobj_count,dep_ccomp_count,dep_dep_count,dep_advcl_count,dep_cc_count,dep_acomp_count,dep_attr_count,dep_appos_count,dep_conj_count,dep_nummod_count,dep_poss_count,dep_case_count,dep_nsubjpass_count,dep_nmod_count,dep_auxpass_count,dep_npadvmod_count,dep_expl_count,dep_xcomp_count,dep_dative_count,dep_oprd_count,dep_acl_count,dep_quantmod_count,dep_pcomp_count,dep_amod_ratio,dep_nsubj_ratio,dep_ROOT_ratio,dep_dobj_ratio,dep_advmod_ratio,dep_relcl_ratio,dep_punct_ratio,dep_det_ratio,dep_aux_ratio,dep_neg_ratio,dep_mark_ratio,dep_csubj_ratio,dep_compound_ratio,dep_prep_ratio,dep_pobj_ratio,dep_ccomp_ratio,dep_dep_ratio,dep_advcl_ratio,dep_cc_ratio,dep_acomp_ratio,dep_attr_ratio,dep_appos_ratio,dep_conj_ratio,dep_nummod_ratio,dep_poss_ratio,dep_case_ratio,dep_nsubjpass_ratio,dep_nmod_ratio,dep_auxpass_ratio,dep_npadvmod_ratio,dep_expl_ratio,dep_xcomp_ratio,dep_dative_ratio,dep_oprd_ratio,dep_acl_ratio,dep_quantmod_ratio,dep_pcomp_ratio,dep_agent_count,dep_intj_count,dep_predet_count,dep_prt_count,dep_agent_ratio,dep_intj_ratio,dep_predet_ratio,dep_prt_ratio,dep_meta_count,dep_meta_ratio,dep_preconj_count,dep_preconj_ratio,dep_parataxis_count,dep_parataxis_ratio,dep_csubjpass_count,dep_csubjpass_ratio,verb_tense_consistency,passive_voice_usage,modal_verb_usage,lexical_diversity,dale_chall_readability,automated_readability_index,coleman_liau_index,conjunction_usage,clause_density,vader_compound,vader_positive,vader_negative,vader_neutral,bert_dim_0,bert_dim_1,bert_dim_2,bert_dim_3,bert_dim_4,bert_dim_5,bert_dim_6,bert_dim_7,bert_dim_8,bert_dim_9,bert_dim_10,bert_dim_11,bert_dim_12,bert_dim_13,bert_dim_14,bert_dim_15,bert_dim_16,bert_dim_17,bert_dim_18,bert_dim_19,bert_dim_20,bert_dim_21,bert_dim_22,bert_dim_23,bert_dim_24,bert_dim_25,bert_dim_26,bert_dim_27,bert_dim_28,bert_dim_29,bert_dim_30,bert_dim_31,bert_dim_32,bert_dim_33,bert_dim_34,bert_dim_35,bert_dim_36,bert_dim_37,bert_dim_38,bert_dim_39,bert_dim_40,bert_dim_41,bert_dim_42,bert_dim_43,bert_dim_44,bert_dim_45,bert_dim_46,bert_dim_47,bert_dim_48,bert_dim_49,bert_dim_50,bert_dim_51,bert_dim_52,bert_dim_53,bert_dim_54,bert_dim_55,bert_dim_56,bert_dim_57,bert_dim_58,bert_dim_59,bert_dim_60,bert_dim_61,bert_dim_62,bert_dim_63,bert_dim_64,bert_dim_65,bert_dim_66,bert_dim_67,bert_dim_68,bert_dim_69,bert_dim_70,bert_dim_71,bert_dim_72,bert_dim_73,bert_dim_74,bert_dim_75,bert_dim_76,bert_dim_77,bert_dim_78,bert_dim_79,bert_dim_80,bert_dim_81,bert_dim_82,bert_dim_83,bert_dim_84,bert_dim_85,bert_dim_86,bert_dim_87,bert_dim_88,bert_dim_89,bert_dim_90,bert_dim_91,bert_dim_92,bert_dim_93,bert_dim_94,bert_dim_95,bert_dim_96,bert_dim_97,bert_dim_98,bert_dim_99,bert_dim_100,bert_dim_101,bert_dim_102,bert_dim_103,bert_dim_104,bert_dim_105,bert_dim_106,bert_dim_107,bert_dim_108,bert_dim_109,bert_dim_110,bert_dim_111,bert_dim_112,bert_dim_113,bert_dim_114,bert_dim_115,bert_dim_116,bert_dim_117,bert_dim_118,bert_dim_119,bert_dim_120,bert_dim_121,bert_dim_122,bert_dim_123,bert_dim_124,bert_dim_125,bert_dim_126,bert_dim_127,bert_dim_128,bert_dim_129,bert_dim_130,bert_dim_131,bert_dim_132,bert_dim_133,bert_dim_134,bert_dim_135,bert_dim_136,bert_dim_137,bert_dim_138,bert_dim_139,bert_dim_140,bert_dim_141,bert_dim_142,bert_dim_143,bert_dim_144,bert_dim_145,bert_dim_146,bert_dim_147,bert_dim_148,bert_dim_149,bert_dim_150,bert_dim_151,bert_dim_152,bert_dim_153,bert_dim_154,bert_dim_155,bert_dim_156,bert_dim_157,bert_dim_158,bert_dim_159,bert_dim_160,bert_dim_161,bert_dim_162,bert_dim_163,bert_dim_164,bert_dim_165,bert_dim_166,bert_dim_167,bert_dim_168,bert_dim_169,bert_dim_170,bert_dim_171,bert_dim_172,bert_dim_173,bert_dim_174,bert_dim_175,bert_dim_176,bert_dim_177,bert_dim_178,bert_dim_179,bert_dim_180,bert_dim_181,bert_dim_182,bert_dim_183,bert_dim_184,bert_dim_185,bert_dim_186,bert_dim_187,bert_dim_188,bert_dim_189,bert_dim_190,bert_dim_191,bert_dim_192,bert_dim_193,bert_dim_194,bert_dim_195,bert_dim_196,bert_dim_197,bert_dim_198,bert_dim_199,bert_dim_200,bert_dim_201,bert_dim_202,bert_dim_203,bert_dim_204,bert_dim_205,bert_dim_206,bert_dim_207,bert_dim_208,bert_dim_209,bert_dim_210,bert_dim_211,bert_dim_212,bert_dim_213,bert_dim_214,bert_dim_215,bert_dim_216,bert_dim_217,bert_dim_218,bert_dim_219,bert_dim_220,bert_dim_221,bert_dim_222,bert_dim_223,bert_dim_224,bert_dim_225,bert_dim_226,bert_dim_227,bert_dim_228,bert_dim_229,bert_dim_230,bert_dim_231,bert_dim_232,bert_dim_233,bert_dim_234,bert_dim_235,bert_dim_236,bert_dim_237,bert_dim_238,bert_dim_239,bert_dim_240,bert_dim_241,bert_dim_242,bert_dim_243,bert_dim_244,bert_dim_245,bert_dim_246,bert_dim_247,bert_dim_248,bert_dim_249,bert_dim_250,bert_dim_251,bert_dim_252,bert_dim_253,bert_dim_254,bert_dim_255,bert_dim_256,bert_dim_257,bert_dim_258,bert_dim_259,bert_dim_260,bert_dim_261,bert_dim_262,bert_dim_263,bert_dim_264,bert_dim_265,bert_dim_266,bert_dim_267,bert_dim_268,bert_dim_269,bert_dim_270,bert_dim_271,bert_dim_272,bert_dim_273,bert_dim_274,bert_dim_275,bert_dim_276,bert_dim_277,bert_dim_278,bert_dim_279,bert_dim_280,bert_dim_281,bert_dim_282,bert_dim_283,bert_dim_284,bert_dim_285,bert_dim_286,bert_dim_287,bert_dim_288,bert_dim_289,bert_dim_290,bert_dim_291,bert_dim_292,bert_dim_293,bert_dim_294,bert_dim_295,bert_dim_296,bert_dim_297,bert_dim_298,bert_dim_299,bert_dim_300,bert_dim_301,bert_dim_302,bert_dim_303,bert_dim_304,bert_dim_305,bert_dim_306,bert_dim_307,bert_dim_308,bert_dim_309,bert_dim_310,bert_dim_311,bert_dim_312,bert_dim_313,bert_dim_314,bert_dim_315,bert_dim_316,bert_dim_317,bert_dim_318,bert_dim_319,bert_dim_320,bert_dim_321,bert_dim_322,bert_dim_323,bert_dim_324,bert_dim_325,bert_dim_326,bert_dim_327,bert_dim_328,bert_dim_329,bert_dim_330,bert_dim_331,bert_dim_332,bert_dim_333,bert_dim_334,bert_dim_335,bert_dim_336,bert_dim_337,bert_dim_338,bert_dim_339,bert_dim_340,bert_dim_341,bert_dim_342,bert_dim_343,bert_dim_344,bert_dim_345,bert_dim_346,bert_dim_347,bert_dim_348,bert_dim_349,bert_dim_350,bert_dim_351,bert_dim_352,bert_dim_353,bert_dim_354,bert_dim_355,bert_dim_356,bert_dim_357,bert_dim_358,bert_dim_359,bert_dim_360,bert_dim_361,bert_dim_362,bert_dim_363,bert_dim_364,bert_dim_365,bert_dim_366,bert_dim_367,bert_dim_368,bert_dim_369,bert_dim_370,bert_dim_371,bert_dim_372,bert_dim_373,bert_dim_374,bert_dim_375,bert_dim_376,bert_dim_377,bert_dim_378,bert_dim_379,bert_dim_380,bert_dim_381,bert_dim_382,bert_dim_383,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,spelling_errors,grammar_errors,linsear_write_formula,ari_score,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,topic,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young

In [22]:

# # Import necessary libraries
# import pandas as pd
# from itertools import combinations

# # Assuming the DataFrame `df` and `score` are already defined
# # and excluding irrelevant columns

# # Calculate correlations with the target

# cor = df.drop(columns=['essay_id', 'full_text', 'clean_text', 'lowered' ,'processed_docs', 'topics', 'score'], axis=1)

# correlations = cor.corrwith(df['score']).sort_values(ascending=False)



# # Set a correlation threshold or select top N features
# correlation_threshold = 0.3

# top_features = correlations[abs(correlations) > correlation_threshold].index.tolist()

# # Print the most correlated features
# print("Top correlations with the score:")
# print(top_features)

# # Generate interaction terms between pairs of top features
# for feature1, feature2 in combinations(top_features, 2):
#     df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]


# # Optional: print the list of created interaction terms
# interaction_terms = [f'interaction_{feature1}_{feature2}' for feature1, feature2 in combinations(top_features, 2)]
# print("Created interaction terms:")
# print(interaction_terms)


# # export top_features to text file

# with open('/home/jack/github/kaggle/scoring/model_data/sklearn/top_corelations.txt', 'w') as f:
#     for item in top_features:
#         f.write("%s\n" % item)

In [23]:
df.head()

,essay_id,full_text,score,lowered,clean_text,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,pos_ADJ_count,pos_NOUN_count,pos_VERB_count,pos_SCONJ_count,pos_PRON_count,pos_PUNCT_count,pos_DET_count,pos_AUX_count,pos_PART_count,pos_ADP_count,pos_SPACE_count,pos_CCONJ_count,pos_PROPN_count,pos_NUM_count,pos_ADV_count,pos_SYM_count,pos_ADJ_ratio,pos_NOUN_ratio,pos_VERB_ratio,pos_SCONJ_ratio,pos_PRON_ratio,pos_PUNCT_ratio,pos_DET_ratio,pos_AUX_ratio,pos_PART_ratio,pos_ADP_ratio,pos_SPACE_ratio,pos_CCONJ_ratio,pos_PROPN_ratio,pos_NUM_ratio,pos_ADV_ratio,pos_SYM_ratio,pos_INTJ_count,pos_INTJ_ratio,pos_X_count,pos_X_ratio,ner_GPE_count,ner_PERCENT_count,ner_NORP_count,ner_ORG_count,ner_CARDINAL_count,ner_MONEY_count,ner_DATE_count,ner_LOC_count,ner_PERSON_count,ner_QUANTITY_count,ner_EVENT_count,ner_GPE_ratio,ner_PERCENT_ratio,ner_NORP_ratio,ner_ORG_ratio,ner_CARDINAL_ratio,ner_MONEY_ratio,ner_DATE_ratio,ner_LOC_ratio,ner_PERSON_ratio,ner_QUANTITY_ratio,ner_EVENT_ratio,ner_ORDINAL_count,ner_ORDINAL_ratio,ner_WORK_OF_ART_count,ner_WORK_OF_ART_ratio,ner_LAW_count,ner_LAW_ratio,ner_PRODUCT_count,ner_PRODUCT_ratio,ner_TIME_count,ner_TIME_ratio,ner_FAC_count,ner_FAC_ratio,ner_LANGUAGE_count,ner_LANGUAGE_ratio,dep_amod_count,dep_nsubj_count,dep_ROOT_count,dep_dobj_count,dep_advmod_count,dep_relcl_count,dep_punct_count,dep_det_count,dep_aux_count,dep_neg_count,dep_mark_count,dep_csubj_count,dep_compound_count,dep_prep_count,dep_pobj_count,dep_ccomp_count,dep_dep_count,dep_advcl_count,dep_cc_count,dep_acomp_count,dep_attr_count,dep_appos_count,dep_conj_count,dep_nummod_count,dep_poss_count,dep_case_count,dep_nsubjpass_count,dep_nmod_count,dep_auxpass_count,dep_npadvmod_count,dep_expl_count,dep_xcomp_count,dep_dative_count,dep_oprd_count,dep_acl_count,dep_quantmod_count,dep_pcomp_count,dep_amod_ratio,dep_nsubj_ratio,dep_ROOT_ratio,dep_dobj_ratio,dep_advmod_ratio,dep_relcl_ratio,dep_punct_ratio,dep_det_ratio,dep_aux_ratio,dep_neg_ratio,dep_mark_ratio,dep_csubj_ratio,dep_compound_ratio,dep_prep_ratio,dep_pobj_ratio,dep_ccomp_ratio,dep_dep_ratio,dep_advcl_ratio,dep_cc_ratio,dep_acomp_ratio,dep_attr_ratio,dep_appos_ratio,dep_conj_ratio,dep_nummod_ratio,dep_poss_ratio,dep_case_ratio,dep_nsubjpass_ratio,dep_nmod_ratio,dep_auxpass_ratio,dep_npadvmod_ratio,dep_expl_ratio,dep_xcomp_ratio,dep_dative_ratio,dep_oprd_ratio,dep_acl_ratio,dep_quantmod_ratio,dep_pcomp_ratio,dep_agent_count,dep_intj_count,dep_predet_count,dep_prt_count,dep_agent_ratio,dep_intj_ratio,dep_predet_ratio,dep_prt_ratio,dep_meta_count,dep_meta_ratio,dep_preconj_count,dep_preconj_ratio,dep_parataxis_count,dep_parataxis_ratio,dep_csubjpass_count,dep_csubjpass_ratio,verb_tense_consistency,passive_voice_usage,modal_verb_usage,lexical_diversity,dale_chall_readability,automated_readability_index,coleman_liau_index,conjunction_usage,clause_density,vader_compound,vader_positive,vader_negative,vader_neutral,bert_dim_0,bert_dim_1,bert_dim_2,bert_dim_3,bert_dim_4,bert_dim_5,bert_dim_6,bert_dim_7,bert_dim_8,bert_dim_9,bert_dim_10,bert_dim_11,bert_dim_12,bert_dim_13,bert_dim_14,bert_dim_15,bert_dim_16,bert_dim_17,bert_dim_18,bert_dim_19,bert_dim_20,bert_dim_21,bert_dim_22,bert_dim_23,bert_dim_24,bert_dim_25,bert_dim_26,bert_dim_27,bert_dim_28,bert_dim_29,bert_dim_30,bert_dim_31,bert_dim_32,bert_dim_33,bert_dim_34,bert_dim_35,bert_dim_36,bert_dim_37,bert_dim_38,bert_dim_39,bert_dim_40,bert_dim_41,bert_dim_42,bert_dim_43,bert_dim_44,bert_dim_45,bert_dim_46,bert_dim_47,bert_dim_48,bert_dim_49,bert_dim_50,bert_dim_51,bert_dim_52,bert_dim_53,bert_dim_54,bert_dim_55,bert_dim_56,bert_dim_57,bert_dim_58,bert_dim_59,bert_dim_60,bert_dim_61,bert_dim_62,bert_dim_63,bert_dim_64,bert_dim_65,bert_dim_66,bert_dim_67,bert_dim_68,bert_dim_69,bert_dim_70,bert_dim_71,bert_dim_72,bert_dim_73,bert_dim_74,bert_dim_75,bert_dim_76,bert_dim_77,bert_dim_78,bert_dim_79,bert_dim_80,bert_dim_81,bert_dim_82,bert_dim_83,bert_dim_84,bert_dim_85,bert_dim_86,bert_dim_87,bert_dim_88,bert_dim_89,bert_dim_90,bert_dim_91,bert_dim_92,bert_dim_93,bert_dim_94,bert_dim_95,bert_dim_96,bert_dim_97,bert_dim_98,bert_dim_99,bert_dim_100,bert_dim_101,bert_dim_102,bert_dim_103,bert_dim_104,bert_dim_105,bert_dim_106,bert_dim_107,bert_dim_108,bert_dim_109,bert_dim_110,bert_dim_111,bert_dim_112,bert_dim_113,bert_dim_114,bert_dim_115,bert_dim_116,bert_dim_117,bert_dim_118,bert_dim_119,bert_dim_120,bert_dim_121,bert_dim_122,bert_dim_123,bert_dim_124,bert_dim_125,bert_dim_126,bert_dim_127,bert_dim_128,bert_dim_129,bert_dim_130,bert_dim_131,bert_dim_132,bert_dim_133,bert_dim_134,bert_dim_135,bert_dim_136,bert_dim_137,bert_dim_138,bert_dim_139,bert_dim_140,bert_dim_141,bert_dim_142,bert_dim_143,bert_dim_144,bert_dim_145,bert_dim_146,bert_dim_147,bert_dim_148,bert_dim_149,bert_dim_150,bert_dim_151,bert_dim_152,bert_dim_153,bert_dim_154,bert_dim_155,bert_dim_156,bert_dim_157,bert_dim_158,bert_dim_159,bert_dim_160,bert_dim_161,bert_dim_162,bert_dim_163,bert_dim_164,bert_dim_165,bert_dim_166,bert_dim_167,bert_dim_168,bert_dim_169,bert_dim_170,bert_dim_171,bert_dim_172,bert_dim_173,bert_dim_174,bert_dim_175,bert_dim_176,bert_dim_177,bert_dim_178,bert_dim_179,bert_dim_180,bert_dim_181,bert_dim_182,bert_dim_183,bert_dim_184,bert_dim_185,bert_dim_186,bert_dim_187,bert_dim_188,bert_dim_189,bert_dim_190,bert_dim_191,bert_dim_192,bert_dim_193,bert_dim_194,bert_dim_195,bert_dim_196,bert_dim_197,bert_dim_198,bert_dim_199,bert_dim_200,bert_dim_201,bert_dim_202,bert_dim_203,bert_dim_204,bert_dim_205,bert_dim_206,bert_dim_207,bert_dim_208,bert_dim_209,bert_dim_210,bert_dim_211,bert_dim_212,bert_dim_213,bert_dim_214,bert_dim_215,bert_dim_216,bert_dim_217,bert_dim_218,bert_dim_219,bert_dim_220,bert_dim_221,bert_dim_222,bert_dim_223,bert_dim_224,bert_dim_225,bert_dim_226,bert_dim_227,bert_dim_228,bert_dim_229,bert_dim_230,bert_dim_231,bert_dim_232,bert_dim_233,bert_dim_234,bert_dim_235,bert_dim_236,bert_dim_237,bert_dim_238,bert_dim_239,bert_dim_240,bert_dim_241,bert_dim_242,bert_dim_243,bert_dim_244,bert_dim_245,bert_dim_246,bert_dim_247,bert_dim_248,bert_dim_249,bert_dim_250,bert_dim_251,bert_dim_252,bert_dim_253,bert_dim_254,bert_dim_255,bert_dim_256,bert_dim_257,bert_dim_258,bert_dim_259,bert_dim_260,bert_dim_261,bert_dim_262,bert_dim_263,bert_dim_264,bert_dim_265,bert_dim_266,bert_dim_267,bert_dim_268,bert_dim_269,bert_dim_270,bert_dim_271,bert_dim_272,bert_dim_273,bert_dim_274,bert_dim_275,bert_dim_276,bert_dim_277,bert_dim_278,bert_dim_279,bert_dim_280,bert_dim_281,bert_dim_282,bert_dim_283,bert_dim_284,bert_dim_285,bert_dim_286,bert_dim_287,bert_dim_288,bert_dim_289,bert_dim_290,bert_dim_291,bert_dim_292,bert_dim_293,bert_dim_294,bert_dim_295,bert_dim_296,bert_dim_297,bert_dim_298,bert_dim_299,bert_dim_300,bert_dim_301,bert_dim_302,bert_dim_303,bert_dim_304,bert_dim_305,bert_dim_306,bert_dim_307,bert_dim_308,bert_dim_309,bert_dim_310,bert_dim_311,bert_dim_312,bert_dim_313,bert_dim_314,bert_dim_315,bert_dim_316,bert_dim_317,bert_dim_318,bert_dim_319,bert_dim_320,bert_dim_321,bert_dim_322,bert_dim_323,bert_dim_324,bert_dim_325,bert_dim_326,bert_dim_327,bert_dim_328,bert_dim_329,bert_dim_330,bert_dim_331,bert_dim_332,bert_dim_333,bert_dim_334,bert_dim_335,bert_dim_336,bert_dim_337,bert_dim_338,bert_dim_339,bert_dim_340,bert_dim_341,bert_dim_342,bert_dim_343,bert_dim_344,bert_dim_345,bert_dim_346,bert_dim_347,bert_dim_348,bert_dim_349,bert_dim_350,bert_dim_351,bert_dim_352,bert_dim_353,bert_dim_354,bert_dim_355,bert_dim_356,bert_dim_357,bert_dim_358,bert_dim_359,bert_dim_360,bert_dim_361,bert_dim_362,bert_dim_363,bert_dim_364,bert_dim_365,bert_dim_366,bert_dim_367,bert_dim_368,bert_dim_369,bert_dim_370,bert_dim_371,bert_dim_372,bert_dim_373,bert_dim_374,bert_dim_375,bert_dim_376,bert_dim_377,bert_dim_378,bert_dim_379,bert_dim_380,bert_dim_381,bert_dim_382,bert_dim_383,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,spelling_errors,grammar_errors,linsear_write_formula,ari_score,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,topic,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young

In [24]:
df.tail()

,essay_id,full_text,score,lowered,clean_text,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,pos_ADJ_count,pos_NOUN_count,pos_VERB_count,pos_SCONJ_count,pos_PRON_count,pos_PUNCT_count,pos_DET_count,pos_AUX_count,pos_PART_count,pos_ADP_count,pos_SPACE_count,pos_CCONJ_count,pos_PROPN_count,pos_NUM_count,pos_ADV_count,pos_SYM_count,pos_ADJ_ratio,pos_NOUN_ratio,pos_VERB_ratio,pos_SCONJ_ratio,pos_PRON_ratio,pos_PUNCT_ratio,pos_DET_ratio,pos_AUX_ratio,pos_PART_ratio,pos_ADP_ratio,pos_SPACE_ratio,pos_CCONJ_ratio,pos_PROPN_ratio,pos_NUM_ratio,pos_ADV_ratio,pos_SYM_ratio,pos_INTJ_count,pos_INTJ_ratio,pos_X_count,pos_X_ratio,ner_GPE_count,ner_PERCENT_count,ner_NORP_count,ner_ORG_count,ner_CARDINAL_count,ner_MONEY_count,ner_DATE_count,ner_LOC_count,ner_PERSON_count,ner_QUANTITY_count,ner_EVENT_count,ner_GPE_ratio,ner_PERCENT_ratio,ner_NORP_ratio,ner_ORG_ratio,ner_CARDINAL_ratio,ner_MONEY_ratio,ner_DATE_ratio,ner_LOC_ratio,ner_PERSON_ratio,ner_QUANTITY_ratio,ner_EVENT_ratio,ner_ORDINAL_count,ner_ORDINAL_ratio,ner_WORK_OF_ART_count,ner_WORK_OF_ART_ratio,ner_LAW_count,ner_LAW_ratio,ner_PRODUCT_count,ner_PRODUCT_ratio,ner_TIME_count,ner_TIME_ratio,ner_FAC_count,ner_FAC_ratio,ner_LANGUAGE_count,ner_LANGUAGE_ratio,dep_amod_count,dep_nsubj_count,dep_ROOT_count,dep_dobj_count,dep_advmod_count,dep_relcl_count,dep_punct_count,dep_det_count,dep_aux_count,dep_neg_count,dep_mark_count,dep_csubj_count,dep_compound_count,dep_prep_count,dep_pobj_count,dep_ccomp_count,dep_dep_count,dep_advcl_count,dep_cc_count,dep_acomp_count,dep_attr_count,dep_appos_count,dep_conj_count,dep_nummod_count,dep_poss_count,dep_case_count,dep_nsubjpass_count,dep_nmod_count,dep_auxpass_count,dep_npadvmod_count,dep_expl_count,dep_xcomp_count,dep_dative_count,dep_oprd_count,dep_acl_count,dep_quantmod_count,dep_pcomp_count,dep_amod_ratio,dep_nsubj_ratio,dep_ROOT_ratio,dep_dobj_ratio,dep_advmod_ratio,dep_relcl_ratio,dep_punct_ratio,dep_det_ratio,dep_aux_ratio,dep_neg_ratio,dep_mark_ratio,dep_csubj_ratio,dep_compound_ratio,dep_prep_ratio,dep_pobj_ratio,dep_ccomp_ratio,dep_dep_ratio,dep_advcl_ratio,dep_cc_ratio,dep_acomp_ratio,dep_attr_ratio,dep_appos_ratio,dep_conj_ratio,dep_nummod_ratio,dep_poss_ratio,dep_case_ratio,dep_nsubjpass_ratio,dep_nmod_ratio,dep_auxpass_ratio,dep_npadvmod_ratio,dep_expl_ratio,dep_xcomp_ratio,dep_dative_ratio,dep_oprd_ratio,dep_acl_ratio,dep_quantmod_ratio,dep_pcomp_ratio,dep_agent_count,dep_intj_count,dep_predet_count,dep_prt_count,dep_agent_ratio,dep_intj_ratio,dep_predet_ratio,dep_prt_ratio,dep_meta_count,dep_meta_ratio,dep_preconj_count,dep_preconj_ratio,dep_parataxis_count,dep_parataxis_ratio,dep_csubjpass_count,dep_csubjpass_ratio,verb_tense_consistency,passive_voice_usage,modal_verb_usage,lexical_diversity,dale_chall_readability,automated_readability_index,coleman_liau_index,conjunction_usage,clause_density,vader_compound,vader_positive,vader_negative,vader_neutral,bert_dim_0,bert_dim_1,bert_dim_2,bert_dim_3,bert_dim_4,bert_dim_5,bert_dim_6,bert_dim_7,bert_dim_8,bert_dim_9,bert_dim_10,bert_dim_11,bert_dim_12,bert_dim_13,bert_dim_14,bert_dim_15,bert_dim_16,bert_dim_17,bert_dim_18,bert_dim_19,bert_dim_20,bert_dim_21,bert_dim_22,bert_dim_23,bert_dim_24,bert_dim_25,bert_dim_26,bert_dim_27,bert_dim_28,bert_dim_29,bert_dim_30,bert_dim_31,bert_dim_32,bert_dim_33,bert_dim_34,bert_dim_35,bert_dim_36,bert_dim_37,bert_dim_38,bert_dim_39,bert_dim_40,bert_dim_41,bert_dim_42,bert_dim_43,bert_dim_44,bert_dim_45,bert_dim_46,bert_dim_47,bert_dim_48,bert_dim_49,bert_dim_50,bert_dim_51,bert_dim_52,bert_dim_53,bert_dim_54,bert_dim_55,bert_dim_56,bert_dim_57,bert_dim_58,bert_dim_59,bert_dim_60,bert_dim_61,bert_dim_62,bert_dim_63,bert_dim_64,bert_dim_65,bert_dim_66,bert_dim_67,bert_dim_68,bert_dim_69,bert_dim_70,bert_dim_71,bert_dim_72,bert_dim_73,bert_dim_74,bert_dim_75,bert_dim_76,bert_dim_77,bert_dim_78,bert_dim_79,bert_dim_80,bert_dim_81,bert_dim_82,bert_dim_83,bert_dim_84,bert_dim_85,bert_dim_86,bert_dim_87,bert_dim_88,bert_dim_89,bert_dim_90,bert_dim_91,bert_dim_92,bert_dim_93,bert_dim_94,bert_dim_95,bert_dim_96,bert_dim_97,bert_dim_98,bert_dim_99,bert_dim_100,bert_dim_101,bert_dim_102,bert_dim_103,bert_dim_104,bert_dim_105,bert_dim_106,bert_dim_107,bert_dim_108,bert_dim_109,bert_dim_110,bert_dim_111,bert_dim_112,bert_dim_113,bert_dim_114,bert_dim_115,bert_dim_116,bert_dim_117,bert_dim_118,bert_dim_119,bert_dim_120,bert_dim_121,bert_dim_122,bert_dim_123,bert_dim_124,bert_dim_125,bert_dim_126,bert_dim_127,bert_dim_128,bert_dim_129,bert_dim_130,bert_dim_131,bert_dim_132,bert_dim_133,bert_dim_134,bert_dim_135,bert_dim_136,bert_dim_137,bert_dim_138,bert_dim_139,bert_dim_140,bert_dim_141,bert_dim_142,bert_dim_143,bert_dim_144,bert_dim_145,bert_dim_146,bert_dim_147,bert_dim_148,bert_dim_149,bert_dim_150,bert_dim_151,bert_dim_152,bert_dim_153,bert_dim_154,bert_dim_155,bert_dim_156,bert_dim_157,bert_dim_158,bert_dim_159,bert_dim_160,bert_dim_161,bert_dim_162,bert_dim_163,bert_dim_164,bert_dim_165,bert_dim_166,bert_dim_167,bert_dim_168,bert_dim_169,bert_dim_170,bert_dim_171,bert_dim_172,bert_dim_173,bert_dim_174,bert_dim_175,bert_dim_176,bert_dim_177,bert_dim_178,bert_dim_179,bert_dim_180,bert_dim_181,bert_dim_182,bert_dim_183,bert_dim_184,bert_dim_185,bert_dim_186,bert_dim_187,bert_dim_188,bert_dim_189,bert_dim_190,bert_dim_191,bert_dim_192,bert_dim_193,bert_dim_194,bert_dim_195,bert_dim_196,bert_dim_197,bert_dim_198,bert_dim_199,bert_dim_200,bert_dim_201,bert_dim_202,bert_dim_203,bert_dim_204,bert_dim_205,bert_dim_206,bert_dim_207,bert_dim_208,bert_dim_209,bert_dim_210,bert_dim_211,bert_dim_212,bert_dim_213,bert_dim_214,bert_dim_215,bert_dim_216,bert_dim_217,bert_dim_218,bert_dim_219,bert_dim_220,bert_dim_221,bert_dim_222,bert_dim_223,bert_dim_224,bert_dim_225,bert_dim_226,bert_dim_227,bert_dim_228,bert_dim_229,bert_dim_230,bert_dim_231,bert_dim_232,bert_dim_233,bert_dim_234,bert_dim_235,bert_dim_236,bert_dim_237,bert_dim_238,bert_dim_239,bert_dim_240,bert_dim_241,bert_dim_242,bert_dim_243,bert_dim_244,bert_dim_245,bert_dim_246,bert_dim_247,bert_dim_248,bert_dim_249,bert_dim_250,bert_dim_251,bert_dim_252,bert_dim_253,bert_dim_254,bert_dim_255,bert_dim_256,bert_dim_257,bert_dim_258,bert_dim_259,bert_dim_260,bert_dim_261,bert_dim_262,bert_dim_263,bert_dim_264,bert_dim_265,bert_dim_266,bert_dim_267,bert_dim_268,bert_dim_269,bert_dim_270,bert_dim_271,bert_dim_272,bert_dim_273,bert_dim_274,bert_dim_275,bert_dim_276,bert_dim_277,bert_dim_278,bert_dim_279,bert_dim_280,bert_dim_281,bert_dim_282,bert_dim_283,bert_dim_284,bert_dim_285,bert_dim_286,bert_dim_287,bert_dim_288,bert_dim_289,bert_dim_290,bert_dim_291,bert_dim_292,bert_dim_293,bert_dim_294,bert_dim_295,bert_dim_296,bert_dim_297,bert_dim_298,bert_dim_299,bert_dim_300,bert_dim_301,bert_dim_302,bert_dim_303,bert_dim_304,bert_dim_305,bert_dim_306,bert_dim_307,bert_dim_308,bert_dim_309,bert_dim_310,bert_dim_311,bert_dim_312,bert_dim_313,bert_dim_314,bert_dim_315,bert_dim_316,bert_dim_317,bert_dim_318,bert_dim_319,bert_dim_320,bert_dim_321,bert_dim_322,bert_dim_323,bert_dim_324,bert_dim_325,bert_dim_326,bert_dim_327,bert_dim_328,bert_dim_329,bert_dim_330,bert_dim_331,bert_dim_332,bert_dim_333,bert_dim_334,bert_dim_335,bert_dim_336,bert_dim_337,bert_dim_338,bert_dim_339,bert_dim_340,bert_dim_341,bert_dim_342,bert_dim_343,bert_dim_344,bert_dim_345,bert_dim_346,bert_dim_347,bert_dim_348,bert_dim_349,bert_dim_350,bert_dim_351,bert_dim_352,bert_dim_353,bert_dim_354,bert_dim_355,bert_dim_356,bert_dim_357,bert_dim_358,bert_dim_359,bert_dim_360,bert_dim_361,bert_dim_362,bert_dim_363,bert_dim_364,bert_dim_365,bert_dim_366,bert_dim_367,bert_dim_368,bert_dim_369,bert_dim_370,bert_dim_371,bert_dim_372,bert_dim_373,bert_dim_374,bert_dim_375,bert_dim_376,bert_dim_377,bert_dim_378,bert_dim_379,bert_dim_380,bert_dim_381,bert_dim_382,bert_dim_383,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,spelling_errors,grammar_errors,linsear_write_formula,ari_score,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,topic,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young

In [25]:
# drop columns with hash in the name

hash_cols = [col for col in deberta_full.columns if 'hash' in col]

df.drop(columns=hash_cols, inplace=True)

import pandas as pd
from sklearn.feature_extraction.text import HashingVectorizer


# Initialize the HashingVectorizer
n_features = 200  # Number of columns in the hashed vector
hashing_vectorizer = HashingVectorizer(n_features=n_features, alternate_sign=False)

# Transform the text column into hash vector features
hashed_features = hashing_vectorizer.transform(df[text_col])

# Convert the hashed features to a dense representation for easier manipulation
hashed_features_dense = hashed_features.todense()

# Create new column names based on the number of features
hashed_columns = [f'hash_{i}' for i in range(n_features)]

# Convert dense representation to a dataframe
hashed_df = pd.DataFrame(hashed_features_dense, columns=hashed_columns)

# Concatenate the original dataframe with the hashed dataframe

df = pd.concat([df, hashed_df], axis=1)

In [26]:
train = df.copy()

In [27]:
train.head()

,essay_id,full_text,score,lowered,clean_text,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,pos_ADJ_count,pos_NOUN_count,pos_VERB_count,pos_SCONJ_count,pos_PRON_count,pos_PUNCT_count,pos_DET_count,pos_AUX_count,pos_PART_count,pos_ADP_count,pos_SPACE_count,pos_CCONJ_count,pos_PROPN_count,pos_NUM_count,pos_ADV_count,pos_SYM_count,pos_ADJ_ratio,pos_NOUN_ratio,pos_VERB_ratio,pos_SCONJ_ratio,pos_PRON_ratio,pos_PUNCT_ratio,pos_DET_ratio,pos_AUX_ratio,pos_PART_ratio,pos_ADP_ratio,pos_SPACE_ratio,pos_CCONJ_ratio,pos_PROPN_ratio,pos_NUM_ratio,pos_ADV_ratio,pos_SYM_ratio,pos_INTJ_count,pos_INTJ_ratio,pos_X_count,pos_X_ratio,ner_GPE_count,ner_PERCENT_count,ner_NORP_count,ner_ORG_count,ner_CARDINAL_count,ner_MONEY_count,ner_DATE_count,ner_LOC_count,ner_PERSON_count,ner_QUANTITY_count,ner_EVENT_count,ner_GPE_ratio,ner_PERCENT_ratio,ner_NORP_ratio,ner_ORG_ratio,ner_CARDINAL_ratio,ner_MONEY_ratio,ner_DATE_ratio,ner_LOC_ratio,ner_PERSON_ratio,ner_QUANTITY_ratio,ner_EVENT_ratio,ner_ORDINAL_count,ner_ORDINAL_ratio,ner_WORK_OF_ART_count,ner_WORK_OF_ART_ratio,ner_LAW_count,ner_LAW_ratio,ner_PRODUCT_count,ner_PRODUCT_ratio,ner_TIME_count,ner_TIME_ratio,ner_FAC_count,ner_FAC_ratio,ner_LANGUAGE_count,ner_LANGUAGE_ratio,dep_amod_count,dep_nsubj_count,dep_ROOT_count,dep_dobj_count,dep_advmod_count,dep_relcl_count,dep_punct_count,dep_det_count,dep_aux_count,dep_neg_count,dep_mark_count,dep_csubj_count,dep_compound_count,dep_prep_count,dep_pobj_count,dep_ccomp_count,dep_dep_count,dep_advcl_count,dep_cc_count,dep_acomp_count,dep_attr_count,dep_appos_count,dep_conj_count,dep_nummod_count,dep_poss_count,dep_case_count,dep_nsubjpass_count,dep_nmod_count,dep_auxpass_count,dep_npadvmod_count,dep_expl_count,dep_xcomp_count,dep_dative_count,dep_oprd_count,dep_acl_count,dep_quantmod_count,dep_pcomp_count,dep_amod_ratio,dep_nsubj_ratio,dep_ROOT_ratio,dep_dobj_ratio,dep_advmod_ratio,dep_relcl_ratio,dep_punct_ratio,dep_det_ratio,dep_aux_ratio,dep_neg_ratio,dep_mark_ratio,dep_csubj_ratio,dep_compound_ratio,dep_prep_ratio,dep_pobj_ratio,dep_ccomp_ratio,dep_dep_ratio,dep_advcl_ratio,dep_cc_ratio,dep_acomp_ratio,dep_attr_ratio,dep_appos_ratio,dep_conj_ratio,dep_nummod_ratio,dep_poss_ratio,dep_case_ratio,dep_nsubjpass_ratio,dep_nmod_ratio,dep_auxpass_ratio,dep_npadvmod_ratio,dep_expl_ratio,dep_xcomp_ratio,dep_dative_ratio,dep_oprd_ratio,dep_acl_ratio,dep_quantmod_ratio,dep_pcomp_ratio,dep_agent_count,dep_intj_count,dep_predet_count,dep_prt_count,dep_agent_ratio,dep_intj_ratio,dep_predet_ratio,dep_prt_ratio,dep_meta_count,dep_meta_ratio,dep_preconj_count,dep_preconj_ratio,dep_parataxis_count,dep_parataxis_ratio,dep_csubjpass_count,dep_csubjpass_ratio,verb_tense_consistency,passive_voice_usage,modal_verb_usage,lexical_diversity,dale_chall_readability,automated_readability_index,coleman_liau_index,conjunction_usage,clause_density,vader_compound,vader_positive,vader_negative,vader_neutral,bert_dim_0,bert_dim_1,bert_dim_2,bert_dim_3,bert_dim_4,bert_dim_5,bert_dim_6,bert_dim_7,bert_dim_8,bert_dim_9,bert_dim_10,bert_dim_11,bert_dim_12,bert_dim_13,bert_dim_14,bert_dim_15,bert_dim_16,bert_dim_17,bert_dim_18,bert_dim_19,bert_dim_20,bert_dim_21,bert_dim_22,bert_dim_23,bert_dim_24,bert_dim_25,bert_dim_26,bert_dim_27,bert_dim_28,bert_dim_29,bert_dim_30,bert_dim_31,bert_dim_32,bert_dim_33,bert_dim_34,bert_dim_35,bert_dim_36,bert_dim_37,bert_dim_38,bert_dim_39,bert_dim_40,bert_dim_41,bert_dim_42,bert_dim_43,bert_dim_44,bert_dim_45,bert_dim_46,bert_dim_47,bert_dim_48,bert_dim_49,bert_dim_50,bert_dim_51,bert_dim_52,bert_dim_53,bert_dim_54,bert_dim_55,bert_dim_56,bert_dim_57,bert_dim_58,bert_dim_59,bert_dim_60,bert_dim_61,bert_dim_62,bert_dim_63,bert_dim_64,bert_dim_65,bert_dim_66,bert_dim_67,bert_dim_68,bert_dim_69,bert_dim_70,bert_dim_71,bert_dim_72,bert_dim_73,bert_dim_74,bert_dim_75,bert_dim_76,bert_dim_77,bert_dim_78,bert_dim_79,bert_dim_80,bert_dim_81,bert_dim_82,bert_dim_83,bert_dim_84,bert_dim_85,bert_dim_86,bert_dim_87,bert_dim_88,bert_dim_89,bert_dim_90,bert_dim_91,bert_dim_92,bert_dim_93,bert_dim_94,bert_dim_95,bert_dim_96,bert_dim_97,bert_dim_98,bert_dim_99,bert_dim_100,bert_dim_101,bert_dim_102,bert_dim_103,bert_dim_104,bert_dim_105,bert_dim_106,bert_dim_107,bert_dim_108,bert_dim_109,bert_dim_110,bert_dim_111,bert_dim_112,bert_dim_113,bert_dim_114,bert_dim_115,bert_dim_116,bert_dim_117,bert_dim_118,bert_dim_119,bert_dim_120,bert_dim_121,bert_dim_122,bert_dim_123,bert_dim_124,bert_dim_125,bert_dim_126,bert_dim_127,bert_dim_128,bert_dim_129,bert_dim_130,bert_dim_131,bert_dim_132,bert_dim_133,bert_dim_134,bert_dim_135,bert_dim_136,bert_dim_137,bert_dim_138,bert_dim_139,bert_dim_140,bert_dim_141,bert_dim_142,bert_dim_143,bert_dim_144,bert_dim_145,bert_dim_146,bert_dim_147,bert_dim_148,bert_dim_149,bert_dim_150,bert_dim_151,bert_dim_152,bert_dim_153,bert_dim_154,bert_dim_155,bert_dim_156,bert_dim_157,bert_dim_158,bert_dim_159,bert_dim_160,bert_dim_161,bert_dim_162,bert_dim_163,bert_dim_164,bert_dim_165,bert_dim_166,bert_dim_167,bert_dim_168,bert_dim_169,bert_dim_170,bert_dim_171,bert_dim_172,bert_dim_173,bert_dim_174,bert_dim_175,bert_dim_176,bert_dim_177,bert_dim_178,bert_dim_179,bert_dim_180,bert_dim_181,bert_dim_182,bert_dim_183,bert_dim_184,bert_dim_185,bert_dim_186,bert_dim_187,bert_dim_188,bert_dim_189,bert_dim_190,bert_dim_191,bert_dim_192,bert_dim_193,bert_dim_194,bert_dim_195,bert_dim_196,bert_dim_197,bert_dim_198,bert_dim_199,bert_dim_200,bert_dim_201,bert_dim_202,bert_dim_203,bert_dim_204,bert_dim_205,bert_dim_206,bert_dim_207,bert_dim_208,bert_dim_209,bert_dim_210,bert_dim_211,bert_dim_212,bert_dim_213,bert_dim_214,bert_dim_215,bert_dim_216,bert_dim_217,bert_dim_218,bert_dim_219,bert_dim_220,bert_dim_221,bert_dim_222,bert_dim_223,bert_dim_224,bert_dim_225,bert_dim_226,bert_dim_227,bert_dim_228,bert_dim_229,bert_dim_230,bert_dim_231,bert_dim_232,bert_dim_233,bert_dim_234,bert_dim_235,bert_dim_236,bert_dim_237,bert_dim_238,bert_dim_239,bert_dim_240,bert_dim_241,bert_dim_242,bert_dim_243,bert_dim_244,bert_dim_245,bert_dim_246,bert_dim_247,bert_dim_248,bert_dim_249,bert_dim_250,bert_dim_251,bert_dim_252,bert_dim_253,bert_dim_254,bert_dim_255,bert_dim_256,bert_dim_257,bert_dim_258,bert_dim_259,bert_dim_260,bert_dim_261,bert_dim_262,bert_dim_263,bert_dim_264,bert_dim_265,bert_dim_266,bert_dim_267,bert_dim_268,bert_dim_269,bert_dim_270,bert_dim_271,bert_dim_272,bert_dim_273,bert_dim_274,bert_dim_275,bert_dim_276,bert_dim_277,bert_dim_278,bert_dim_279,bert_dim_280,bert_dim_281,bert_dim_282,bert_dim_283,bert_dim_284,bert_dim_285,bert_dim_286,bert_dim_287,bert_dim_288,bert_dim_289,bert_dim_290,bert_dim_291,bert_dim_292,bert_dim_293,bert_dim_294,bert_dim_295,bert_dim_296,bert_dim_297,bert_dim_298,bert_dim_299,bert_dim_300,bert_dim_301,bert_dim_302,bert_dim_303,bert_dim_304,bert_dim_305,bert_dim_306,bert_dim_307,bert_dim_308,bert_dim_309,bert_dim_310,bert_dim_311,bert_dim_312,bert_dim_313,bert_dim_314,bert_dim_315,bert_dim_316,bert_dim_317,bert_dim_318,bert_dim_319,bert_dim_320,bert_dim_321,bert_dim_322,bert_dim_323,bert_dim_324,bert_dim_325,bert_dim_326,bert_dim_327,bert_dim_328,bert_dim_329,bert_dim_330,bert_dim_331,bert_dim_332,bert_dim_333,bert_dim_334,bert_dim_335,bert_dim_336,bert_dim_337,bert_dim_338,bert_dim_339,bert_dim_340,bert_dim_341,bert_dim_342,bert_dim_343,bert_dim_344,bert_dim_345,bert_dim_346,bert_dim_347,bert_dim_348,bert_dim_349,bert_dim_350,bert_dim_351,bert_dim_352,bert_dim_353,bert_dim_354,bert_dim_355,bert_dim_356,bert_dim_357,bert_dim_358,bert_dim_359,bert_dim_360,bert_dim_361,bert_dim_362,bert_dim_363,bert_dim_364,bert_dim_365,bert_dim_366,bert_dim_367,bert_dim_368,bert_dim_369,bert_dim_370,bert_dim_371,bert_dim_372,bert_dim_373,bert_dim_374,bert_dim_375,bert_dim_376,bert_dim_377,bert_dim_378,bert_dim_379,bert_dim_380,bert_dim_381,bert_dim_382,bert_dim_383,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,spelling_errors,grammar_errors,linsear_write_formula,ari_score,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,topic,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199

In [28]:
len(train.columns)

1805

In [29]:
# import gc

# del df_train_final, df, df_ngrams, df_svd, df_pos, df_entities, df_deps, pos_df, ner_df, dep_df, pos_features, ner_features, dep_features

# gc.collect()

In [30]:
# show columns with nan values greater than 0

nan_cols = train.isna().sum()

nan_cols = nan_cols[nan_cols > 0]

nan_cols

Series([], dtype: int64)

In [31]:
drop_cols = [ 'full_text', 'clean_text', 'lowered', 'min_word_length']   # processed_docs', , 'global_coherence', 'topics'


train_df = train.copy()

train_df.drop(columns=drop_cols, inplace= True)

In [32]:
train_df.head()

,essay_id,score,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,pos_ADJ_count,pos_NOUN_count,pos_VERB_count,pos_SCONJ_count,pos_PRON_count,pos_PUNCT_count,pos_DET_count,pos_AUX_count,pos_PART_count,pos_ADP_count,pos_SPACE_count,pos_CCONJ_count,pos_PROPN_count,pos_NUM_count,pos_ADV_count,pos_SYM_count,pos_ADJ_ratio,pos_NOUN_ratio,pos_VERB_ratio,pos_SCONJ_ratio,pos_PRON_ratio,pos_PUNCT_ratio,pos_DET_ratio,pos_AUX_ratio,pos_PART_ratio,pos_ADP_ratio,pos_SPACE_ratio,pos_CCONJ_ratio,pos_PROPN_ratio,pos_NUM_ratio,pos_ADV_ratio,pos_SYM_ratio,pos_INTJ_count,pos_INTJ_ratio,pos_X_count,pos_X_ratio,ner_GPE_count,ner_PERCENT_count,ner_NORP_count,ner_ORG_count,ner_CARDINAL_count,ner_MONEY_count,ner_DATE_count,ner_LOC_count,ner_PERSON_count,ner_QUANTITY_count,ner_EVENT_count,ner_GPE_ratio,ner_PERCENT_ratio,ner_NORP_ratio,ner_ORG_ratio,ner_CARDINAL_ratio,ner_MONEY_ratio,ner_DATE_ratio,ner_LOC_ratio,ner_PERSON_ratio,ner_QUANTITY_ratio,ner_EVENT_ratio,ner_ORDINAL_count,ner_ORDINAL_ratio,ner_WORK_OF_ART_count,ner_WORK_OF_ART_ratio,ner_LAW_count,ner_LAW_ratio,ner_PRODUCT_count,ner_PRODUCT_ratio,ner_TIME_count,ner_TIME_ratio,ner_FAC_count,ner_FAC_ratio,ner_LANGUAGE_count,ner_LANGUAGE_ratio,dep_amod_count,dep_nsubj_count,dep_ROOT_count,dep_dobj_count,dep_advmod_count,dep_relcl_count,dep_punct_count,dep_det_count,dep_aux_count,dep_neg_count,dep_mark_count,dep_csubj_count,dep_compound_count,dep_prep_count,dep_pobj_count,dep_ccomp_count,dep_dep_count,dep_advcl_count,dep_cc_count,dep_acomp_count,dep_attr_count,dep_appos_count,dep_conj_count,dep_nummod_count,dep_poss_count,dep_case_count,dep_nsubjpass_count,dep_nmod_count,dep_auxpass_count,dep_npadvmod_count,dep_expl_count,dep_xcomp_count,dep_dative_count,dep_oprd_count,dep_acl_count,dep_quantmod_count,dep_pcomp_count,dep_amod_ratio,dep_nsubj_ratio,dep_ROOT_ratio,dep_dobj_ratio,dep_advmod_ratio,dep_relcl_ratio,dep_punct_ratio,dep_det_ratio,dep_aux_ratio,dep_neg_ratio,dep_mark_ratio,dep_csubj_ratio,dep_compound_ratio,dep_prep_ratio,dep_pobj_ratio,dep_ccomp_ratio,dep_dep_ratio,dep_advcl_ratio,dep_cc_ratio,dep_acomp_ratio,dep_attr_ratio,dep_appos_ratio,dep_conj_ratio,dep_nummod_ratio,dep_poss_ratio,dep_case_ratio,dep_nsubjpass_ratio,dep_nmod_ratio,dep_auxpass_ratio,dep_npadvmod_ratio,dep_expl_ratio,dep_xcomp_ratio,dep_dative_ratio,dep_oprd_ratio,dep_acl_ratio,dep_quantmod_ratio,dep_pcomp_ratio,dep_agent_count,dep_intj_count,dep_predet_count,dep_prt_count,dep_agent_ratio,dep_intj_ratio,dep_predet_ratio,dep_prt_ratio,dep_meta_count,dep_meta_ratio,dep_preconj_count,dep_preconj_ratio,dep_parataxis_count,dep_parataxis_ratio,dep_csubjpass_count,dep_csubjpass_ratio,verb_tense_consistency,passive_voice_usage,modal_verb_usage,lexical_diversity,dale_chall_readability,automated_readability_index,coleman_liau_index,conjunction_usage,clause_density,vader_compound,vader_positive,vader_negative,vader_neutral,bert_dim_0,bert_dim_1,bert_dim_2,bert_dim_3,bert_dim_4,bert_dim_5,bert_dim_6,bert_dim_7,bert_dim_8,bert_dim_9,bert_dim_10,bert_dim_11,bert_dim_12,bert_dim_13,bert_dim_14,bert_dim_15,bert_dim_16,bert_dim_17,bert_dim_18,bert_dim_19,bert_dim_20,bert_dim_21,bert_dim_22,bert_dim_23,bert_dim_24,bert_dim_25,bert_dim_26,bert_dim_27,bert_dim_28,bert_dim_29,bert_dim_30,bert_dim_31,bert_dim_32,bert_dim_33,bert_dim_34,bert_dim_35,bert_dim_36,bert_dim_37,bert_dim_38,bert_dim_39,bert_dim_40,bert_dim_41,bert_dim_42,bert_dim_43,bert_dim_44,bert_dim_45,bert_dim_46,bert_dim_47,bert_dim_48,bert_dim_49,bert_dim_50,bert_dim_51,bert_dim_52,bert_dim_53,bert_dim_54,bert_dim_55,bert_dim_56,bert_dim_57,bert_dim_58,bert_dim_59,bert_dim_60,bert_dim_61,bert_dim_62,bert_dim_63,bert_dim_64,bert_dim_65,bert_dim_66,bert_dim_67,bert_dim_68,bert_dim_69,bert_dim_70,bert_dim_71,bert_dim_72,bert_dim_73,bert_dim_74,bert_dim_75,bert_dim_76,bert_dim_77,bert_dim_78,bert_dim_79,bert_dim_80,bert_dim_81,bert_dim_82,bert_dim_83,bert_dim_84,bert_dim_85,bert_dim_86,bert_dim_87,bert_dim_88,bert_dim_89,bert_dim_90,bert_dim_91,bert_dim_92,bert_dim_93,bert_dim_94,bert_dim_95,bert_dim_96,bert_dim_97,bert_dim_98,bert_dim_99,bert_dim_100,bert_dim_101,bert_dim_102,bert_dim_103,bert_dim_104,bert_dim_105,bert_dim_106,bert_dim_107,bert_dim_108,bert_dim_109,bert_dim_110,bert_dim_111,bert_dim_112,bert_dim_113,bert_dim_114,bert_dim_115,bert_dim_116,bert_dim_117,bert_dim_118,bert_dim_119,bert_dim_120,bert_dim_121,bert_dim_122,bert_dim_123,bert_dim_124,bert_dim_125,bert_dim_126,bert_dim_127,bert_dim_128,bert_dim_129,bert_dim_130,bert_dim_131,bert_dim_132,bert_dim_133,bert_dim_134,bert_dim_135,bert_dim_136,bert_dim_137,bert_dim_138,bert_dim_139,bert_dim_140,bert_dim_141,bert_dim_142,bert_dim_143,bert_dim_144,bert_dim_145,bert_dim_146,bert_dim_147,bert_dim_148,bert_dim_149,bert_dim_150,bert_dim_151,bert_dim_152,bert_dim_153,bert_dim_154,bert_dim_155,bert_dim_156,bert_dim_157,bert_dim_158,bert_dim_159,bert_dim_160,bert_dim_161,bert_dim_162,bert_dim_163,bert_dim_164,bert_dim_165,bert_dim_166,bert_dim_167,bert_dim_168,bert_dim_169,bert_dim_170,bert_dim_171,bert_dim_172,bert_dim_173,bert_dim_174,bert_dim_175,bert_dim_176,bert_dim_177,bert_dim_178,bert_dim_179,bert_dim_180,bert_dim_181,bert_dim_182,bert_dim_183,bert_dim_184,bert_dim_185,bert_dim_186,bert_dim_187,bert_dim_188,bert_dim_189,bert_dim_190,bert_dim_191,bert_dim_192,bert_dim_193,bert_dim_194,bert_dim_195,bert_dim_196,bert_dim_197,bert_dim_198,bert_dim_199,bert_dim_200,bert_dim_201,bert_dim_202,bert_dim_203,bert_dim_204,bert_dim_205,bert_dim_206,bert_dim_207,bert_dim_208,bert_dim_209,bert_dim_210,bert_dim_211,bert_dim_212,bert_dim_213,bert_dim_214,bert_dim_215,bert_dim_216,bert_dim_217,bert_dim_218,bert_dim_219,bert_dim_220,bert_dim_221,bert_dim_222,bert_dim_223,bert_dim_224,bert_dim_225,bert_dim_226,bert_dim_227,bert_dim_228,bert_dim_229,bert_dim_230,bert_dim_231,bert_dim_232,bert_dim_233,bert_dim_234,bert_dim_235,bert_dim_236,bert_dim_237,bert_dim_238,bert_dim_239,bert_dim_240,bert_dim_241,bert_dim_242,bert_dim_243,bert_dim_244,bert_dim_245,bert_dim_246,bert_dim_247,bert_dim_248,bert_dim_249,bert_dim_250,bert_dim_251,bert_dim_252,bert_dim_253,bert_dim_254,bert_dim_255,bert_dim_256,bert_dim_257,bert_dim_258,bert_dim_259,bert_dim_260,bert_dim_261,bert_dim_262,bert_dim_263,bert_dim_264,bert_dim_265,bert_dim_266,bert_dim_267,bert_dim_268,bert_dim_269,bert_dim_270,bert_dim_271,bert_dim_272,bert_dim_273,bert_dim_274,bert_dim_275,bert_dim_276,bert_dim_277,bert_dim_278,bert_dim_279,bert_dim_280,bert_dim_281,bert_dim_282,bert_dim_283,bert_dim_284,bert_dim_285,bert_dim_286,bert_dim_287,bert_dim_288,bert_dim_289,bert_dim_290,bert_dim_291,bert_dim_292,bert_dim_293,bert_dim_294,bert_dim_295,bert_dim_296,bert_dim_297,bert_dim_298,bert_dim_299,bert_dim_300,bert_dim_301,bert_dim_302,bert_dim_303,bert_dim_304,bert_dim_305,bert_dim_306,bert_dim_307,bert_dim_308,bert_dim_309,bert_dim_310,bert_dim_311,bert_dim_312,bert_dim_313,bert_dim_314,bert_dim_315,bert_dim_316,bert_dim_317,bert_dim_318,bert_dim_319,bert_dim_320,bert_dim_321,bert_dim_322,bert_dim_323,bert_dim_324,bert_dim_325,bert_dim_326,bert_dim_327,bert_dim_328,bert_dim_329,bert_dim_330,bert_dim_331,bert_dim_332,bert_dim_333,bert_dim_334,bert_dim_335,bert_dim_336,bert_dim_337,bert_dim_338,bert_dim_339,bert_dim_340,bert_dim_341,bert_dim_342,bert_dim_343,bert_dim_344,bert_dim_345,bert_dim_346,bert_dim_347,bert_dim_348,bert_dim_349,bert_dim_350,bert_dim_351,bert_dim_352,bert_dim_353,bert_dim_354,bert_dim_355,bert_dim_356,bert_dim_357,bert_dim_358,bert_dim_359,bert_dim_360,bert_dim_361,bert_dim_362,bert_dim_363,bert_dim_364,bert_dim_365,bert_dim_366,bert_dim_367,bert_dim_368,bert_dim_369,bert_dim_370,bert_dim_371,bert_dim_372,bert_dim_373,bert_dim_374,bert_dim_375,bert_dim_376,bert_dim_377,bert_dim_378,bert_dim_379,bert_dim_380,bert_dim_381,bert_dim_382,bert_dim_383,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,spelling_errors,grammar_errors,linsear_write_formula,ari_score,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,topic,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199

In [33]:
from sklearn.model_selection import train_test_split

# Features and target variable
X = train_df.drop('score', axis=1)
y = train_df['score']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

In [34]:
X_train.head()

,essay_id,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,pos_ADJ_count,pos_NOUN_count,pos_VERB_count,pos_SCONJ_count,pos_PRON_count,pos_PUNCT_count,pos_DET_count,pos_AUX_count,pos_PART_count,pos_ADP_count,pos_SPACE_count,pos_CCONJ_count,pos_PROPN_count,pos_NUM_count,pos_ADV_count,pos_SYM_count,pos_ADJ_ratio,pos_NOUN_ratio,pos_VERB_ratio,pos_SCONJ_ratio,pos_PRON_ratio,pos_PUNCT_ratio,pos_DET_ratio,pos_AUX_ratio,pos_PART_ratio,pos_ADP_ratio,pos_SPACE_ratio,pos_CCONJ_ratio,pos_PROPN_ratio,pos_NUM_ratio,pos_ADV_ratio,pos_SYM_ratio,pos_INTJ_count,pos_INTJ_ratio,pos_X_count,pos_X_ratio,ner_GPE_count,ner_PERCENT_count,ner_NORP_count,ner_ORG_count,ner_CARDINAL_count,ner_MONEY_count,ner_DATE_count,ner_LOC_count,ner_PERSON_count,ner_QUANTITY_count,ner_EVENT_count,ner_GPE_ratio,ner_PERCENT_ratio,ner_NORP_ratio,ner_ORG_ratio,ner_CARDINAL_ratio,ner_MONEY_ratio,ner_DATE_ratio,ner_LOC_ratio,ner_PERSON_ratio,ner_QUANTITY_ratio,ner_EVENT_ratio,ner_ORDINAL_count,ner_ORDINAL_ratio,ner_WORK_OF_ART_count,ner_WORK_OF_ART_ratio,ner_LAW_count,ner_LAW_ratio,ner_PRODUCT_count,ner_PRODUCT_ratio,ner_TIME_count,ner_TIME_ratio,ner_FAC_count,ner_FAC_ratio,ner_LANGUAGE_count,ner_LANGUAGE_ratio,dep_amod_count,dep_nsubj_count,dep_ROOT_count,dep_dobj_count,dep_advmod_count,dep_relcl_count,dep_punct_count,dep_det_count,dep_aux_count,dep_neg_count,dep_mark_count,dep_csubj_count,dep_compound_count,dep_prep_count,dep_pobj_count,dep_ccomp_count,dep_dep_count,dep_advcl_count,dep_cc_count,dep_acomp_count,dep_attr_count,dep_appos_count,dep_conj_count,dep_nummod_count,dep_poss_count,dep_case_count,dep_nsubjpass_count,dep_nmod_count,dep_auxpass_count,dep_npadvmod_count,dep_expl_count,dep_xcomp_count,dep_dative_count,dep_oprd_count,dep_acl_count,dep_quantmod_count,dep_pcomp_count,dep_amod_ratio,dep_nsubj_ratio,dep_ROOT_ratio,dep_dobj_ratio,dep_advmod_ratio,dep_relcl_ratio,dep_punct_ratio,dep_det_ratio,dep_aux_ratio,dep_neg_ratio,dep_mark_ratio,dep_csubj_ratio,dep_compound_ratio,dep_prep_ratio,dep_pobj_ratio,dep_ccomp_ratio,dep_dep_ratio,dep_advcl_ratio,dep_cc_ratio,dep_acomp_ratio,dep_attr_ratio,dep_appos_ratio,dep_conj_ratio,dep_nummod_ratio,dep_poss_ratio,dep_case_ratio,dep_nsubjpass_ratio,dep_nmod_ratio,dep_auxpass_ratio,dep_npadvmod_ratio,dep_expl_ratio,dep_xcomp_ratio,dep_dative_ratio,dep_oprd_ratio,dep_acl_ratio,dep_quantmod_ratio,dep_pcomp_ratio,dep_agent_count,dep_intj_count,dep_predet_count,dep_prt_count,dep_agent_ratio,dep_intj_ratio,dep_predet_ratio,dep_prt_ratio,dep_meta_count,dep_meta_ratio,dep_preconj_count,dep_preconj_ratio,dep_parataxis_count,dep_parataxis_ratio,dep_csubjpass_count,dep_csubjpass_ratio,verb_tense_consistency,passive_voice_usage,modal_verb_usage,lexical_diversity,dale_chall_readability,automated_readability_index,coleman_liau_index,conjunction_usage,clause_density,vader_compound,vader_positive,vader_negative,vader_neutral,bert_dim_0,bert_dim_1,bert_dim_2,bert_dim_3,bert_dim_4,bert_dim_5,bert_dim_6,bert_dim_7,bert_dim_8,bert_dim_9,bert_dim_10,bert_dim_11,bert_dim_12,bert_dim_13,bert_dim_14,bert_dim_15,bert_dim_16,bert_dim_17,bert_dim_18,bert_dim_19,bert_dim_20,bert_dim_21,bert_dim_22,bert_dim_23,bert_dim_24,bert_dim_25,bert_dim_26,bert_dim_27,bert_dim_28,bert_dim_29,bert_dim_30,bert_dim_31,bert_dim_32,bert_dim_33,bert_dim_34,bert_dim_35,bert_dim_36,bert_dim_37,bert_dim_38,bert_dim_39,bert_dim_40,bert_dim_41,bert_dim_42,bert_dim_43,bert_dim_44,bert_dim_45,bert_dim_46,bert_dim_47,bert_dim_48,bert_dim_49,bert_dim_50,bert_dim_51,bert_dim_52,bert_dim_53,bert_dim_54,bert_dim_55,bert_dim_56,bert_dim_57,bert_dim_58,bert_dim_59,bert_dim_60,bert_dim_61,bert_dim_62,bert_dim_63,bert_dim_64,bert_dim_65,bert_dim_66,bert_dim_67,bert_dim_68,bert_dim_69,bert_dim_70,bert_dim_71,bert_dim_72,bert_dim_73,bert_dim_74,bert_dim_75,bert_dim_76,bert_dim_77,bert_dim_78,bert_dim_79,bert_dim_80,bert_dim_81,bert_dim_82,bert_dim_83,bert_dim_84,bert_dim_85,bert_dim_86,bert_dim_87,bert_dim_88,bert_dim_89,bert_dim_90,bert_dim_91,bert_dim_92,bert_dim_93,bert_dim_94,bert_dim_95,bert_dim_96,bert_dim_97,bert_dim_98,bert_dim_99,bert_dim_100,bert_dim_101,bert_dim_102,bert_dim_103,bert_dim_104,bert_dim_105,bert_dim_106,bert_dim_107,bert_dim_108,bert_dim_109,bert_dim_110,bert_dim_111,bert_dim_112,bert_dim_113,bert_dim_114,bert_dim_115,bert_dim_116,bert_dim_117,bert_dim_118,bert_dim_119,bert_dim_120,bert_dim_121,bert_dim_122,bert_dim_123,bert_dim_124,bert_dim_125,bert_dim_126,bert_dim_127,bert_dim_128,bert_dim_129,bert_dim_130,bert_dim_131,bert_dim_132,bert_dim_133,bert_dim_134,bert_dim_135,bert_dim_136,bert_dim_137,bert_dim_138,bert_dim_139,bert_dim_140,bert_dim_141,bert_dim_142,bert_dim_143,bert_dim_144,bert_dim_145,bert_dim_146,bert_dim_147,bert_dim_148,bert_dim_149,bert_dim_150,bert_dim_151,bert_dim_152,bert_dim_153,bert_dim_154,bert_dim_155,bert_dim_156,bert_dim_157,bert_dim_158,bert_dim_159,bert_dim_160,bert_dim_161,bert_dim_162,bert_dim_163,bert_dim_164,bert_dim_165,bert_dim_166,bert_dim_167,bert_dim_168,bert_dim_169,bert_dim_170,bert_dim_171,bert_dim_172,bert_dim_173,bert_dim_174,bert_dim_175,bert_dim_176,bert_dim_177,bert_dim_178,bert_dim_179,bert_dim_180,bert_dim_181,bert_dim_182,bert_dim_183,bert_dim_184,bert_dim_185,bert_dim_186,bert_dim_187,bert_dim_188,bert_dim_189,bert_dim_190,bert_dim_191,bert_dim_192,bert_dim_193,bert_dim_194,bert_dim_195,bert_dim_196,bert_dim_197,bert_dim_198,bert_dim_199,bert_dim_200,bert_dim_201,bert_dim_202,bert_dim_203,bert_dim_204,bert_dim_205,bert_dim_206,bert_dim_207,bert_dim_208,bert_dim_209,bert_dim_210,bert_dim_211,bert_dim_212,bert_dim_213,bert_dim_214,bert_dim_215,bert_dim_216,bert_dim_217,bert_dim_218,bert_dim_219,bert_dim_220,bert_dim_221,bert_dim_222,bert_dim_223,bert_dim_224,bert_dim_225,bert_dim_226,bert_dim_227,bert_dim_228,bert_dim_229,bert_dim_230,bert_dim_231,bert_dim_232,bert_dim_233,bert_dim_234,bert_dim_235,bert_dim_236,bert_dim_237,bert_dim_238,bert_dim_239,bert_dim_240,bert_dim_241,bert_dim_242,bert_dim_243,bert_dim_244,bert_dim_245,bert_dim_246,bert_dim_247,bert_dim_248,bert_dim_249,bert_dim_250,bert_dim_251,bert_dim_252,bert_dim_253,bert_dim_254,bert_dim_255,bert_dim_256,bert_dim_257,bert_dim_258,bert_dim_259,bert_dim_260,bert_dim_261,bert_dim_262,bert_dim_263,bert_dim_264,bert_dim_265,bert_dim_266,bert_dim_267,bert_dim_268,bert_dim_269,bert_dim_270,bert_dim_271,bert_dim_272,bert_dim_273,bert_dim_274,bert_dim_275,bert_dim_276,bert_dim_277,bert_dim_278,bert_dim_279,bert_dim_280,bert_dim_281,bert_dim_282,bert_dim_283,bert_dim_284,bert_dim_285,bert_dim_286,bert_dim_287,bert_dim_288,bert_dim_289,bert_dim_290,bert_dim_291,bert_dim_292,bert_dim_293,bert_dim_294,bert_dim_295,bert_dim_296,bert_dim_297,bert_dim_298,bert_dim_299,bert_dim_300,bert_dim_301,bert_dim_302,bert_dim_303,bert_dim_304,bert_dim_305,bert_dim_306,bert_dim_307,bert_dim_308,bert_dim_309,bert_dim_310,bert_dim_311,bert_dim_312,bert_dim_313,bert_dim_314,bert_dim_315,bert_dim_316,bert_dim_317,bert_dim_318,bert_dim_319,bert_dim_320,bert_dim_321,bert_dim_322,bert_dim_323,bert_dim_324,bert_dim_325,bert_dim_326,bert_dim_327,bert_dim_328,bert_dim_329,bert_dim_330,bert_dim_331,bert_dim_332,bert_dim_333,bert_dim_334,bert_dim_335,bert_dim_336,bert_dim_337,bert_dim_338,bert_dim_339,bert_dim_340,bert_dim_341,bert_dim_342,bert_dim_343,bert_dim_344,bert_dim_345,bert_dim_346,bert_dim_347,bert_dim_348,bert_dim_349,bert_dim_350,bert_dim_351,bert_dim_352,bert_dim_353,bert_dim_354,bert_dim_355,bert_dim_356,bert_dim_357,bert_dim_358,bert_dim_359,bert_dim_360,bert_dim_361,bert_dim_362,bert_dim_363,bert_dim_364,bert_dim_365,bert_dim_366,bert_dim_367,bert_dim_368,bert_dim_369,bert_dim_370,bert_dim_371,bert_dim_372,bert_dim_373,bert_dim_374,bert_dim_375,bert_dim_376,bert_dim_377,bert_dim_378,bert_dim_379,bert_dim_380,bert_dim_381,bert_dim_382,bert_dim_383,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,spelling_errors,grammar_errors,linsear_write_formula,ari_score,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,topic,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199

In [35]:
y_train.value_counts()

score
3    4396
2    3306
4    2748
1     876
5     679
6     109
Name: count, dtype: int64

In [36]:
feature_cols = []

for col in X_train.columns:
    if (col != 'essay_id') and (col != 'score'):
        feature_cols.append(col)

In [37]:
pd.set_option('display.max_columns', None)
feature_cols

['paragraph_count',
 'sentence_count',
 'word_count',
 'avg_paragraph_length',
 'max_paragraph_length',
 'min_paragraph_length',
 'avg_sentence_length',
 'max_sentence_length',
 'min_sentence_length',
 'avg_word_length',
 'max_word_length',
 'flesch_reading_ease',
 'gunning_fog_index',
 'sentiment_score',
 'deberta_prob_0',
 'deberta_prob_1',
 'deberta_prob_2',
 'deberta_prob_3',
 'deberta_prob_4',
 'deberta_prob_5',
 'xlnet_prob_0',
 'xlnet_prob_1',
 'xlnet_prob_2',
 'xlnet_prob_3',
 'xlnet_prob_4',
 'xlnet_prob_5',
 'pos_ADJ_count',
 'pos_NOUN_count',
 'pos_VERB_count',
 'pos_SCONJ_count',
 'pos_PRON_count',
 'pos_PUNCT_count',
 'pos_DET_count',
 'pos_AUX_count',
 'pos_PART_count',
 'pos_ADP_count',
 'pos_SPACE_count',
 'pos_CCONJ_count',
 'pos_PROPN_count',
 'pos_NUM_count',
 'pos_ADV_count',
 'pos_SYM_count',
 'pos_ADJ_ratio',
 'pos_NOUN_ratio',
 'pos_VERB_ratio',
 'pos_SCONJ_ratio',
 'pos_PRON_ratio',
 'pos_PUNCT_ratio',
 'pos_DET_ratio',
 'pos_AUX_ratio',
 'pos_PART_ratio',
 'pos_ADP_ratio',
 'pos_SPACE_ratio',
 'pos_CCONJ_ratio',
 'pos_PROPN_ratio',
 'pos_NUM_ratio',
 'pos_ADV_ratio',
 'pos_SYM_ratio',
 'pos_INTJ_count',
 'pos_INTJ_ratio',
 'pos_X_count',
 'pos_X_ratio',
 'ner_GPE_count',
 'ner_PERCENT_count',
 'ner_NORP_count',
 'ner_ORG_count',
 'ner_CARDINAL_count',
 'ner_MONEY_count',
 'ner_DATE_count',
 'ner_LOC_count',
 'ner_PERSON_count',
 'ner_QUANTITY_count',
 'ner_EVENT_count',
 'ner_GPE_ratio',
 'ner_PERCENT_ratio',
 'ner_NORP_ratio',
 'ner_ORG_ratio',
 'ner_CARDINAL_ratio',
 'ner_MONEY_ratio',
 'ner_DATE_ratio',
 'ner_LOC_ratio',
 'ner_PERSON_ratio',
 'ner_QUANTITY_ratio',
 'ner_EVENT_ratio',
 'ner_ORDINAL_count',
 'ner_ORDINAL_ratio',
 'ner_WORK_OF_ART_count',
 'ner_WORK_OF_ART_ratio',
 'ner_LAW_count',
 'ner_LAW_ratio',
 'ner_PRODUCT_count',
 'ner_PRODUCT_ratio',
 'ner_TIME_count',
 'ner_TIME_ratio',
 'ner_FAC_count',
 'ner_FAC_ratio',
 'ner_LANGUAGE_count',
 'ner_LANGUAGE_ratio',
 'dep_amod_count',
 'dep_nsubj_count',
 'dep_ROOT_count',
 'dep_dobj_count',
 'dep_advmod_count',
 'dep_relcl_count',
 'dep_punct_count',
 'dep_det_count',
 'dep_aux_count',
 'dep_neg_count',
 'dep_mark_count',
 'dep_csubj_count',
 'dep_compound_count',
 'dep_prep_count',
 'dep_pobj_count',
 'dep_ccomp_count',
 'dep_dep_count',
 'dep_advcl_count',
 'dep_cc_count',
 'dep_acomp_count',
 'dep_attr_count',
 'dep_appos_count',
 'dep_conj_count',
 'dep_nummod_count',
 'dep_poss_count',
 'dep_case_count',
 'dep_nsubjpass_count',
 'dep_nmod_count',
 'dep_auxpass_count',
 'dep_npadvmod_count',
 'dep_expl_count',
 'dep_xcomp_count',
 'dep_dative_count',
 'dep_oprd_count',
 'dep_acl_count',
 'dep_quantmod_count',
 'dep_pcomp_count',
 'dep_amod_ratio',
 'dep_nsubj_ratio',
 'dep_ROOT_ratio',
 'dep_dobj_ratio',
 'dep_advmod_ratio',
 'dep_relcl_ratio',
 'dep_punct_ratio',
 'dep_det_ratio',
 'dep_aux_ratio',
 'dep_neg_ratio',
 'dep_mark_ratio',
 'dep_csubj_ratio',
 'dep_compound_ratio',
 'dep_prep_ratio',
 'dep_pobj_ratio',
 'dep_ccomp_ratio',
 'dep_dep_ratio',
 'dep_advcl_ratio',
 'dep_cc_ratio',
 'dep_acomp_ratio',
 'dep_attr_ratio',
 'dep_appos_ratio',
 'dep_conj_ratio',
 'dep_nummod_ratio',
 'dep_poss_ratio',
 'dep_case_ratio',
 'dep_nsubjpass_ratio',
 'dep_nmod_ratio',
 'dep_auxpass_ratio',
 'dep_npadvmod_ratio',
 'dep_expl_ratio',
 'dep_xcomp_ratio',
 'dep_dative_ratio',
 'dep_oprd_ratio',
 'dep_acl_ratio',
 'dep_quantmod_ratio',
 'dep_pcomp_ratio',
 'dep_agent_count',
 'dep_intj_count',
 'dep_predet_count',
 'dep_prt_count',
 'dep_agent_ratio',
 'dep_intj_ratio',
 'dep_predet_ratio',
 'dep_prt_ratio',
 'dep_meta_count',
 'dep_meta_ratio',
 'dep_preconj_count',
 'dep_preconj_ratio',
 'dep_parataxis_count',
 'dep_parataxis_ratio',
 'dep_csubjpass_count',
 'dep_csubjpass_ratio',
 'verb_tense_consistency',
 'passive_voice_usage',
 'modal_verb_usage',
 'lexical_diversity',
 'dale_chall_readability',
 'automated_readability_index',
 'coleman_liau_index',
 'conjunction_usage',
 'clause_density',
 'vader_compound',
 'vader_positive',
 'vader_negative',
 'vader_neutral',
 'bert_dim_0',
 'bert_dim_1',
 'bert_dim_2',
 'bert_dim_3',
 'bert_dim_4',
 'bert_dim_5',
 'bert_dim_6',
 'bert_dim_7',
 'bert_dim_8',
 'bert_dim_9',
 'bert_dim_10',
 'bert_dim_11',
 'bert_dim_12',
 'bert_dim_13',
 'bert_dim_14',
 'bert_dim_15',
 'bert_dim_16',
 'bert_dim_17',
 'bert_dim_18',
 'bert_dim_19',
 'bert_dim_20',
 'bert_dim_21',
 'bert_dim_22',
 'bert_dim_23',
 'bert_dim_24',
 'bert_dim_25',
 'bert_dim_26',
 'bert_dim_27',
 'bert_dim_28',
 'bert_dim_29',
 'bert_dim_30',
 'bert_dim_31',
 'bert_dim_32',
 'bert_dim_33',
 'bert_dim_34',
 'bert_dim_35',
 'bert_dim_36',
 'bert_dim_37',
 'bert_dim_38',
 'bert_dim_39',
 'bert_dim_40',
 'bert_dim_41',
 'bert_dim_42',
 'bert_dim_43',
 'bert_dim_44',
 'bert_dim_45',
 'bert_dim_46',
 'bert_dim_47',
 'bert_dim_48',
 'bert_dim_49',
 'bert_dim_50',
 'bert_dim_51',
 'bert_dim_52',
 'bert_dim_53',
 'bert_dim_54',
 'bert_dim_55',
 'bert_dim_56',
 'bert_dim_57',
 'bert_dim_58',
 'bert_dim_59',
 'bert_dim_60',
 'bert_dim_61',
 'bert_dim_62',
 'bert_dim_63',
 'bert_dim_64',
 'bert_dim_65',
 'bert_dim_66',
 'bert_dim_67',
 'bert_dim_68',
 'bert_dim_69',
 'bert_dim_70',
 'bert_dim_71',
 'bert_dim_72',
 'bert_dim_73',
 'bert_dim_74',
 'bert_dim_75',
 'bert_dim_76',
 'bert_dim_77',
 'bert_dim_78',
 'bert_dim_79',
 'bert_dim_80',
 'bert_dim_81',
 'bert_dim_82',
 'bert_dim_83',
 'bert_dim_84',
 'bert_dim_85',
 'bert_dim_86',
 'bert_dim_87',
 'bert_dim_88',
 'bert_dim_89',
 'bert_dim_90',
 'bert_dim_91',
 'bert_dim_92',
 'bert_dim_93',
 'bert_dim_94',
 'bert_dim_95',
 'bert_dim_96',
 'bert_dim_97',
 'bert_dim_98',
 'bert_dim_99',
 'bert_dim_100',
 'bert_dim_101',
 'bert_dim_102',
 'bert_dim_103',
 'bert_dim_104',
 'bert_dim_105',
 'bert_dim_106',
 'bert_dim_107',
 'bert_dim_108',
 'bert_dim_109',
 'bert_dim_110',
 'bert_dim_111',
 'bert_dim_112',
 'bert_dim_113',
 'bert_dim_114',
 'bert_dim_115',
 'bert_dim_116',
 'bert_dim_117',
 'bert_dim_118',
 'bert_dim_119',
 'bert_dim_120',
 'bert_dim_121',
 'bert_dim_122',
 'bert_dim_123',
 'bert_dim_124',
 'bert_dim_125',
 'bert_dim_126',
 'bert_dim_127',
 'bert_dim_128',
 'bert_dim_129',
 'bert_dim_130',
 'bert_dim_131',
 'bert_dim_132',
 'bert_dim_133',
 'bert_dim_134',
 'bert_dim_135',
 'bert_dim_136',
 'bert_dim_137',
 'bert_dim_138',
 'bert_dim_139',
 'bert_dim_140',
 'bert_dim_141',
 'bert_dim_142',
 'bert_dim_143',
 'bert_dim_144',
 'bert_dim_145',
 'bert_dim_146',
 'bert_dim_147',
 'bert_dim_148',
 'bert_dim_149',
 'bert_dim_150',
 'bert_dim_151',
 'bert_dim_152',
 'bert_dim_153',
 'bert_dim_154',
 'bert_dim_155',
 'bert_dim_156',
 'bert_dim_157',
 'bert_dim_158',
 'bert_dim_159',
 'bert_dim_160',
 'bert_dim_161',
 'bert_dim_162',
 'bert_dim_163',
 'bert_dim_164',
 'bert_dim_165',
 'bert_dim_166',
 'bert_dim_167',
 'bert_dim_168',
 'bert_dim_169',
 'bert_dim_170',
 'bert_dim_171',
 'bert_dim_172',
 'bert_dim_173',
 'bert_dim_174',
 'bert_dim_175',
 'bert_dim_176',
 'bert_dim_177',
 'bert_dim_178',
 'bert_dim_179',
 'bert_dim_180',
 'bert_dim_181',
 'bert_dim_182',
 'bert_dim_183',
 'bert_dim_184',
 'bert_dim_185',
 'bert_dim_186',
 'bert_dim_187',
 'bert_dim_188',
 'bert_dim_189',
 'bert_dim_190',
 'bert_dim_191',
 'bert_dim_192',
 'bert_dim_193',
 'bert_dim_194',
 'bert_dim_195',
 'bert_dim_196',
 'bert_dim_197',
 'bert_dim_198',
 'bert_dim_199',
 'bert_dim_200',
 'bert_dim_201',
 'bert_dim_202',
 'bert_dim_203',
 'bert_dim_204',
 'bert_dim_205',
 'bert_dim_206',
 'bert_dim_207',
 'bert_dim_208',
 'bert_dim_209',
 'bert_dim_210',
 'bert_dim_211',
 'bert_dim_212',
 'bert_dim_213',
 'bert_dim_214',
 'bert_dim_215',
 'bert_dim_216',
 'bert_dim_217',
 'bert_dim_218',
 'bert_dim_219',
 'bert_dim_220',
 'bert_dim_221',
 'bert_dim_222',
 'bert_dim_223',
 'bert_dim_224',
 'bert_dim_225',
 'bert_dim_226',
 'bert_dim_227',
 'bert_dim_228',
 'bert_dim_229',
 'bert_dim_230',
 'bert_dim_231',
 'bert_dim_232',
 'bert_dim_233',
 'bert_dim_234',
 'bert_dim_235',
 'bert_dim_236',
 'bert_dim_237',
 'bert_dim_238',
 'bert_dim_239',
 'bert_dim_240',
 'bert_dim_241',
 'bert_dim_242',
 'bert_dim_243',
 'bert_dim_244',
 'bert_dim_245',
 'bert_dim_246',
 'bert_dim_247',
 'bert_dim_248',
 'bert_dim_249',
 'bert_dim_250',
 'bert_dim_251',
 'bert_dim_252',
 'bert_dim_253',
 'bert_dim_254',
 'bert_dim_255',
 'bert_dim_256',
 'bert_dim_257',
 'bert_dim_258',
 'bert_dim_259',
 'bert_dim_260',
 'bert_dim_261',
 'bert_dim_262',
 'bert_dim_263',
 'bert_dim_264',
 'bert_dim_265',
 'bert_dim_266',
 'bert_dim_267',
 'bert_dim_268',
 'bert_dim_269',
 'bert_dim_270',
 'bert_dim_271',
 'bert_dim_272',
 'bert_dim_273',
 'bert_dim_274',
 'bert_dim_275',
 'bert_dim_276',
 'bert_dim_277',
 'bert_dim_278',
 'bert_dim_279',
 'bert_dim_280',
 'bert_dim_281',
 'bert_dim_282',
 'bert_dim_283',
 'bert_dim_284',
 'bert_dim_285',
 'bert_dim_286',
 'bert_dim_287',
 'bert_dim_288',
 'bert_dim_289',
 'bert_dim_290',
 'bert_dim_291',
 'bert_dim_292',
 'bert_dim_293',
 'bert_dim_294',
 'bert_dim_295',
 'bert_dim_296',
 'bert_dim_297',
 'bert_dim_298',
 'bert_dim_299',
 'bert_dim_300',
 'bert_dim_301',
 'bert_dim_302',
 'bert_dim_303',
 'bert_dim_304',
 'bert_dim_305',
 'bert_dim_306',
 'bert_dim_307',
 'bert_dim_308',
 'bert_dim_309',
 'bert_dim_310',
 'bert_dim_311',
 'bert_dim_312',
 'bert_dim_313',
 'bert_dim_314',
 'bert_dim_315',
 'bert_dim_316',
 'bert_dim_317',
 'bert_dim_318',
 'bert_dim_319',
 'bert_dim_320',
 'bert_dim_321',
 'bert_dim_322',
 'bert_dim_323',
 'bert_dim_324',
 'bert_dim_325',
 'bert_dim_326',
 'bert_dim_327',
 'bert_dim_328',
 'bert_dim_329',
 'bert_dim_330',
 'bert_dim_331',
 'bert_dim_332',
 'bert_dim_333',
 'bert_dim_334',
 'bert_dim_335',
 'bert_dim_336',
 'bert_dim_337',
 'bert_dim_338',
 'bert_dim_339',
 'bert_dim_340',
 'bert_dim_341',
 'bert_dim_342',
 'bert_dim_343',
 'bert_dim_344',
 'bert_dim_345',
 'bert_dim_346',
 'bert_dim_347',
 'bert_dim_348',
 'bert_dim_349',
 'bert_dim_350',
 'bert_dim_351',
 'bert_dim_352',
 'bert_dim_353',
 'bert_dim_354',
 'bert_dim_355',
 'bert_dim_356',
 'bert_dim_357',
 'bert_dim_358',
 'bert_dim_359',
 'bert_dim_360',
 'bert_dim_361',
 'bert_dim_362',
 'bert_dim_363',
 'bert_dim_364',
 'bert_dim_365',
 'bert_dim_366',
 'bert_dim_367',
 'bert_dim_368',
 'bert_dim_369',
 'bert_dim_370',
 'bert_dim_371',
 'bert_dim_372',
 'bert_dim_373',
 'bert_dim_374',
 'bert_dim_375',
 'bert_dim_376',
 'bert_dim_377',
 'bert_dim_378',
 'bert_dim_379',
 'bert_dim_380',
 'bert_dim_381',
 'bert_dim_382',
 'bert_dim_383',
 'topic_0',
 'topic_1',
 'topic_2',
 'topic_3',
 'topic_4',
 'topic_5',
 'topic_6',
 'topic_7',
 'topic_8',
 'topic_9',
 'spelling_errors',
 'grammar_errors',
 'linsear_write_formula',
 'ari_score',
 '000',
 '12',
 '1976',
 '1998',
 '2000',
 '2001',
 '25',
 '30',
 '44',
 '50',
 '60',
 '800',
 '800 degrees',
 '800 degrees fahrenheit',
 '90',
 '90 times',
 '90 times greater',
 '97',
 '97 percent',
 '97 percent carbon',
 'ability',
 'able',
 'accident',
 'accidents',
 'according',
 'acid',
 'action',
 'action coding',
 'actually',
 'ad',
 'advanced',
 'advantage',
 'advantages',
 'ago',
 'agree',
 'ahead',
 'air',
 'air pollution',
 'alert',
 'alien',
 'alien monument',
 'aliens',
 'allow',
 'allowed',
 'allows',
 'alot',
 'amazing',
 'america',
 'american',
 'american west',
 'americans',
 'anger',
 'angry',
 'animals',
 'answer',
 'anymore',
 'april',
 'area',
 'areas',
 'aren',
 'argue',
 'argument',
 'article',
 'article says',
 'article states',
 'artifact',
 'ask',
 'aspects',
 'astronomers',
 'atmosphere',
 'atmosphere 97',
 'atmospheric',
 'atmospheric pressure',
 'attention',
 'author',
 'author states',
 'author supports',
 'average',
 'average 800',
 'avoid',
 'aware',
 'away',
 'bad',
 'ban',
 'banned',
 'based',
 'basic',
 'basically',
 'becuase',
 'begin',
 'believe',
 'belive',
 'beneficial',
 'benefit',
 'benefits',
 'best',
 'better',
 'big',
 'bigger',
 'bike',
 'bit',
 'blame',
 'board',
 'boat',
 'bogota',
 'bored',
 'bring',
 'built',
 'bus',
 'buses',
 'butte',
 'butte mesa',
 'buy',
 'buying',
 'called',
 'came',
 'camera',
 'cameras',
 'campaign',
 'candidate',
 'candidates',
 'canidate',
 'car',
 'car drive',
 'car free',
 'car free day',
 'car usage',
 'car use',
 'carbon',
 'carbon dioxide',
 'care',
 'cars',
 'cars coming',
 'cars drive',
 'cars good',
 'cars people',
 'case',
 'cattle',
 'cause',
 'caused',
 'causes',
 'causing',
 'certain',
 'challenge',
 'challenge exploring',
 'challenge exploring venus',
 'challenges',
 'challenging',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'children',
 'china',
 'choice',
 'choose',
 'cities',
 'citizens',
 'city',
 'claim',
 'class',
 'classroom',
 'classroom computer',
 'classroom computer recognize',
 'classrooms',
 'clear',
 'clearly',
 'close',
 'closer',
 'closest',
 'closest planet',
 'clouds',
 'coding',
 'college',
 'college unfair',
 'colombia',
 'columbia',
 'come',
 'comes',
 'coming',
 'common',
 'communication',
 'community',
 'companies',
 'company',
 'compared',
 'completely',
 'computer',
 'computer recognize',
 'computer recognize student',
 'computers',
 'conclusion',
 'conditions',
 'confused',
 'confused bored',
 'congress',
 'continue',
 'control',
 'cool',
 'corrosive',
 'cost',
 'couldn',
 'countries',
 'country',
 'couple',
 'course',
 'covered',
 'cowboy',
 'cowboys',
 'cowboys program',
 'crash',
 'crashes',
 'craters',
 'create',
 'created',
 'created aliens',
 'creating',
 'curiosity',
 'cut',
 'cydonia',
 'danger',
 'dangerous',
 'dangers',
 'dangers presents',
 'day',
 'days',
 'dear',
 'decades',
 'decide',
 'decrease',
 'degrees',
 'degrees fahrenheit',
 'democratic',
 'density',
 'density size',
 'despite',
 'despite dangers',
 'despite dangers presents',
 'detect',
 'developed',
 'development',
 'did',
 'didn',
 'didnt',
 'diesel',
 'different',
 'difficult',
 'dioxide',
 'distance',
 'does',
 'doesn',
 'doesnt',
 'doing',
 'don',
 'don know',
 'don think',
 'dont',
 'dr',
 'dr huang',
 'drive',
 'driveless',
 'driveless cars',
 'driven',
 'driver',
 'driverless',
 'driverless car',
 'driverless cars',
 'driverless cars coming',
 'drivers',
 'driving',
 'driving car',
 'driving cars',
 'earth',
 'earth like',
 'earth like planet',
 'earth twin',
 'earth venus',
 'easier',
 'easily',
 'easy',
 'effect',
 'effective',
 'effective human',
 'elect',
 'elect president',
 'election',
 'election popular',
 'election popular vote',
 'elections',
 'electoral',
 'electoral college',
 'electoral college unfair',
 'electoral vote',
 'electoral votes',
 'electors',
 'electors vote',
 'electronics',
 'emissions',
 'emotion',
 'emotional',
 'emotional expressions',
 'emotions',
 'end',
 'enjoy',
 'enviroment',
 'environment',
 'especially',
 'europe',
 'everyday',
 'evidence',
 'exactly',
 'example',
 'expensive',
 'experience',
 'explain',
 'explains',
 'exploration',
 'explore',
 'explore venus',
 'exploring',
 'exploring venus',
 'expression',
 'expressions',
 'expressions students',
 'extreme',
 'extremely',
 'eyes',
 'face',
 'face just',
 'face mars',
 'faces',
 'facial',
 'facial action',
 'facial action coding',
 'facial expressions',
 'facial muscles',
 'facs',
 'fact',
 'factor',
 'facts',
 'fahrenheit',
 'fails',
 'fair',
 'family',
 'far',
 'fault',
 'favor',
 'fear',
 'features',
 'feel',
 'feel like',
 'feeling',
 'feelings',
 'fewer',
 'figure',
 'finally',
 'fine',
 'fix',
 'focus',
 'food',
 'form',
 'formation',
 'formed',
 'forms',
 'forms life',
 'france',
 'free',
 'free day',
 'friend',
 'friends',
 'fuel',
 'fully',
 'fun',
 'future',
 'games',
 'garvin',
 'gas',
 'gas emissions',
 'gases',
 'germany',
 'gets',
 'getting',
 'given',
 'gives',
 'giving',
 'global',
 'global surveyor',
 'goes',
 'going',
 'gone',
 'good',
 'good idea',
 'good thing',
 'google',
 'got',
 'government',
 'great',
 'greater',
 'greece',
 'greenhouse',
 ...]

In [38]:
print(f'Number of features: {len(feature_cols)}')

Number of features: 1799

In [39]:
# save the order of the column names to a txt file

with open(file_config['feature_cols'], 'w') as f:
    for item in feature_cols:
        f.write("%s\n" % item)

In [40]:
import sklearn
print(sklearn.__version__)

1.2.2

In [42]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pickle
import numpy as np

# Extract labels from the training and validation datasets
train_labels = y_train
val_labels = y_test

# Extract features for scaling
train_features = X_train[feature_cols] # Subset with only feature columns
val_features = X_test[feature_cols]

# Initialize the scaler
scaler = MinMaxScaler()  # Using StandardScaler for scaling

# Fit the scaler to the training features
scaler.fit(train_features)  # This defines the transformation based on the training data

# Transform training and validation features
train_feats_scaled = scaler.transform(train_features)  # Transforms the training data
val_feats_scaled = scaler.transform(val_features)  # Transforms the validation data

# Reassign the scaled features to the original DataFrames, keeping the same column names
X_train[feature_cols] = train_feats_scaled  # Replace the original features with scaled ones
X_test[feature_cols] = val_feats_scaled

# Save the scaler for later use
with open(file_config['scaler'], 'wb') as f:
    pickle.dump(scaler, f)  # Persist the scaler for future use or reference

In [43]:
# Check if the file has been written correctly and is not empty
import os

scaler_path = file_config['scaler']

if os.path.getsize(scaler_path) > 0:

    print(f"Scaler saved successfully in {scaler_path}.")
    
else:

    print(f"Failed to save scaler to {scaler_path}. File is empty.")

Scaler saved successfully in /home/jack/github/kaggle/scoring/model_data/sklearn/scaler.pkl.

In [44]:
# Check if the scaler is StandardScaler
if isinstance(scaler, StandardScaler):
    print("The scaler is a StandardScaler.")
elif isinstance(scaler, MinMaxScaler):
    print("The scaler is a MinMaxScaler.")
else:
    print("The scaler is neither StandardScaler nor MinMaxScaler.")

The scaler is a MinMaxScaler.

In [45]:
X_train.head()

,essay_id,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,pos_ADJ_count,pos_NOUN_count,pos_VERB_count,pos_SCONJ_count,pos_PRON_count,pos_PUNCT_count,pos_DET_count,pos_AUX_count,pos_PART_count,pos_ADP_count,pos_SPACE_count,pos_CCONJ_count,pos_PROPN_count,pos_NUM_count,pos_ADV_count,pos_SYM_count,pos_ADJ_ratio,pos_NOUN_ratio,pos_VERB_ratio,pos_SCONJ_ratio,pos_PRON_ratio,pos_PUNCT_ratio,pos_DET_ratio,pos_AUX_ratio,pos_PART_ratio,pos_ADP_ratio,pos_SPACE_ratio,pos_CCONJ_ratio,pos_PROPN_ratio,pos_NUM_ratio,pos_ADV_ratio,pos_SYM_ratio,pos_INTJ_count,pos_INTJ_ratio,pos_X_count,pos_X_ratio,ner_GPE_count,ner_PERCENT_count,ner_NORP_count,ner_ORG_count,ner_CARDINAL_count,ner_MONEY_count,ner_DATE_count,ner_LOC_count,ner_PERSON_count,ner_QUANTITY_count,ner_EVENT_count,ner_GPE_ratio,ner_PERCENT_ratio,ner_NORP_ratio,ner_ORG_ratio,ner_CARDINAL_ratio,ner_MONEY_ratio,ner_DATE_ratio,ner_LOC_ratio,ner_PERSON_ratio,ner_QUANTITY_ratio,ner_EVENT_ratio,ner_ORDINAL_count,ner_ORDINAL_ratio,ner_WORK_OF_ART_count,ner_WORK_OF_ART_ratio,ner_LAW_count,ner_LAW_ratio,ner_PRODUCT_count,ner_PRODUCT_ratio,ner_TIME_count,ner_TIME_ratio,ner_FAC_count,ner_FAC_ratio,ner_LANGUAGE_count,ner_LANGUAGE_ratio,dep_amod_count,dep_nsubj_count,dep_ROOT_count,dep_dobj_count,dep_advmod_count,dep_relcl_count,dep_punct_count,dep_det_count,dep_aux_count,dep_neg_count,dep_mark_count,dep_csubj_count,dep_compound_count,dep_prep_count,dep_pobj_count,dep_ccomp_count,dep_dep_count,dep_advcl_count,dep_cc_count,dep_acomp_count,dep_attr_count,dep_appos_count,dep_conj_count,dep_nummod_count,dep_poss_count,dep_case_count,dep_nsubjpass_count,dep_nmod_count,dep_auxpass_count,dep_npadvmod_count,dep_expl_count,dep_xcomp_count,dep_dative_count,dep_oprd_count,dep_acl_count,dep_quantmod_count,dep_pcomp_count,dep_amod_ratio,dep_nsubj_ratio,dep_ROOT_ratio,dep_dobj_ratio,dep_advmod_ratio,dep_relcl_ratio,dep_punct_ratio,dep_det_ratio,dep_aux_ratio,dep_neg_ratio,dep_mark_ratio,dep_csubj_ratio,dep_compound_ratio,dep_prep_ratio,dep_pobj_ratio,dep_ccomp_ratio,dep_dep_ratio,dep_advcl_ratio,dep_cc_ratio,dep_acomp_ratio,dep_attr_ratio,dep_appos_ratio,dep_conj_ratio,dep_nummod_ratio,dep_poss_ratio,dep_case_ratio,dep_nsubjpass_ratio,dep_nmod_ratio,dep_auxpass_ratio,dep_npadvmod_ratio,dep_expl_ratio,dep_xcomp_ratio,dep_dative_ratio,dep_oprd_ratio,dep_acl_ratio,dep_quantmod_ratio,dep_pcomp_ratio,dep_agent_count,dep_intj_count,dep_predet_count,dep_prt_count,dep_agent_ratio,dep_intj_ratio,dep_predet_ratio,dep_prt_ratio,dep_meta_count,dep_meta_ratio,dep_preconj_count,dep_preconj_ratio,dep_parataxis_count,dep_parataxis_ratio,dep_csubjpass_count,dep_csubjpass_ratio,verb_tense_consistency,passive_voice_usage,modal_verb_usage,lexical_diversity,dale_chall_readability,automated_readability_index,coleman_liau_index,conjunction_usage,clause_density,vader_compound,vader_positive,vader_negative,vader_neutral,bert_dim_0,bert_dim_1,bert_dim_2,bert_dim_3,bert_dim_4,bert_dim_5,bert_dim_6,bert_dim_7,bert_dim_8,bert_dim_9,bert_dim_10,bert_dim_11,bert_dim_12,bert_dim_13,bert_dim_14,bert_dim_15,bert_dim_16,bert_dim_17,bert_dim_18,bert_dim_19,bert_dim_20,bert_dim_21,bert_dim_22,bert_dim_23,bert_dim_24,bert_dim_25,bert_dim_26,bert_dim_27,bert_dim_28,bert_dim_29,bert_dim_30,bert_dim_31,bert_dim_32,bert_dim_33,bert_dim_34,bert_dim_35,bert_dim_36,bert_dim_37,bert_dim_38,bert_dim_39,bert_dim_40,bert_dim_41,bert_dim_42,bert_dim_43,bert_dim_44,bert_dim_45,bert_dim_46,bert_dim_47,bert_dim_48,bert_dim_49,bert_dim_50,bert_dim_51,bert_dim_52,bert_dim_53,bert_dim_54,bert_dim_55,bert_dim_56,bert_dim_57,bert_dim_58,bert_dim_59,bert_dim_60,bert_dim_61,bert_dim_62,bert_dim_63,bert_dim_64,bert_dim_65,bert_dim_66,bert_dim_67,bert_dim_68,bert_dim_69,bert_dim_70,bert_dim_71,bert_dim_72,bert_dim_73,bert_dim_74,bert_dim_75,bert_dim_76,bert_dim_77,bert_dim_78,bert_dim_79,bert_dim_80,bert_dim_81,bert_dim_82,bert_dim_83,bert_dim_84,bert_dim_85,bert_dim_86,bert_dim_87,bert_dim_88,bert_dim_89,bert_dim_90,bert_dim_91,bert_dim_92,bert_dim_93,bert_dim_94,bert_dim_95,bert_dim_96,bert_dim_97,bert_dim_98,bert_dim_99,bert_dim_100,bert_dim_101,bert_dim_102,bert_dim_103,bert_dim_104,bert_dim_105,bert_dim_106,bert_dim_107,bert_dim_108,bert_dim_109,bert_dim_110,bert_dim_111,bert_dim_112,bert_dim_113,bert_dim_114,bert_dim_115,bert_dim_116,bert_dim_117,bert_dim_118,bert_dim_119,bert_dim_120,bert_dim_121,bert_dim_122,bert_dim_123,bert_dim_124,bert_dim_125,bert_dim_126,bert_dim_127,bert_dim_128,bert_dim_129,bert_dim_130,bert_dim_131,bert_dim_132,bert_dim_133,bert_dim_134,bert_dim_135,bert_dim_136,bert_dim_137,bert_dim_138,bert_dim_139,bert_dim_140,bert_dim_141,bert_dim_142,bert_dim_143,bert_dim_144,bert_dim_145,bert_dim_146,bert_dim_147,bert_dim_148,bert_dim_149,bert_dim_150,bert_dim_151,bert_dim_152,bert_dim_153,bert_dim_154,bert_dim_155,bert_dim_156,bert_dim_157,bert_dim_158,bert_dim_159,bert_dim_160,bert_dim_161,bert_dim_162,bert_dim_163,bert_dim_164,bert_dim_165,bert_dim_166,bert_dim_167,bert_dim_168,bert_dim_169,bert_dim_170,bert_dim_171,bert_dim_172,bert_dim_173,bert_dim_174,bert_dim_175,bert_dim_176,bert_dim_177,bert_dim_178,bert_dim_179,bert_dim_180,bert_dim_181,bert_dim_182,bert_dim_183,bert_dim_184,bert_dim_185,bert_dim_186,bert_dim_187,bert_dim_188,bert_dim_189,bert_dim_190,bert_dim_191,bert_dim_192,bert_dim_193,bert_dim_194,bert_dim_195,bert_dim_196,bert_dim_197,bert_dim_198,bert_dim_199,bert_dim_200,bert_dim_201,bert_dim_202,bert_dim_203,bert_dim_204,bert_dim_205,bert_dim_206,bert_dim_207,bert_dim_208,bert_dim_209,bert_dim_210,bert_dim_211,bert_dim_212,bert_dim_213,bert_dim_214,bert_dim_215,bert_dim_216,bert_dim_217,bert_dim_218,bert_dim_219,bert_dim_220,bert_dim_221,bert_dim_222,bert_dim_223,bert_dim_224,bert_dim_225,bert_dim_226,bert_dim_227,bert_dim_228,bert_dim_229,bert_dim_230,bert_dim_231,bert_dim_232,bert_dim_233,bert_dim_234,bert_dim_235,bert_dim_236,bert_dim_237,bert_dim_238,bert_dim_239,bert_dim_240,bert_dim_241,bert_dim_242,bert_dim_243,bert_dim_244,bert_dim_245,bert_dim_246,bert_dim_247,bert_dim_248,bert_dim_249,bert_dim_250,bert_dim_251,bert_dim_252,bert_dim_253,bert_dim_254,bert_dim_255,bert_dim_256,bert_dim_257,bert_dim_258,bert_dim_259,bert_dim_260,bert_dim_261,bert_dim_262,bert_dim_263,bert_dim_264,bert_dim_265,bert_dim_266,bert_dim_267,bert_dim_268,bert_dim_269,bert_dim_270,bert_dim_271,bert_dim_272,bert_dim_273,bert_dim_274,bert_dim_275,bert_dim_276,bert_dim_277,bert_dim_278,bert_dim_279,bert_dim_280,bert_dim_281,bert_dim_282,bert_dim_283,bert_dim_284,bert_dim_285,bert_dim_286,bert_dim_287,bert_dim_288,bert_dim_289,bert_dim_290,bert_dim_291,bert_dim_292,bert_dim_293,bert_dim_294,bert_dim_295,bert_dim_296,bert_dim_297,bert_dim_298,bert_dim_299,bert_dim_300,bert_dim_301,bert_dim_302,bert_dim_303,bert_dim_304,bert_dim_305,bert_dim_306,bert_dim_307,bert_dim_308,bert_dim_309,bert_dim_310,bert_dim_311,bert_dim_312,bert_dim_313,bert_dim_314,bert_dim_315,bert_dim_316,bert_dim_317,bert_dim_318,bert_dim_319,bert_dim_320,bert_dim_321,bert_dim_322,bert_dim_323,bert_dim_324,bert_dim_325,bert_dim_326,bert_dim_327,bert_dim_328,bert_dim_329,bert_dim_330,bert_dim_331,bert_dim_332,bert_dim_333,bert_dim_334,bert_dim_335,bert_dim_336,bert_dim_337,bert_dim_338,bert_dim_339,bert_dim_340,bert_dim_341,bert_dim_342,bert_dim_343,bert_dim_344,bert_dim_345,bert_dim_346,bert_dim_347,bert_dim_348,bert_dim_349,bert_dim_350,bert_dim_351,bert_dim_352,bert_dim_353,bert_dim_354,bert_dim_355,bert_dim_356,bert_dim_357,bert_dim_358,bert_dim_359,bert_dim_360,bert_dim_361,bert_dim_362,bert_dim_363,bert_dim_364,bert_dim_365,bert_dim_366,bert_dim_367,bert_dim_368,bert_dim_369,bert_dim_370,bert_dim_371,bert_dim_372,bert_dim_373,bert_dim_374,bert_dim_375,bert_dim_376,bert_dim_377,bert_dim_378,bert_dim_379,bert_dim_380,bert_dim_381,bert_dim_382,bert_dim_383,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,spelling_errors,grammar_errors,linsear_write_formula,ari_score,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,topic,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199

In [46]:
X_train.tail()

,essay_id,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,pos_ADJ_count,pos_NOUN_count,pos_VERB_count,pos_SCONJ_count,pos_PRON_count,pos_PUNCT_count,pos_DET_count,pos_AUX_count,pos_PART_count,pos_ADP_count,pos_SPACE_count,pos_CCONJ_count,pos_PROPN_count,pos_NUM_count,pos_ADV_count,pos_SYM_count,pos_ADJ_ratio,pos_NOUN_ratio,pos_VERB_ratio,pos_SCONJ_ratio,pos_PRON_ratio,pos_PUNCT_ratio,pos_DET_ratio,pos_AUX_ratio,pos_PART_ratio,pos_ADP_ratio,pos_SPACE_ratio,pos_CCONJ_ratio,pos_PROPN_ratio,pos_NUM_ratio,pos_ADV_ratio,pos_SYM_ratio,pos_INTJ_count,pos_INTJ_ratio,pos_X_count,pos_X_ratio,ner_GPE_count,ner_PERCENT_count,ner_NORP_count,ner_ORG_count,ner_CARDINAL_count,ner_MONEY_count,ner_DATE_count,ner_LOC_count,ner_PERSON_count,ner_QUANTITY_count,ner_EVENT_count,ner_GPE_ratio,ner_PERCENT_ratio,ner_NORP_ratio,ner_ORG_ratio,ner_CARDINAL_ratio,ner_MONEY_ratio,ner_DATE_ratio,ner_LOC_ratio,ner_PERSON_ratio,ner_QUANTITY_ratio,ner_EVENT_ratio,ner_ORDINAL_count,ner_ORDINAL_ratio,ner_WORK_OF_ART_count,ner_WORK_OF_ART_ratio,ner_LAW_count,ner_LAW_ratio,ner_PRODUCT_count,ner_PRODUCT_ratio,ner_TIME_count,ner_TIME_ratio,ner_FAC_count,ner_FAC_ratio,ner_LANGUAGE_count,ner_LANGUAGE_ratio,dep_amod_count,dep_nsubj_count,dep_ROOT_count,dep_dobj_count,dep_advmod_count,dep_relcl_count,dep_punct_count,dep_det_count,dep_aux_count,dep_neg_count,dep_mark_count,dep_csubj_count,dep_compound_count,dep_prep_count,dep_pobj_count,dep_ccomp_count,dep_dep_count,dep_advcl_count,dep_cc_count,dep_acomp_count,dep_attr_count,dep_appos_count,dep_conj_count,dep_nummod_count,dep_poss_count,dep_case_count,dep_nsubjpass_count,dep_nmod_count,dep_auxpass_count,dep_npadvmod_count,dep_expl_count,dep_xcomp_count,dep_dative_count,dep_oprd_count,dep_acl_count,dep_quantmod_count,dep_pcomp_count,dep_amod_ratio,dep_nsubj_ratio,dep_ROOT_ratio,dep_dobj_ratio,dep_advmod_ratio,dep_relcl_ratio,dep_punct_ratio,dep_det_ratio,dep_aux_ratio,dep_neg_ratio,dep_mark_ratio,dep_csubj_ratio,dep_compound_ratio,dep_prep_ratio,dep_pobj_ratio,dep_ccomp_ratio,dep_dep_ratio,dep_advcl_ratio,dep_cc_ratio,dep_acomp_ratio,dep_attr_ratio,dep_appos_ratio,dep_conj_ratio,dep_nummod_ratio,dep_poss_ratio,dep_case_ratio,dep_nsubjpass_ratio,dep_nmod_ratio,dep_auxpass_ratio,dep_npadvmod_ratio,dep_expl_ratio,dep_xcomp_ratio,dep_dative_ratio,dep_oprd_ratio,dep_acl_ratio,dep_quantmod_ratio,dep_pcomp_ratio,dep_agent_count,dep_intj_count,dep_predet_count,dep_prt_count,dep_agent_ratio,dep_intj_ratio,dep_predet_ratio,dep_prt_ratio,dep_meta_count,dep_meta_ratio,dep_preconj_count,dep_preconj_ratio,dep_parataxis_count,dep_parataxis_ratio,dep_csubjpass_count,dep_csubjpass_ratio,verb_tense_consistency,passive_voice_usage,modal_verb_usage,lexical_diversity,dale_chall_readability,automated_readability_index,coleman_liau_index,conjunction_usage,clause_density,vader_compound,vader_positive,vader_negative,vader_neutral,bert_dim_0,bert_dim_1,bert_dim_2,bert_dim_3,bert_dim_4,bert_dim_5,bert_dim_6,bert_dim_7,bert_dim_8,bert_dim_9,bert_dim_10,bert_dim_11,bert_dim_12,bert_dim_13,bert_dim_14,bert_dim_15,bert_dim_16,bert_dim_17,bert_dim_18,bert_dim_19,bert_dim_20,bert_dim_21,bert_dim_22,bert_dim_23,bert_dim_24,bert_dim_25,bert_dim_26,bert_dim_27,bert_dim_28,bert_dim_29,bert_dim_30,bert_dim_31,bert_dim_32,bert_dim_33,bert_dim_34,bert_dim_35,bert_dim_36,bert_dim_37,bert_dim_38,bert_dim_39,bert_dim_40,bert_dim_41,bert_dim_42,bert_dim_43,bert_dim_44,bert_dim_45,bert_dim_46,bert_dim_47,bert_dim_48,bert_dim_49,bert_dim_50,bert_dim_51,bert_dim_52,bert_dim_53,bert_dim_54,bert_dim_55,bert_dim_56,bert_dim_57,bert_dim_58,bert_dim_59,bert_dim_60,bert_dim_61,bert_dim_62,bert_dim_63,bert_dim_64,bert_dim_65,bert_dim_66,bert_dim_67,bert_dim_68,bert_dim_69,bert_dim_70,bert_dim_71,bert_dim_72,bert_dim_73,bert_dim_74,bert_dim_75,bert_dim_76,bert_dim_77,bert_dim_78,bert_dim_79,bert_dim_80,bert_dim_81,bert_dim_82,bert_dim_83,bert_dim_84,bert_dim_85,bert_dim_86,bert_dim_87,bert_dim_88,bert_dim_89,bert_dim_90,bert_dim_91,bert_dim_92,bert_dim_93,bert_dim_94,bert_dim_95,bert_dim_96,bert_dim_97,bert_dim_98,bert_dim_99,bert_dim_100,bert_dim_101,bert_dim_102,bert_dim_103,bert_dim_104,bert_dim_105,bert_dim_106,bert_dim_107,bert_dim_108,bert_dim_109,bert_dim_110,bert_dim_111,bert_dim_112,bert_dim_113,bert_dim_114,bert_dim_115,bert_dim_116,bert_dim_117,bert_dim_118,bert_dim_119,bert_dim_120,bert_dim_121,bert_dim_122,bert_dim_123,bert_dim_124,bert_dim_125,bert_dim_126,bert_dim_127,bert_dim_128,bert_dim_129,bert_dim_130,bert_dim_131,bert_dim_132,bert_dim_133,bert_dim_134,bert_dim_135,bert_dim_136,bert_dim_137,bert_dim_138,bert_dim_139,bert_dim_140,bert_dim_141,bert_dim_142,bert_dim_143,bert_dim_144,bert_dim_145,bert_dim_146,bert_dim_147,bert_dim_148,bert_dim_149,bert_dim_150,bert_dim_151,bert_dim_152,bert_dim_153,bert_dim_154,bert_dim_155,bert_dim_156,bert_dim_157,bert_dim_158,bert_dim_159,bert_dim_160,bert_dim_161,bert_dim_162,bert_dim_163,bert_dim_164,bert_dim_165,bert_dim_166,bert_dim_167,bert_dim_168,bert_dim_169,bert_dim_170,bert_dim_171,bert_dim_172,bert_dim_173,bert_dim_174,bert_dim_175,bert_dim_176,bert_dim_177,bert_dim_178,bert_dim_179,bert_dim_180,bert_dim_181,bert_dim_182,bert_dim_183,bert_dim_184,bert_dim_185,bert_dim_186,bert_dim_187,bert_dim_188,bert_dim_189,bert_dim_190,bert_dim_191,bert_dim_192,bert_dim_193,bert_dim_194,bert_dim_195,bert_dim_196,bert_dim_197,bert_dim_198,bert_dim_199,bert_dim_200,bert_dim_201,bert_dim_202,bert_dim_203,bert_dim_204,bert_dim_205,bert_dim_206,bert_dim_207,bert_dim_208,bert_dim_209,bert_dim_210,bert_dim_211,bert_dim_212,bert_dim_213,bert_dim_214,bert_dim_215,bert_dim_216,bert_dim_217,bert_dim_218,bert_dim_219,bert_dim_220,bert_dim_221,bert_dim_222,bert_dim_223,bert_dim_224,bert_dim_225,bert_dim_226,bert_dim_227,bert_dim_228,bert_dim_229,bert_dim_230,bert_dim_231,bert_dim_232,bert_dim_233,bert_dim_234,bert_dim_235,bert_dim_236,bert_dim_237,bert_dim_238,bert_dim_239,bert_dim_240,bert_dim_241,bert_dim_242,bert_dim_243,bert_dim_244,bert_dim_245,bert_dim_246,bert_dim_247,bert_dim_248,bert_dim_249,bert_dim_250,bert_dim_251,bert_dim_252,bert_dim_253,bert_dim_254,bert_dim_255,bert_dim_256,bert_dim_257,bert_dim_258,bert_dim_259,bert_dim_260,bert_dim_261,bert_dim_262,bert_dim_263,bert_dim_264,bert_dim_265,bert_dim_266,bert_dim_267,bert_dim_268,bert_dim_269,bert_dim_270,bert_dim_271,bert_dim_272,bert_dim_273,bert_dim_274,bert_dim_275,bert_dim_276,bert_dim_277,bert_dim_278,bert_dim_279,bert_dim_280,bert_dim_281,bert_dim_282,bert_dim_283,bert_dim_284,bert_dim_285,bert_dim_286,bert_dim_287,bert_dim_288,bert_dim_289,bert_dim_290,bert_dim_291,bert_dim_292,bert_dim_293,bert_dim_294,bert_dim_295,bert_dim_296,bert_dim_297,bert_dim_298,bert_dim_299,bert_dim_300,bert_dim_301,bert_dim_302,bert_dim_303,bert_dim_304,bert_dim_305,bert_dim_306,bert_dim_307,bert_dim_308,bert_dim_309,bert_dim_310,bert_dim_311,bert_dim_312,bert_dim_313,bert_dim_314,bert_dim_315,bert_dim_316,bert_dim_317,bert_dim_318,bert_dim_319,bert_dim_320,bert_dim_321,bert_dim_322,bert_dim_323,bert_dim_324,bert_dim_325,bert_dim_326,bert_dim_327,bert_dim_328,bert_dim_329,bert_dim_330,bert_dim_331,bert_dim_332,bert_dim_333,bert_dim_334,bert_dim_335,bert_dim_336,bert_dim_337,bert_dim_338,bert_dim_339,bert_dim_340,bert_dim_341,bert_dim_342,bert_dim_343,bert_dim_344,bert_dim_345,bert_dim_346,bert_dim_347,bert_dim_348,bert_dim_349,bert_dim_350,bert_dim_351,bert_dim_352,bert_dim_353,bert_dim_354,bert_dim_355,bert_dim_356,bert_dim_357,bert_dim_358,bert_dim_359,bert_dim_360,bert_dim_361,bert_dim_362,bert_dim_363,bert_dim_364,bert_dim_365,bert_dim_366,bert_dim_367,bert_dim_368,bert_dim_369,bert_dim_370,bert_dim_371,bert_dim_372,bert_dim_373,bert_dim_374,bert_dim_375,bert_dim_376,bert_dim_377,bert_dim_378,bert_dim_379,bert_dim_380,bert_dim_381,bert_dim_382,bert_dim_383,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,spelling_errors,grammar_errors,linsear_write_formula,ari_score,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,topic,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199

In [47]:
import pandas as pd
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE


# Now, let's apply SMOTE to balance the minority classes up to 1,000 samples
X = X_train.drop(columns=['essay_id'])
y = train_labels

# Create SMOTE instance to ensure all classes have 1,000 samples
smote = SMOTE(sampling_strategy='not majority', random_state=42)

X_resampled, y_resampled = smote.fit_resample(X, y)

# Create the resampled DataFrame
df_resampled = pd.DataFrame(X_resampled, columns=X.columns)
y_train_resampled = y_resampled

# Display the resampled class distribution to confirm the balancing
print("Resampled class distribution:")
print(y_train_resampled.value_counts())


UPSAMPLE = True

if UPSAMPLE:
    
    # Balance only the training DataFrame
    X_train = df_resampled.copy()
    train_labels = y_train_resampled

    
else:
    pass

print(train_labels.value_counts())

Resampled class distribution:
score
2    4396
3    4396
4    4396
1    4396
5    4396
6    4396
Name: count, dtype: int64
score
2    4396
3    4396
4    4396
1    4396
5    4396
6    4396
Name: count, dtype: int64

In [48]:
X_train.head()

,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,pos_ADJ_count,pos_NOUN_count,pos_VERB_count,pos_SCONJ_count,pos_PRON_count,pos_PUNCT_count,pos_DET_count,pos_AUX_count,pos_PART_count,pos_ADP_count,pos_SPACE_count,pos_CCONJ_count,pos_PROPN_count,pos_NUM_count,pos_ADV_count,pos_SYM_count,pos_ADJ_ratio,pos_NOUN_ratio,pos_VERB_ratio,pos_SCONJ_ratio,pos_PRON_ratio,pos_PUNCT_ratio,pos_DET_ratio,pos_AUX_ratio,pos_PART_ratio,pos_ADP_ratio,pos_SPACE_ratio,pos_CCONJ_ratio,pos_PROPN_ratio,pos_NUM_ratio,pos_ADV_ratio,pos_SYM_ratio,pos_INTJ_count,pos_INTJ_ratio,pos_X_count,pos_X_ratio,ner_GPE_count,ner_PERCENT_count,ner_NORP_count,ner_ORG_count,ner_CARDINAL_count,ner_MONEY_count,ner_DATE_count,ner_LOC_count,ner_PERSON_count,ner_QUANTITY_count,ner_EVENT_count,ner_GPE_ratio,ner_PERCENT_ratio,ner_NORP_ratio,ner_ORG_ratio,ner_CARDINAL_ratio,ner_MONEY_ratio,ner_DATE_ratio,ner_LOC_ratio,ner_PERSON_ratio,ner_QUANTITY_ratio,ner_EVENT_ratio,ner_ORDINAL_count,ner_ORDINAL_ratio,ner_WORK_OF_ART_count,ner_WORK_OF_ART_ratio,ner_LAW_count,ner_LAW_ratio,ner_PRODUCT_count,ner_PRODUCT_ratio,ner_TIME_count,ner_TIME_ratio,ner_FAC_count,ner_FAC_ratio,ner_LANGUAGE_count,ner_LANGUAGE_ratio,dep_amod_count,dep_nsubj_count,dep_ROOT_count,dep_dobj_count,dep_advmod_count,dep_relcl_count,dep_punct_count,dep_det_count,dep_aux_count,dep_neg_count,dep_mark_count,dep_csubj_count,dep_compound_count,dep_prep_count,dep_pobj_count,dep_ccomp_count,dep_dep_count,dep_advcl_count,dep_cc_count,dep_acomp_count,dep_attr_count,dep_appos_count,dep_conj_count,dep_nummod_count,dep_poss_count,dep_case_count,dep_nsubjpass_count,dep_nmod_count,dep_auxpass_count,dep_npadvmod_count,dep_expl_count,dep_xcomp_count,dep_dative_count,dep_oprd_count,dep_acl_count,dep_quantmod_count,dep_pcomp_count,dep_amod_ratio,dep_nsubj_ratio,dep_ROOT_ratio,dep_dobj_ratio,dep_advmod_ratio,dep_relcl_ratio,dep_punct_ratio,dep_det_ratio,dep_aux_ratio,dep_neg_ratio,dep_mark_ratio,dep_csubj_ratio,dep_compound_ratio,dep_prep_ratio,dep_pobj_ratio,dep_ccomp_ratio,dep_dep_ratio,dep_advcl_ratio,dep_cc_ratio,dep_acomp_ratio,dep_attr_ratio,dep_appos_ratio,dep_conj_ratio,dep_nummod_ratio,dep_poss_ratio,dep_case_ratio,dep_nsubjpass_ratio,dep_nmod_ratio,dep_auxpass_ratio,dep_npadvmod_ratio,dep_expl_ratio,dep_xcomp_ratio,dep_dative_ratio,dep_oprd_ratio,dep_acl_ratio,dep_quantmod_ratio,dep_pcomp_ratio,dep_agent_count,dep_intj_count,dep_predet_count,dep_prt_count,dep_agent_ratio,dep_intj_ratio,dep_predet_ratio,dep_prt_ratio,dep_meta_count,dep_meta_ratio,dep_preconj_count,dep_preconj_ratio,dep_parataxis_count,dep_parataxis_ratio,dep_csubjpass_count,dep_csubjpass_ratio,verb_tense_consistency,passive_voice_usage,modal_verb_usage,lexical_diversity,dale_chall_readability,automated_readability_index,coleman_liau_index,conjunction_usage,clause_density,vader_compound,vader_positive,vader_negative,vader_neutral,bert_dim_0,bert_dim_1,bert_dim_2,bert_dim_3,bert_dim_4,bert_dim_5,bert_dim_6,bert_dim_7,bert_dim_8,bert_dim_9,bert_dim_10,bert_dim_11,bert_dim_12,bert_dim_13,bert_dim_14,bert_dim_15,bert_dim_16,bert_dim_17,bert_dim_18,bert_dim_19,bert_dim_20,bert_dim_21,bert_dim_22,bert_dim_23,bert_dim_24,bert_dim_25,bert_dim_26,bert_dim_27,bert_dim_28,bert_dim_29,bert_dim_30,bert_dim_31,bert_dim_32,bert_dim_33,bert_dim_34,bert_dim_35,bert_dim_36,bert_dim_37,bert_dim_38,bert_dim_39,bert_dim_40,bert_dim_41,bert_dim_42,bert_dim_43,bert_dim_44,bert_dim_45,bert_dim_46,bert_dim_47,bert_dim_48,bert_dim_49,bert_dim_50,bert_dim_51,bert_dim_52,bert_dim_53,bert_dim_54,bert_dim_55,bert_dim_56,bert_dim_57,bert_dim_58,bert_dim_59,bert_dim_60,bert_dim_61,bert_dim_62,bert_dim_63,bert_dim_64,bert_dim_65,bert_dim_66,bert_dim_67,bert_dim_68,bert_dim_69,bert_dim_70,bert_dim_71,bert_dim_72,bert_dim_73,bert_dim_74,bert_dim_75,bert_dim_76,bert_dim_77,bert_dim_78,bert_dim_79,bert_dim_80,bert_dim_81,bert_dim_82,bert_dim_83,bert_dim_84,bert_dim_85,bert_dim_86,bert_dim_87,bert_dim_88,bert_dim_89,bert_dim_90,bert_dim_91,bert_dim_92,bert_dim_93,bert_dim_94,bert_dim_95,bert_dim_96,bert_dim_97,bert_dim_98,bert_dim_99,bert_dim_100,bert_dim_101,bert_dim_102,bert_dim_103,bert_dim_104,bert_dim_105,bert_dim_106,bert_dim_107,bert_dim_108,bert_dim_109,bert_dim_110,bert_dim_111,bert_dim_112,bert_dim_113,bert_dim_114,bert_dim_115,bert_dim_116,bert_dim_117,bert_dim_118,bert_dim_119,bert_dim_120,bert_dim_121,bert_dim_122,bert_dim_123,bert_dim_124,bert_dim_125,bert_dim_126,bert_dim_127,bert_dim_128,bert_dim_129,bert_dim_130,bert_dim_131,bert_dim_132,bert_dim_133,bert_dim_134,bert_dim_135,bert_dim_136,bert_dim_137,bert_dim_138,bert_dim_139,bert_dim_140,bert_dim_141,bert_dim_142,bert_dim_143,bert_dim_144,bert_dim_145,bert_dim_146,bert_dim_147,bert_dim_148,bert_dim_149,bert_dim_150,bert_dim_151,bert_dim_152,bert_dim_153,bert_dim_154,bert_dim_155,bert_dim_156,bert_dim_157,bert_dim_158,bert_dim_159,bert_dim_160,bert_dim_161,bert_dim_162,bert_dim_163,bert_dim_164,bert_dim_165,bert_dim_166,bert_dim_167,bert_dim_168,bert_dim_169,bert_dim_170,bert_dim_171,bert_dim_172,bert_dim_173,bert_dim_174,bert_dim_175,bert_dim_176,bert_dim_177,bert_dim_178,bert_dim_179,bert_dim_180,bert_dim_181,bert_dim_182,bert_dim_183,bert_dim_184,bert_dim_185,bert_dim_186,bert_dim_187,bert_dim_188,bert_dim_189,bert_dim_190,bert_dim_191,bert_dim_192,bert_dim_193,bert_dim_194,bert_dim_195,bert_dim_196,bert_dim_197,bert_dim_198,bert_dim_199,bert_dim_200,bert_dim_201,bert_dim_202,bert_dim_203,bert_dim_204,bert_dim_205,bert_dim_206,bert_dim_207,bert_dim_208,bert_dim_209,bert_dim_210,bert_dim_211,bert_dim_212,bert_dim_213,bert_dim_214,bert_dim_215,bert_dim_216,bert_dim_217,bert_dim_218,bert_dim_219,bert_dim_220,bert_dim_221,bert_dim_222,bert_dim_223,bert_dim_224,bert_dim_225,bert_dim_226,bert_dim_227,bert_dim_228,bert_dim_229,bert_dim_230,bert_dim_231,bert_dim_232,bert_dim_233,bert_dim_234,bert_dim_235,bert_dim_236,bert_dim_237,bert_dim_238,bert_dim_239,bert_dim_240,bert_dim_241,bert_dim_242,bert_dim_243,bert_dim_244,bert_dim_245,bert_dim_246,bert_dim_247,bert_dim_248,bert_dim_249,bert_dim_250,bert_dim_251,bert_dim_252,bert_dim_253,bert_dim_254,bert_dim_255,bert_dim_256,bert_dim_257,bert_dim_258,bert_dim_259,bert_dim_260,bert_dim_261,bert_dim_262,bert_dim_263,bert_dim_264,bert_dim_265,bert_dim_266,bert_dim_267,bert_dim_268,bert_dim_269,bert_dim_270,bert_dim_271,bert_dim_272,bert_dim_273,bert_dim_274,bert_dim_275,bert_dim_276,bert_dim_277,bert_dim_278,bert_dim_279,bert_dim_280,bert_dim_281,bert_dim_282,bert_dim_283,bert_dim_284,bert_dim_285,bert_dim_286,bert_dim_287,bert_dim_288,bert_dim_289,bert_dim_290,bert_dim_291,bert_dim_292,bert_dim_293,bert_dim_294,bert_dim_295,bert_dim_296,bert_dim_297,bert_dim_298,bert_dim_299,bert_dim_300,bert_dim_301,bert_dim_302,bert_dim_303,bert_dim_304,bert_dim_305,bert_dim_306,bert_dim_307,bert_dim_308,bert_dim_309,bert_dim_310,bert_dim_311,bert_dim_312,bert_dim_313,bert_dim_314,bert_dim_315,bert_dim_316,bert_dim_317,bert_dim_318,bert_dim_319,bert_dim_320,bert_dim_321,bert_dim_322,bert_dim_323,bert_dim_324,bert_dim_325,bert_dim_326,bert_dim_327,bert_dim_328,bert_dim_329,bert_dim_330,bert_dim_331,bert_dim_332,bert_dim_333,bert_dim_334,bert_dim_335,bert_dim_336,bert_dim_337,bert_dim_338,bert_dim_339,bert_dim_340,bert_dim_341,bert_dim_342,bert_dim_343,bert_dim_344,bert_dim_345,bert_dim_346,bert_dim_347,bert_dim_348,bert_dim_349,bert_dim_350,bert_dim_351,bert_dim_352,bert_dim_353,bert_dim_354,bert_dim_355,bert_dim_356,bert_dim_357,bert_dim_358,bert_dim_359,bert_dim_360,bert_dim_361,bert_dim_362,bert_dim_363,bert_dim_364,bert_dim_365,bert_dim_366,bert_dim_367,bert_dim_368,bert_dim_369,bert_dim_370,bert_dim_371,bert_dim_372,bert_dim_373,bert_dim_374,bert_dim_375,bert_dim_376,bert_dim_377,bert_dim_378,bert_dim_379,bert_dim_380,bert_dim_381,bert_dim_382,bert_dim_383,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,spelling_errors,grammar_errors,linsear_write_formula,ari_score,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,topic,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199

In [49]:
# To convert features and targets to NumPy arrays for ML use

train_features = X_train.values

train_labels = np.array(train_labels.values)

val_features = X_test.values

val_labels = np.array(y_test.values)




print("Features shape:", train_features.shape)
print("Target shape:", train_labels.shape)

print("Features shape:", val_features.shape)
print("Target shape:", val_labels.shape)



#####     Features shape: (3, 1389)

Features shape: (26376, 1799)
Target shape: (26376,)
Features shape: (5193, 1800)
Target shape: (5193,)

In [50]:
from sklearn.metrics import make_scorer, cohen_kappa_score

def quadratic_weighted_kappa_scorer(y_true, y_pred):
    """
    Compute the Quadratic Weighted Kappa (QWK), also known as Cohen's kappa.
    
    Parameters:
    y_true : array-like of shape (n_samples,)
        True labels.
    y_pred : array-liimport keras_tuner
from sklearn import ensemble
from sklearn import datasets
from sklearn import linear_model
from sklearn import metrics
from sklearn import model_selection

def build_model(hp):
  model_type = hp.Choice('model_type', ['random_forest', 'ridge'])
  if model_type == 'random_forest':
    model = ensemble.RandomForestClassifier(
        n_estimators=hp.Int('n_estimators', 10, 50, step=10),
        max_depth=hp.Int('max_depth', 3, 10))
  else:
    model = linear_model.RidgeClassifier(
        alpha=hp.Float('alpha', 1e-3, 1, sampling='log'))
  return model

tuner = keras_tuner.tuners.SklearnTuner(
    oracle=keras_tuner.oracles.BayesianOptimizationOracle(
        objective=keras_tuner.Objective('score', 'max'),
        max_trials=100),
    hypermodel=build_model,
    scoring=metrics.make_scorer(metrics.accuracy_score),
    cv=model_selection.StratifiedKFold(10),
    directory='.',
    project_name='my_project')ke of shape (n_samples,)
        Predicted labels.
    
    Returns:
    score : float
        Quadratic Weighted Kappa score.
    """
    return cohen_kappa_score(y_true, y_pred, weights='quadratic')

In [ ]:
# from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
# import keras_tuner as kt

# model_checkpoint = ModelCheckpoint('data/models/best_standard_model_epoch.keras', 
#                                    save_best_only=True, monitor='val_loss', mode='min')

# early_stopping = EarlyStopping(monitor='val_loss', patience=5, 
#                                restore_best_weights=True)

# call_backs = [model_checkpoint, early_stopping]

In [52]:
import keras_tuner
from sklearn import ensemble, linear_model, model_selection, svm
from lightgbm import LGBMClassifier


def build_model(hp):
    """
    Builds a more comprehensive machine learning model based on hyperparameters for multiclass classification.
    
    Parameters:
    hp : HyperParameters
        Hyperparameters for tuning the model.
    
    Returns:
    model : An instance of a Scikit-learn model.
    """
    # Adding 'lightgbm' as a new model type
    model_type = hp.Choice('model_type', ['random_forest',  'gradient_boosting', 'lightgbm'])

    if model_type == 'random_forest':
        model = ensemble.RandomForestClassifier(
            n_estimators=hp.Int('n_estimators', 10, 100, step=10),
            max_depth=hp.Int('max_depth', 3, 20),
            min_samples_split=hp.Int('min_samples_split', 2, 20),
            min_samples_leaf=hp.Int('min_samples_leaf', 1, 10),
            criterion=hp.Choice('criterion', ['gini', 'entropy']),
            class_weight=hp.Choice('class_weight', ['balanced', 'balanced_subsample']),
            max_samples=hp.Float('max_samples', 0.1, 1.0, sampling='log')
        )



    elif model_type == 'gradient_boosting':
        model = ensemble.GradientBoostingClassifier(
            n_estimators=hp.Int('n_estimators', 50, 200, step=50),
            learning_rate=hp.Float('learning_rate', 0.01, 0.2, sampling='log'),
            max_depth=hp.Int('max_depth', 3, 15),
            subsample=hp.Float('subsample', 0.5, 1.0, step=0.1)
        )

    # Adding LightGBM as a new model type
    elif model_type == 'lightgbm':
        model = LGBMClassifier(
            n_estimators=hp.Int('n_estimators', 50, 200, step=50),
            num_leaves=hp.Int('num_leaves', 31, 127, step=16),
            learning_rate=hp.Float('learning_rate', 0.01, 0.2, sampling='log'),
            min_child_samples=hp.Int('min_child_samples', 10, 50, step=10),
            class_weight=hp.Choice('class_weight', ['balanced']),  #  'balanced_sample'
        )

    return model


# Defining the custom QWK scorer
qwk_scorer = make_scorer(quadratic_weighted_kappa_scorer)

# Tuner configuration
tuner = keras_tuner.tuners.SklearnTuner(
    oracle=keras_tuner.oracles.BayesianOptimizationOracle(
        objective=keras_tuner.Objective('score', 'max'),
        max_trials=10),
    hypermodel=build_model,
    scoring=qwk_scorer,
    cv=model_selection.StratifiedKFold(3),
    directory='.',
    project_name='data/sklearn',
    overwrite=True)

# Starting the search
tuner.search(train_features, train_labels)      # class_weight=class_weights_dict,

# Retrieving the best model
best_model = tuner.get_best_models(num_models=1)[0]

Search: Running Trial #1

Value             |Best Value So Far |Hyperparameter
gradient_boosting |gradient_boosting |model_type
70                |70                |n_estimators
7                 |7                 |max_depth
20                |20                |min_samples_split
8                 |8                 |min_samples_leaf
entropy           |entropy           |criterion
balanced_subsample|balanced_subsample|class_weight
0.43306           |0.43306           |max_samples

In [ ]:
full_train = np.concatenate((train_features, val_features), axis=0)

full_labels = np.concatenate((train_labels, val_labels), axis=0)

X_train, X_val, y_train, y_val = model_selection.train_test_split(full_train, full_labels, test_size=0.1, random_state=42, stratify=full_labels)

In [ ]:
full_train.shape, full_labels.shape

In [ ]:
best_model.fit(X_train, y_train)

In [ ]:
predictions = best_model.predict(X_val)

y_true = y_val

# predictions = target_scaler.inverse_transform(predictions.reshape(-1, 1)).flatten()

In [ ]:
# confusion matrix

from sklearn.metrics import confusion_matrix

confusion_matrix(y_true, predictions)

In [ ]:
# classification report

from sklearn.metrics import classification_report

print(classification_report(y_true, predictions))

In [ ]:
# cohens kappa

from sklearn.metrics import cohen_kappa_score

cohen = cohen_kappa_score(y_true, predictions)

In [ ]:
# quadratic weighted kappa

from sklearn.metrics import cohen_kappa_score

quadratic = cohen_kappa_score(y_true, predictions, weights='quadratic')

print(f"Cohen's Kappa: {cohen}")
print(f"Quadratic Weighted Kappa: {quadratic}")

In [ ]:
from joblib import dump, load

dump(best_model, file_config['sklearn_model'])

In [ ]:
# forest_model = load('random_forest.joblib')

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Generate and display the confusion matrix for the test predictions
cm = confusion_matrix(y_true, predictions, labels=best_model.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=best_model.classes_)
disp.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix')
plt.show()

In [ ]:
# Identifying misclassified samples
misclassified_indices = (y_true != predictions)
misclassified_samples = val_features[misclassified_indices]
misclassified_true_labels = y_true[misclassified_indices]
misclassified_predicted_labels = predictions[misclassified_indices]

In [ ]:
# Examining features of misclassified samples
import pandas as pd
misclassified_df = pd.DataFrame(misclassified_samples)
misclassified_df['True_Label'] = misclassified_true_labels
misclassified_df['Predicted_Label'] = misclassified_predicted_labels
# Display the first few rows of the misclassified samples
misclassified_df.head()

In [ ]:
# # Feature importance from LightGBM
# feature_importance = best_model.feature_importance(importance_type='gain')
# feature_names = val_features.columns
# feature_importance_df = pd.DataFrame({
#     'Feature': feature_names,
#     'Importance': feature_importance
# })
# # Sort features by importance
# feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)
# print(feature_importance_df)

In [ ]:
# Checking class distribution in the true labels
label_counts = pd.Series(y_true).value_counts()
print(label_counts)

In [ ]:
# from sklearn.model_selection import GridSearchCV
# # Define the hyperparameters to tune
# param_grid = {
#     'learning_rate': [0.01, 0.05, 0.1],
#     'num_leaves': [31, 62, 128],
#     'n_estimators': [50, 100, 200]
# }
# grid_search = GridSearchCV(best_model, param_grid, scoring='', cv=5)
# grid_search.fit(val_features, val_labels)
# print("Best parameters:", grid_search.best_params_)

In [ ]:
# Check LightGBM version
import lightgbm as lgb
print(lgb.__version__)

In [ ]:
# # Ensure the model is fitted
# if not hasattr(best_model, 'feature_importance_'):
#     best_model.fit(val_features, val_labels)  # Train or re-train the model

# # Retrieve feature importance
# feature_importance = best_model.feature_importance_  # Underscore at the end
# feature_names = val_features.columns

# # Create DataFrame for feature importance
# feature_importance_df = pd.DataFrame({
#     'Feature': feature_names,
#     'Importance': feature_importance
# })
# feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# print(feature_importance_df)

In [ ]:
# Assuming `df` is the original DataFrame and `predictions` is a list/array of predicted labels
# If there's a subset used for predictions, ensure it aligns with the DataFrame
val_df['Predicted_Label'] = predictions

In [ ]:
print(len(val_features), len(val_df), len(predictions))

In [ ]:
val_df.tail()

In [ ]:
# merge 'clean_text' column back with val df 

text = val_essays[['essay_id', 'clean_text']]

val_df = val_df.merge(text, on = 'essay_id')

val_df.head()

In [ ]:
# Assuming `df` has the original labels in a column named 'True_Label'
misclassified_samples = val_df[val_df['score'] != val_df['Predicted_Label']]

# Display misclassified samples
print(misclassified_samples[['score', 'Predicted_Label', 'clean_text']][:15])

In [ ]:
# Example: Analyze original text of misclassified samples
misclassified_text = misclassified_samples['clean_text']  # Assuming 'Text' is the original text data
print(misclassified_text.head())

In [ ]:
# load tf model
len(misclassified_text)

In [ ]:
# add full mis classified text to a txt file seperated by  '---' and a new line after every 10 words in each essay

with open('misclassified_text.txt', 'w') as f:
    for essay in misclassified_text:
        f.write("%s\n" % essay)
        f.write('---\n')

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Assuming `df` has your model's features and labels
X = val_df[feature_cols]
y = val_df['score'] == val_df['Predicted_Label']

# Splitting the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Fit a RandomForest to see feature importances
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)

# Get the most important features
importances = clf.feature_importances_
features = feature_cols
important_features = {features[i]: importances[i] for i in range(len(features))}

# convert to percentages rounded and sort

important_features = {k: round(v, 5) for k, v in important_features.items()}

print("Most predictive features of misclassification:", sorted(important_features.items(), key=lambda x: x[1], reverse=True))

In [ ]:
# import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt

# # Assume val_df and feature_cols are already defined

# # Set the option to display all rows
# pd.set_option('display.max_rows', None)

# # Selecting the features and the target
# X = val_df[feature_cols]
# y = val_df['score']

# # Calculate the correlation between features and the target
# corr = X.corrwith(y)

# # Sort the correlation values
# corr = corr.sort_values(ascending=False)

# # Convert the Series to a DataFrame for heatmap compatibility
# corr_df = pd.DataFrame(corr, columns=['Correlation'])

# corr_df

In [ ]:
# from sklearn.model_selection import train_test_split
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.metrics import classification_report

# # Define the feature set with and without the specific features
# X_with = val_df[feature_cols]  # including all features
# X_without = val_df.drop(columns=['misspelling_count', 'sentence_length'], axis=1) # excluding problematic features

# y = val_df['score']  # target variable

# # Split the data
# X_train_with, X_test_with, y_train, y_test = train_test_split(X_with, y, test_size=0.3, random_state=42)
# X_train_without, X_test_without, _ , _ = train_test_split(X_without, y, test_size=0.3, random_state=42)

# # Train models
# model_with = RandomForestClassifier().fit(X_train_with, y_train)
# model_without = RandomForestClassifier().fit(X_train_without, y_train)

# # Evaluate models
# print("With features:")
# print(classification_report(y_test, model_with.predict(X_test_with)))

# print("Without features:")
# print(classification_report(y_test, model_without.predict(X_test_without)))