# sklearn model with tensorflow keras tuner

In [ ]:
# ! python -m pip install --no-index --find-links=/kaggle/usr/lib/pip_install_permanent/my_packages -r /kaggle/usr/lib/pip_install_permanent/requirements.txt

In [ ]:
# import os
# os.environ['PACKAGE_DIR'] = '/kaggle/usr/lib/pip_install_permanent'

In [65]:
import sklearn
print(sklearn.__version__)

1.2.2

In [66]:
from helper_func import *
# # import helper_functions as hf
# import sys
# import nltk
# from nltk.corpus import stopwords
# from nltk.stem import WordNetLemmatizer
# import string
# from spellchecker import SpellChecker
# from textblob import TextBlob
# from multiprocessing import Pool
# from tqdm import tqdm
# import numpy as np
# import pandas as pd
# # Preprocessing
# from nltk.tokenize import word_tokenize, sent_tokenize
# import operator
# from spellchecker import SpellChecker
# from tqdm import tqdm  # Import tqdm
# import re
# import inflect
# from wordsegment import load, segment
# from nltk.corpus import words
# word_list = set(words.words())
# from spellchecker import SpellChecker

# from tqdm.contrib.concurrent import process_map  # If this import fails, you might need to update tqdm

# import multiprocessing
 
# # Import Packages
# # import shutup; shutup.please()
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import tensorflow as tf
# import keras_tuner as kt
# import seaborn as sns

# from nltk.corpus import stopwords, wordnet
# from nltk.tokenize import word_tokenize, sent_tokenize
# from nltk import pos_tag, ne_chunk
# from textblob import TextBlob

# from textstat import flesch_reading_ease, smog_index

# import spacy
# from collections import Counter
# from gensim import corpora, models
# import pyLDAvis.gensim as gen
# import pyLDAvis
# import re

# # Machine Learning & Data Preprocessing

# from sklearn.preprocessing import StandardScaler, MinMaxScaler
# from sklearn.model_selection import train_test_split
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import cosine_similarity

# # Deep Learning

# from tensorflow.keras import layers
# from tensorflow.keras.preprocessing.text import Tokenizer
# from tensorflow.keras.preprocessing.sequence import pad_sequences

# # Gensim
# # from gensim.models import Word2Vec, KeyedVectors
# import pandas as pd
# # Progress bar
# from tqdm import tqdm

# # Keras Tuner
# from keras_tuner.tuners import RandomSearch

# # # Setting logging levels and environment variables
# # tf.get_logger().setLevel(logging.ERROR)
# # os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

# from textstat import flesch_reading_ease

# # from helper_functions import *
# import nltk
# from nltk.corpus import stopwords
# from nltk.stem import WordNetLemmatizer
# import string
# from spellchecker import SpellChecker
# from textblob import TextBlob
# from multiprocessing import Pool
# from tqdm import tqdm
# import numpy as np
# import pandas as pd
# # Preprocessing
# from nltk.tokenize import word_tokenize, sent_tokenize
# import operator
# from spellchecker import SpellChecker
# from tqdm import tqdm  # Import tqdm
# import re
# import inflect
# from wordsegment import load, segment
# from nltk.corpus import words
# word_list = set(words.words())
# print('Packages Instaled......')
import sklearn
print(sklearn.__version__)

1.2.2

In [67]:
import sklearn
print(sklearn.__version__)

1.2.2

In [68]:
# import pandas as pd

# deberta_train = pd.read_csv('/home/jack/github/kaggle/scoring/deberta_train_predictions.csv')
# deberta_val = pd.read_csv('/home/jack/github/kaggle/scoring/deberta_val_predictions.csv')

In [69]:
# deberta_full = pd.concat([deberta_train, deberta_val])
# deberta_full.head()

In [70]:
pd.set_option('display.max_columns', None)

deberta_full = pd.read_csv('/home/jack/github/kaggle/scoring/xlnet_hash.csv')
deberta_full.drop(columns=['score', 'labels'], inplace=True)
deberta_full.head()

,essay_id,clean_text,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199
0,000fe60,i am a scientist at nasa that is discussing th...,0.015906,0.832160,0.148738,0.002510,0.000311,0.000375,0.136665,0.115104,0.258191,0.112356,0.164195,0.213489,0.071429,0.023810,0.023810,0.000000,0.000000,0.119048,0.000000,0.02381,0.000000,0.047619,0.023810,0.023810,0.023810,0.0,0.119048,0.023810,0.02381,0.000000,0.119048,0.023810,0.000000,0.000000,0.000000,0.023810,0.000000,0.0,0.000000,0.023810,0.000000,0.047619,0.000000,0.000000,0.047619,0.071429,0.047619,0.071429,0.000000,0.142857,0.000000,0.000000,0.190476,0.000000,0.000000,0.023810,0.000000,0.190476,0.047619,0.000000,0.000000,0.000000,0.000000,0.095238,0.000000,0.000000,0.000000,0.095238,0.071429,0.047619,0.000000,0.023810,0.023810,0.119048,0.047619,0.000000,0.000000,0.000000,0.0,0.000000,0.023810,0.023810,0.0,0.000000,0.000000,0.023810,0.023810,0.071429,0.047619,0.285714,0.000000,0.000000,0.000000,0.047619,0.000000,0.000000,0.00000,0.023810,0.119048,0.047619,0.023810,0.023810,0.071429,0.214286,0.023810,0.095238,0.000000,0.261905,0.000000,0.047619,0.023810,0.071429,0.000000,0.02381,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.023810,0.071429,0.285714,0.023810,0.000000,0.000000,0.071429,0.000000,0.000000,0.190476,0.023810,0.000000,0.023810,0.000000,0.023810,0.238095,0.000000,0.047619,0.000000,0.000000,0.000000,0.000000,0.071429,0.000000,0.000000,0.000000,0.000000,0.142857,0.0,0.000000,0.023810,0.071429,0.0,0.023810,0.047619,0.000000,0.095238,0.000000,0.0,0.02381,0.000000,0.000000,0.000000,0.047619,0.190476,0.023810,0.142857,0.000000,0.071429,0.214286,0.023810,0.047619,0.000000,0.000000,0.023810,0.000000,0.000000,0.047619,0.0,0.000000,0.047619,0.000000,0.02381,0.00000,0.000000,0.000000,0.071429,0.000000,0.000000,0.02381,0.000000,0.000000,0.071429,0.142857,0.0,0.047619,0.023810,0.047619,0.047619,0.285714,0.095238,0.000000,0.119048,0.000000,0.000000,0.000000,0.023810,0.190476,0.071429,0.000000,0.02381
1,001ab80,people always wish they had the same technolog...,0.001099,0.010704,0.344778,0.631197,0.011407,0.000815,0.132327,0.110495,0.258206,0.115311,0.163469,0.220192,0.014565,0.000000,0.058259,0.000000,0.014565,0.058259,0.189343,0.00000,0.014565,0.029130,0.014565,0.058259,0.000000,0.0,0.029130,0.014565,0.00000,0.014565,0.000000,0.014565,0.000000,0.000000,0.000000,0.014565,0.014565,0.0,0.000000,0.029130,0.000000,0.160213,0.014565,0.029130,0.000000,0.029130,0.058259,0.043694,0.000000,0.145648,0.014565,0.029130,0.087389,0.029130,0.116519,0.000000,0.014565,0.116519,0.029130,0.000000,0.014565,0.043694,0.014565,0.014565,0.043694,0.029130,0.000000,0.043694,0.000000,0.014565,0.000000,0.000000,0.029130,0.131083,0.058259,0.014565,0.014565,0.000000,0.0,0.000000,0.014565,0.000000,0.0,0.000000,0.014565,0.029130,0.014565,0.072824,0.058259,0.145648,0.043694,0.029130,0.145648,0.000000,0.029130,0.000000,0.02913,0.029130,0.160213,0.029130,0.000000,0.131083,0.043694,0.305861,0.087389,0.087389,0.000000,0.189343,0.000000,0.014565,0.145648,0.014565,0.014565,0.00000,0.0,0.145648,0.000000,0.000000,0.000000,0.0,0.043694,0.000000,0.087389,0.160213,0.000000,0.014565,0.000000,0.029130,0.000000,0.014565,0.072824,0.029130,0.000000,0.029130,0.000000,0.014565,0.043694,0.014565,0.072824,0.029130,0.014565,0.000000,0.014565,0.087389,0.000000,0.101954,0.145648,0.116519,0.116519,0.0,0.014565,0.000000,0.000000,0.0,0.014565,0.014565,0.014565,0.160213,0.014565,0.0,0.00000,0.029130,0.000000,0.014565,0.087389,0.043694,0.000000,0.014565,0.043694,0.029130,0.407815,0.029130,0.000000,0.058259,0.014565,0.072824,0.000000,0.043694,0.029130,0.0,0.014565,0.058259,0.000000,0.00000,0.02913,0.000000,0.000000,0.000000,0.087389,0.014565,0.00000,0.000000,0.029130,0.029130,0.189343,0.0,0.101954,0.043694,0.087389,0.087389,0.189343,0.116519,0.029130,0.043694,0.014565,0.014565,0.000000,0.014565,0.262167,0.014565,0.000000,0.00000
2,002ba53,dear state senator this is a letter to argue i...,0.059430,0.691130,0.233244,0.014120,0.001189,0.000887,0.132971,0.113607,0.266656,0.112359,0.161093,0.213313,0.047637,0.000000,0.079395,0.015879,0.000000,0.000000,0.015879,0.00000,0.000000,0.000000,0.015879,0.079395,0.015879,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.063516,0.000000,0.031758,0.0,0.000000,0.015879,0.000000,0.031758,0.031758,0.000000,0.000000,0.000000,0.063516,0.015879,0.000000,0.015879,0.000000,0.015879,0.000000,0.015879,0.000000,0.031758,0.031758,0.079395,0.000000,0.206427,0.015879,0.000000,0.000000,0.015879,0.095274,0.095274,0.047637,0.015879,0.015879,0.000000,0.031758,0.015879,0.015879,0.000000,0.111153,0.015879,0.079395,0.000000,0.0,0.000000,0.000000,0.015879,0.0,0.000000,0.015879,0.015879,0.000000,0.047637,0.031758,0.238185,0.015879,0.000000,0.031758,0.000000,0.000000,0.015879,0.00000,0.000000,0.063516,0.285822,0.031758,0.238185,0.063516,0.079395,0.047637,0.031758,0.000000,0.127032,0.142911,0.031758,0.047637,0.127032,0.000000,0.00000,0.0,0.000000,0.031758,0.000000,0.031758,0.0,0.015879,0.000000,0.063516,0.031758,0.015879,0.000000,0.031758,0.000000,0.000000,0.000000,0.127032,0.000000,0.000000,0.000000,0.047637,0.015879,0.015879,0.047637,0.000000,0.000000,0.000000,0.000000,0.015879,0.031758,0.031758,0.000000,0.047637,0.000000,0.031758,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.015879,0.0,0.00000,0.015879,0.063516,0.000000,0.015879,0.015879,0.015879,0.000000,0.015879,0.000000,0.619282,0.000000,0.000000,0.079395,0.015879,0.031758,0.047637,0.000000,0.063516,0.0,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.015879,0.000000,0.015879,0.000000,0.00000,0.031758,0.000000,0.000000,0.031758,0.0,0.015879,0.031758,0.015879,0.063516,0.095274,0.031758,0.000000,0.031758,0.000000,0.000000,0.000000,0.000000,0.381096,0.000000,0.031758,0.00000
3,0033037,the posibilty of a face reconizing computer wo...,0.110127,0.875540,0.012530,0.000799,0.000427,0.000577,0.133904,0.109733,0.257915,0.112806,0.166446,0.219196,0.000000,0.000000,0.000000,0.000000,0.000000,0.039073,0.000000,0.00000,0.000000,0.078146,0.156293,0.117220,0.000000,0.0,0.039073,0.000000,0.00000,0.000000,0.000000,0.000000,0.039073,0.039073,0.000000,0.000000,0.000000,0.0,0.039073,0.000000,0.039073,0.000000,0.000000,0.039073,0.078146,0.000000,0.039073,0.000000,0.039073,0.039073,0.039073,0.039073,0.039073,0.000000,0.000000,0.000000,0.000000,0.195366,0.000000,0.000000,0.000000,0.078146,0.000000,0.039073,0.039073,0.000000,0.000000,0.000000,0.000000,0.078146,0.000000,0.039073,0.000000,0.039073,0.039073,0.000000,0.156293,0.000000,0.0,0.078146,0.000000,0.000000,0.0,0.078146,0.000000,0.000000,0.000000,0.000000,0.000000,0.195366,0.000000,0.039073,0.000000,0.000000,0.000000,0.195366,0.00000,0.039073,0.156293,0.039073,0.000000,0.273513,0.078146,0.117220,0.000000,0.000000,0.000000,0.156293,0.078146,0.000000,0.039073,0.000000,0.039073,0.00000,0.0,0.117220,0.039073,0.000000,0.000000,0.0,0.000000,0.000000,0.117220,0.078146,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.039073,0.000000,0.000000,0.000000,0.039073,0.039073,0.000000,0.156293,0.000000,0.039073,0.000000,0.000000,0.078146,0.078146,0.078146,0.000000,0.156293,0.000000,0.0,0.000000,0.078146,0.156293,0.0,0.000000,0.000000,0.000000,0.039073,0.039073,0.0,0.00000,0.156293,0.000000,0.039073,0.000000,0.000000,0.078146,0.156293,0.000000,0.000000,0.468879,0.078146,0.000000,0.039073,0.039073,0.195366,0.000000,0.000000,0.039073,0.0,0.000000,0.000000,0.039073,0.00000,0.00000,0.000000,0.000000,0.234439,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.117220,0.000000,0.000000,0.156293,0.000000,0.000000,0.039073,0.000000,0.000000,0.000000,0.000000,0.195366,0.000000,0.000000,0.00000
4,0033bf4,what is the seagoing cowboys progam it was to ...,0.004650,0.469768,0.515730,0.009045,0.000419,0.000389,0.133583,0.111408,0.263863,0.108937,0.168764,0.213444,0.000000,0.019364,0.038727,0.019364,0.000000,0.019364,0.019364,0.00000,0.000000,0.116182,0.000000,0.038727,0.000000,0.0,0.038727,0.000000,0.00000,0.038727,0.019364,0.019364,0.000000,0.019364,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.058091,0.000000,0.000000,0.000000,0.038727,0.038727,0.019364,0.019364,0.019364,0.058091,0.000000,0.058091,0.000000,0.019364,0.000000,0.000000,0.213001,0.000000,0.096819,0.000000,0.019364,0.000000,0.000000,0.019364,0.000000,0.000000,0.019364,0.000000,0.019364,0.000000,0.000000,0.000000,0.116182,0.019364,0.000000,0.019364,0.077455,0.0,0.000000,0.116182,0.077455,0.0,0.000000,0.019364,0.000000,0.019364,0.019364,0.000000,0.019364,0.000000,0.000000,0.000000,0.000000,0.038727,0.000000,0.00000,0.000000,0.038727,0.038727,0.000000,0.135546,0.000000,0.251728,0.000000,0.154910,0.038727,0.135546,0.000000,0.000000,0.116182,0.058091,0.000000,0.00000,0.0,0.000000,0.000000,0.019364,0.000000,0.0,0.000000,0.135546,0.077455,0.058091,0.000000,0.077455,0.000000,0.154910,0.019364,0.000000,0.116182,0.058091,0.019364,0.096819,0.000000,0.096819,0.000000,0.000000,0.038727,0.038727,0.038727,0.077455,0.019364,0.000000,0.000000,0.038727,0.019364,0.077455,0.077455,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.116182,0.019364,0.0,0.00000,0.058091,0.000000,0.000000,0.000000,0.058091,0.000000,0.000000,0.000000,0.077455,0.426002,0.058091,0.154910,0.038727,0.000000,0.077455,0.116182,0.019364,0.058091,0.0,0.000000,0.038727,0.000000,0.00000,0.00000,0.019364,0.000000,0.174273,0.019364,0.000000,0.00000,0.019364,0.077455,0.000000,0.019364,0.0,0.213001,0.077455,0.019364,0.038727,0.445365,0.000000,0.019364,0.019364,0.000000,0.019364,0.019364,0.000000,0.096819,0.193637,0.000000,0.00000

In [71]:
# drop columns with hash in the name

hash_cols = [col for col in deberta_full.columns if 'hash' in col]

deberta_full.drop(columns=hash_cols, inplace=True)

deberta_full.head()

,essay_id,clean_text,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5
0,000fe60,i am a scientist at nasa that is discussing th...,0.015906,0.832160,0.148738,0.002510,0.000311,0.000375,0.136665,0.115104,0.258191,0.112356,0.164195,0.213489
1,001ab80,people always wish they had the same technolog...,0.001099,0.010704,0.344778,0.631197,0.011407,0.000815,0.132327,0.110495,0.258206,0.115311,0.163469,0.220192
2,002ba53,dear state senator this is a letter to argue i...,0.059430,0.691130,0.233244,0.014120,0.001189,0.000887,0.132971,0.113607,0.266656,0.112359,0.161093,0.213313
3,0033037,the posibilty of a face reconizing computer wo...,0.110127,0.875540,0.012530,0.000799,0.000427,0.000577,0.133904,0.109733,0.257915,0.112806,0.166446,0.219196
4,0033bf4,what is the seagoing cowboys progam it was to ...,0.004650,0.469768,0.515730,0.009045,0.000419,0.000389,0.133583,0.111408,0.263863,0.108937,0.168764,0.213444

In [72]:
import pandas as pd
from sklearn.feature_extraction.text import HashingVectorizer


# Initialize the HashingVectorizer
n_features = 500  # Number of columns in the hashed vector
hashing_vectorizer = HashingVectorizer(n_features=n_features, alternate_sign=False)

# Transform the text column into hash vector features
hashed_features = hashing_vectorizer.transform(deberta_full['clean_text'])

# Convert the hashed features to a dense representation for easier manipulation
hashed_features_dense = hashed_features.todense()

# Create new column names based on the number of features
hashed_columns = [f'hash_{i}' for i in range(n_features)]

# Convert dense representation to a dataframe
hashed_df = pd.DataFrame(hashed_features_dense, columns=hashed_columns)

# Concatenate the original dataframe with the hashed dataframe

deberta_full = pd.concat([deberta_full, hashed_df], axis=1)

In [73]:
# deberta_full.tail()

In [74]:
# deberta_full = deberta_full.merge(xlnet, on='essay_id', how='left')
# deberta_full.head()deberta_full.drop(columns=['score', 'labels'], inplace=True)

In [ ]:
# deberta_full.tail()

In [ ]:
# deberta_full.drop(columns=[ 'score'], inplace=True)

In [75]:
train = pd.read_csv('/home/jack/github/kaggle/scoring/data/train.csv')

In [76]:
print(deberta_full.shape, train.shape)

(17307, 514) (17307, 3)

In [77]:
# Combine train and deberta_full on essay_id

train = train.merge(deberta_full, on='essay_id')

In [78]:
train.head()

,essay_id,full_text,score,clean_text,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,hash_200,hash_201,hash_202,hash_203,hash_204,hash_205,hash_206,hash_207,hash_208,hash_209,hash_210,hash_211,hash_212,hash_213,hash_214,hash_215,hash_216,hash_217,hash_218,hash_219,hash_220,hash_221,hash_222,hash_223,hash_224,hash_225,hash_226,hash_227,hash_228,hash_229,hash_230,hash_231,hash_232,hash_233,hash_234,hash_235,hash_236,hash_237,hash_238,hash_239,hash_240,hash_241,hash_242,hash_243,hash_244,hash_245,hash_246,hash_247,hash_248,hash_249,hash_250,hash_251,hash_252,hash_253,hash_254,hash_255,hash_256,hash_257,hash_258,hash_259,hash_260,hash_261,hash_262,hash_263,hash_264,hash_265,hash_266,hash_267,hash_268,hash_269,hash_270,hash_271,hash_272,hash_273,hash_274,hash_275,hash_276,hash_277,hash_278,hash_279,hash_280,hash_281,hash_282,hash_283,hash_284,hash_285,hash_286,hash_287,hash_288,hash_289,hash_290,hash_291,hash_292,hash_293,hash_294,hash_295,hash_296,hash_297,hash_298,hash_299,hash_300,hash_301,hash_302,hash_303,hash_304,hash_305,hash_306,hash_307,hash_308,hash_309,hash_310,hash_311,hash_312,hash_313,hash_314,hash_315,hash_316,hash_317,hash_318,hash_319,hash_320,hash_321,hash_322,hash_323,hash_324,hash_325,hash_326,hash_327,hash_328,hash_329,hash_330,hash_331,hash_332,hash_333,hash_334,hash_335,hash_336,hash_337,hash_338,hash_339,hash_340,hash_341,hash_342,hash_343,hash_344,hash_345,hash_346,hash_347,hash_348,hash_349,hash_350,hash_351,hash_352,hash_353,hash_354,hash_355,hash_356,hash_357,hash_358,hash_359,hash_360,hash_361,hash_362,hash_363,hash_364,hash_365,hash_366,hash_367,hash_368,hash_369,hash_370,hash_371,hash_372,hash_373,hash_374,hash_375,hash_376,hash_377,hash_378,hash_379,hash_380,hash_381,hash_382,hash_383,hash_384,hash_385,hash_386,hash_387,hash_388,hash_389,hash_390,hash_391,hash_392,hash_393,hash_394,hash_395,hash_396,hash_397,hash_398,hash_399,hash_400,hash_401,hash_402,hash_403,hash_404,hash_405,hash_406,hash_407,hash_408,hash_409,hash_410,hash_411,hash_412,hash_413,hash_414,hash_415,hash_416,hash_417,hash_418,hash_419,hash_420,hash_421,hash_422,hash_423,hash_424,hash_425,hash_426,hash_427,hash_428,hash_429,hash_430,hash_431,hash_432,hash_433,hash_434,hash_435,hash_436,hash_437,hash_438,hash_439,hash_440,hash_441,hash_442,hash_443,hash_444,hash_445,hash_446,hash_447,hash_448,hash_449,hash_450,hash_451,hash_452,hash_453,hash_454,hash_455,hash_456,hash_457,hash_458,hash_459,hash_460,hash_461,hash_462,hash_463,hash_464,hash_465,hash_466,hash_467,hash_468,hash_469,hash_470,hash_471,hash_472,hash_473,hash_474,hash_475,hash_476,hash_477,hash_478,hash_479,hash_480,hash_481,hash_482,hash_483,hash_484,hash_485,hash_486,hash_487,hash_488,hash_489,hash_490,hash_491,hash_492,hash_493,hash_494,hash_495,hash_496,hash_497,hash_498,hash_499
0,000d118,Many people have car where they live. The thin...,3,many people have car where they live the thing...,0.156896,0.756281,0.079829,0.005163,0.000922,0.000909,0.116983,0.173203,0.157604,0.287849,0.154709,0.109652,0.034437,0.000000,0.0,0.017218,0.000000,0.000000,0.0,0.000000,0.034437,0.0,0.154965,0.000000,0.017218,0.000000,0.000000,0.00000,0.00000,0.00000,0.000000,0.017218,0.017218,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.275494,0.0,0.068873,0.017218,0.000000,0.000000,0.000000,0.0,0.068873,0.0,0.017218,0.068873,0.000000,0.017218,0.0,0.0,0.000000,0.0,0.0,0.0,0.017218,0.00000,0.0,0.017218,0.000000,0.017218,0.000000,0.000000,0.0,0.0,0.034437,0.051655,0.034437,0.000000,0.068873,0.000000,0.000000,0.034437,0.0,0.000000,0.017218,0.017218,0.0,0.0,0.000000,0.017218,0.000000,0.017218,0.0,0.051655,0.017218,0.000000,0.000000,0.086092,0.000000,0.034437,0.000000,0.017218,0.034437,0.017218,0.000000,0.00000,0.034437,0.017218,0.051655,0.00000,0.017218,0.000000,0.000000,0.000000,0.017218,0.000000,0.0,0.000000,0.0,0.000000,0.017218,0.241057,0.0,0.000000,0.017218,0.034437,0.051655,0.017218,0.0,0.034437,0.0,0.000000,0.00000,0.017218,0.000000,0.0,0.0,0.017218,0.0,0.034437,0.000000,0.051655,0.00000,0.017218,0.017218,0.0,0.017218,0.0,0.0,0.000000,0.0,0.154965,0.0,0.000000,0.017218,0.00000,0.000000,0.000000,0.0,0.000000,0.068873,0.00000,0.000000,0.000000,0.000000,0.0,0.017218,0.000000,0.0,0.000000,0.00000,0.000000,0.000000,0.000000,0.017218,0.0,0.034437,0.0,0.0,0.0,0.034437,0.00000,0.0,0.0,0.0,0.0,0.017218,0.034437,0.017218,0.000000,0.0,0.000000,0.000000,0.000000,0.017218,0.017218,0.0,0.017218,0.0,0.034437,0.051655,0.000000,0.000000,0.017218,0.275494,0.000000,0.309931,0.000000,0.103310,0.017218,0.017218,0.172184,0.000000,0.0,0.017218,0.000000,0.0,0.051655,0.0,0.0,0.000000,0.000000,0.017218,0.0,0.034437,0.000000,0.086092,0.000000,0.0,0.000000,0.000000,0.0,0.034437,0.0,0.000000,0.068873,0.034437,0.017218,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.086092,0.000000,0.000000,0.034437,0.017218,0.000000,0.000000,0.000000,0.086092,0.051655,0.017218,0.017218,0.017218,0.000000,0.0,0.0,0.000000,0.000000,0.051655,0.000000,0.0,0.0,0.0,0.051655,0.000000,0.00000,0.000000,0.017218,0.017218,0.0,0.0,0.0,0.017218,0.00000,0.000000,0.000000,0.000000,0.068873,0.0,0.017218,0.000000,0.017218,0.017218,0.034437,0.0,0.0,0.000000,0.00000,0.137747,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.034437,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.103310,0.0,0.017218,0.0,0.0,0.086092,0.034437,0.000000,0.0,0.034437,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.00000,0.017218,0.0,0.086092,0.00000,0.0,0.0,0.000000,0.0,0.000000,0.017218,0.0,0.0,0.034437,0.0,0.017218,0.000000,0.0,0.000000,0.0,0.00000,0.017218,0.0,0.017218,0.0,0.017218,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.034437,0.017218,0.000000,0.000000,0.000000,0.223839,0.051655,0.017218,0.017218,0.017218,0.000000,0.017218,0.017218,0.017218,0.017218,0.017218,0.000000,0.068873,0.0,0.0,0.00000,0.00000,0.000000,0.0,0.017218,0.000000,0.000000,0.0,0.017218,0.000000,0.034437,0.000000,0.00000,0.00000,0.000000,0.000000,0.017218,0.000000,0.000000,0.0,0.000000,0.000000,0.017218,0.0,0.017218,0.000000,0.017218,0.0,0.120529,0.000000,0.000000,0.000000,0.00000,0.017218,0.00000,0.361586,0.017218,0.017218,0.017218,0.017218,0.000000,0.0,0.000000,0.034437,0.017218,0.0,0.0,0.0,0.000000,0.017218,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.00000,0.0,0.051655,0.017218,0.017218,0.000000,0.103310,0.000000,0.000000,0.000000,0.000000,0.034437,0.00000,0.000000,0.017218,0.000000,0.0,0.000000,0.068873,0.034437,0.017218,0.000000,0.034437,0.017218,0.051655,0.017218,0.000000,0.000000,0.017218,0.000000,0.0,0.0,0.017218,0.000000,0.000000,0.017218,0.068873,0.017218,0.000000,0.000000,0.000000,0.017218,0.361586,0.017218,0.000000,0.000000,0.068873,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.034437,0.00000,0.0,0.0,0.017218,0.051655,0.000000,0.017218,0.00000,0.000000,0.000000,0.068873,0.000000,0.017218,0.068873,0.017218,0.051655,0.137747,0.086092,0.000000,0.000000,0.000000,0.000000,0.00000,0.0,0.000000,0.034437,0.000000,0.000000,0.000000
1,000fe60,I am a scientist at NASA that is discussing th...,3,i am a scientist at nasa that is discussing th...,0.015906,0.832160,0.148738,0.002510,0.000311,0.000375,0.136665,0.115104,0.258191,0.112356,0.164195,0.213489,0.000000,0.051198,0.0,0.000000,0.000000,0.000000,0.0,0.025599,0.000000,0.0,0.076797,0.127995,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.025599,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.051198,0.0,0.051198,0.051198,0.000000,0.000000,0.025599,0.0,0.000000,0.0,0.000000,0.255990,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.00000,0.0,0.000000,0.153594,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.102396,0.000000,0.025599,0.000000,0.000000,0.000000,0.0,0.025599,0.025599,0.000000,0.0,0.0,0.025599,0.000000,0.051198,0.000000,0.0,0.000000,0.000000,0.000000,0.025599,0.153594,0.000000,0.051198,0.025599,0.000000,0.025599,0.051198,0.000000,0.00000,0.000000,0.025599,0.051198,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.076797,0.0,0.000000,0.0,0.000000,0.102396,0.000000,0.0,0.000000,0.000000,0.000000,0.179193,0.025599,0.0,0.127995,0.0,0.025599,0.00000,0.051198,0.025599,0.0,0.0,0.000000,0.0,0.076797,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.127995,0.0,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000,0.076797,0.00000,0.000000,0.025599,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.00000,0.000000,0.076797,0.000000,0.025599,0.0,0.000000,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.051198,0.000000,0.025599,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.025599,0.000000,0.025599,0.025599,0.025599,0.025599,0.230391,0.000000,0.025599,0.000000,0.025599,0.179193,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.025599,0.000000,0.000000,0.0,0.025599,0.025599,0.000000,0.025599,0.0,0.000000,0.051198,0.0,0.000000,0.0,0.025599,0.000000,0.025599,0.000000,0.0,0.025599,0.000000,0.0,0.025599,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.025599,0.025599,0.127995,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.025599,0.051198,0.000000,0.000000,0.0,0.0,0.0,0.051198,0.000000,0.00000,0.000000,0.051198,0.000000,0.0,0.0,0.0,0.025599,0.00000,0.000000,0.000000,0.000000,0.051198,0.0,0.000000,0.000000,0.000000,0.025599,0.000000,0.0,0.0,0.076797,0.00000,0.307188,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.00000,0.127995,0.025599,0.000000,0.000000,0.000000,0.102396,0.0,0.025599,0.0,0.0,0.025599,0.076797,0.000000,0.0,0.000000,0.0,0.025599,0.0,0.0,0.000000,0.0,0.0,0.00000,0.000000,0.0,0.025599,0.00000,0.0,0.0,0.025599,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.025599,0.000000,0.0,0.000000,0.0,0.00000,0.000000,0.0,0.000000,0.0,0.076797,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.076797,0.000000,0.204792,0.000000,0.000000,0.000000,0.000000,0.000000,0.102396,0.000000,0.051198,0.025599,0.255990,0.000000,0.051198,0.0,0.0,0.00000,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.025599,0.025599,0.000000,0.000000,0.000000,0.0,0.000000,0.102396,0.000000,0.0,0.000000,0.000000,0.051198,0.0,0.127995,0.102396,0.025599,0.000000,0.00000,0.000000,0.00000,0.281589,0.000000,0.051198,0.025599,0.076797,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.051198,0.000000,0.0,0.0,0.0,0.000000,0.025599,0.00000,0.0,0.255990,0.000000,0.000000,0.000000,0.000000,0.025599,0.153594,0.000000,0.051198,0.000000,0.00000,0.000000,0.000000,0.025599,0.0,0.000000,0.051198,0.025599,0.000000,0.025599,0.000000,0.025599,0.025599,0.000000,0.025599,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.025599,0.000000,0.230391,0.025599,0.076797,0.000000,0.051198,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.051198,0.000000,0.00000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.025599,0.127995,0.000000,0.025599,0.025599,0.000000,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.025599
2,001ab80,People always wish they had the same technolog...,4,people always wish they had the same technolog...,0.001099,0.010704,0.344778,0.631197,0.011407,0.000815,0.132327,0.110495,0.258206,0.115311,0.163469,0.220192,0.015931,0.000000,0.0,0.000000,0.000000,0.047794,0.0,0.000000,0.000000,0.0,0.095588,0.015931,0.000000,0.015931,0.000000,0.00000,0.00000,0.00000,0.000000,0.015931,0.000000,0.015931,0.000000,0.015931,0.0,0.0,0.0,0.031863,0.0,0.175245,0.0,0.095588,0.000000,0.015931,0.031863,0.015931,0.0,0.000000,0.0,0.000000,0.031863,0.015931,0.031863,0.0,0.0,0.031863,0.0,0.0,0.0,0.047794,0.00000,0.0,0.000000,0.015931,0.000000,0.015931,0.015931,0.0,0.0,0.031863,0.031863,0.111519,0.063725,0.063725,0.000000,0.015931,0.000000,0.0,0.015931,0.015931,0.000000,0.0,0.0,0.015931,0.000000,0.000000,0.031863,0.0,0.000000,0.000000,0.000000,0.000000,0.143382,0.000000,0.095588,0.000000,0.047794,0.015931,0.000000,0.015931,0.00000,0.000000,0.047794,0.015931,0.00000,0.015931,0.000000,0.000000,0.047794,0.015931,0.000000,0.0,0.000000,0.0,0.015931,0.000000,0.207107,0.0,0.000000,0.000000,0.000000,0.047794,0.000000,0.0,0.015931,0.0,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.047794,0.015931,0.031863,0.00000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.143382,0.0,0.127451,0.0,0.015931,0.000000,0.00000,0.015931,0.000000,0.0,0.015931,0.111519,0.00000,0.000000,0.000000,0.015931,0.0,0.000000,0.031863,0.0,0.000000,0.00000,0.015931,0.031863,0.000000,0.000000,0.0,0.047794,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.000000,0.031863,0.015931,0.015931,0.0,0.063725,0.015931,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.031863,0.000000,0.000000,0.000000,0.127451,0.031863,0.318626,0.031863,0.047794,0.000000,0.000000,0.286764,0.015931,0.0,0.000000,0.000000,0.0,0.031863,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.031863,0.000000,0.143382,0.000000,0.0,0.000000,0.031863,0.0,0.000000,0.0,0.031863,0.000000,0.015931,0.000000,0.0,0.000000,0.000000,0.0,0.031863,0.015931,0.000000,0.031863,0.000000,0.000000,0.000000,0.000000,0.015931,0.000000,0.063725,0.000000,0.015931,0.015931,0.000000,0.095588,0.0,0.0,0.031863,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.047794,0.015931,0.00000,0.015931,0.015931,0.000000,0.0,0.0,0.0,0.047794,0.00000,0.015931,0.000000,0.015931,0.031863,0.0,0.000000,0.031863,0.000000,0.000000,0.015931,0.0,0.0,0.000000,0.00000,0.143382,0.0,0.015931,0.015931,0.031863,0.000000,0.0,0.015931,0.00000,0.159313,0.031863,0.000000,0.015931,0.015931,0.015931,0.0,0.047794,0.0,0.0,0.000000,0.000000,0.015931,0.0,0.000000,0.0,0.000000,0.0,0.0,0.015931,0.0,0.0,0.00000,0.000000,0.0,0.031863,0.00000,0.0,0.0,0.000000,0.0,0.031863,0.015931,0.0,0.0,0.000000,0.0,0.000000,0.015931,0.0,0.000000,0.0,0.00000,0.000000,0.0,0.015931,0.0,0.031863,0.015931,0.031863,0.00000,0.079657,0.015931,0.00000,0.047794,0.000000,0.000000,0.015931,0.000000,0.127451,0.047794,0.000000,0.000000,0.000000,0.015931,0.015931,0.031863,0.047794,0.000000,0.031863,0.000000,0.015931,0.0,0.0,0.00000,0.00000,0.000000,0.0,0.000000,0.015931,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.063725,0.015931,0.047794,0.0,0.015931,0.000000,0.000000,0.0,0.000000,0.000000,0.047794,0.0,0.015931,0.095588,0.031863,0.015931,0.00000,0.000000,0.00000,0.191176,0.000000,0.000000,0.095588,0.000000,0.015931,0.0,0.031863,0.159313,0.000000,0.0,0.0,0.0,0.063725,0.000000,0.015931,0.0,0.0,0.0,0.015931,0.015931,0.00000,0.0,0.063725,0.000000,0.000000,0.000000,0.000000,0.015931,0.000000,0.000000,0.047794,0.000000,0.00000,0.000000,0.000000,0.015931,0.0,0.095588,0.031863,0.111519,0.000000,0.015931,0.000000,0.015931,0.000000,0.000000,0.015931,0.000000,0.015931,0.000000,0.0,0.0,0.015931,0.015931,0.000000,0.015931,0.031863,0.000000,0.000000,0.000000,0.000000,0.000000,0.446077,0.000000,0.000000,0.000000,0.015931,0.015931,0.015931,0.0,0.0,0.0,0.015931,0.015931,0.000000,0.00000,0.0,0.0,0.000000,0.079657,0.000000,0.000000,0.00000,0.015931,0.159313,0.000000,0.095588,0.000000,0.031863,0.047794,0.015931,0.079657,0.191176,0.015931,0.000000,0.031863,0.031863,0.00000,0.0,0.015931,0.000000,0.015931,0.000000,0.000000

In [81]:
df = train.copy()

In [82]:
# import pandas as pd
# import numpy as np
# import re
# from nltk.corpus import stopwords
# from nltk.tokenize import word_tokenize
# from nltk.stem import PorterStemmer
# from sklearn.feature_extraction.text import HashingVectorizer
# import spacy

# # Custom Preprocessing
# def custom_preprocessing(text):
#     text = text.lower()
#     text = re.sub(r'[^\w\s]', '', text)
#     tokens = word_tokenize(text)
#     stop_words = set(stopwords.words('english'))
#     tokens = [word for word in tokens if word not in stop_words]
#     ps = PorterStemmer()
#     tokens = [ps.stem(word) for word in tokens]
#     return ' '.join(tokens)

# # Initialize a HashingVectorizer
# vectorizer = HashingVectorizer(n_features=2**10, ngram_range=(1, 3), preprocessor=custom_preprocessing)

# # Load spaCy model
# nlp = spacy.load("en_core_web_sm")

# def hash_features(tag_counts, total_count, n_features=256):
#     # Initialize a vector of zeros with size `n_features`
#     feature_vector = np.zeros(n_features)
#     for tag, count in tag_counts.items():
#         # Hash the tag to a position in the feature vector
#         index = hash(tag) % n_features
#         # Add the normalized count to the corresponding position in the feature vector
#         feature_vector[index] += count / total_count
#     return feature_vector

# def extract_features(text):
#     doc = nlp(text)
#     total_tokens = len(doc)
#     pos_counts = doc.count_by(spacy.attrs.POS)
#     dep_counts = doc.count_by(spacy.attrs.DEP)
#     ner_counts = {}
#     for ent in doc.ents:
#         ner_counts[ent.label_] = ner_counts.get(ent.label_, 0) + 1
#     total_entities = sum(ner_counts.values()) or 1  # Avoid division by zero

#     # Hash each set of features with normalization
#     pos_features = hash_features({doc.vocab.strings[pos_id]: count for pos_id, count in pos_counts.items()}, total_tokens)
#     dep_features = hash_features({doc.vocab.strings[dep_id]: count for dep_id, count in dep_counts.items()}, total_tokens)
#     ner_features = hash_features(ner_counts, total_entities)

#     # Concatenate all feature vectors
#     return np.concatenate([pos_features, dep_features, ner_features])

# # Assuming 'full_text' column contains the text data
# # Example DataFrame loading step (replace with actual data loading)
# # df = pd.read_csv('your_dataset.csv')

# # Extract n-gram features with progress bar
# tqdm.pandas(desc="Hashing n-grams")
# X_ngrams = vectorizer.fit_transform(tqdm(df['full_text'], desc="Vectorizing"))

# # Apply the feature extraction for POS, DEP, and NER with ratios and progress bar
# tqdm.pandas(desc="Extracting features")
# df['hashed_features'] = df['full_text'].progress_apply(extract_features)
# features_df = pd.DataFrame(list(df['hashed_features']))

# # Concatenate n-gram features with hashed linguistic features
# final_df = pd.concat([pd.DataFrame(X_ngrams.toarray()), features_df], axis=1)

# # Ensure all missing values are filled
# final_df.fillna(0, inplace=True)

In [84]:
# final_df.head()

In [83]:
# # Number of features for each type based on your setup
# ngram_features = 1024  # From HashingVectorizer
# pos_features = 256     # From hash_features for POS tags
# dep_features = 256     # From hash_features for DEP tags
# ner_features = 256     # From hash_features for NER tags

# # Generate feature names
# ngram_feature_names = [f'ngram_{i}' for i in range(ngram_features)]
# pos_feature_names = [f'pos_hashed_{i}' for i in range(pos_features)]
# dep_feature_names = [f'dep_hashed_{i}' for i in range(dep_features)]
# ner_feature_names = [f'ner_hashed_{i}' for i in range(ner_features)]

# # Concatenate all feature names
# feature_names = ngram_feature_names + pos_feature_names + dep_feature_names + ner_feature_names

# # Assuming `final_df` is your DataFrame with all features
# final_df.columns = feature_names

In [ ]:
# final_df.head()

In [ ]:
# train = pd.concat([train, final_df], axis=1)

In [ ]:
# import spacy

# # Load a spaCy model

# nlp = spacy.load("en_core_web_sm")

# # Function to count POS tags and return a dictionary
# def pos_counts(text):
#     doc = nlp(text)
#     pos_counts = doc.count_by(spacy.attrs.POS)
#     return {doc.vocab.strings[pos_id]: count for pos_id, count in pos_counts.items()}

# # Create a DataFrame with POS counts for each document
# df_pos = df['full_text'].apply(pos_counts).apply(pd.Series).fillna(0)
# df_pos.columns = [f'pos_{col}' for col in df_pos.columns]

# # Concatenate POS feature DataFrame back to the original DataFrame
# # df = pd.concat([df, df_pos], axis=1)

In [ ]:
# df_pos.head()

In [ ]:
# # Extract named entities and count by types
# def named_entities(text):
#     doc = nlp(text)
#     entities = {}
#     for ent in doc.ents:
#         entities[ent.label_] = entities.get(ent.label_, 0) + 1
#     return entities

# # Create a DataFrame with named entity counts
# df_entities = df['full_text'].apply(named_entities).apply(pd.Series).fillna(0)
# df_entities.columns = [f'ner_{col}' for col in df_entities.columns]

# # Concatenate entity feature DataFrame back to the original DataFrame
# # df = pd.concat([df, df_entities], axis=1)

In [ ]:
# df_entities.head()

In [ ]:
# df_entities.tail()

In [ ]:
# def dependency_tags(text):
#     doc = nlp(text)
#     dep_counts = doc.count_by(spacy.attrs.DEP)
#     return {doc.vocab.strings[dep_id]: count for dep_id, count in dep_counts.items()}

# df_deps = df['full_text'].apply(dependency_tags).apply(pd.Series).fillna(0)

# df_deps.columns = [f'dep_{col}' for col in df_deps.columns]

# # df = pd.concat([df, df_deps], axis=1)

In [ ]:
# df_deps.tail()

In [ ]:
# from gensim.scripts.glove2word2vec import glove2word2vec

# glove_input_file = '/home/jack/github/kaggle/scoring/data/glove.6B.100d.txt'
# word2vec_output_file = 'word2vec.glove.6B.100d.txt'
# glove2word2vec(glove_input_file, word2vec_output_file)

In [ ]:
# from sklearn.feature_extraction.text import CountVectorizer
# import pandas as pd
# import spacy
# import numpy as np
# import pickle
# from gensim.models import KeyedVectors
# from sklearn.decomposition import PCA

# df_train = train.copy()

# # Load spaCy model

# # Load GloVe model
# glove_model = KeyedVectors.load_word2vec_format('glove.840B.300d.word2vec.clean', binary=False, no_header=True)

# # Initialize CountVectorizer with tokens that exist in the GloVe vocabulary
# vectorizer = CountVectorizer(ngram_range=(1, 3), max_features=500, vocabulary=set(glove_model.key_to_index.keys()))

# # Function to embed text using GloVe embeddings
# def embed_text(text, model, vectorizer):
#     matrix = vectorizer.transform([text])
#     words = vectorizer.get_feature_names_out()
#     embeddings = np.zeros((300,))  # Corrected to 300 dimensions
#     for word in words:
#         if word in model:
#             embeddings += model[word] * matrix[0, vectorizer.vocabulary_[word]]
#     return embeddings / len(words) if len(words) > 0 else embeddings

# # Embed the text data

# # Collect and embed tags
# def get_tag_embeddings(text, model):
#     doc = nlp(text)
#     tag_vector = np.zeros((300,))  # Corrected to 300 dimensions
#     tags = doc.count_by(spacy.attrs.POS)
#     for tag_id, count in tags.items():
#         tag = doc.vocab.strings[tag_id]
#         if tag.lower() in model:
#             tag_vector += model[tag.lower()] * count
#     return tag_vector

# df_train['tag_embeddings'] = df_train['full_text'].apply(lambda x: get_tag_embeddings(x, glove_model))

# # Apply PCA to reduce dimensionality
# pca = PCA(n_components=50)  # Reduce to 50 features for example
# features = np.vstack(df_train['text_embeddings'].values)
# tag_features = np.vstack(df_train['tag_embeddings'].values)
# combined_features = np.hstack((features, tag_features))

# pca_features = pca.fit_transform(combined_features)

# # Create a DataFrame from the PCA features
# df_train_pca = pd.DataFrame(pca_features, columns=[f'pca_feature_{i}' for i in range(pca_features.shape[1])])

# # Concatenate PCA features back to the original DataFrame
# df_train_final = pd.concat([df_train.reset_index(drop=True), df_train_pca], axis=1)

# # Serialize and save the PCA model and vectorizer
# with open('vectorizer.pkl', 'wb') as f:
#     pickle.dump(vectorizer, f)
# with open('pca_model.pkl', 'wb') as f:
#     pickle.dump(pca, f)

In [ ]:
import pandas as pd
import numpy as np
from scipy.stats import skew, kurtosis

# Function to calculate statistical features for a list of tag counts
# Function to calculate statistical features for a list of tag counts
def calculate_statistical_features(tag_counts):
    # Calculate statistical features
    mean = np.mean(tag_counts)
    std = np.std(tag_counts)
    max_count = np.max(tag_counts)
    min_count = np.min(tag_counts)

    # Check if standard deviation is close to zero
    if np.isclose(std, 0):
        skewness = 0
        kurt = 0
    else:
        skewness = skew(tag_counts)
        kurt = kurtosis(tag_counts)
        
    return mean, std, max_count, min_count, skewness, kurt

# Function to extract statistical features from tag dataframes
def extract_statistical_features(tag_df,tag=None):
    # Calculate statistical features across rows
    tag_df[f'{tag}_mean'], tag_df[f'{tag}_std'], tag_df[f'{tag}_max'], tag_df[f'{tag}_min'], tag_df[f'{tag}_skew'], tag_df[f'{tag}_kurtosis'] = \
        zip(*tag_df.apply(lambda row: calculate_statistical_features(row), axis=1))

    tag_df.drop(columns=tag_df.columns[:-6], inplace=True)
    
    return tag_df

# Assuming you have separate dataframes for each tag type: pos_df, ner_df, dep_df
# You would pass these dataframes to the function accordingly
# For example:

pos_df = df_pos.copy()    # dataframe containing POS tag counts
ner_df = df_entities.copy()  # dataframe containing named entity tag counts
dep_df = df_deps.copy()  # dataframe containing dependency tag counts

# Extract statistical features for each tag type
pos_features = extract_statistical_features(pos_df,tag='pos')
ner_features = extract_statistical_features(ner_df,tag='ner')
dep_features = extract_statistical_features(dep_df,tag='dep')

# Concatenate statistical features DataFrames back to the original DataFrame
final_df = pd.concat([df.reset_index(drop=True), pos_features, ner_features, dep_features], axis=1)

In [ ]:
# final_df.tail()

In [ ]:
# train.to_parquet('train_with_deberta.parquet')

In [ ]:
# train = final_df.copy()

In [91]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

df = train.copy()


# Initialize a CountVectorizer with n-gram range from 1 to 3 (unigrams to trigrams)
vectorizer = CountVectorizer(ngram_range=(1, 3), max_features=1000, stop_words='english')

# Assuming 'essay' column contains the text data
X_ngrams = vectorizer.fit_transform(df['full_text'])

# Convert the matrix to a DataFrame
df_ngrams = pd.DataFrame(X_ngrams.toarray(), columns=vectorizer.get_feature_names_out())

df = pd.concat([df.reset_index(drop=True), df_ngrams.reset_index(drop=True)], axis=1)



import spacy

# Load a spaCy model

nlp = spacy.load("en_core_web_sm")

# Function to count POS tags and return a dictionary
def pos_counts(text):
    doc = nlp(text)
    total_tokens = len(doc)
    pos_counts = doc.count_by(spacy.attrs.POS)
    return {f'pos_{doc.vocab.strings[pos_id]}': count / total_tokens for pos_id, count in pos_counts.items() if total_tokens > 0}


# Create a DataFrame with POS counts for each document
df_pos = df['full_text'].apply(pos_counts).apply(pd.Series).fillna(0)
df_pos.columns = [f'pos_{col}' for col in df_pos.columns]

# Concatenate POS feature DataFrame back to the original DataFrame
df = pd.concat([df, df_pos], axis=1)


# Extract named entities and count by types
def named_entities(text):
    doc = nlp(text)
    total_tokens = len(doc)
    entities = {}
    for ent in doc.ents:
        entities[ent.label_] = entities.get(ent.label_, 0) + 1
    return {f'ner_{label}': count / total_tokens for label, count in entities.items() if total_tokens > 0}


# Create a DataFrame with named entity counts
df_entities = df['full_text'].apply(named_entities).apply(pd.Series).fillna(0)
df_entities.columns = [f'ner_{col}' for col in df_entities.columns]

# Concatenate entity feature DataFrame back to the original DataFrame
df = pd.concat([df, df_entities], axis=1)


def dependency_tags(text):
    doc = nlp(text)
    total_tokens = len(doc)
    dep_counts = doc.count_by(spacy.attrs.DEP)
    return {f'dep_{doc.vocab.strings[dep_id]}': count / total_tokens for dep_id, count in dep_counts.items() if total_tokens > 0}


df_deps = df['full_text'].apply(dependency_tags).apply(pd.Series).fillna(0)
df_deps.columns = [f'dep_{col}' for col in df_deps.columns]

df = pd.concat([df, df_deps], axis=1)

df.head()

Vectorizing:  15%|█▌        | 2612/17307 [40:41<3:48:54,  1.07it/s]

,essay_id,full_text,score,clean_text,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,hash_200,hash_201,hash_202,hash_203,hash_204,hash_205,hash_206,hash_207,hash_208,hash_209,hash_210,hash_211,hash_212,hash_213,hash_214,hash_215,hash_216,hash_217,hash_218,hash_219,hash_220,hash_221,hash_222,hash_223,hash_224,hash_225,hash_226,hash_227,hash_228,hash_229,hash_230,hash_231,hash_232,hash_233,hash_234,hash_235,hash_236,hash_237,hash_238,hash_239,hash_240,hash_241,hash_242,hash_243,hash_244,hash_245,hash_246,hash_247,hash_248,hash_249,hash_250,hash_251,hash_252,hash_253,hash_254,hash_255,hash_256,hash_257,hash_258,hash_259,hash_260,hash_261,hash_262,hash_263,hash_264,hash_265,hash_266,hash_267,hash_268,hash_269,hash_270,hash_271,hash_272,hash_273,hash_274,hash_275,hash_276,hash_277,hash_278,hash_279,hash_280,hash_281,hash_282,hash_283,hash_284,hash_285,hash_286,hash_287,hash_288,hash_289,hash_290,hash_291,hash_292,hash_293,hash_294,hash_295,hash_296,hash_297,hash_298,hash_299,hash_300,hash_301,hash_302,hash_303,hash_304,hash_305,hash_306,hash_307,hash_308,hash_309,hash_310,hash_311,hash_312,hash_313,hash_314,hash_315,hash_316,hash_317,hash_318,hash_319,hash_320,hash_321,hash_322,hash_323,hash_324,hash_325,hash_326,hash_327,hash_328,hash_329,hash_330,hash_331,hash_332,hash_333,hash_334,hash_335,hash_336,hash_337,hash_338,hash_339,hash_340,hash_341,hash_342,hash_343,hash_344,hash_345,hash_346,hash_347,hash_348,hash_349,hash_350,hash_351,hash_352,hash_353,hash_354,hash_355,hash_356,hash_357,hash_358,hash_359,hash_360,hash_361,hash_362,hash_363,hash_364,hash_365,hash_366,hash_367,hash_368,hash_369,hash_370,hash_371,hash_372,hash_373,hash_374,hash_375,hash_376,hash_377,hash_378,hash_379,hash_380,hash_381,hash_382,hash_383,hash_384,hash_385,hash_386,hash_387,hash_388,hash_389,hash_390,hash_391,hash_392,hash_393,hash_394,hash_395,hash_396,hash_397,hash_398,hash_399,hash_400,hash_401,hash_402,hash_403,hash_404,hash_405,hash_406,hash_407,hash_408,hash_409,hash_410,hash_411,hash_412,hash_413,hash_414,hash_415,hash_416,hash_417,hash_418,hash_419,hash_420,hash_421,hash_422,hash_423,hash_424,hash_425,hash_426,hash_427,hash_428,hash_429,hash_430,hash_431,hash_432,hash_433,hash_434,hash_435,hash_436,hash_437,hash_438,hash_439,hash_440,hash_441,hash_442,hash_443,hash_444,hash_445,hash_446,hash_447,hash_448,hash_449,hash_450,hash_451,hash_452,hash_453,hash_454,hash_455,hash_456,hash_457,hash_458,hash_459,hash_460,hash_461,hash_462,hash_463,hash_464,hash_465,hash_466,hash_467,hash_468,hash_469,hash_470,hash_471,hash_472,hash_473,hash_474,hash_475,hash_476,hash_477,hash_478,hash_479,hash_480,hash_481,hash_482,hash_483,hash_484,hash_485,hash_486,hash_487,hash_488,hash_489,hash_490,hash_491,hash_492,hash_493,hash_494,hash_495,hash_496,hash_497,hash_498,hash_499,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,topic,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,pos_pos_ADJ,pos_pos_NOUN,pos_pos_VERB,pos_pos_SCONJ,pos_pos_PRON,pos_pos_PUNCT,pos_pos_DET,pos_pos_AUX,pos_pos_PART,pos_pos_ADP,pos_pos_SPACE,pos_pos_CCONJ,pos_pos_PROPN,pos_pos_NUM,pos_pos_ADV,pos_pos_SYM,pos_pos_INTJ,pos_pos_X,ner_ner_GPE,ner_ner_PERCENT,ner_ner_NORP,ner_ner_ORG,ner_ner_CARDINAL,ner_ner_MONEY,ner_ner_DATE,ner_ner_LOC,ner_ner_PERSON,ner_ner_QUANTITY,ner_ner_EVENT,ner_ner_ORDINAL,ner_ner_WORK_OF_ART,ner_ner_LAW,ner_ner_PRODUCT,ner_ner_TIME,ner_ner_FAC,ner_ner_LANGUAGE,dep_dep_amod,dep_dep_nsubj,dep_dep_ROOT,dep_dep_dobj,dep_dep_advmod,dep_dep_relcl,dep_dep_punct,dep_dep_det,dep_dep_aux,dep_dep_neg,dep_dep_mark,dep_dep_csubj,dep_dep_compound,dep_dep_prep,dep_dep_pobj,dep_dep_ccomp,dep_dep_dep,dep_dep_advcl,dep_dep_cc,dep_dep_acomp,dep_dep_attr,dep_dep_appos,dep_dep_conj,dep_dep_nummod,dep_dep_poss,dep_dep_case,dep_dep_nsubjpass,dep_dep_nmod,dep_dep_auxpass,dep_dep_npadvmod,dep_dep_expl,dep_dep_xcomp,dep_dep_dative,dep_dep_oprd,dep_dep_acl,dep_dep_quantmod,dep_dep_pcomp,dep_dep_agent,dep_dep_intj,dep_dep_predet,dep_dep_prt,dep_dep_meta,dep_dep_preconj,dep_dep_parataxis,dep_dep_csubjpass

In [92]:
import spacy
import numpy as np
import pandas as pd

nlp = spacy.load("en_core_web_sm")

# Register the custom attribute 'yngve' for Token objects if it's not already registered
if not spacy.tokens.Token.has_extension('yngve'):
    spacy.tokens.Token.set_extension('yngve', default=None)

def compute_syntactic_complexity(doc):
    parsed = nlp(doc)
    # Ensure that some logic sets 'yngve' scores; here we're setting them to a default value for illustration
    for token in parsed:
        token._.yngve = token.i  # Example: set yngve score to token index, replace this with actual computation
    yngve_scores = [token._.yngve for token in parsed]
    dependency_distances = [abs(token.head.i - token.i) for token in parsed]
    return np.mean(yngve_scores), np.mean(dependency_distances)



# Apply the function to DataFrame
df['yngve_score'], df['dep_distance'] = zip(*df['full_text'].apply(compute_syntactic_complexity))

In [93]:
discourse_markers = [
    "However", "Nevertheless", "On the other hand", "Conversely", "Though", 
    "Although", "Yet", "But", "And", "Also", "Furthermore", "Moreover", "Plus", 
    "Additionally", "In addition", "Therefore", "Thus", "Hence", "Consequently", 
    "As a result", "So", "Because", "Due to", "As a consequence", "That is to say", 
    "In other words", "To clarify", "Namely", "Simply put", "This means", 
    "For example", "For instance", "Such as", "Like", "Then", "Next", "After", 
    "Afterwards", "Subsequently", "Previously", "First", "Second", "Third", 
    "Finally", "Meanwhile", "In summary", "To sum up", "In conclusion", "Overall", 
    "To conclude", "In short", "Indeed", "In fact", "Certainly", "Definitely", 
    "Obviously", "Clearly", "If", "Unless", "Provided that", "In case", 
    "Fortunately", "Unfortunately", "Interestingly", "Surprisingly", "Importantly", 
    "Similarly", "Likewise", "Equally"
]

def count_discourse_markers(doc):
    words = doc.split()
    return sum(word in discourse_markers for word in words)

df['discourse_marker_count'] = df['full_text'].apply(count_discourse_markers)

In [101]:
import spacy
import pandas as pd
from gensim.corpora import Dictionary
from gensim.models import LdaModel
from gensim.models.coherencemodel import CoherenceModel

# Load spacy model for text processing
nlp = spacy.load('en_core_web_sm', disable=['parser', 'ner'])  # We only need the tokenizer

def preprocess(text):
    doc = nlp(text)
    # Tokenize, remove stop words and lemmatize
    return [token.lemma_ for token in doc if not token.is_stop and not token.is_punct and len(token) > 2]

# Assuming df is your DataFrame and 'full_text' is the column with essays
df['processed_docs'] = df['full_text'].apply(preprocess)


dictionary = Dictionary(df['processed_docs'])
corpus = [dictionary.doc2bow(doc) for doc in df['processed_docs']]


lda_model = LdaModel(corpus=corpus, num_topics=10, id2word=dictionary, passes=10, random_state=42)


def document_topics(bow):
    return lda_model.get_document_topics(bow, minimum_probability=0.0)

df['topics'] = [document_topics(bow) for bow in corpus]


# Compute global coherence
coherence_model_lda = CoherenceModel(model=lda_model, texts=df['processed_docs'].tolist(), dictionary=dictionary, coherence='c_v')
global_coherence = coherence_model_lda.get_coherence()
df['global_coherence'] = global_coherence

# Compute diversity for each document
def calculate_diversity(topics):
    unique_terms = set()
    for topic_id, prob in topics:
        unique_terms.update([term for term, _ in lda_model.show_topic(topic_id)])
    return len(unique_terms) / len(topics) if topics else 0

df['topic_diversity'] = df['topics'].apply(calculate_diversity)


# You may need to expand topic proportions or other relevant statistics per document
# Here's an example of storing the main topic per document
df['main_topic'] = df['topics'].apply(lambda x: sorted(x, key=lambda y: y[1], reverse=True)[0][0])

df.head()

,essay_id,full_text,score,clean_text,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,hash_200,hash_201,hash_202,hash_203,hash_204,hash_205,hash_206,hash_207,hash_208,hash_209,hash_210,hash_211,hash_212,hash_213,hash_214,hash_215,hash_216,hash_217,hash_218,hash_219,hash_220,hash_221,hash_222,hash_223,hash_224,hash_225,hash_226,hash_227,hash_228,hash_229,hash_230,hash_231,hash_232,hash_233,hash_234,hash_235,hash_236,hash_237,hash_238,hash_239,hash_240,hash_241,hash_242,hash_243,hash_244,hash_245,hash_246,hash_247,hash_248,hash_249,hash_250,hash_251,hash_252,hash_253,hash_254,hash_255,hash_256,hash_257,hash_258,hash_259,hash_260,hash_261,hash_262,hash_263,hash_264,hash_265,hash_266,hash_267,hash_268,hash_269,hash_270,hash_271,hash_272,hash_273,hash_274,hash_275,hash_276,hash_277,hash_278,hash_279,hash_280,hash_281,hash_282,hash_283,hash_284,hash_285,hash_286,hash_287,hash_288,hash_289,hash_290,hash_291,hash_292,hash_293,hash_294,hash_295,hash_296,hash_297,hash_298,hash_299,hash_300,hash_301,hash_302,hash_303,hash_304,hash_305,hash_306,hash_307,hash_308,hash_309,hash_310,hash_311,hash_312,hash_313,hash_314,hash_315,hash_316,hash_317,hash_318,hash_319,hash_320,hash_321,hash_322,hash_323,hash_324,hash_325,hash_326,hash_327,hash_328,hash_329,hash_330,hash_331,hash_332,hash_333,hash_334,hash_335,hash_336,hash_337,hash_338,hash_339,hash_340,hash_341,hash_342,hash_343,hash_344,hash_345,hash_346,hash_347,hash_348,hash_349,hash_350,hash_351,hash_352,hash_353,hash_354,hash_355,hash_356,hash_357,hash_358,hash_359,hash_360,hash_361,hash_362,hash_363,hash_364,hash_365,hash_366,hash_367,hash_368,hash_369,hash_370,hash_371,hash_372,hash_373,hash_374,hash_375,hash_376,hash_377,hash_378,hash_379,hash_380,hash_381,hash_382,hash_383,hash_384,hash_385,hash_386,hash_387,hash_388,hash_389,hash_390,hash_391,hash_392,hash_393,hash_394,hash_395,hash_396,hash_397,hash_398,hash_399,hash_400,hash_401,hash_402,hash_403,hash_404,hash_405,hash_406,hash_407,hash_408,hash_409,hash_410,hash_411,hash_412,hash_413,hash_414,hash_415,hash_416,hash_417,hash_418,hash_419,hash_420,hash_421,hash_422,hash_423,hash_424,hash_425,hash_426,hash_427,hash_428,hash_429,hash_430,hash_431,hash_432,hash_433,hash_434,hash_435,hash_436,hash_437,hash_438,hash_439,hash_440,hash_441,hash_442,hash_443,hash_444,hash_445,hash_446,hash_447,hash_448,hash_449,hash_450,hash_451,hash_452,hash_453,hash_454,hash_455,hash_456,hash_457,hash_458,hash_459,hash_460,hash_461,hash_462,hash_463,hash_464,hash_465,hash_466,hash_467,hash_468,hash_469,hash_470,hash_471,hash_472,hash_473,hash_474,hash_475,hash_476,hash_477,hash_478,hash_479,hash_480,hash_481,hash_482,hash_483,hash_484,hash_485,hash_486,hash_487,hash_488,hash_489,hash_490,hash_491,hash_492,hash_493,hash_494,hash_495,hash_496,hash_497,hash_498,hash_499,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,pos_pos_ADJ,pos_pos_NOUN,pos_pos_VERB,pos_pos_SCONJ,pos_pos_PRON,pos_pos_PUNCT,pos_pos_DET,pos_pos_AUX,pos_pos_PART,pos_pos_ADP,pos_pos_SPACE,pos_pos_CCONJ,pos_pos_PROPN,pos_pos_NUM,pos_pos_ADV,pos_pos_SYM,pos_pos_INTJ,pos_pos_X,ner_ner_GPE,ner_ner_PERCENT,ner_ner_NORP,ner_ner_ORG,ner_ner_CARDINAL,ner_ner_MONEY,ner_ner_DATE,ner_ner_LOC,ner_ner_PERSON,ner_ner_QUANTITY,ner_ner_EVENT,ner_ner_ORDINAL,ner_ner_WORK_OF_ART,ner_ner_LAW,ner_ner_PRODUCT,ner_ner_TIME,ner_ner_FAC,ner_ner_LANGUAGE,dep_dep_amod,dep_dep_nsubj,dep_dep_ROOT,dep_dep_dobj,dep_dep_advmod,dep_dep_relcl,dep_dep_punct,dep_dep_det,dep_dep_aux,dep_dep_neg,dep_dep_mark,dep_dep_csubj,dep_dep_compound,dep_dep_prep,dep_dep_pobj,dep_dep_ccomp,dep_dep_dep,dep_dep_advcl,dep_dep_cc,dep_dep_acomp,dep_dep_attr,dep_dep_appos,dep_dep_conj,dep_dep_nummod,dep_dep_poss,dep_dep_case,dep_dep_nsubjpass,dep_dep_nmod,dep_dep_auxpass,dep_dep_npadvmod,dep_dep_expl,dep_dep_xcomp,dep_dep_dative,dep_dep_oprd,dep_dep_acl,dep_dep_quantmod,dep_dep_pcomp,dep_dep_agent,dep_dep_intj,dep_dep_predet,dep_dep_prt,dep_dep_meta,dep_dep_preconj,dep_dep_parataxis,dep_dep_csubjpass,yngve_score,dep_distance,discourse_marker_count,processed_docs,global_coherence,topics,topic_diversity,main_topic

In [102]:
import pandas as pd

# Example DataFrame with topic distributions (list of tuples where each tuple is (topic_id, proportion))
# Assuming df['topics'] already exists with topic distributions

def expand_topics(topics, num_topics=10):
    """Expand list of (topic, proportion) to a full list of proportions for all topics."""
    topic_proportions = [0] * num_topics  # Initialize a list of zeros for each topic
    for topic, proportion in topics:
        topic_proportions[topic] = proportion  # Set the proportion for each topic
    return topic_proportions

# Apply the function to each row in the DataFrame
topic_features = df['topics'].apply(lambda x: expand_topics(x, num_topics=10))

# Convert list of topic contributions to a DataFrame
topics_df = pd.DataFrame(topic_features.tolist(), columns=[f'topic_{i}' for i in range(10)])

# Concatenate this new DataFrame with the original DataFrame
df = pd.concat([df, topics_df], axis=1)

df.head()

,essay_id,full_text,score,clean_text,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,hash_200,hash_201,hash_202,hash_203,hash_204,hash_205,hash_206,hash_207,hash_208,hash_209,hash_210,hash_211,hash_212,hash_213,hash_214,hash_215,hash_216,hash_217,hash_218,hash_219,hash_220,hash_221,hash_222,hash_223,hash_224,hash_225,hash_226,hash_227,hash_228,hash_229,hash_230,hash_231,hash_232,hash_233,hash_234,hash_235,hash_236,hash_237,hash_238,hash_239,hash_240,hash_241,hash_242,hash_243,hash_244,hash_245,hash_246,hash_247,hash_248,hash_249,hash_250,hash_251,hash_252,hash_253,hash_254,hash_255,hash_256,hash_257,hash_258,hash_259,hash_260,hash_261,hash_262,hash_263,hash_264,hash_265,hash_266,hash_267,hash_268,hash_269,hash_270,hash_271,hash_272,hash_273,hash_274,hash_275,hash_276,hash_277,hash_278,hash_279,hash_280,hash_281,hash_282,hash_283,hash_284,hash_285,hash_286,hash_287,hash_288,hash_289,hash_290,hash_291,hash_292,hash_293,hash_294,hash_295,hash_296,hash_297,hash_298,hash_299,hash_300,hash_301,hash_302,hash_303,hash_304,hash_305,hash_306,hash_307,hash_308,hash_309,hash_310,hash_311,hash_312,hash_313,hash_314,hash_315,hash_316,hash_317,hash_318,hash_319,hash_320,hash_321,hash_322,hash_323,hash_324,hash_325,hash_326,hash_327,hash_328,hash_329,hash_330,hash_331,hash_332,hash_333,hash_334,hash_335,hash_336,hash_337,hash_338,hash_339,hash_340,hash_341,hash_342,hash_343,hash_344,hash_345,hash_346,hash_347,hash_348,hash_349,hash_350,hash_351,hash_352,hash_353,hash_354,hash_355,hash_356,hash_357,hash_358,hash_359,hash_360,hash_361,hash_362,hash_363,hash_364,hash_365,hash_366,hash_367,hash_368,hash_369,hash_370,hash_371,hash_372,hash_373,hash_374,hash_375,hash_376,hash_377,hash_378,hash_379,hash_380,hash_381,hash_382,hash_383,hash_384,hash_385,hash_386,hash_387,hash_388,hash_389,hash_390,hash_391,hash_392,hash_393,hash_394,hash_395,hash_396,hash_397,hash_398,hash_399,hash_400,hash_401,hash_402,hash_403,hash_404,hash_405,hash_406,hash_407,hash_408,hash_409,hash_410,hash_411,hash_412,hash_413,hash_414,hash_415,hash_416,hash_417,hash_418,hash_419,hash_420,hash_421,hash_422,hash_423,hash_424,hash_425,hash_426,hash_427,hash_428,hash_429,hash_430,hash_431,hash_432,hash_433,hash_434,hash_435,hash_436,hash_437,hash_438,hash_439,hash_440,hash_441,hash_442,hash_443,hash_444,hash_445,hash_446,hash_447,hash_448,hash_449,hash_450,hash_451,hash_452,hash_453,hash_454,hash_455,hash_456,hash_457,hash_458,hash_459,hash_460,hash_461,hash_462,hash_463,hash_464,hash_465,hash_466,hash_467,hash_468,hash_469,hash_470,hash_471,hash_472,hash_473,hash_474,hash_475,hash_476,hash_477,hash_478,hash_479,hash_480,hash_481,hash_482,hash_483,hash_484,hash_485,hash_486,hash_487,hash_488,hash_489,hash_490,hash_491,hash_492,hash_493,hash_494,hash_495,hash_496,hash_497,hash_498,hash_499,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,pos_pos_ADJ,pos_pos_NOUN,pos_pos_VERB,pos_pos_SCONJ,pos_pos_PRON,pos_pos_PUNCT,pos_pos_DET,pos_pos_AUX,pos_pos_PART,pos_pos_ADP,pos_pos_SPACE,pos_pos_CCONJ,pos_pos_PROPN,pos_pos_NUM,pos_pos_ADV,pos_pos_SYM,pos_pos_INTJ,pos_pos_X,ner_ner_GPE,ner_ner_PERCENT,ner_ner_NORP,ner_ner_ORG,ner_ner_CARDINAL,ner_ner_MONEY,ner_ner_DATE,ner_ner_LOC,ner_ner_PERSON,ner_ner_QUANTITY,ner_ner_EVENT,ner_ner_ORDINAL,ner_ner_WORK_OF_ART,ner_ner_LAW,ner_ner_PRODUCT,ner_ner_TIME,ner_ner_FAC,ner_ner_LANGUAGE,dep_dep_amod,dep_dep_nsubj,dep_dep_ROOT,dep_dep_dobj,dep_dep_advmod,dep_dep_relcl,dep_dep_punct,dep_dep_det,dep_dep_aux,dep_dep_neg,dep_dep_mark,dep_dep_csubj,dep_dep_compound,dep_dep_prep,dep_dep_pobj,dep_dep_ccomp,dep_dep_dep,dep_dep_advcl,dep_dep_cc,dep_dep_acomp,dep_dep_attr,dep_dep_appos,dep_dep_conj,dep_dep_nummod,dep_dep_poss,dep_dep_case,dep_dep_nsubjpass,dep_dep_nmod,dep_dep_auxpass,dep_dep_npadvmod,dep_dep_expl,dep_dep_xcomp,dep_dep_dative,dep_dep_oprd,dep_dep_acl,dep_dep_quantmod,dep_dep_pcomp,dep_dep_agent,dep_dep_intj,dep_dep_predet,dep_dep_prt,dep_dep_meta,dep_dep_preconj,dep_dep_parataxis,dep_dep_csubjpass,yngve_score,dep_distance,discourse_marker_count,processed_docs,global_coherence,topics,topic_diversity,main_topic,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9

In [103]:
# Number of topics
num_topics = 10  # Adjust based on your LDA model configuration

# Initialize columns for topic probabilities
for i in range(num_topics):
    df[f'topic_prob_{i}'] = 0.0

# Fill the DataFrame with the topic probabilities
for index, row in df.iterrows():
    for topic, prob in row['topics']:
        df.at[index, f'topic_prob_{topic}'] = prob

In [104]:
df.head()

,essay_id,full_text,score,clean_text,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,hash_200,hash_201,hash_202,hash_203,hash_204,hash_205,hash_206,hash_207,hash_208,hash_209,hash_210,hash_211,hash_212,hash_213,hash_214,hash_215,hash_216,hash_217,hash_218,hash_219,hash_220,hash_221,hash_222,hash_223,hash_224,hash_225,hash_226,hash_227,hash_228,hash_229,hash_230,hash_231,hash_232,hash_233,hash_234,hash_235,hash_236,hash_237,hash_238,hash_239,hash_240,hash_241,hash_242,hash_243,hash_244,hash_245,hash_246,hash_247,hash_248,hash_249,hash_250,hash_251,hash_252,hash_253,hash_254,hash_255,hash_256,hash_257,hash_258,hash_259,hash_260,hash_261,hash_262,hash_263,hash_264,hash_265,hash_266,hash_267,hash_268,hash_269,hash_270,hash_271,hash_272,hash_273,hash_274,hash_275,hash_276,hash_277,hash_278,hash_279,hash_280,hash_281,hash_282,hash_283,hash_284,hash_285,hash_286,hash_287,hash_288,hash_289,hash_290,hash_291,hash_292,hash_293,hash_294,hash_295,hash_296,hash_297,hash_298,hash_299,hash_300,hash_301,hash_302,hash_303,hash_304,hash_305,hash_306,hash_307,hash_308,hash_309,hash_310,hash_311,hash_312,hash_313,hash_314,hash_315,hash_316,hash_317,hash_318,hash_319,hash_320,hash_321,hash_322,hash_323,hash_324,hash_325,hash_326,hash_327,hash_328,hash_329,hash_330,hash_331,hash_332,hash_333,hash_334,hash_335,hash_336,hash_337,hash_338,hash_339,hash_340,hash_341,hash_342,hash_343,hash_344,hash_345,hash_346,hash_347,hash_348,hash_349,hash_350,hash_351,hash_352,hash_353,hash_354,hash_355,hash_356,hash_357,hash_358,hash_359,hash_360,hash_361,hash_362,hash_363,hash_364,hash_365,hash_366,hash_367,hash_368,hash_369,hash_370,hash_371,hash_372,hash_373,hash_374,hash_375,hash_376,hash_377,hash_378,hash_379,hash_380,hash_381,hash_382,hash_383,hash_384,hash_385,hash_386,hash_387,hash_388,hash_389,hash_390,hash_391,hash_392,hash_393,hash_394,hash_395,hash_396,hash_397,hash_398,hash_399,hash_400,hash_401,hash_402,hash_403,hash_404,hash_405,hash_406,hash_407,hash_408,hash_409,hash_410,hash_411,hash_412,hash_413,hash_414,hash_415,hash_416,hash_417,hash_418,hash_419,hash_420,hash_421,hash_422,hash_423,hash_424,hash_425,hash_426,hash_427,hash_428,hash_429,hash_430,hash_431,hash_432,hash_433,hash_434,hash_435,hash_436,hash_437,hash_438,hash_439,hash_440,hash_441,hash_442,hash_443,hash_444,hash_445,hash_446,hash_447,hash_448,hash_449,hash_450,hash_451,hash_452,hash_453,hash_454,hash_455,hash_456,hash_457,hash_458,hash_459,hash_460,hash_461,hash_462,hash_463,hash_464,hash_465,hash_466,hash_467,hash_468,hash_469,hash_470,hash_471,hash_472,hash_473,hash_474,hash_475,hash_476,hash_477,hash_478,hash_479,hash_480,hash_481,hash_482,hash_483,hash_484,hash_485,hash_486,hash_487,hash_488,hash_489,hash_490,hash_491,hash_492,hash_493,hash_494,hash_495,hash_496,hash_497,hash_498,hash_499,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,pos_pos_ADJ,pos_pos_NOUN,pos_pos_VERB,pos_pos_SCONJ,pos_pos_PRON,pos_pos_PUNCT,pos_pos_DET,pos_pos_AUX,pos_pos_PART,pos_pos_ADP,pos_pos_SPACE,pos_pos_CCONJ,pos_pos_PROPN,pos_pos_NUM,pos_pos_ADV,pos_pos_SYM,pos_pos_INTJ,pos_pos_X,ner_ner_GPE,ner_ner_PERCENT,ner_ner_NORP,ner_ner_ORG,ner_ner_CARDINAL,ner_ner_MONEY,ner_ner_DATE,ner_ner_LOC,ner_ner_PERSON,ner_ner_QUANTITY,ner_ner_EVENT,ner_ner_ORDINAL,ner_ner_WORK_OF_ART,ner_ner_LAW,ner_ner_PRODUCT,ner_ner_TIME,ner_ner_FAC,ner_ner_LANGUAGE,dep_dep_amod,dep_dep_nsubj,dep_dep_ROOT,dep_dep_dobj,dep_dep_advmod,dep_dep_relcl,dep_dep_punct,dep_dep_det,dep_dep_aux,dep_dep_neg,dep_dep_mark,dep_dep_csubj,dep_dep_compound,dep_dep_prep,dep_dep_pobj,dep_dep_ccomp,dep_dep_dep,dep_dep_advcl,dep_dep_cc,dep_dep_acomp,dep_dep_attr,dep_dep_appos,dep_dep_conj,dep_dep_nummod,dep_dep_poss,dep_dep_case,dep_dep_nsubjpass,dep_dep_nmod,dep_dep_auxpass,dep_dep_npadvmod,dep_dep_expl,dep_dep_xcomp,dep_dep_dative,dep_dep_oprd,dep_dep_acl,dep_dep_quantmod,dep_dep_pcomp,dep_dep_agent,dep_dep_intj,dep_dep_predet,dep_dep_prt,dep_dep_meta,dep_dep_preconj,dep_dep_parataxis,dep_dep_csubjpass,yngve_score,dep_distance,discourse_marker_count,processed_docs,global_coherence,topics,topic_diversity,main_topic,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,topic_prob_0,topic_prob_1,topic_prob_2,topic_prob_3,topic_prob_4,topic_prob_5,topic_prob_6,topic_prob_7,topic_prob_8,topic_prob_9

In [108]:
cor.head()

,score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,hash_200,hash_201,hash_202,hash_203,hash_204,hash_205,hash_206,hash_207,hash_208,hash_209,hash_210,hash_211,hash_212,hash_213,hash_214,hash_215,hash_216,hash_217,hash_218,hash_219,hash_220,hash_221,hash_222,hash_223,hash_224,hash_225,hash_226,hash_227,hash_228,hash_229,hash_230,hash_231,hash_232,hash_233,hash_234,hash_235,hash_236,hash_237,hash_238,hash_239,hash_240,hash_241,hash_242,hash_243,hash_244,hash_245,hash_246,hash_247,hash_248,hash_249,hash_250,hash_251,hash_252,hash_253,hash_254,hash_255,hash_256,hash_257,hash_258,hash_259,hash_260,hash_261,hash_262,hash_263,hash_264,hash_265,hash_266,hash_267,hash_268,hash_269,hash_270,hash_271,hash_272,hash_273,hash_274,hash_275,hash_276,hash_277,hash_278,hash_279,hash_280,hash_281,hash_282,hash_283,hash_284,hash_285,hash_286,hash_287,hash_288,hash_289,hash_290,hash_291,hash_292,hash_293,hash_294,hash_295,hash_296,hash_297,hash_298,hash_299,hash_300,hash_301,hash_302,hash_303,hash_304,hash_305,hash_306,hash_307,hash_308,hash_309,hash_310,hash_311,hash_312,hash_313,hash_314,hash_315,hash_316,hash_317,hash_318,hash_319,hash_320,hash_321,hash_322,hash_323,hash_324,hash_325,hash_326,hash_327,hash_328,hash_329,hash_330,hash_331,hash_332,hash_333,hash_334,hash_335,hash_336,hash_337,hash_338,hash_339,hash_340,hash_341,hash_342,hash_343,hash_344,hash_345,hash_346,hash_347,hash_348,hash_349,hash_350,hash_351,hash_352,hash_353,hash_354,hash_355,hash_356,hash_357,hash_358,hash_359,hash_360,hash_361,hash_362,hash_363,hash_364,hash_365,hash_366,hash_367,hash_368,hash_369,hash_370,hash_371,hash_372,hash_373,hash_374,hash_375,hash_376,hash_377,hash_378,hash_379,hash_380,hash_381,hash_382,hash_383,hash_384,hash_385,hash_386,hash_387,hash_388,hash_389,hash_390,hash_391,hash_392,hash_393,hash_394,hash_395,hash_396,hash_397,hash_398,hash_399,hash_400,hash_401,hash_402,hash_403,hash_404,hash_405,hash_406,hash_407,hash_408,hash_409,hash_410,hash_411,hash_412,hash_413,hash_414,hash_415,hash_416,hash_417,hash_418,hash_419,hash_420,hash_421,hash_422,hash_423,hash_424,hash_425,hash_426,hash_427,hash_428,hash_429,hash_430,hash_431,hash_432,hash_433,hash_434,hash_435,hash_436,hash_437,hash_438,hash_439,hash_440,hash_441,hash_442,hash_443,hash_444,hash_445,hash_446,hash_447,hash_448,hash_449,hash_450,hash_451,hash_452,hash_453,hash_454,hash_455,hash_456,hash_457,hash_458,hash_459,hash_460,hash_461,hash_462,hash_463,hash_464,hash_465,hash_466,hash_467,hash_468,hash_469,hash_470,hash_471,hash_472,hash_473,hash_474,hash_475,hash_476,hash_477,hash_478,hash_479,hash_480,hash_481,hash_482,hash_483,hash_484,hash_485,hash_486,hash_487,hash_488,hash_489,hash_490,hash_491,hash_492,hash_493,hash_494,hash_495,hash_496,hash_497,hash_498,hash_499,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,pos_pos_ADJ,pos_pos_NOUN,pos_pos_VERB,pos_pos_SCONJ,pos_pos_PRON,pos_pos_PUNCT,pos_pos_DET,pos_pos_AUX,pos_pos_PART,pos_pos_ADP,pos_pos_SPACE,pos_pos_CCONJ,pos_pos_PROPN,pos_pos_NUM,pos_pos_ADV,pos_pos_SYM,pos_pos_INTJ,pos_pos_X,ner_ner_GPE,ner_ner_PERCENT,ner_ner_NORP,ner_ner_ORG,ner_ner_CARDINAL,ner_ner_MONEY,ner_ner_DATE,ner_ner_LOC,ner_ner_PERSON,ner_ner_QUANTITY,ner_ner_EVENT,ner_ner_ORDINAL,ner_ner_WORK_OF_ART,ner_ner_LAW,ner_ner_PRODUCT,ner_ner_TIME,ner_ner_FAC,ner_ner_LANGUAGE,dep_dep_amod,dep_dep_nsubj,dep_dep_ROOT,dep_dep_dobj,dep_dep_advmod,dep_dep_relcl,dep_dep_punct,dep_dep_det,dep_dep_aux,dep_dep_neg,dep_dep_mark,dep_dep_csubj,dep_dep_compound,dep_dep_prep,dep_dep_pobj,dep_dep_ccomp,dep_dep_dep,dep_dep_advcl,dep_dep_cc,dep_dep_acomp,dep_dep_attr,dep_dep_appos,dep_dep_conj,dep_dep_nummod,dep_dep_poss,dep_dep_case,dep_dep_nsubjpass,dep_dep_nmod,dep_dep_auxpass,dep_dep_npadvmod,dep_dep_expl,dep_dep_xcomp,dep_dep_dative,dep_dep_oprd,dep_dep_acl,dep_dep_quantmod,dep_dep_pcomp,dep_dep_agent,dep_dep_intj,dep_dep_predet,dep_dep_prt,dep_dep_meta,dep_dep_preconj,dep_dep_parataxis,dep_dep_csubjpass,yngve_score,dep_distance,discourse_marker_count,processed_docs,global_coherence,topics,topic_diversity,main_topic,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,topic_prob_0,topic_prob_1,topic_prob_2,topic_prob_3,topic_prob_4,topic_prob_5,topic_prob_6,topic_prob_7,topic_prob_8,topic_prob_9

In [109]:
# Calculate correlations with the target

cor = df.drop(columns = ['essay_id', 'full_text', 'clean_text','processed_docs','topics'],axis=1)
correlations = cor.corrwith(df['score']).sort_values(ascending=False)

# Print the most correlated features
print(correlations.head())

score             1.000000
yngve_score       0.692587
deberta_prob_2    0.634452
deberta_prob_3    0.608547
deberta_prob_4    0.363460
dtype: float64

/home/jack/envs/scoring/lib/python3.10/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/jack/envs/scoring/lib/python3.10/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

In [110]:
top_features = correlations.head(5).index.tolist()  # Adjust the number to select top N features

from itertools import combinations

# Generate all pairs of top N features and create interaction terms
for feature1, feature2 in combinations(top_features, 2):
    df[f'interaction_{feature1}_{feature2}'] = df[feature1] * df[feature2]

In [111]:
df.head()

,essay_id,full_text,score,clean_text,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,hash_200,hash_201,hash_202,hash_203,hash_204,hash_205,hash_206,hash_207,hash_208,hash_209,hash_210,hash_211,hash_212,hash_213,hash_214,hash_215,hash_216,hash_217,hash_218,hash_219,hash_220,hash_221,hash_222,hash_223,hash_224,hash_225,hash_226,hash_227,hash_228,hash_229,hash_230,hash_231,hash_232,hash_233,hash_234,hash_235,hash_236,hash_237,hash_238,hash_239,hash_240,hash_241,hash_242,hash_243,hash_244,hash_245,hash_246,hash_247,hash_248,hash_249,hash_250,hash_251,hash_252,hash_253,hash_254,hash_255,hash_256,hash_257,hash_258,hash_259,hash_260,hash_261,hash_262,hash_263,hash_264,hash_265,hash_266,hash_267,hash_268,hash_269,hash_270,hash_271,hash_272,hash_273,hash_274,hash_275,hash_276,hash_277,hash_278,hash_279,hash_280,hash_281,hash_282,hash_283,hash_284,hash_285,hash_286,hash_287,hash_288,hash_289,hash_290,hash_291,hash_292,hash_293,hash_294,hash_295,hash_296,hash_297,hash_298,hash_299,hash_300,hash_301,hash_302,hash_303,hash_304,hash_305,hash_306,hash_307,hash_308,hash_309,hash_310,hash_311,hash_312,hash_313,hash_314,hash_315,hash_316,hash_317,hash_318,hash_319,hash_320,hash_321,hash_322,hash_323,hash_324,hash_325,hash_326,hash_327,hash_328,hash_329,hash_330,hash_331,hash_332,hash_333,hash_334,hash_335,hash_336,hash_337,hash_338,hash_339,hash_340,hash_341,hash_342,hash_343,hash_344,hash_345,hash_346,hash_347,hash_348,hash_349,hash_350,hash_351,hash_352,hash_353,hash_354,hash_355,hash_356,hash_357,hash_358,hash_359,hash_360,hash_361,hash_362,hash_363,hash_364,hash_365,hash_366,hash_367,hash_368,hash_369,hash_370,hash_371,hash_372,hash_373,hash_374,hash_375,hash_376,hash_377,hash_378,hash_379,hash_380,hash_381,hash_382,hash_383,hash_384,hash_385,hash_386,hash_387,hash_388,hash_389,hash_390,hash_391,hash_392,hash_393,hash_394,hash_395,hash_396,hash_397,hash_398,hash_399,hash_400,hash_401,hash_402,hash_403,hash_404,hash_405,hash_406,hash_407,hash_408,hash_409,hash_410,hash_411,hash_412,hash_413,hash_414,hash_415,hash_416,hash_417,hash_418,hash_419,hash_420,hash_421,hash_422,hash_423,hash_424,hash_425,hash_426,hash_427,hash_428,hash_429,hash_430,hash_431,hash_432,hash_433,hash_434,hash_435,hash_436,hash_437,hash_438,hash_439,hash_440,hash_441,hash_442,hash_443,hash_444,hash_445,hash_446,hash_447,hash_448,hash_449,hash_450,hash_451,hash_452,hash_453,hash_454,hash_455,hash_456,hash_457,hash_458,hash_459,hash_460,hash_461,hash_462,hash_463,hash_464,hash_465,hash_466,hash_467,hash_468,hash_469,hash_470,hash_471,hash_472,hash_473,hash_474,hash_475,hash_476,hash_477,hash_478,hash_479,hash_480,hash_481,hash_482,hash_483,hash_484,hash_485,hash_486,hash_487,hash_488,hash_489,hash_490,hash_491,hash_492,hash_493,hash_494,hash_495,hash_496,hash_497,hash_498,hash_499,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,pos_pos_ADJ,pos_pos_NOUN,pos_pos_VERB,pos_pos_SCONJ,pos_pos_PRON,pos_pos_PUNCT,pos_pos_DET,pos_pos_AUX,pos_pos_PART,pos_pos_ADP,pos_pos_SPACE,pos_pos_CCONJ,pos_pos_PROPN,pos_pos_NUM,pos_pos_ADV,pos_pos_SYM,pos_pos_INTJ,pos_pos_X,ner_ner_GPE,ner_ner_PERCENT,ner_ner_NORP,ner_ner_ORG,ner_ner_CARDINAL,ner_ner_MONEY,ner_ner_DATE,ner_ner_LOC,ner_ner_PERSON,ner_ner_QUANTITY,ner_ner_EVENT,ner_ner_ORDINAL,ner_ner_WORK_OF_ART,ner_ner_LAW,ner_ner_PRODUCT,ner_ner_TIME,ner_ner_FAC,ner_ner_LANGUAGE,dep_dep_amod,dep_dep_nsubj,dep_dep_ROOT,dep_dep_dobj,dep_dep_advmod,dep_dep_relcl,dep_dep_punct,dep_dep_det,dep_dep_aux,dep_dep_neg,dep_dep_mark,dep_dep_csubj,dep_dep_compound,dep_dep_prep,dep_dep_pobj,dep_dep_ccomp,dep_dep_dep,dep_dep_advcl,dep_dep_cc,dep_dep_acomp,dep_dep_attr,dep_dep_appos,dep_dep_conj,dep_dep_nummod,dep_dep_poss,dep_dep_case,dep_dep_nsubjpass,dep_dep_nmod,dep_dep_auxpass,dep_dep_npadvmod,dep_dep_expl,dep_dep_xcomp,dep_dep_dative,dep_dep_oprd,dep_dep_acl,dep_dep_quantmod,dep_dep_pcomp,dep_dep_agent,dep_dep_intj,dep_dep_predet,dep_dep_prt,dep_dep_meta,dep_dep_preconj,dep_dep_parataxis,dep_dep_csubjpass,yngve_score,dep_distance,discourse_marker_count,processed_docs,global_coherence,topics,topic_diversity,main_topic,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,topic_prob_0,topic_prob_1,topic_prob_2,topic_prob_3,topic_prob_4,topic_prob_5,topic_prob_6,topic_prob_7,topic_prob_8,topic_prob_9,interaction_score_yngve_score,interaction_score_deberta_prob_2,interaction_score_deberta_prob_3,interaction_score_deberta_prob_4,interaction_yngve_score_deberta_prob_2,interaction_yngve_score_deberta_prob_3,interaction_yngve_score_deberta_prob_4,interaction_deberta_prob_2_deberta_prob_3,interaction_deberta_prob_2_deberta_prob_4,interaction_deberta_prob_3_deberta_prob_4

In [ ]:
df.tail()

In [112]:
train = df.copy()

In [113]:
train.head()

,essay_id,full_text,score,clean_text,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,hash_200,hash_201,hash_202,hash_203,hash_204,hash_205,hash_206,hash_207,hash_208,hash_209,hash_210,hash_211,hash_212,hash_213,hash_214,hash_215,hash_216,hash_217,hash_218,hash_219,hash_220,hash_221,hash_222,hash_223,hash_224,hash_225,hash_226,hash_227,hash_228,hash_229,hash_230,hash_231,hash_232,hash_233,hash_234,hash_235,hash_236,hash_237,hash_238,hash_239,hash_240,hash_241,hash_242,hash_243,hash_244,hash_245,hash_246,hash_247,hash_248,hash_249,hash_250,hash_251,hash_252,hash_253,hash_254,hash_255,hash_256,hash_257,hash_258,hash_259,hash_260,hash_261,hash_262,hash_263,hash_264,hash_265,hash_266,hash_267,hash_268,hash_269,hash_270,hash_271,hash_272,hash_273,hash_274,hash_275,hash_276,hash_277,hash_278,hash_279,hash_280,hash_281,hash_282,hash_283,hash_284,hash_285,hash_286,hash_287,hash_288,hash_289,hash_290,hash_291,hash_292,hash_293,hash_294,hash_295,hash_296,hash_297,hash_298,hash_299,hash_300,hash_301,hash_302,hash_303,hash_304,hash_305,hash_306,hash_307,hash_308,hash_309,hash_310,hash_311,hash_312,hash_313,hash_314,hash_315,hash_316,hash_317,hash_318,hash_319,hash_320,hash_321,hash_322,hash_323,hash_324,hash_325,hash_326,hash_327,hash_328,hash_329,hash_330,hash_331,hash_332,hash_333,hash_334,hash_335,hash_336,hash_337,hash_338,hash_339,hash_340,hash_341,hash_342,hash_343,hash_344,hash_345,hash_346,hash_347,hash_348,hash_349,hash_350,hash_351,hash_352,hash_353,hash_354,hash_355,hash_356,hash_357,hash_358,hash_359,hash_360,hash_361,hash_362,hash_363,hash_364,hash_365,hash_366,hash_367,hash_368,hash_369,hash_370,hash_371,hash_372,hash_373,hash_374,hash_375,hash_376,hash_377,hash_378,hash_379,hash_380,hash_381,hash_382,hash_383,hash_384,hash_385,hash_386,hash_387,hash_388,hash_389,hash_390,hash_391,hash_392,hash_393,hash_394,hash_395,hash_396,hash_397,hash_398,hash_399,hash_400,hash_401,hash_402,hash_403,hash_404,hash_405,hash_406,hash_407,hash_408,hash_409,hash_410,hash_411,hash_412,hash_413,hash_414,hash_415,hash_416,hash_417,hash_418,hash_419,hash_420,hash_421,hash_422,hash_423,hash_424,hash_425,hash_426,hash_427,hash_428,hash_429,hash_430,hash_431,hash_432,hash_433,hash_434,hash_435,hash_436,hash_437,hash_438,hash_439,hash_440,hash_441,hash_442,hash_443,hash_444,hash_445,hash_446,hash_447,hash_448,hash_449,hash_450,hash_451,hash_452,hash_453,hash_454,hash_455,hash_456,hash_457,hash_458,hash_459,hash_460,hash_461,hash_462,hash_463,hash_464,hash_465,hash_466,hash_467,hash_468,hash_469,hash_470,hash_471,hash_472,hash_473,hash_474,hash_475,hash_476,hash_477,hash_478,hash_479,hash_480,hash_481,hash_482,hash_483,hash_484,hash_485,hash_486,hash_487,hash_488,hash_489,hash_490,hash_491,hash_492,hash_493,hash_494,hash_495,hash_496,hash_497,hash_498,hash_499,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,pos_pos_ADJ,pos_pos_NOUN,pos_pos_VERB,pos_pos_SCONJ,pos_pos_PRON,pos_pos_PUNCT,pos_pos_DET,pos_pos_AUX,pos_pos_PART,pos_pos_ADP,pos_pos_SPACE,pos_pos_CCONJ,pos_pos_PROPN,pos_pos_NUM,pos_pos_ADV,pos_pos_SYM,pos_pos_INTJ,pos_pos_X,ner_ner_GPE,ner_ner_PERCENT,ner_ner_NORP,ner_ner_ORG,ner_ner_CARDINAL,ner_ner_MONEY,ner_ner_DATE,ner_ner_LOC,ner_ner_PERSON,ner_ner_QUANTITY,ner_ner_EVENT,ner_ner_ORDINAL,ner_ner_WORK_OF_ART,ner_ner_LAW,ner_ner_PRODUCT,ner_ner_TIME,ner_ner_FAC,ner_ner_LANGUAGE,dep_dep_amod,dep_dep_nsubj,dep_dep_ROOT,dep_dep_dobj,dep_dep_advmod,dep_dep_relcl,dep_dep_punct,dep_dep_det,dep_dep_aux,dep_dep_neg,dep_dep_mark,dep_dep_csubj,dep_dep_compound,dep_dep_prep,dep_dep_pobj,dep_dep_ccomp,dep_dep_dep,dep_dep_advcl,dep_dep_cc,dep_dep_acomp,dep_dep_attr,dep_dep_appos,dep_dep_conj,dep_dep_nummod,dep_dep_poss,dep_dep_case,dep_dep_nsubjpass,dep_dep_nmod,dep_dep_auxpass,dep_dep_npadvmod,dep_dep_expl,dep_dep_xcomp,dep_dep_dative,dep_dep_oprd,dep_dep_acl,dep_dep_quantmod,dep_dep_pcomp,dep_dep_agent,dep_dep_intj,dep_dep_predet,dep_dep_prt,dep_dep_meta,dep_dep_preconj,dep_dep_parataxis,dep_dep_csubjpass,yngve_score,dep_distance,discourse_marker_count,processed_docs,global_coherence,topics,topic_diversity,main_topic,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,topic_prob_0,topic_prob_1,topic_prob_2,topic_prob_3,topic_prob_4,topic_prob_5,topic_prob_6,topic_prob_7,topic_prob_8,topic_prob_9,interaction_score_yngve_score,interaction_score_deberta_prob_2,interaction_score_deberta_prob_3,interaction_score_deberta_prob_4,interaction_yngve_score_deberta_prob_2,interaction_yngve_score_deberta_prob_3,interaction_yngve_score_deberta_prob_4,interaction_deberta_prob_2_deberta_prob_3,interaction_deberta_prob_2_deberta_prob_4,interaction_deberta_prob_3_deberta_prob_4

In [ ]:
# import gc

# del df_train_final, df, df_ngrams, df_svd, df_pos, df_entities, df_deps, pos_df, ner_df, dep_df, pos_features, ner_features, dep_features

# gc.collect()

In [ ]:
# import os
# from tqdm import tqdm

# glove_path = 'data/glove-840B-300d.txt'

# paragram_path = '/home/jack/github/kaggle/scoring/data/paragram-300-sl999.txt'

# wiki_news_path = 'data/wiki-news-1M-300d.vec'


# # Load embeddings

# embeddings = parallel_load_embeddings([glove_path, paragram_path, wiki_news_path])

# glove = embeddings["glove"]
# paragram = embeddings["paragram"]
# fasttext = embeddings["fasttext"]

In [ ]:
# train, oov_glove, oov_paragram, oov_fasttxt = spellcheck_and_correct_text(train, embeddings)

In [ ]:
# train.to_parquet('train_full_clean_process.parquet')

In [ ]:
# import pandas as pd

# train = pd.read_parquet('train_with_deberta.parquet')

# train.head()

In [114]:
train = clean_text(train)

train.head()

Starting text cleaning process.

Adding Text Features.................

Complete.................

,essay_id,full_text,score,clean_text,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,hash_200,hash_201,hash_202,hash_203,hash_204,hash_205,hash_206,hash_207,hash_208,hash_209,hash_210,hash_211,hash_212,hash_213,hash_214,hash_215,hash_216,hash_217,hash_218,hash_219,hash_220,hash_221,hash_222,hash_223,hash_224,hash_225,hash_226,hash_227,hash_228,hash_229,hash_230,hash_231,hash_232,hash_233,hash_234,hash_235,hash_236,hash_237,hash_238,hash_239,hash_240,hash_241,hash_242,hash_243,hash_244,hash_245,hash_246,hash_247,hash_248,hash_249,hash_250,hash_251,hash_252,hash_253,hash_254,hash_255,hash_256,hash_257,hash_258,hash_259,hash_260,hash_261,hash_262,hash_263,hash_264,hash_265,hash_266,hash_267,hash_268,hash_269,hash_270,hash_271,hash_272,hash_273,hash_274,hash_275,hash_276,hash_277,hash_278,hash_279,hash_280,hash_281,hash_282,hash_283,hash_284,hash_285,hash_286,hash_287,hash_288,hash_289,hash_290,hash_291,hash_292,hash_293,hash_294,hash_295,hash_296,hash_297,hash_298,hash_299,hash_300,hash_301,hash_302,hash_303,hash_304,hash_305,hash_306,hash_307,hash_308,hash_309,hash_310,hash_311,hash_312,hash_313,hash_314,hash_315,hash_316,hash_317,hash_318,hash_319,hash_320,hash_321,hash_322,hash_323,hash_324,hash_325,hash_326,hash_327,hash_328,hash_329,hash_330,hash_331,hash_332,hash_333,hash_334,hash_335,hash_336,hash_337,hash_338,hash_339,hash_340,hash_341,hash_342,hash_343,hash_344,hash_345,hash_346,hash_347,hash_348,hash_349,hash_350,hash_351,hash_352,hash_353,hash_354,hash_355,hash_356,hash_357,hash_358,hash_359,hash_360,hash_361,hash_362,hash_363,hash_364,hash_365,hash_366,hash_367,hash_368,hash_369,hash_370,hash_371,hash_372,hash_373,hash_374,hash_375,hash_376,hash_377,hash_378,hash_379,hash_380,hash_381,hash_382,hash_383,hash_384,hash_385,hash_386,hash_387,hash_388,hash_389,hash_390,hash_391,hash_392,hash_393,hash_394,hash_395,hash_396,hash_397,hash_398,hash_399,hash_400,hash_401,hash_402,hash_403,hash_404,hash_405,hash_406,hash_407,hash_408,hash_409,hash_410,hash_411,hash_412,hash_413,hash_414,hash_415,hash_416,hash_417,hash_418,hash_419,hash_420,hash_421,hash_422,hash_423,hash_424,hash_425,hash_426,hash_427,hash_428,hash_429,hash_430,hash_431,hash_432,hash_433,hash_434,hash_435,hash_436,hash_437,hash_438,hash_439,hash_440,hash_441,hash_442,hash_443,hash_444,hash_445,hash_446,hash_447,hash_448,hash_449,hash_450,hash_451,hash_452,hash_453,hash_454,hash_455,hash_456,hash_457,hash_458,hash_459,hash_460,hash_461,hash_462,hash_463,hash_464,hash_465,hash_466,hash_467,hash_468,hash_469,hash_470,hash_471,hash_472,hash_473,hash_474,hash_475,hash_476,hash_477,hash_478,hash_479,hash_480,hash_481,hash_482,hash_483,hash_484,hash_485,hash_486,hash_487,hash_488,hash_489,hash_490,hash_491,hash_492,hash_493,hash_494,hash_495,hash_496,hash_497,hash_498,hash_499,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,pos_pos_ADJ,pos_pos_NOUN,pos_pos_VERB,pos_pos_SCONJ,pos_pos_PRON,pos_pos_PUNCT,pos_pos_DET,pos_pos_AUX,pos_pos_PART,pos_pos_ADP,pos_pos_SPACE,pos_pos_CCONJ,pos_pos_PROPN,pos_pos_NUM,pos_pos_ADV,pos_pos_SYM,pos_pos_INTJ,pos_pos_X,ner_ner_GPE,ner_ner_PERCENT,ner_ner_NORP,ner_ner_ORG,ner_ner_CARDINAL,ner_ner_MONEY,ner_ner_DATE,ner_ner_LOC,ner_ner_PERSON,ner_ner_QUANTITY,ner_ner_EVENT,ner_ner_ORDINAL,ner_ner_WORK_OF_ART,ner_ner_LAW,ner_ner_PRODUCT,ner_ner_TIME,ner_ner_FAC,ner_ner_LANGUAGE,dep_dep_amod,dep_dep_nsubj,dep_dep_ROOT,dep_dep_dobj,dep_dep_advmod,dep_dep_relcl,dep_dep_punct,dep_dep_det,dep_dep_aux,dep_dep_neg,dep_dep_mark,dep_dep_csubj,dep_dep_compound,dep_dep_prep,dep_dep_pobj,dep_dep_ccomp,dep_dep_dep,dep_dep_advcl,dep_dep_cc,dep_dep_acomp,dep_dep_attr,dep_dep_appos,dep_dep_conj,dep_dep_nummod,dep_dep_poss,dep_dep_case,dep_dep_nsubjpass,dep_dep_nmod,dep_dep_auxpass,dep_dep_npadvmod,dep_dep_expl,dep_dep_xcomp,dep_dep_dative,dep_dep_oprd,dep_dep_acl,dep_dep_quantmod,dep_dep_pcomp,dep_dep_agent,dep_dep_intj,dep_dep_predet,dep_dep_prt,dep_dep_meta,dep_dep_preconj,dep_dep_parataxis,dep_dep_csubjpass,yngve_score,dep_distance,discourse_marker_count,processed_docs,global_coherence,topics,topic_diversity,main_topic,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,topic_prob_0,topic_prob_1,topic_prob_2,topic_prob_3,topic_prob_4,topic_prob_5,topic_prob_6,topic_prob_7,topic_prob_8,topic_prob_9,interaction_score_yngve_score,interaction_score_deberta_prob_2,interaction_score_deberta_prob_3,interaction_score_deberta_prob_4,interaction_yngve_score_deberta_prob_2,interaction_yngve_score_deberta_prob_3,interaction_yngve_score_deberta_prob_4,interaction_deberta_prob_2_deberta_prob_3,interaction_deberta_prob_2_deberta_prob_4,interaction_deberta_prob_3_deberta_prob_4,lowered,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score

In [115]:
# show columns with nan values greater than 0

nan_cols = train.isna().sum()

nan_cols = nan_cols[nan_cols > 0]

nan_cols

Series([], dtype: int64)

In [116]:
def custom_train_validation_split(essays, test_size=0.2, random_state=56):
    
    """
    Custom function to perform train-validation split ensuring that
    the same prompt IDs are in both training and validation sets.

    Parameters:
    - summaries: DataFrame containing summaries and associated prompt_ids
    - prompts: DataFrame containing prompts and associated prompt_ids
    - test_size: Proportion of the dataset to be used as the validation set
    - random_state: Random seed for reproducibility

    Returns:
    - train_summaries: Training set containing summaries
    - validation_summaries: Validation set containing summaries
    - train_prompts: Training set containing prompts
    - validation_prompts: Validation set containing prompts
    """

    from sklearn.model_selection import train_test_split

    
    # Extract unique prompt IDs
    unique_essay_ids = essays['essay_id'].unique()

    # Split the unique prompt IDs into training and validation sets
    train_ids, validation_ids = train_test_split(unique_essay_ids, test_size=test_size, random_state=random_state)

    # Use these IDs to filter the original summaries and prompts DataFrames
    train_essays = essays[essays['essay_id'].isin(train_ids)]
    validation_essays = essays[essays['essay_id'].isin(validation_ids)]

    return train_essays, validation_essays

In [117]:
train_essays, val_essays = custom_train_validation_split(train, test_size=0.25, random_state=42)

In [118]:
train_essays.head()

,essay_id,full_text,score,clean_text,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,hash_200,hash_201,hash_202,hash_203,hash_204,hash_205,hash_206,hash_207,hash_208,hash_209,hash_210,hash_211,hash_212,hash_213,hash_214,hash_215,hash_216,hash_217,hash_218,hash_219,hash_220,hash_221,hash_222,hash_223,hash_224,hash_225,hash_226,hash_227,hash_228,hash_229,hash_230,hash_231,hash_232,hash_233,hash_234,hash_235,hash_236,hash_237,hash_238,hash_239,hash_240,hash_241,hash_242,hash_243,hash_244,hash_245,hash_246,hash_247,hash_248,hash_249,hash_250,hash_251,hash_252,hash_253,hash_254,hash_255,hash_256,hash_257,hash_258,hash_259,hash_260,hash_261,hash_262,hash_263,hash_264,hash_265,hash_266,hash_267,hash_268,hash_269,hash_270,hash_271,hash_272,hash_273,hash_274,hash_275,hash_276,hash_277,hash_278,hash_279,hash_280,hash_281,hash_282,hash_283,hash_284,hash_285,hash_286,hash_287,hash_288,hash_289,hash_290,hash_291,hash_292,hash_293,hash_294,hash_295,hash_296,hash_297,hash_298,hash_299,hash_300,hash_301,hash_302,hash_303,hash_304,hash_305,hash_306,hash_307,hash_308,hash_309,hash_310,hash_311,hash_312,hash_313,hash_314,hash_315,hash_316,hash_317,hash_318,hash_319,hash_320,hash_321,hash_322,hash_323,hash_324,hash_325,hash_326,hash_327,hash_328,hash_329,hash_330,hash_331,hash_332,hash_333,hash_334,hash_335,hash_336,hash_337,hash_338,hash_339,hash_340,hash_341,hash_342,hash_343,hash_344,hash_345,hash_346,hash_347,hash_348,hash_349,hash_350,hash_351,hash_352,hash_353,hash_354,hash_355,hash_356,hash_357,hash_358,hash_359,hash_360,hash_361,hash_362,hash_363,hash_364,hash_365,hash_366,hash_367,hash_368,hash_369,hash_370,hash_371,hash_372,hash_373,hash_374,hash_375,hash_376,hash_377,hash_378,hash_379,hash_380,hash_381,hash_382,hash_383,hash_384,hash_385,hash_386,hash_387,hash_388,hash_389,hash_390,hash_391,hash_392,hash_393,hash_394,hash_395,hash_396,hash_397,hash_398,hash_399,hash_400,hash_401,hash_402,hash_403,hash_404,hash_405,hash_406,hash_407,hash_408,hash_409,hash_410,hash_411,hash_412,hash_413,hash_414,hash_415,hash_416,hash_417,hash_418,hash_419,hash_420,hash_421,hash_422,hash_423,hash_424,hash_425,hash_426,hash_427,hash_428,hash_429,hash_430,hash_431,hash_432,hash_433,hash_434,hash_435,hash_436,hash_437,hash_438,hash_439,hash_440,hash_441,hash_442,hash_443,hash_444,hash_445,hash_446,hash_447,hash_448,hash_449,hash_450,hash_451,hash_452,hash_453,hash_454,hash_455,hash_456,hash_457,hash_458,hash_459,hash_460,hash_461,hash_462,hash_463,hash_464,hash_465,hash_466,hash_467,hash_468,hash_469,hash_470,hash_471,hash_472,hash_473,hash_474,hash_475,hash_476,hash_477,hash_478,hash_479,hash_480,hash_481,hash_482,hash_483,hash_484,hash_485,hash_486,hash_487,hash_488,hash_489,hash_490,hash_491,hash_492,hash_493,hash_494,hash_495,hash_496,hash_497,hash_498,hash_499,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,pos_pos_ADJ,pos_pos_NOUN,pos_pos_VERB,pos_pos_SCONJ,pos_pos_PRON,pos_pos_PUNCT,pos_pos_DET,pos_pos_AUX,pos_pos_PART,pos_pos_ADP,pos_pos_SPACE,pos_pos_CCONJ,pos_pos_PROPN,pos_pos_NUM,pos_pos_ADV,pos_pos_SYM,pos_pos_INTJ,pos_pos_X,ner_ner_GPE,ner_ner_PERCENT,ner_ner_NORP,ner_ner_ORG,ner_ner_CARDINAL,ner_ner_MONEY,ner_ner_DATE,ner_ner_LOC,ner_ner_PERSON,ner_ner_QUANTITY,ner_ner_EVENT,ner_ner_ORDINAL,ner_ner_WORK_OF_ART,ner_ner_LAW,ner_ner_PRODUCT,ner_ner_TIME,ner_ner_FAC,ner_ner_LANGUAGE,dep_dep_amod,dep_dep_nsubj,dep_dep_ROOT,dep_dep_dobj,dep_dep_advmod,dep_dep_relcl,dep_dep_punct,dep_dep_det,dep_dep_aux,dep_dep_neg,dep_dep_mark,dep_dep_csubj,dep_dep_compound,dep_dep_prep,dep_dep_pobj,dep_dep_ccomp,dep_dep_dep,dep_dep_advcl,dep_dep_cc,dep_dep_acomp,dep_dep_attr,dep_dep_appos,dep_dep_conj,dep_dep_nummod,dep_dep_poss,dep_dep_case,dep_dep_nsubjpass,dep_dep_nmod,dep_dep_auxpass,dep_dep_npadvmod,dep_dep_expl,dep_dep_xcomp,dep_dep_dative,dep_dep_oprd,dep_dep_acl,dep_dep_quantmod,dep_dep_pcomp,dep_dep_agent,dep_dep_intj,dep_dep_predet,dep_dep_prt,dep_dep_meta,dep_dep_preconj,dep_dep_parataxis,dep_dep_csubjpass,yngve_score,dep_distance,discourse_marker_count,processed_docs,global_coherence,topics,topic_diversity,main_topic,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,topic_prob_0,topic_prob_1,topic_prob_2,topic_prob_3,topic_prob_4,topic_prob_5,topic_prob_6,topic_prob_7,topic_prob_8,topic_prob_9,interaction_score_yngve_score,interaction_score_deberta_prob_2,interaction_score_deberta_prob_3,interaction_score_deberta_prob_4,interaction_yngve_score_deberta_prob_2,interaction_yngve_score_deberta_prob_3,interaction_yngve_score_deberta_prob_4,interaction_deberta_prob_2_deberta_prob_3,interaction_deberta_prob_2_deberta_prob_4,interaction_deberta_prob_3_deberta_prob_4,lowered,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,min_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score

In [ ]:
# import pandas as pd

# train_essays = pd.read_parquet('/home/jack/github/kaggle/scoring/train_essays.parquet')
# val_essays = pd.read_parquet('/home/jack/github/kaggle/scoring/validation_essays.parquet')

In [119]:
train_essays['score'].value_counts()

score
3    4706
2    3517
4    2988
1     926
5     731
6     112
Name: count, dtype: int64

In [121]:
drop_cols = [ 'full_text', 'clean_text' , 'lowered', 
             'processed_docs', 'min_word_length', 
             
               'global_coherence', 'topics'] # ,'dep_min', 'ner_min', 'pos_min', 'combined_dense_vector']   


train_df = train_essays.copy()
val_df = val_essays.copy()

train_df.drop(columns=drop_cols, inplace= True)
val_df.drop(columns=drop_cols, inplace= True)

In [122]:
train_df.head()

,essay_id,score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,hash_200,hash_201,hash_202,hash_203,hash_204,hash_205,hash_206,hash_207,hash_208,hash_209,hash_210,hash_211,hash_212,hash_213,hash_214,hash_215,hash_216,hash_217,hash_218,hash_219,hash_220,hash_221,hash_222,hash_223,hash_224,hash_225,hash_226,hash_227,hash_228,hash_229,hash_230,hash_231,hash_232,hash_233,hash_234,hash_235,hash_236,hash_237,hash_238,hash_239,hash_240,hash_241,hash_242,hash_243,hash_244,hash_245,hash_246,hash_247,hash_248,hash_249,hash_250,hash_251,hash_252,hash_253,hash_254,hash_255,hash_256,hash_257,hash_258,hash_259,hash_260,hash_261,hash_262,hash_263,hash_264,hash_265,hash_266,hash_267,hash_268,hash_269,hash_270,hash_271,hash_272,hash_273,hash_274,hash_275,hash_276,hash_277,hash_278,hash_279,hash_280,hash_281,hash_282,hash_283,hash_284,hash_285,hash_286,hash_287,hash_288,hash_289,hash_290,hash_291,hash_292,hash_293,hash_294,hash_295,hash_296,hash_297,hash_298,hash_299,hash_300,hash_301,hash_302,hash_303,hash_304,hash_305,hash_306,hash_307,hash_308,hash_309,hash_310,hash_311,hash_312,hash_313,hash_314,hash_315,hash_316,hash_317,hash_318,hash_319,hash_320,hash_321,hash_322,hash_323,hash_324,hash_325,hash_326,hash_327,hash_328,hash_329,hash_330,hash_331,hash_332,hash_333,hash_334,hash_335,hash_336,hash_337,hash_338,hash_339,hash_340,hash_341,hash_342,hash_343,hash_344,hash_345,hash_346,hash_347,hash_348,hash_349,hash_350,hash_351,hash_352,hash_353,hash_354,hash_355,hash_356,hash_357,hash_358,hash_359,hash_360,hash_361,hash_362,hash_363,hash_364,hash_365,hash_366,hash_367,hash_368,hash_369,hash_370,hash_371,hash_372,hash_373,hash_374,hash_375,hash_376,hash_377,hash_378,hash_379,hash_380,hash_381,hash_382,hash_383,hash_384,hash_385,hash_386,hash_387,hash_388,hash_389,hash_390,hash_391,hash_392,hash_393,hash_394,hash_395,hash_396,hash_397,hash_398,hash_399,hash_400,hash_401,hash_402,hash_403,hash_404,hash_405,hash_406,hash_407,hash_408,hash_409,hash_410,hash_411,hash_412,hash_413,hash_414,hash_415,hash_416,hash_417,hash_418,hash_419,hash_420,hash_421,hash_422,hash_423,hash_424,hash_425,hash_426,hash_427,hash_428,hash_429,hash_430,hash_431,hash_432,hash_433,hash_434,hash_435,hash_436,hash_437,hash_438,hash_439,hash_440,hash_441,hash_442,hash_443,hash_444,hash_445,hash_446,hash_447,hash_448,hash_449,hash_450,hash_451,hash_452,hash_453,hash_454,hash_455,hash_456,hash_457,hash_458,hash_459,hash_460,hash_461,hash_462,hash_463,hash_464,hash_465,hash_466,hash_467,hash_468,hash_469,hash_470,hash_471,hash_472,hash_473,hash_474,hash_475,hash_476,hash_477,hash_478,hash_479,hash_480,hash_481,hash_482,hash_483,hash_484,hash_485,hash_486,hash_487,hash_488,hash_489,hash_490,hash_491,hash_492,hash_493,hash_494,hash_495,hash_496,hash_497,hash_498,hash_499,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,pos_pos_ADJ,pos_pos_NOUN,pos_pos_VERB,pos_pos_SCONJ,pos_pos_PRON,pos_pos_PUNCT,pos_pos_DET,pos_pos_AUX,pos_pos_PART,pos_pos_ADP,pos_pos_SPACE,pos_pos_CCONJ,pos_pos_PROPN,pos_pos_NUM,pos_pos_ADV,pos_pos_SYM,pos_pos_INTJ,pos_pos_X,ner_ner_GPE,ner_ner_PERCENT,ner_ner_NORP,ner_ner_ORG,ner_ner_CARDINAL,ner_ner_MONEY,ner_ner_DATE,ner_ner_LOC,ner_ner_PERSON,ner_ner_QUANTITY,ner_ner_EVENT,ner_ner_ORDINAL,ner_ner_WORK_OF_ART,ner_ner_LAW,ner_ner_PRODUCT,ner_ner_TIME,ner_ner_FAC,ner_ner_LANGUAGE,dep_dep_amod,dep_dep_nsubj,dep_dep_ROOT,dep_dep_dobj,dep_dep_advmod,dep_dep_relcl,dep_dep_punct,dep_dep_det,dep_dep_aux,dep_dep_neg,dep_dep_mark,dep_dep_csubj,dep_dep_compound,dep_dep_prep,dep_dep_pobj,dep_dep_ccomp,dep_dep_dep,dep_dep_advcl,dep_dep_cc,dep_dep_acomp,dep_dep_attr,dep_dep_appos,dep_dep_conj,dep_dep_nummod,dep_dep_poss,dep_dep_case,dep_dep_nsubjpass,dep_dep_nmod,dep_dep_auxpass,dep_dep_npadvmod,dep_dep_expl,dep_dep_xcomp,dep_dep_dative,dep_dep_oprd,dep_dep_acl,dep_dep_quantmod,dep_dep_pcomp,dep_dep_agent,dep_dep_intj,dep_dep_predet,dep_dep_prt,dep_dep_meta,dep_dep_preconj,dep_dep_parataxis,dep_dep_csubjpass,yngve_score,dep_distance,discourse_marker_count,topic_diversity,main_topic,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,topic_prob_0,topic_prob_1,topic_prob_2,topic_prob_3,topic_prob_4,topic_prob_5,topic_prob_6,topic_prob_7,topic_prob_8,topic_prob_9,interaction_score_yngve_score,interaction_score_deberta_prob_2,interaction_score_deberta_prob_3,interaction_score_deberta_prob_4,interaction_yngve_score_deberta_prob_2,interaction_yngve_score_deberta_prob_3,interaction_yngve_score_deberta_prob_4,interaction_deberta_prob_2_deberta_prob_3,interaction_deberta_prob_2_deberta_prob_4,interaction_deberta_prob_3_deberta_prob_4,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score

In [123]:
feature_cols = []

for col in train_df.columns:
    if (col != 'essay_id') and (col != 'score'):
        feature_cols.append(col)

In [124]:
pd.set_option('display.max_columns', None)
feature_cols

['deberta_prob_0',
 'deberta_prob_1',
 'deberta_prob_2',
 'deberta_prob_3',
 'deberta_prob_4',
 'deberta_prob_5',
 'xlnet_prob_0',
 'xlnet_prob_1',
 'xlnet_prob_2',
 'xlnet_prob_3',
 'xlnet_prob_4',
 'xlnet_prob_5',
 'hash_0',
 'hash_1',
 'hash_2',
 'hash_3',
 'hash_4',
 'hash_5',
 'hash_6',
 'hash_7',
 'hash_8',
 'hash_9',
 'hash_10',
 'hash_11',
 'hash_12',
 'hash_13',
 'hash_14',
 'hash_15',
 'hash_16',
 'hash_17',
 'hash_18',
 'hash_19',
 'hash_20',
 'hash_21',
 'hash_22',
 'hash_23',
 'hash_24',
 'hash_25',
 'hash_26',
 'hash_27',
 'hash_28',
 'hash_29',
 'hash_30',
 'hash_31',
 'hash_32',
 'hash_33',
 'hash_34',
 'hash_35',
 'hash_36',
 'hash_37',
 'hash_38',
 'hash_39',
 'hash_40',
 'hash_41',
 'hash_42',
 'hash_43',
 'hash_44',
 'hash_45',
 'hash_46',
 'hash_47',
 'hash_48',
 'hash_49',
 'hash_50',
 'hash_51',
 'hash_52',
 'hash_53',
 'hash_54',
 'hash_55',
 'hash_56',
 'hash_57',
 'hash_58',
 'hash_59',
 'hash_60',
 'hash_61',
 'hash_62',
 'hash_63',
 'hash_64',
 'hash_65',
 'hash_66',
 'hash_67',
 'hash_68',
 'hash_69',
 'hash_70',
 'hash_71',
 'hash_72',
 'hash_73',
 'hash_74',
 'hash_75',
 'hash_76',
 'hash_77',
 'hash_78',
 'hash_79',
 'hash_80',
 'hash_81',
 'hash_82',
 'hash_83',
 'hash_84',
 'hash_85',
 'hash_86',
 'hash_87',
 'hash_88',
 'hash_89',
 'hash_90',
 'hash_91',
 'hash_92',
 'hash_93',
 'hash_94',
 'hash_95',
 'hash_96',
 'hash_97',
 'hash_98',
 'hash_99',
 'hash_100',
 'hash_101',
 'hash_102',
 'hash_103',
 'hash_104',
 'hash_105',
 'hash_106',
 'hash_107',
 'hash_108',
 'hash_109',
 'hash_110',
 'hash_111',
 'hash_112',
 'hash_113',
 'hash_114',
 'hash_115',
 'hash_116',
 'hash_117',
 'hash_118',
 'hash_119',
 'hash_120',
 'hash_121',
 'hash_122',
 'hash_123',
 'hash_124',
 'hash_125',
 'hash_126',
 'hash_127',
 'hash_128',
 'hash_129',
 'hash_130',
 'hash_131',
 'hash_132',
 'hash_133',
 'hash_134',
 'hash_135',
 'hash_136',
 'hash_137',
 'hash_138',
 'hash_139',
 'hash_140',
 'hash_141',
 'hash_142',
 'hash_143',
 'hash_144',
 'hash_145',
 'hash_146',
 'hash_147',
 'hash_148',
 'hash_149',
 'hash_150',
 'hash_151',
 'hash_152',
 'hash_153',
 'hash_154',
 'hash_155',
 'hash_156',
 'hash_157',
 'hash_158',
 'hash_159',
 'hash_160',
 'hash_161',
 'hash_162',
 'hash_163',
 'hash_164',
 'hash_165',
 'hash_166',
 'hash_167',
 'hash_168',
 'hash_169',
 'hash_170',
 'hash_171',
 'hash_172',
 'hash_173',
 'hash_174',
 'hash_175',
 'hash_176',
 'hash_177',
 'hash_178',
 'hash_179',
 'hash_180',
 'hash_181',
 'hash_182',
 'hash_183',
 'hash_184',
 'hash_185',
 'hash_186',
 'hash_187',
 'hash_188',
 'hash_189',
 'hash_190',
 'hash_191',
 'hash_192',
 'hash_193',
 'hash_194',
 'hash_195',
 'hash_196',
 'hash_197',
 'hash_198',
 'hash_199',
 'hash_200',
 'hash_201',
 'hash_202',
 'hash_203',
 'hash_204',
 'hash_205',
 'hash_206',
 'hash_207',
 'hash_208',
 'hash_209',
 'hash_210',
 'hash_211',
 'hash_212',
 'hash_213',
 'hash_214',
 'hash_215',
 'hash_216',
 'hash_217',
 'hash_218',
 'hash_219',
 'hash_220',
 'hash_221',
 'hash_222',
 'hash_223',
 'hash_224',
 'hash_225',
 'hash_226',
 'hash_227',
 'hash_228',
 'hash_229',
 'hash_230',
 'hash_231',
 'hash_232',
 'hash_233',
 'hash_234',
 'hash_235',
 'hash_236',
 'hash_237',
 'hash_238',
 'hash_239',
 'hash_240',
 'hash_241',
 'hash_242',
 'hash_243',
 'hash_244',
 'hash_245',
 'hash_246',
 'hash_247',
 'hash_248',
 'hash_249',
 'hash_250',
 'hash_251',
 'hash_252',
 'hash_253',
 'hash_254',
 'hash_255',
 'hash_256',
 'hash_257',
 'hash_258',
 'hash_259',
 'hash_260',
 'hash_261',
 'hash_262',
 'hash_263',
 'hash_264',
 'hash_265',
 'hash_266',
 'hash_267',
 'hash_268',
 'hash_269',
 'hash_270',
 'hash_271',
 'hash_272',
 'hash_273',
 'hash_274',
 'hash_275',
 'hash_276',
 'hash_277',
 'hash_278',
 'hash_279',
 'hash_280',
 'hash_281',
 'hash_282',
 'hash_283',
 'hash_284',
 'hash_285',
 'hash_286',
 'hash_287',
 'hash_288',
 'hash_289',
 'hash_290',
 'hash_291',
 'hash_292',
 'hash_293',
 'hash_294',
 'hash_295',
 'hash_296',
 'hash_297',
 'hash_298',
 'hash_299',
 'hash_300',
 'hash_301',
 'hash_302',
 'hash_303',
 'hash_304',
 'hash_305',
 'hash_306',
 'hash_307',
 'hash_308',
 'hash_309',
 'hash_310',
 'hash_311',
 'hash_312',
 'hash_313',
 'hash_314',
 'hash_315',
 'hash_316',
 'hash_317',
 'hash_318',
 'hash_319',
 'hash_320',
 'hash_321',
 'hash_322',
 'hash_323',
 'hash_324',
 'hash_325',
 'hash_326',
 'hash_327',
 'hash_328',
 'hash_329',
 'hash_330',
 'hash_331',
 'hash_332',
 'hash_333',
 'hash_334',
 'hash_335',
 'hash_336',
 'hash_337',
 'hash_338',
 'hash_339',
 'hash_340',
 'hash_341',
 'hash_342',
 'hash_343',
 'hash_344',
 'hash_345',
 'hash_346',
 'hash_347',
 'hash_348',
 'hash_349',
 'hash_350',
 'hash_351',
 'hash_352',
 'hash_353',
 'hash_354',
 'hash_355',
 'hash_356',
 'hash_357',
 'hash_358',
 'hash_359',
 'hash_360',
 'hash_361',
 'hash_362',
 'hash_363',
 'hash_364',
 'hash_365',
 'hash_366',
 'hash_367',
 'hash_368',
 'hash_369',
 'hash_370',
 'hash_371',
 'hash_372',
 'hash_373',
 'hash_374',
 'hash_375',
 'hash_376',
 'hash_377',
 'hash_378',
 'hash_379',
 'hash_380',
 'hash_381',
 'hash_382',
 'hash_383',
 'hash_384',
 'hash_385',
 'hash_386',
 'hash_387',
 'hash_388',
 'hash_389',
 'hash_390',
 'hash_391',
 'hash_392',
 'hash_393',
 'hash_394',
 'hash_395',
 'hash_396',
 'hash_397',
 'hash_398',
 'hash_399',
 'hash_400',
 'hash_401',
 'hash_402',
 'hash_403',
 'hash_404',
 'hash_405',
 'hash_406',
 'hash_407',
 'hash_408',
 'hash_409',
 'hash_410',
 'hash_411',
 'hash_412',
 'hash_413',
 'hash_414',
 'hash_415',
 'hash_416',
 'hash_417',
 'hash_418',
 'hash_419',
 'hash_420',
 'hash_421',
 'hash_422',
 'hash_423',
 'hash_424',
 'hash_425',
 'hash_426',
 'hash_427',
 'hash_428',
 'hash_429',
 'hash_430',
 'hash_431',
 'hash_432',
 'hash_433',
 'hash_434',
 'hash_435',
 'hash_436',
 'hash_437',
 'hash_438',
 'hash_439',
 'hash_440',
 'hash_441',
 'hash_442',
 'hash_443',
 'hash_444',
 'hash_445',
 'hash_446',
 'hash_447',
 'hash_448',
 'hash_449',
 'hash_450',
 'hash_451',
 'hash_452',
 'hash_453',
 'hash_454',
 'hash_455',
 'hash_456',
 'hash_457',
 'hash_458',
 'hash_459',
 'hash_460',
 'hash_461',
 'hash_462',
 'hash_463',
 'hash_464',
 'hash_465',
 'hash_466',
 'hash_467',
 'hash_468',
 'hash_469',
 'hash_470',
 'hash_471',
 'hash_472',
 'hash_473',
 'hash_474',
 'hash_475',
 'hash_476',
 'hash_477',
 'hash_478',
 'hash_479',
 'hash_480',
 'hash_481',
 'hash_482',
 'hash_483',
 'hash_484',
 'hash_485',
 'hash_486',
 'hash_487',
 'hash_488',
 'hash_489',
 'hash_490',
 'hash_491',
 'hash_492',
 'hash_493',
 'hash_494',
 'hash_495',
 'hash_496',
 'hash_497',
 'hash_498',
 'hash_499',
 '000',
 '12',
 '1976',
 '1998',
 '2000',
 '2001',
 '25',
 '30',
 '44',
 '50',
 '60',
 '800',
 '800 degrees',
 '800 degrees fahrenheit',
 '90',
 '90 times',
 '90 times greater',
 '97',
 '97 percent',
 '97 percent carbon',
 'ability',
 'able',
 'accident',
 'accidents',
 'according',
 'acid',
 'action',
 'action coding',
 'actually',
 'ad',
 'advanced',
 'advantage',
 'advantages',
 'ago',
 'agree',
 'ahead',
 'air',
 'air pollution',
 'alert',
 'alien',
 'alien monument',
 'aliens',
 'allow',
 'allowed',
 'allows',
 'alot',
 'amazing',
 'america',
 'american',
 'american west',
 'americans',
 'anger',
 'angry',
 'animals',
 'answer',
 'anymore',
 'april',
 'area',
 'areas',
 'aren',
 'argue',
 'argument',
 'article',
 'article says',
 'article states',
 'artifact',
 'ask',
 'aspects',
 'astronomers',
 'atmosphere',
 'atmosphere 97',
 'atmospheric',
 'atmospheric pressure',
 'attention',
 'author',
 'author states',
 'author supports',
 'average',
 'average 800',
 'avoid',
 'aware',
 'away',
 'bad',
 'ban',
 'banned',
 'based',
 'basic',
 'basically',
 'becuase',
 'begin',
 'believe',
 'belive',
 'beneficial',
 'benefit',
 'benefits',
 'best',
 'better',
 'big',
 'bigger',
 'bike',
 'bit',
 'blame',
 'board',
 'boat',
 'bogota',
 'bored',
 'bring',
 'built',
 'bus',
 'buses',
 'butte',
 'butte mesa',
 'buy',
 'buying',
 'called',
 'came',
 'camera',
 'cameras',
 'campaign',
 'candidate',
 'candidates',
 'canidate',
 'car',
 'car drive',
 'car free',
 'car free day',
 'car usage',
 'car use',
 'carbon',
 'carbon dioxide',
 'care',
 'cars',
 'cars coming',
 'cars drive',
 'cars good',
 'cars people',
 'case',
 'cattle',
 'cause',
 'caused',
 'causes',
 'causing',
 'certain',
 'challenge',
 'challenge exploring',
 'challenge exploring venus',
 'challenges',
 'challenging',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'children',
 'china',
 'choice',
 'choose',
 'cities',
 'citizens',
 'city',
 'claim',
 'class',
 'classroom',
 'classroom computer',
 'classroom computer recognize',
 'classrooms',
 'clear',
 'clearly',
 'close',
 'closer',
 'closest',
 'closest planet',
 'clouds',
 'coding',
 'college',
 'college unfair',
 'colombia',
 'columbia',
 'come',
 'comes',
 'coming',
 'common',
 'communication',
 'community',
 'companies',
 'company',
 'compared',
 'completely',
 'computer',
 'computer recognize',
 'computer recognize student',
 'computers',
 'conclusion',
 'conditions',
 'confused',
 'confused bored',
 'congress',
 'continue',
 'control',
 'cool',
 'corrosive',
 'cost',
 'couldn',
 'countries',
 'country',
 'couple',
 'course',
 'covered',
 'cowboy',
 'cowboys',
 'cowboys program',
 'crash',
 'crashes',
 'craters',
 'create',
 'created',
 'created aliens',
 'creating',
 'curiosity',
 'cut',
 'cydonia',
 'danger',
 'dangerous',
 'dangers',
 'dangers presents',
 'day',
 'days',
 'dear',
 'decades',
 'decide',
 'decrease',
 'degrees',
 'degrees fahrenheit',
 'democratic',
 'density',
 'density size',
 'despite',
 'despite dangers',
 'despite dangers presents',
 'detect',
 'developed',
 'development',
 'did',
 'didn',
 'didnt',
 'diesel',
 'different',
 'difficult',
 'dioxide',
 'distance',
 'does',
 'doesn',
 'doesnt',
 'doing',
 'don',
 'don know',
 'don think',
 'dont',
 'dr',
 'dr huang',
 'drive',
 'driveless',
 'driveless cars',
 'driven',
 'driver',
 'driverless',
 'driverless car',
 'driverless cars',
 'driverless cars coming',
 'drivers',
 'driving',
 'driving car',
 'driving cars',
 'earth',
 'earth like',
 'earth like planet',
 'earth twin',
 'earth venus',
 'easier',
 'easily',
 'easy',
 'effect',
 'effective',
 'effective human',
 'elect',
 'elect president',
 'election',
 'election popular',
 'election popular vote',
 'elections',
 'electoral',
 'electoral college',
 'electoral college unfair',
 'electoral vote',
 'electoral votes',
 'electors',
 'electors vote',
 'electronics',
 'emissions',
 'emotion',
 'emotional',
 'emotional expressions',
 'emotions',
 'end',
 'enjoy',
 'enviroment',
 'environment',
 'especially',
 'europe',
 'everyday',
 'evidence',
 'exactly',
 'example',
 'expensive',
 'experience',
 'explain',
 'explains',
 'exploration',
 'explore',
 'explore venus',
 'exploring',
 'exploring venus',
 'expression',
 'expressions',
 'expressions students',
 'extreme',
 'extremely',
 'eyes',
 'face',
 'face just',
 'face mars',
 'faces',
 'facial',
 'facial action',
 'facial action coding',
 'facial expressions',
 'facial muscles',
 'facs',
 'fact',
 'factor',
 'facts',
 'fahrenheit',
 'fails',
 'fair',
 'family',
 'far',
 'fault',
 'favor',
 'fear',
 'features',
 'feel',
 'feel like',
 'feeling',
 'feelings',
 'fewer',
 'figure',
 'finally',
 'fine',
 'fix',
 'focus',
 'food',
 'form',
 'formation',
 'formed',
 'forms',
 'forms life',
 'france',
 'free',
 'free day',
 'friend',
 'friends',
 'fuel',
 'fully',
 'fun',
 'future',
 'games',
 'garvin',
 'gas',
 'gas emissions',
 'gases',
 'germany',
 'gets',
 'getting',
 'given',
 'gives',
 'giving',
 'global',
 'global surveyor',
 'goes',
 'going',
 'gone',
 'good',
 'good idea',
 'good thing',
 'google',
 'got',
 'government',
 'great',
 'greater',
 'greece',
 'greenhouse',
 'greenhouse gas',
 'greenhouse gas emissions',
 'ground',
 'half',
 'hand',
 'handle',
 'hands',
 'happen',
 'happened',
 'happening',
 'happens',
 'happier',
 'happiness',
 'happy',
 'hard',
 'having',
 'head',
 'heat',
 'help',
 'help people',
 'help students',
 'helped',
 'helpful',
 'helping',
 'helps',
 'hide',
 'high',
 'highly',
 'hit',
 'home',
 'hope',
 'horses',
 'hot',
 'hottest',
 'hours',
 'house',
 'hovering',
 'huang',
 'huge',
 'human',
 'human driver',
 'human face',
 'human instructor',
 'humans',
 'humans study',
 'hurt',
 'idea',
 'ideas',
 'identify',
 'illusion',
 'im',
 'image',
 'imagination',
 'imagine',
 'impact',
 'important',
 'improve',
 'includes',
 'including',
 'information',
 'injured',
 'innovation',
 'inside',
 'insight',
 'instead',
 'instructor',
 'interesting',
 'isn',
 'issue',
 'issues',
 'job',
 'jobs',
 'join',
 'join seagoing',
 'join seagoing cowboys',
 'just',
 'just like',
 'just like earth',
 'just natural',
 'just natural landform',
 'keeping',
 'kids',
 'kind',
 'knew',
 'know',
 'knowing',
 'knowledge',
 ...]

In [125]:
# save the order of the column names to a txt file

with open('feature_cols.txt', 'w') as f:
    for item in feature_cols:
        f.write("%s\n" % item)

In [ ]:
# # read in the feature columns

# with open('feature_cols.txt', 'r') as f:
#     feature_cols = f.read().splitlines()

In [ ]:
# !pip install scikit-learn==1.2.2

In [126]:
import sklearn
print(sklearn.__version__)

1.2.2

In [127]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pickle
import numpy as np

# Extract labels from the training and validation datasets
train_labels = train_df['score']  # Extracts 'score' column as the label
val_labels = val_df['score']

# Extract features for scaling
train_features = train_df[feature_cols] # Subset with only feature columns
val_features = val_df[feature_cols]

# Initialize the scaler
scaler = StandardScaler()  # Using StandardScaler for scaling

# Fit the scaler to the training features
scaler.fit(train_features)  # This defines the transformation based on the training data

# Transform training and validation features
train_feats_scaled = scaler.transform(train_features)  # Transforms the training data
val_feats_scaled = scaler.transform(val_features)  # Transforms the validation data

# Reassign the scaled features to the original DataFrames, keeping the same column names
train_df[feature_cols] = train_feats_scaled  # Replace the original features with scaled ones
val_df[feature_cols] = val_feats_scaled

# Save the scaler for later use
with open('sklearn_scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)  # Persist the scaler for future use or reference

In [128]:
# Check if the file has been written correctly and is not empty
import os
scaler_path = 'sklearn_scaler.pkl'
if os.path.getsize(scaler_path) > 0:
    print(f"Scaler saved successfully in {scaler_path}.")
else:
    print(f"Failed to save scaler to {scaler_path}. File is empty.")

Scaler saved successfully in sklearn_scaler.pkl.

In [129]:
# Check if the scaler is StandardScaler
if isinstance(scaler, StandardScaler):
    print("The scaler is a StandardScaler.")
elif isinstance(scaler, MinMaxScaler):
    print("The scaler is a MinMaxScaler.")
else:
    print("The scaler is neither StandardScaler nor MinMaxScaler.")

The scaler is a StandardScaler.

In [130]:
# train_df = pca_dataframe(train_df)
# val_df = pca_dataframe(val_df)

In [131]:
train_df.head()

,essay_id,score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,hash_200,hash_201,hash_202,hash_203,hash_204,hash_205,hash_206,hash_207,hash_208,hash_209,hash_210,hash_211,hash_212,hash_213,hash_214,hash_215,hash_216,hash_217,hash_218,hash_219,hash_220,hash_221,hash_222,hash_223,hash_224,hash_225,hash_226,hash_227,hash_228,hash_229,hash_230,hash_231,hash_232,hash_233,hash_234,hash_235,hash_236,hash_237,hash_238,hash_239,hash_240,hash_241,hash_242,hash_243,hash_244,hash_245,hash_246,hash_247,hash_248,hash_249,hash_250,hash_251,hash_252,hash_253,hash_254,hash_255,hash_256,hash_257,hash_258,hash_259,hash_260,hash_261,hash_262,hash_263,hash_264,hash_265,hash_266,hash_267,hash_268,hash_269,hash_270,hash_271,hash_272,hash_273,hash_274,hash_275,hash_276,hash_277,hash_278,hash_279,hash_280,hash_281,hash_282,hash_283,hash_284,hash_285,hash_286,hash_287,hash_288,hash_289,hash_290,hash_291,hash_292,hash_293,hash_294,hash_295,hash_296,hash_297,hash_298,hash_299,hash_300,hash_301,hash_302,hash_303,hash_304,hash_305,hash_306,hash_307,hash_308,hash_309,hash_310,hash_311,hash_312,hash_313,hash_314,hash_315,hash_316,hash_317,hash_318,hash_319,hash_320,hash_321,hash_322,hash_323,hash_324,hash_325,hash_326,hash_327,hash_328,hash_329,hash_330,hash_331,hash_332,hash_333,hash_334,hash_335,hash_336,hash_337,hash_338,hash_339,hash_340,hash_341,hash_342,hash_343,hash_344,hash_345,hash_346,hash_347,hash_348,hash_349,hash_350,hash_351,hash_352,hash_353,hash_354,hash_355,hash_356,hash_357,hash_358,hash_359,hash_360,hash_361,hash_362,hash_363,hash_364,hash_365,hash_366,hash_367,hash_368,hash_369,hash_370,hash_371,hash_372,hash_373,hash_374,hash_375,hash_376,hash_377,hash_378,hash_379,hash_380,hash_381,hash_382,hash_383,hash_384,hash_385,hash_386,hash_387,hash_388,hash_389,hash_390,hash_391,hash_392,hash_393,hash_394,hash_395,hash_396,hash_397,hash_398,hash_399,hash_400,hash_401,hash_402,hash_403,hash_404,hash_405,hash_406,hash_407,hash_408,hash_409,hash_410,hash_411,hash_412,hash_413,hash_414,hash_415,hash_416,hash_417,hash_418,hash_419,hash_420,hash_421,hash_422,hash_423,hash_424,hash_425,hash_426,hash_427,hash_428,hash_429,hash_430,hash_431,hash_432,hash_433,hash_434,hash_435,hash_436,hash_437,hash_438,hash_439,hash_440,hash_441,hash_442,hash_443,hash_444,hash_445,hash_446,hash_447,hash_448,hash_449,hash_450,hash_451,hash_452,hash_453,hash_454,hash_455,hash_456,hash_457,hash_458,hash_459,hash_460,hash_461,hash_462,hash_463,hash_464,hash_465,hash_466,hash_467,hash_468,hash_469,hash_470,hash_471,hash_472,hash_473,hash_474,hash_475,hash_476,hash_477,hash_478,hash_479,hash_480,hash_481,hash_482,hash_483,hash_484,hash_485,hash_486,hash_487,hash_488,hash_489,hash_490,hash_491,hash_492,hash_493,hash_494,hash_495,hash_496,hash_497,hash_498,hash_499,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,pos_pos_ADJ,pos_pos_NOUN,pos_pos_VERB,pos_pos_SCONJ,pos_pos_PRON,pos_pos_PUNCT,pos_pos_DET,pos_pos_AUX,pos_pos_PART,pos_pos_ADP,pos_pos_SPACE,pos_pos_CCONJ,pos_pos_PROPN,pos_pos_NUM,pos_pos_ADV,pos_pos_SYM,pos_pos_INTJ,pos_pos_X,ner_ner_GPE,ner_ner_PERCENT,ner_ner_NORP,ner_ner_ORG,ner_ner_CARDINAL,ner_ner_MONEY,ner_ner_DATE,ner_ner_LOC,ner_ner_PERSON,ner_ner_QUANTITY,ner_ner_EVENT,ner_ner_ORDINAL,ner_ner_WORK_OF_ART,ner_ner_LAW,ner_ner_PRODUCT,ner_ner_TIME,ner_ner_FAC,ner_ner_LANGUAGE,dep_dep_amod,dep_dep_nsubj,dep_dep_ROOT,dep_dep_dobj,dep_dep_advmod,dep_dep_relcl,dep_dep_punct,dep_dep_det,dep_dep_aux,dep_dep_neg,dep_dep_mark,dep_dep_csubj,dep_dep_compound,dep_dep_prep,dep_dep_pobj,dep_dep_ccomp,dep_dep_dep,dep_dep_advcl,dep_dep_cc,dep_dep_acomp,dep_dep_attr,dep_dep_appos,dep_dep_conj,dep_dep_nummod,dep_dep_poss,dep_dep_case,dep_dep_nsubjpass,dep_dep_nmod,dep_dep_auxpass,dep_dep_npadvmod,dep_dep_expl,dep_dep_xcomp,dep_dep_dative,dep_dep_oprd,dep_dep_acl,dep_dep_quantmod,dep_dep_pcomp,dep_dep_agent,dep_dep_intj,dep_dep_predet,dep_dep_prt,dep_dep_meta,dep_dep_preconj,dep_dep_parataxis,dep_dep_csubjpass,yngve_score,dep_distance,discourse_marker_count,topic_diversity,main_topic,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,topic_prob_0,topic_prob_1,topic_prob_2,topic_prob_3,topic_prob_4,topic_prob_5,topic_prob_6,topic_prob_7,topic_prob_8,topic_prob_9,interaction_score_yngve_score,interaction_score_deberta_prob_2,interaction_score_deberta_prob_3,interaction_score_deberta_prob_4,interaction_yngve_score_deberta_prob_2,interaction_yngve_score_deberta_prob_3,interaction_yngve_score_deberta_prob_4,interaction_deberta_prob_2_deberta_prob_3,interaction_deberta_prob_2_deberta_prob_4,interaction_deberta_prob_3_deberta_prob_4,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score

In [132]:
val_df.tail()

,essay_id,score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,hash_200,hash_201,hash_202,hash_203,hash_204,hash_205,hash_206,hash_207,hash_208,hash_209,hash_210,hash_211,hash_212,hash_213,hash_214,hash_215,hash_216,hash_217,hash_218,hash_219,hash_220,hash_221,hash_222,hash_223,hash_224,hash_225,hash_226,hash_227,hash_228,hash_229,hash_230,hash_231,hash_232,hash_233,hash_234,hash_235,hash_236,hash_237,hash_238,hash_239,hash_240,hash_241,hash_242,hash_243,hash_244,hash_245,hash_246,hash_247,hash_248,hash_249,hash_250,hash_251,hash_252,hash_253,hash_254,hash_255,hash_256,hash_257,hash_258,hash_259,hash_260,hash_261,hash_262,hash_263,hash_264,hash_265,hash_266,hash_267,hash_268,hash_269,hash_270,hash_271,hash_272,hash_273,hash_274,hash_275,hash_276,hash_277,hash_278,hash_279,hash_280,hash_281,hash_282,hash_283,hash_284,hash_285,hash_286,hash_287,hash_288,hash_289,hash_290,hash_291,hash_292,hash_293,hash_294,hash_295,hash_296,hash_297,hash_298,hash_299,hash_300,hash_301,hash_302,hash_303,hash_304,hash_305,hash_306,hash_307,hash_308,hash_309,hash_310,hash_311,hash_312,hash_313,hash_314,hash_315,hash_316,hash_317,hash_318,hash_319,hash_320,hash_321,hash_322,hash_323,hash_324,hash_325,hash_326,hash_327,hash_328,hash_329,hash_330,hash_331,hash_332,hash_333,hash_334,hash_335,hash_336,hash_337,hash_338,hash_339,hash_340,hash_341,hash_342,hash_343,hash_344,hash_345,hash_346,hash_347,hash_348,hash_349,hash_350,hash_351,hash_352,hash_353,hash_354,hash_355,hash_356,hash_357,hash_358,hash_359,hash_360,hash_361,hash_362,hash_363,hash_364,hash_365,hash_366,hash_367,hash_368,hash_369,hash_370,hash_371,hash_372,hash_373,hash_374,hash_375,hash_376,hash_377,hash_378,hash_379,hash_380,hash_381,hash_382,hash_383,hash_384,hash_385,hash_386,hash_387,hash_388,hash_389,hash_390,hash_391,hash_392,hash_393,hash_394,hash_395,hash_396,hash_397,hash_398,hash_399,hash_400,hash_401,hash_402,hash_403,hash_404,hash_405,hash_406,hash_407,hash_408,hash_409,hash_410,hash_411,hash_412,hash_413,hash_414,hash_415,hash_416,hash_417,hash_418,hash_419,hash_420,hash_421,hash_422,hash_423,hash_424,hash_425,hash_426,hash_427,hash_428,hash_429,hash_430,hash_431,hash_432,hash_433,hash_434,hash_435,hash_436,hash_437,hash_438,hash_439,hash_440,hash_441,hash_442,hash_443,hash_444,hash_445,hash_446,hash_447,hash_448,hash_449,hash_450,hash_451,hash_452,hash_453,hash_454,hash_455,hash_456,hash_457,hash_458,hash_459,hash_460,hash_461,hash_462,hash_463,hash_464,hash_465,hash_466,hash_467,hash_468,hash_469,hash_470,hash_471,hash_472,hash_473,hash_474,hash_475,hash_476,hash_477,hash_478,hash_479,hash_480,hash_481,hash_482,hash_483,hash_484,hash_485,hash_486,hash_487,hash_488,hash_489,hash_490,hash_491,hash_492,hash_493,hash_494,hash_495,hash_496,hash_497,hash_498,hash_499,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,pos_pos_ADJ,pos_pos_NOUN,pos_pos_VERB,pos_pos_SCONJ,pos_pos_PRON,pos_pos_PUNCT,pos_pos_DET,pos_pos_AUX,pos_pos_PART,pos_pos_ADP,pos_pos_SPACE,pos_pos_CCONJ,pos_pos_PROPN,pos_pos_NUM,pos_pos_ADV,pos_pos_SYM,pos_pos_INTJ,pos_pos_X,ner_ner_GPE,ner_ner_PERCENT,ner_ner_NORP,ner_ner_ORG,ner_ner_CARDINAL,ner_ner_MONEY,ner_ner_DATE,ner_ner_LOC,ner_ner_PERSON,ner_ner_QUANTITY,ner_ner_EVENT,ner_ner_ORDINAL,ner_ner_WORK_OF_ART,ner_ner_LAW,ner_ner_PRODUCT,ner_ner_TIME,ner_ner_FAC,ner_ner_LANGUAGE,dep_dep_amod,dep_dep_nsubj,dep_dep_ROOT,dep_dep_dobj,dep_dep_advmod,dep_dep_relcl,dep_dep_punct,dep_dep_det,dep_dep_aux,dep_dep_neg,dep_dep_mark,dep_dep_csubj,dep_dep_compound,dep_dep_prep,dep_dep_pobj,dep_dep_ccomp,dep_dep_dep,dep_dep_advcl,dep_dep_cc,dep_dep_acomp,dep_dep_attr,dep_dep_appos,dep_dep_conj,dep_dep_nummod,dep_dep_poss,dep_dep_case,dep_dep_nsubjpass,dep_dep_nmod,dep_dep_auxpass,dep_dep_npadvmod,dep_dep_expl,dep_dep_xcomp,dep_dep_dative,dep_dep_oprd,dep_dep_acl,dep_dep_quantmod,dep_dep_pcomp,dep_dep_agent,dep_dep_intj,dep_dep_predet,dep_dep_prt,dep_dep_meta,dep_dep_preconj,dep_dep_parataxis,dep_dep_csubjpass,yngve_score,dep_distance,discourse_marker_count,topic_diversity,main_topic,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,topic_prob_0,topic_prob_1,topic_prob_2,topic_prob_3,topic_prob_4,topic_prob_5,topic_prob_6,topic_prob_7,topic_prob_8,topic_prob_9,interaction_score_yngve_score,interaction_score_deberta_prob_2,interaction_score_deberta_prob_3,interaction_score_deberta_prob_4,interaction_yngve_score_deberta_prob_2,interaction_yngve_score_deberta_prob_3,interaction_yngve_score_deberta_prob_4,interaction_deberta_prob_2_deberta_prob_3,interaction_deberta_prob_2_deberta_prob_4,interaction_deberta_prob_3_deberta_prob_4,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score

In [133]:
# train_df.to_parquet('train_df.parquet')
# val_df.to_parquet('val_df.parquet')

In [134]:
import pandas as pd
from sklearn.utils import resample
from imblearn.over_sampling import SMOTE

df = train_df.copy()
# Downsample majority classes to 1,000 samples
target_samples = 1000
balanced_df = pd.DataFrame()

for class_label in df['score'].unique():
    class_subset = df[df['score'] == class_label]
    
    if len(class_subset) > target_samples:
        # Downsample to 1,000 samples for majority classes
        class_subset = resample(
            class_subset,
            replace=False,
            n_samples=target_samples,
            random_state=42
        )
    
    balanced_df = pd.concat([balanced_df, class_subset], axis=0)

# Now, let's apply SMOTE to balance the minority classes up to 1,000 samples
X = balanced_df.drop(columns = ['essay_id','score'], axis=1)
y = balanced_df['score']

# Create SMOTE instance to ensure all classes have 1,000 samples
smote = SMOTE(sampling_strategy={k: 1000 for k in y.unique()}, random_state=42)

X_resampled, y_resampled = smote.fit_resample(X, y)

# Create the resampled DataFrame
df_resampled = pd.DataFrame(X_resampled, columns=X.columns)
df_resampled['score'] = y_resampled

# Display the resampled class distribution to confirm the balancing
print("Resampled class distribution:")
print(df_resampled['score'].value_counts())

Resampled class distribution:
score
3    1000
4    1000
2    1000
1    1000
5    1000
6    1000
Name: count, dtype: int64

/tmp/ipykernel_448115/557032744.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_resampled['score'] = y_resampled

In [135]:
UPSAMPLE = False

if UPSAMPLE:
    
    # Balance only the training DataFrame
    train_df = df_resampled.copy()

    
else:
    pass

print(train_df['score'].value_counts())
print(val_df['score'].value_counts())

score
3    4706
2    3517
4    2988
1     926
5     731
6     112
Name: count, dtype: int64
score
3    1574
2    1206
4     938
1     326
5     239
6      44
Name: count, dtype: int64

In [136]:
train_df.head()

,essay_id,score,deberta_prob_0,deberta_prob_1,deberta_prob_2,deberta_prob_3,deberta_prob_4,deberta_prob_5,xlnet_prob_0,xlnet_prob_1,xlnet_prob_2,xlnet_prob_3,xlnet_prob_4,xlnet_prob_5,hash_0,hash_1,hash_2,hash_3,hash_4,hash_5,hash_6,hash_7,hash_8,hash_9,hash_10,hash_11,hash_12,hash_13,hash_14,hash_15,hash_16,hash_17,hash_18,hash_19,hash_20,hash_21,hash_22,hash_23,hash_24,hash_25,hash_26,hash_27,hash_28,hash_29,hash_30,hash_31,hash_32,hash_33,hash_34,hash_35,hash_36,hash_37,hash_38,hash_39,hash_40,hash_41,hash_42,hash_43,hash_44,hash_45,hash_46,hash_47,hash_48,hash_49,hash_50,hash_51,hash_52,hash_53,hash_54,hash_55,hash_56,hash_57,hash_58,hash_59,hash_60,hash_61,hash_62,hash_63,hash_64,hash_65,hash_66,hash_67,hash_68,hash_69,hash_70,hash_71,hash_72,hash_73,hash_74,hash_75,hash_76,hash_77,hash_78,hash_79,hash_80,hash_81,hash_82,hash_83,hash_84,hash_85,hash_86,hash_87,hash_88,hash_89,hash_90,hash_91,hash_92,hash_93,hash_94,hash_95,hash_96,hash_97,hash_98,hash_99,hash_100,hash_101,hash_102,hash_103,hash_104,hash_105,hash_106,hash_107,hash_108,hash_109,hash_110,hash_111,hash_112,hash_113,hash_114,hash_115,hash_116,hash_117,hash_118,hash_119,hash_120,hash_121,hash_122,hash_123,hash_124,hash_125,hash_126,hash_127,hash_128,hash_129,hash_130,hash_131,hash_132,hash_133,hash_134,hash_135,hash_136,hash_137,hash_138,hash_139,hash_140,hash_141,hash_142,hash_143,hash_144,hash_145,hash_146,hash_147,hash_148,hash_149,hash_150,hash_151,hash_152,hash_153,hash_154,hash_155,hash_156,hash_157,hash_158,hash_159,hash_160,hash_161,hash_162,hash_163,hash_164,hash_165,hash_166,hash_167,hash_168,hash_169,hash_170,hash_171,hash_172,hash_173,hash_174,hash_175,hash_176,hash_177,hash_178,hash_179,hash_180,hash_181,hash_182,hash_183,hash_184,hash_185,hash_186,hash_187,hash_188,hash_189,hash_190,hash_191,hash_192,hash_193,hash_194,hash_195,hash_196,hash_197,hash_198,hash_199,hash_200,hash_201,hash_202,hash_203,hash_204,hash_205,hash_206,hash_207,hash_208,hash_209,hash_210,hash_211,hash_212,hash_213,hash_214,hash_215,hash_216,hash_217,hash_218,hash_219,hash_220,hash_221,hash_222,hash_223,hash_224,hash_225,hash_226,hash_227,hash_228,hash_229,hash_230,hash_231,hash_232,hash_233,hash_234,hash_235,hash_236,hash_237,hash_238,hash_239,hash_240,hash_241,hash_242,hash_243,hash_244,hash_245,hash_246,hash_247,hash_248,hash_249,hash_250,hash_251,hash_252,hash_253,hash_254,hash_255,hash_256,hash_257,hash_258,hash_259,hash_260,hash_261,hash_262,hash_263,hash_264,hash_265,hash_266,hash_267,hash_268,hash_269,hash_270,hash_271,hash_272,hash_273,hash_274,hash_275,hash_276,hash_277,hash_278,hash_279,hash_280,hash_281,hash_282,hash_283,hash_284,hash_285,hash_286,hash_287,hash_288,hash_289,hash_290,hash_291,hash_292,hash_293,hash_294,hash_295,hash_296,hash_297,hash_298,hash_299,hash_300,hash_301,hash_302,hash_303,hash_304,hash_305,hash_306,hash_307,hash_308,hash_309,hash_310,hash_311,hash_312,hash_313,hash_314,hash_315,hash_316,hash_317,hash_318,hash_319,hash_320,hash_321,hash_322,hash_323,hash_324,hash_325,hash_326,hash_327,hash_328,hash_329,hash_330,hash_331,hash_332,hash_333,hash_334,hash_335,hash_336,hash_337,hash_338,hash_339,hash_340,hash_341,hash_342,hash_343,hash_344,hash_345,hash_346,hash_347,hash_348,hash_349,hash_350,hash_351,hash_352,hash_353,hash_354,hash_355,hash_356,hash_357,hash_358,hash_359,hash_360,hash_361,hash_362,hash_363,hash_364,hash_365,hash_366,hash_367,hash_368,hash_369,hash_370,hash_371,hash_372,hash_373,hash_374,hash_375,hash_376,hash_377,hash_378,hash_379,hash_380,hash_381,hash_382,hash_383,hash_384,hash_385,hash_386,hash_387,hash_388,hash_389,hash_390,hash_391,hash_392,hash_393,hash_394,hash_395,hash_396,hash_397,hash_398,hash_399,hash_400,hash_401,hash_402,hash_403,hash_404,hash_405,hash_406,hash_407,hash_408,hash_409,hash_410,hash_411,hash_412,hash_413,hash_414,hash_415,hash_416,hash_417,hash_418,hash_419,hash_420,hash_421,hash_422,hash_423,hash_424,hash_425,hash_426,hash_427,hash_428,hash_429,hash_430,hash_431,hash_432,hash_433,hash_434,hash_435,hash_436,hash_437,hash_438,hash_439,hash_440,hash_441,hash_442,hash_443,hash_444,hash_445,hash_446,hash_447,hash_448,hash_449,hash_450,hash_451,hash_452,hash_453,hash_454,hash_455,hash_456,hash_457,hash_458,hash_459,hash_460,hash_461,hash_462,hash_463,hash_464,hash_465,hash_466,hash_467,hash_468,hash_469,hash_470,hash_471,hash_472,hash_473,hash_474,hash_475,hash_476,hash_477,hash_478,hash_479,hash_480,hash_481,hash_482,hash_483,hash_484,hash_485,hash_486,hash_487,hash_488,hash_489,hash_490,hash_491,hash_492,hash_493,hash_494,hash_495,hash_496,hash_497,hash_498,hash_499,000,12,1976,1998,2000,2001,25,30,44,50,60,800,800 degrees,800 degrees fahrenheit,90,90 times,90 times greater,97,97 percent,97 percent carbon,ability,able,accident,accidents,according,acid,action,action coding,actually,ad,advanced,advantage,advantages,ago,agree,ahead,air,air pollution,alert,alien,alien monument,aliens,allow,allowed,allows,alot,amazing,america,american,american west,americans,anger,angry,animals,answer,anymore,april,area,areas,aren,argue,argument,article,article says,article states,artifact,ask,aspects,astronomers,atmosphere,atmosphere 97,atmospheric,atmospheric pressure,attention,author,author states,author supports,average,average 800,avoid,aware,away,bad,ban,banned,based,basic,basically,becuase,begin,believe,belive,beneficial,benefit,benefits,best,better,big,bigger,bike,bit,blame,board,boat,bogota,bored,bring,built,bus,buses,butte,butte mesa,buy,buying,called,came,camera,cameras,campaign,candidate,candidates,canidate,car,car drive,car free,car free day,car usage,car use,carbon,carbon dioxide,care,cars,cars coming,cars drive,cars good,cars people,case,cattle,cause,caused,causes,causing,certain,challenge,challenge exploring,challenge exploring venus,challenges,challenging,chance,change,changed,changes,changing,children,china,choice,choose,cities,citizens,city,claim,class,classroom,classroom computer,classroom computer recognize,classrooms,clear,clearly,close,closer,closest,closest planet,clouds,coding,college,college unfair,colombia,columbia,come,comes,coming,common,communication,community,companies,company,compared,completely,computer,computer recognize,computer recognize student,computers,conclusion,conditions,confused,confused bored,congress,continue,control,cool,corrosive,cost,couldn,countries,country,couple,course,covered,cowboy,cowboys,cowboys program,crash,crashes,craters,create,created,created aliens,creating,curiosity,cut,cydonia,danger,dangerous,dangers,dangers presents,day,days,dear,decades,decide,decrease,degrees,degrees fahrenheit,democratic,density,density size,despite,despite dangers,despite dangers presents,detect,developed,development,did,didn,didnt,diesel,different,difficult,dioxide,distance,does,doesn,doesnt,doing,don,don know,don think,dont,dr,dr huang,drive,driveless,driveless cars,driven,driver,driverless,driverless car,driverless cars,driverless cars coming,drivers,driving,driving car,driving cars,earth,earth like,earth like planet,earth twin,earth venus,easier,easily,easy,effect,effective,effective human,elect,elect president,election,election popular,election popular vote,elections,electoral,electoral college,electoral college unfair,electoral vote,electoral votes,electors,electors vote,electronics,emissions,emotion,emotional,emotional expressions,emotions,end,enjoy,enviroment,environment,especially,europe,everyday,evidence,exactly,example,expensive,experience,explain,explains,exploration,explore,explore venus,exploring,exploring venus,expression,expressions,expressions students,extreme,extremely,eyes,face,face just,face mars,faces,facial,facial action,facial action coding,facial expressions,facial muscles,facs,fact,factor,facts,fahrenheit,fails,fair,family,far,fault,favor,fear,features,feel,feel like,feeling,feelings,fewer,figure,finally,fine,fix,focus,food,form,formation,formed,forms,forms life,france,free,free day,friend,friends,fuel,fully,fun,future,games,garvin,gas,gas emissions,gases,germany,gets,getting,given,gives,giving,global,global surveyor,goes,going,gone,good,good idea,good thing,google,got,government,great,greater,greece,greenhouse,greenhouse gas,greenhouse gas emissions,ground,half,hand,handle,hands,happen,happened,happening,happens,happier,happiness,happy,hard,having,head,heat,help,help people,help students,helped,helpful,helping,helps,hide,high,highly,hit,home,hope,horses,hot,hottest,hours,house,hovering,huang,huge,human,human driver,human face,human instructor,humans,humans study,hurt,idea,ideas,identify,illusion,im,image,imagination,imagine,impact,important,improve,includes,including,information,injured,innovation,inside,insight,instead,instructor,interesting,isn,issue,issues,job,jobs,join,join seagoing,join seagoing cowboys,just,just like,just like earth,just natural,just natural landform,keeping,kids,kind,knew,know,knowing,knowledge,known,knows,land,landform,landforms,landing,large,largely,lastly,later,law,laws,lazy,lead,learn,learning,leave,left,lesson,lesson like,lesson like effective,let,lets,level,license,life,life just,life mars,light,like,like earth,like effective,like effective human,like face,like planet,like planet solar,likely,limit,limited,limiting,limiting car,limiting car usage,lisa,lisa smile,little,live,lives,living,ll,long,long ago,long time,longer,look,look like,looked,looking,looks,looks like,lose,lost,lot,lots,love,lower,luke,machine,machines,mad,main,major,majority,make,make sure,makes,making,man,manufacturer,manufacturers,mars,mars global,mars global surveyor,mars just,martian,matter,maybe,mean,meaning,means,mechanical,meet,mesa,method,middle,miles,million,millions,mind,mission,model,modern,modify,modify lesson,modify lesson like,mona,mona lisa,mona lisa smile,money,monument,mountains,mouth,movements,muscle,muscles,nasa,nasa working,natural,natural landform,near,need,needed,needs,negative,new,new technology,nice,night,normal,nose,number,numbered,ocean,oceans,oceans supported,old,ones,opinion,opportunity,option,order,outcome,outdated,overall,paragraph,paragraph author,paragraph states,paris,parts,party,pass,passage,past,pay,pay attention,paying,paying attention,people,people need,people say,people think,people vote,people want,peoples,percent,percent carbon,percent carbon dioxide,person,personal,phone,photo,photos,pick,picture,pictures,pixel,place,places,plan,planet,planet earth,planet solar,planet surface,planet venus,planets,plates,play,plus,point,points,pollution,popular,popular vote,popular votes,population,positive,possible,possibly,power,powerful,present,presents,president,presidential,pressure,pressure 90,pressure 90 times,pretty,prevent,probably,problem,problems,process,program,proof,prove,proven,provide,public,public transportation,pursuit,pursuit despite,pursuit despite dangers,putting,question,questions,quite,quote,read,read emotional,read emotional expressions,reading,ready,real,reality,really,reason,reasons,recognize,recognize student,recognize student confused,reduce,regular,require,requires,research,researchers,responsible,result,rid,ride,right,risk,risks,road,roads,rock,rock formation,rocky,rosenthal,run,running,sad,sadness,safe,safer,safety,said,save,saw,say,saying,says,school,schools,science,scientist,scientists,sea,seagoing,seagoing cowboy,seagoing cowboys,seagoing cowboys program,second,seeing,seen,self,self driving,self driving cars,senator,send,sending,sense,sensor,sensors,sent,set,shadows,ship,shouldn,showing,shown,shows,sign,similar,simple,simply,single,situation,situations,size,skills,slate,slate electors,small,smart,smart cars,smile,smog,society,software,solar,solution,soon,sound,sounds,source,space,spacecraft,special,speed,spend,star,start,started,state,stated,states,stay,step,stop,story,street,streets,stress,student,student confused,student confused bored,students,students classroom,study,study venus,studying,studying venus,studying venus worthy,stuff,sulfuric,sulfuric acid,sun,support,supported,supported various,supports,supports idea,sure,surface,surveyor,survive,swing,swing states,systems,taken,takes,taking,talk,talking,talks,taxis,teacher,teachers,teaching,team,technology,technology read,tell,telling,tells,temperature,temperatures,tense,terms,test,tested,text,text states,thats,thing,things,things like,think,think driverless,thinking,thinks,thought,thousands,tie,time,times,times greater,today,told,took,town,traffic,transportation,travel,trip,trips,trouble,true,truly,trust,try,trying,turn,twin,type,understand,understanding,unfair,united,united states,usage,use,use cars,use technology,used,useful,uses,using,valleys,valleys mountains,valuable,value,various,various forms,various forms life,vauban,vauban germany,ve,vehicle,vehicles,venus,venus atmosphere,venus author,venus closest,venus earth,venus earth like,venus surface,venus venus,venus worthy,venus worthy pursuit,video,viking,visit,vote,vote president,voted,voters,votes,voting,waiting,walk,walking,want,wanted,wants,war,wasn,waste,watch,water,way,ways,weather,web,weeks,went,west,wheel,win,winner,winning,won,wont,work,working,works,world,world war,worry,worth,worthy,worthy pursuit,worthy pursuit despite,wouldn,wouldnt,wrong,year,years,yes,young,pos_pos_ADJ,pos_pos_NOUN,pos_pos_VERB,pos_pos_SCONJ,pos_pos_PRON,pos_pos_PUNCT,pos_pos_DET,pos_pos_AUX,pos_pos_PART,pos_pos_ADP,pos_pos_SPACE,pos_pos_CCONJ,pos_pos_PROPN,pos_pos_NUM,pos_pos_ADV,pos_pos_SYM,pos_pos_INTJ,pos_pos_X,ner_ner_GPE,ner_ner_PERCENT,ner_ner_NORP,ner_ner_ORG,ner_ner_CARDINAL,ner_ner_MONEY,ner_ner_DATE,ner_ner_LOC,ner_ner_PERSON,ner_ner_QUANTITY,ner_ner_EVENT,ner_ner_ORDINAL,ner_ner_WORK_OF_ART,ner_ner_LAW,ner_ner_PRODUCT,ner_ner_TIME,ner_ner_FAC,ner_ner_LANGUAGE,dep_dep_amod,dep_dep_nsubj,dep_dep_ROOT,dep_dep_dobj,dep_dep_advmod,dep_dep_relcl,dep_dep_punct,dep_dep_det,dep_dep_aux,dep_dep_neg,dep_dep_mark,dep_dep_csubj,dep_dep_compound,dep_dep_prep,dep_dep_pobj,dep_dep_ccomp,dep_dep_dep,dep_dep_advcl,dep_dep_cc,dep_dep_acomp,dep_dep_attr,dep_dep_appos,dep_dep_conj,dep_dep_nummod,dep_dep_poss,dep_dep_case,dep_dep_nsubjpass,dep_dep_nmod,dep_dep_auxpass,dep_dep_npadvmod,dep_dep_expl,dep_dep_xcomp,dep_dep_dative,dep_dep_oprd,dep_dep_acl,dep_dep_quantmod,dep_dep_pcomp,dep_dep_agent,dep_dep_intj,dep_dep_predet,dep_dep_prt,dep_dep_meta,dep_dep_preconj,dep_dep_parataxis,dep_dep_csubjpass,yngve_score,dep_distance,discourse_marker_count,topic_diversity,main_topic,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,topic_prob_0,topic_prob_1,topic_prob_2,topic_prob_3,topic_prob_4,topic_prob_5,topic_prob_6,topic_prob_7,topic_prob_8,topic_prob_9,interaction_score_yngve_score,interaction_score_deberta_prob_2,interaction_score_deberta_prob_3,interaction_score_deberta_prob_4,interaction_yngve_score_deberta_prob_2,interaction_yngve_score_deberta_prob_3,interaction_yngve_score_deberta_prob_4,interaction_deberta_prob_2_deberta_prob_3,interaction_deberta_prob_2_deberta_prob_4,interaction_deberta_prob_3_deberta_prob_4,paragraph_count,sentence_count,word_count,avg_paragraph_length,max_paragraph_length,min_paragraph_length,avg_sentence_length,max_sentence_length,min_sentence_length,avg_word_length,max_word_length,flesch_reading_ease,gunning_fog_index,sentiment_score

In [137]:
# To convert features and targets to NumPy arrays for ML use

if UPSAMPLE:
    train_features = train_df.drop(columns=['score'], axis=1).values
    train_labels = train_df['score'].values

    val_features = val_df.drop(columns=['essay_id','score'], axis=1).values
    val_labels = val_df['score'].values

else:
    
    train_features = train_df.drop(columns=['essay_id','score'], axis=1).values
    train_labels = train_df['score'].values

    val_features = val_df.drop(columns=['essay_id','score'], axis=1).values
    val_labels = val_df['score'].values


print("Features shape:", train_features.shape)
print("Target shape:", train_labels.shape)

print("Features shape:", val_features.shape)
print("Target shape:", val_labels.shape)



#####     Features shape: (3, 1389)

Features shape: (12980, 1641)
Target shape: (12980,)
Features shape: (4327, 1641)
Target shape: (4327,)

In [138]:
from sklearn.metrics import make_scorer, cohen_kappa_score

def quadratic_weighted_kappa_scorer(y_true, y_pred):
    """
    Compute the Quadratic Weighted Kappa (QWK), also known as Cohen's kappa.
    
    Parameters:
    y_true : array-like of shape (n_samples,)
        True labels.
    y_pred : array-liimport keras_tuner
from sklearn import ensemble
from sklearn import datasets
from sklearn import linear_model
from sklearn import metrics
from sklearn import model_selection

def build_model(hp):
  model_type = hp.Choice('model_type', ['random_forest', 'ridge'])
  if model_type == 'random_forest':
    model = ensemble.RandomForestClassifier(
        n_estimators=hp.Int('n_estimators', 10, 50, step=10),
        max_depth=hp.Int('max_depth', 3, 10))
  else:
    model = linear_model.RidgeClassifier(
        alpha=hp.Float('alpha', 1e-3, 1, sampling='log'))
  return model

tuner = keras_tuner.tuners.SklearnTuner(
    oracle=keras_tuner.oracles.BayesianOptimizationOracle(
        objective=keras_tuner.Objective('score', 'max'),
        max_trials=100),
    hypermodel=build_model,
    scoring=metrics.make_scorer(metrics.accuracy_score),
    cv=model_selection.StratifiedKFold(10),
    directory='.',
    project_name='my_project')ke of shape (n_samples,)
        Predicted labels.
    
    Returns:
    score : float
        Quadratic Weighted Kappa score.
    """
    return cohen_kappa_score(y_true, y_pred, weights='quadratic')

In [ ]:
# from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
# import keras_tuner as kt

# model_checkpoint = ModelCheckpoint('data/models/best_standard_model_epoch.keras', 
#                                    save_best_only=True, monitor='val_loss', mode='min')

# early_stopping = EarlyStopping(monitor='val_loss', patience=5, 
#                                restore_best_weights=True)

# call_backs = [model_checkpoint, early_stopping]

In [139]:
import keras_tuner
from sklearn import ensemble, linear_model, model_selection, svm
from lightgbm import LGBMClassifier


def build_model(hp):
    """
    Builds a more comprehensive machine learning model based on hyperparameters for multiclass classification.
    
    Parameters:
    hp : HyperParameters
        Hyperparameters for tuning the model.
    
    Returns:
    model : An instance of a Scikit-learn model.
    """
    # Adding 'lightgbm' as a new model type
    model_type = hp.Choice('model_type', ['random_forest',  'gradient_boosting', 'lightgbm'])

    if model_type == 'random_forest':
        model = ensemble.RandomForestClassifier(
            n_estimators=hp.Int('n_estimators', 10, 100, step=10),
            max_depth=hp.Int('max_depth', 3, 20),
            min_samples_split=hp.Int('min_samples_split', 2, 20),
            min_samples_leaf=hp.Int('min_samples_leaf', 1, 10),
            criterion=hp.Choice('criterion', ['gini', 'entropy']),
            class_weight=hp.Choice('class_weight', ['balanced', 'balanced_subsample']),
            max_samples=hp.Float('max_samples', 0.1, 1.0, sampling='log')
        )



    elif model_type == 'gradient_boosting':
        model = ensemble.GradientBoostingClassifier(
            n_estimators=hp.Int('n_estimators', 50, 200, step=50),
            learning_rate=hp.Float('learning_rate', 0.01, 0.2, sampling='log'),
            max_depth=hp.Int('max_depth', 3, 15),
            subsample=hp.Float('subsample', 0.5, 1.0, step=0.1)
        )

    # Adding LightGBM as a new model type
    elif model_type == 'lightgbm':
        model = LGBMClassifier(
            n_estimators=hp.Int('n_estimators', 50, 200, step=50),
            num_leaves=hp.Int('num_leaves', 31, 127, step=16),
            learning_rate=hp.Float('learning_rate', 0.01, 0.2, sampling='log'),
            min_child_samples=hp.Int('min_child_samples', 10, 50, step=10),
            class_weight=hp.Choice('class_weight', ['balanced', 'balanced_sample']),
        )

    return model


# Defining the custom QWK scorer
qwk_scorer = make_scorer(quadratic_weighted_kappa_scorer)

# Tuner configuration
tuner = keras_tuner.tuners.SklearnTuner(
    oracle=keras_tuner.oracles.BayesianOptimizationOracle(
        objective=keras_tuner.Objective('score', 'max'),
        max_trials=10),
    hypermodel=build_model,
    scoring=qwk_scorer,
    cv=model_selection.StratifiedKFold(3),
    directory='.',
    project_name='data/sklearn',
    overwrite=True)

# Starting the search
tuner.search(train_features, train_labels)      # class_weight=class_weights_dict,

# Retrieving the best model
best_model = tuner.get_best_models(num_models=1)[0]

Trial 1 Complete [00h 00m 03s]
score: 0.8709448189934506

Best score So Far: 0.8709448189934506
Total elapsed time: 00h 00m 03s

Search: Running Trial #2

Value             |Best Value So Far |Hyperparameter
gradient_boosting |random_forest     |model_type
70                |30                |n_estimators
9                 |10                |max_depth
8                 |2                 |min_samples_split
1                 |7                 |min_samples_leaf
entropy           |gini              |criterion
balanced_subsample|balanced          |class_weight
0.66898           |0.63898           |max_samples

In [ ]:
best_model.fit(train_features, train_labels)

In [ ]:
predictions = best_model.predict(val_features)

y_true = val_labels

# predictions = target_scaler.inverse_transform(predictions.reshape(-1, 1)).flatten()

In [ ]:
# confusion matrix

from sklearn.metrics import confusion_matrix

confusion_matrix(y_true, predictions)

In [ ]:
# classification report

from sklearn.metrics import classification_report

print(classification_report(y_true, predictions))

In [ ]:
# cohens kappa

from sklearn.metrics import cohen_kappa_score

cohen = cohen_kappa_score(y_true, predictions)

In [ ]:
# quadratic weighted kappa

from sklearn.metrics import cohen_kappa_score

quadratic = cohen_kappa_score(y_true, predictions, weights='quadratic')

print(f"Cohen's Kappa: {cohen}")
print(f"Quadratic Weighted Kappa: {quadratic}")

In [ ]:
from joblib import dump, load

if UPSAMPLE:
    
    dump(best_model, 'upsampled_random_forest.joblib')

else:
    
    dump(best_model, 'standard_random_forest.joblib')

In [ ]:
# forest_model = load('random_forest.joblib')

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Generate and display the confusion matrix for the test predictions
cm = confusion_matrix(y_true, predictions, labels=best_model.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=best_model.classes_)
disp.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix')
plt.show()

In [ ]:
# Identifying misclassified samples
misclassified_indices = (y_true != predictions)
misclassified_samples = val_features[misclassified_indices]
misclassified_true_labels = y_true[misclassified_indices]
misclassified_predicted_labels = predictions[misclassified_indices]

In [ ]:
# Examining features of misclassified samples
import pandas as pd
misclassified_df = pd.DataFrame(misclassified_samples)
misclassified_df['True_Label'] = misclassified_true_labels
misclassified_df['Predicted_Label'] = misclassified_predicted_labels
# Display the first few rows of the misclassified samples
misclassified_df.head()

In [ ]:
# # Feature importance from LightGBM
# feature_importance = best_model.feature_importance(importance_type='gain')
# feature_names = val_features.columns
# feature_importance_df = pd.DataFrame({
#     'Feature': feature_names,
#     'Importance': feature_importance
# })
# # Sort features by importance
# feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)
# print(feature_importance_df)

In [ ]:
# Checking class distribution in the true labels
label_counts = pd.Series(y_true).value_counts()
print(label_counts)

In [ ]:
# from sklearn.model_selection import GridSearchCV
# # Define the hyperparameters to tune
# param_grid = {
#     'learning_rate': [0.01, 0.05, 0.1],
#     'num_leaves': [31, 62, 128],
#     'n_estimators': [50, 100, 200]
# }
# grid_search = GridSearchCV(best_model, param_grid, scoring='', cv=5)
# grid_search.fit(val_features, val_labels)
# print("Best parameters:", grid_search.best_params_)

In [ ]:
# Check LightGBM version
import lightgbm as lgb
print(lgb.__version__)

In [ ]:
# # Ensure the model is fitted
# if not hasattr(best_model, 'feature_importance_'):
#     best_model.fit(val_features, val_labels)  # Train or re-train the model

# # Retrieve feature importance
# feature_importance = best_model.feature_importance_  # Underscore at the end
# feature_names = val_features.columns

# # Create DataFrame for feature importance
# feature_importance_df = pd.DataFrame({
#     'Feature': feature_names,
#     'Importance': feature_importance
# })
# feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# print(feature_importance_df)

In [ ]:
# Assuming `df` is the original DataFrame and `predictions` is a list/array of predicted labels
# If there's a subset used for predictions, ensure it aligns with the DataFrame
val_df['Predicted_Label'] = predictions

In [ ]:
print(len(val_features), len(val_df), len(predictions))

In [ ]:
val_df.tail()

In [ ]:
# merge 'clean_text' column back with val df 

text = val_essays[['essay_id', 'clean_text']]

val_df = val_df.merge(text, on = 'essay_id')

val_df.head()

In [ ]:
# Assuming `df` has the original labels in a column named 'True_Label'
misclassified_samples = val_df[val_df['score'] != val_df['Predicted_Label']]

# Display misclassified samples
print(misclassified_samples[['score', 'Predicted_Label', 'clean_text']][:15])

In [ ]:
# Example: Analyze original text of misclassified samples
misclassified_text = misclassified_samples['clean_text']  # Assuming 'Text' is the original text data
print(misclassified_text.head())

In [ ]:
# load tf model
len(misclassified_text)

In [ ]:
# add full mis classified text to a txt file seperated by  '---' and a new line after every 10 words in each essay

with open('misclassified_text.txt', 'w') as f:
    for essay in misclassified_text:
        f.write("%s\n" % essay)
        f.write('---\n')

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Assuming `df` has your model's features and labels
X = val_df[feature_cols]
y = val_df['score'] == val_df['Predicted_Label']

# Splitting the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Fit a RandomForest to see feature importances
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)

# Get the most important features
importances = clf.feature_importances_
features = feature_cols
important_features = {features[i]: importances[i] for i in range(len(features))}

# convert to percentages rounded and sort

important_features = {k: round(v, 5) for k, v in important_features.items()}

print("Most predictive features of misclassification:", sorted(important_features.items(), key=lambda x: x[1], reverse=True))

In [ ]:
# import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt

# # Assume val_df and feature_cols are already defined

# # Set the option to display all rows
# pd.set_option('display.max_rows', None)

# # Selecting the features and the target
# X = val_df[feature_cols]
# y = val_df['score']

# # Calculate the correlation between features and the target
# corr = X.corrwith(y)

# # Sort the correlation values
# corr = corr.sort_values(ascending=False)

# # Convert the Series to a DataFrame for heatmap compatibility
# corr_df = pd.DataFrame(corr, columns=['Correlation'])

# corr_df

In [ ]:
# from sklearn.model_selection import train_test_split
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.metrics import classification_report

# # Define the feature set with and without the specific features
# X_with = val_df[feature_cols]  # including all features
# X_without = val_df.drop(columns=['misspelling_count', 'sentence_length'], axis=1) # excluding problematic features

# y = val_df['score']  # target variable

# # Split the data
# X_train_with, X_test_with, y_train, y_test = train_test_split(X_with, y, test_size=0.3, random_state=42)
# X_train_without, X_test_without, _ , _ = train_test_split(X_without, y, test_size=0.3, random_state=42)

# # Train models
# model_with = RandomForestClassifier().fit(X_train_with, y_train)
# model_without = RandomForestClassifier().fit(X_train_without, y_train)

# # Evaluate models
# print("With features:")
# print(classification_report(y_test, model_with.predict(X_test_with)))

# print("Without features:")
# print(classification_report(y_test, model_without.predict(X_test_without)))